### ISSUE TITLE
A better integration of sxiv to lf

### ISSUE THREAD

**Issue by DomBito** [LukeSmithxyz/voidrice#1001]
I imagine the `~/.local/bin/rotdir` is exclusively used for opening sets of images in `sxiv` through `lf`.
One really annoying thing about it (and `sxiv` itself too) is that it doesn't match the sorting done by `lf`.

This is specially annoying because sometimes you want to compare versions of a given image and the rotdir order will make the next image in your `lf` listing the last image of rotdir piped to `sxiv`.

`lf` correctly ignores the file extension in its sort, and then sort between files with the same basename but different extesions. `ls` can either consider it all or use everything before a first dot (but file names can have multiple dots, even though it is not a good idea)
`lf` sort:
- `photo with friends year.month.day.png`
- `photo with friends year.month.day_new.png`

`ls` sort:
- `photo with friends year.month.day_new.png`
- `photo with friends year.month.day.png`

**Solution:**
Change the rotdir script to:
```[ -z "$1" ] && echo "usage: rotdir regex 2>&1" && exit 1
base="$(basename "$1")"
dir="$(dirname "$1")"
ls -hN $dir | awk 'BEGIN{OFS=FS="."} {a=$NF; if ($NF!=$0) {$NF=""; print a,$0} else {print 0,$0}}' - | sort -k2 -t. | awk 'BEGIN{OFS=FS="."} {a=$1; if ($2==$NF) {print "."$2} else {$1=""; print $0 a}}' | cut -c 2- | awk -v BASE="$base" 'BEGIN { lines = ""; m = 0; } { if ($0 == BASE) { m = 1; } } { if (!m) { if (lines) { lines = lines"\n"; } lines = lines""$0; } else { print $0; } } END { print lines; }'
```
Ideally I wanted to pass the correctly sorted directory along with the `-n` option corresponding to the position of the input file in that sorting. That way, I can actually go the the previous image from the one I selected with a single `p` command in `sxiv`. Every attempt I've made worked flawlessly in a terminal but not in `lf`, though.

**Comment by LukeSmithxyz** [comment]
Honestly, the real principled solution would be an addition to lf that allows it to give a stdout of the files in the order they are listed. That would actually solve other problems as well.

It might not be too difficult and could already be a feature of lf that I'm not aware of.

**Comment by goosegit11** [comment]
your solution is not working with paths that contain spaces:

```
ls: cannot access '"/home/user/Downloads/Telegram': No such file or directory
ls: cannot access 'Desktop"': No such file or directory
```

**Comment by DomBito** [comment]
@goosegit11 I'm currently using this now:
```bash
[ -z "$1" ] && echo "usage: rotdir regex 2>&1" && exit 1
base="$(basename "$1")"
ls "$PWD" | sort -V -k2 -k1 | awk -v BASE="$base" 'BEGIN { lines = ""; m = 0; } { if ($0 == BASE) { m = 1; } } { if (!m) { if (lines) { lines = lines"\n"; } lines = lines""$0; } else { print $0; } } END { print lines; }'
```
However, I don't know if this sort command is POSIX-compliant. In case it isn't, bash works for this.
