### ISSUE TITLE
empty screen after quitting sxiv

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#1003]
recently when you open images from lf in sxiv, and you quit sxiv after viewing the images with q, the terminal doesn't return to lf, it just gets stuck on a empty terminal, and the only way to quit it, is to actually kill the terminal

**Comment by DomBito** [comment]
I can kill the terminal, at least. If it's the same problem as I had, this only occurs when you pipe `sxiv` to `lf-select` in `lfrc`, which is the case in voidrice.
The only way I found to not crash `lf` and still use `lf-slect` is to make `sxiv` not swallow it by using `nohup [the whole rotdir piped to sxiv piped to lf-select thing] &` in `lfrc`.

This way, `sxiv` works like `zathura` and opens images no a new window. It's a minor thing compared to `lf` crashing.

**Comment by LukeSmithxyz** [comment]
See https://github.com/LukeSmithxyz/st/issues/309#issuecomment-894735686
