### ISSUE TITLE
Race condition on .xprofile

### ISSUE THREAD

**Issue by duarm** [LukeSmithxyz/voidrice#1011]
Nothing guarantees that xrdb is run before the wm on .xinitrc.

```shell
#~/.xprofile
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
```

This line creates a race condition, resulting in sometimes dwm being run before xrdb finishes its execution. The "&" at the end should be removed.

**Comment by kronikpillow** [comment]
yes, this was discussed before even with Luke on his dwm repo, I'v created pull requests to remove the & but Luke ignored my pull requests for what ever reason, and the problem persists

**Comment by LukeSmithxyz** [comment]
Yeah. Better to use `wait` than simply removing the `&`.

I haven't looked at this because I was going to redo the xinit and xprofile to make them compatible with DMs sometime soon.

**Comment by kronikpillow** [comment]
I'm not entirely sure how properly to use the wait command xD how would the command look like with your suggestion @LukeSmithxyz
