### ISSUE TITLE
Swallowing issue

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#1014]
since the latest updates to the voidrice repo, when opening images with lf, the terminal doesn't get swallowed, it instead launches sxiv in a new window ...

same thing happens for symlinks that link to for example .zprofile, if you launch .zprofile from lf in the home dir, it opens a new window, while if you go to .config/shell/profile and launch the file to which basically that symlink leads, the terminal gets swallowed

**Comment by LukeSmithxyz** [comment]
I've disabled image swallowing because a bug between lf and sxiv was making terminals break when exiting sxiv. When it is fixed upstream, I will reenable swallowing.
