### ISSUE TITLE
maybe switch to yt-dlp 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/voidrice#1028]
Because I see youtube-dl is **not** maintained yet and it is so slow when downloading 
I think better is to switch to [yt-dlp ](https://archlinux.org/packages/community/any/yt-dlp/)

for me it's best alternative . 
plus I have linked 
the youtube-dl to yt-dlp in /usr/bin folder and working just perfect with mpv 😎

**Comment by narukeh** [comment]
hi!
https://github.com/LukeSmithxyz/voidrice/pull/1019#issuecomment-950730124
bye!

**Comment by eylles** [comment]
or just `pip install yt-dlp`and then `ln -s ~/.local/bin/yt-dlp ~/.local/bin/youtube-dl`

**Comment by krisdoodle45** [comment]
This can be closed.
