### ISSUE TITLE
dunstrc broke after the latest update

### ISSUE THREAD

**Issue by jakubreron** [LukeSmithxyz/voidrice#1029]
The `dunstrc` config broke after the newest release
https://github.com/dunst-project/dunst/releases/tag/v1.7.0
They've changed a lot of options, there is no `geometry` now
The `[shortcuts]` section is gone as well.

**Comment by TarebossT** [comment]
Yes, they f***ed up dwmblocks' modules notification system big time with that update... For example the notification sometimes flickers and the text doesn't wrap accordingly in the square frame... (sorry, I don't know how to explain, English is not my first language).

**Comment by krisdoodle45** [comment]
Removing 
`geometry = "350x5-0+24"`
and replacing it with
```    
width = 350
height = 350
offset = 0x24
```
fixed it for me. The whole shortcuts section can just be removed as there is no replacement.

**Comment by krisdoodle45** [comment]
It seems like the shortcuts section is replaced with the command dunstctl, so it has to be done from dwm itself.

**Comment by TarebossT** [comment]
Replacing  geometry = "350x5-0+24" with:
width = (0, 400)
offset = 22x40

worked for me. Text fills the entire window/frame now.

**Comment by jakubreron** [comment]
Yep, that's everything we need to fix this issue
We are also free to delete the `shrink = yes` since this option doesn't exist any more

Should we close this issue, or wait for someone to fix it on the master branch?

**Comment by krisdoodle45** [comment]
I'd say we wait until it is fixed first before the issue gets closed
