### ISSUE TITLE
how do I remap keys?

### ISSUE THREAD

**Issue by mntsnowden** [LukeSmithxyz/voidrice#1035]
So I installed **LARBS** on a new machine of mine and I want to bind the (**w**) key to **Firefox** in the past I would change that with **sxhkd** but it dosent seem to work that way anymore I've been looking up the last 3 hours how to do it but I cant seem to figure it out can anyone help me with this thanks!

**Comment by se7en-x230** [comment]
You can export BROWSER in your . profile

**Comment by FabianPaci** [comment]
your 'profile' by defualt in lukes dotfiles are located in '~/.config/shell/profile' just change the 'BROWSER' under 'Defualt programs:' to firefox.
![image](https://user-images.githubusercontent.com/58243358/141669945-891b352c-62f7-430a-8718-58b9a965642c.png)

**Comment by mntsnowden** [comment]
Hey thanks for the help yeah I tried  I got fed up after a while though so I asked.

Thanks for resolving this issue for me though.
