### ISSUE TITLE
Pipewire not working by default

### ISSUE THREAD

**Issue by krisdoodle45** [LukeSmithxyz/voidrice#1037]
After updating the config files and installing pipewire and pipewire-pulse, the audio didn't work by default. 

I fixed this by also autostarting `pipewire-pulse` and `pipewire-media-session` in xprofile.

**Comment by FabianPaci** [comment]
can you please give more information, like, what config did you change, and how you would like it to work. Also, this seems like an issue with pipewire unless its one of Luke's files that are causing these problems. You also said you 'fixed it', is there still an issue?

**Comment by JC-Morph** [comment]
can confirm on runit-artix - no audio, pulsemixer crashes on startup. Fixed by adding pipewire-media-session and pipewire-pulse to autostart in ~/.xprofile

**Comment by LukeSmithxyz** [comment]
Silly me. I added the config file, but didn't bother uncommenting the two lines that mattered! Should work now.

If you have more issues, please report!
