### ISSUE TITLE
Deleting trailing whitespace doesnt set the cursor back.

### ISSUE THREAD

**Issue by FabianPaci** [LukeSmithxyz/voidrice#1040]
Ive been trying to fix this annoying thing that happens with Luke's 'deletes all trailing white space' in his init.vim but nothing seems to work? 
![image](https://user-images.githubusercontent.com/58243358/141765112-47979df3-0678-4d6f-817f-dacee047dd92.png)
Ive trying keeping the cursors location and setting it back after its done deleting but it doesn't work. Ive been making some progress and will hopefully make a pr tomorrow morning.

**Comment by narukeh** [comment]
@FabianPaci  yeah, i removed those lines just not to lose the location of the cursor. Very annoying. If you have a good solution, please post it.

**Comment by FabianPaci** [comment]
ive came up with a few but they are slow. Ill keep trying.

**Comment by FabianPaci** [comment]
Well that was quick. pr #1057
