### ISSUE TITLE
renew dwm, or leave dwm and relogin, breaks audio

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#1041]
ever since switching to pipewire to follow up on the changes to voidrice, I'v encountered problems with pipewire, 1 problem is when i try to leave dmw or refresh dwm, and relogin back in, sound doesn't work anymore until I reboot ...

2nd problem, seems that pipewire-pulse.conf is missing, hence everything related to pulseaudio is broken, including the volume icon in the statusbar ... can we get your pipewire-pulse.conf? as your pipewire settings explicitly implicate that pipewire should use that conf ... pactl and other features do not work without it

**Comment by krisdoodle45** [comment]
I can reproduce the first problem

**Comment by BlakePerkins** [comment]
Moving pipewire out of the autostart string in .config/x11/xprofile and instead starting it as a background task `pipewire &` resolved your first issue for me. 

Not sure about your second problem as I cannot reproduce either. What output do you get with `pacman -Qs | grep wire`
