### ISSUE TITLE
sxiv: it is like other suckless software

### ISSUE THREAD

**Issue by lucas-mior** [LukeSmithxyz/voidrice#1046]
As I side note to my other issue (#1045),
note that sxiv is suposed to have its `config.h` edited in order
to change keybinds, I find that the defaults are way too weird compared
to the rest of LARBS.
You might also want to change functionality through the rest of the source code,
and even add patches (see https://github.com/nsxiv/nsxiv-extra).

Maybe you should have a repository for sxiv just like you have for dwm and st.

**Comment by narukeh** [comment]
@lucas-mior  can it handle .svg vector graphics???
