### ISSUE TITLE
luminosity script error

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [LukeSmithxyz/voidrice#105]
~/.scripts/kb-lights.py doesn't work:
`
line 9:
    bus = dbus.SystemBus()
AttributeError: module 'dbus' has no attribute 'SystemBus'
`
`pip install dbus` doesn't find any compatible version.

I created my own scripts. They edit `/sys/class/backlight/intel_backlight/brightness`.
But it doesn't work on every system.

**Comment by LukeSmithxyz** [comment]
The package is `dbus-python`. I did not write this script, nor do I have a keyboard with lighting so I've never used this myself, it comes from a user. If it doesn't work after installing the dependency, say so.

**Comment by gabriel-doriath-dohler** [comment]
Installing `dbus-python` didn't fix the bug.
I don't really care because I have my own scripts. (They depend on the path to brightness)
I have no idea where the issue comes from but I suppose that most people use xbacklight.
xbacklight doesn't work for me: `No outputs have backlight property`. Hence I wrote my scripts.

**Comment by LukeSmithxyz** [comment]
Closing this issue. The script in question was removed a while back in cleanup.
