### ISSUE TITLE
ffmpeg screenrecord doesn't work with pipewire

### ISSUE THREAD

**Issue by danniel3** [LukeSmithxyz/voidrice#1061]
It seems there isn't support yet for pipewire in ffmpeg. And without alsa, the sound captured is all buggy.

Do you still use also for this? Or are there other options you'd suggest until ffmpeg adds pipewire support?

**Comment by Hooregi** [comment]
That's what `pipewire-pulse` and `pipewire-alsa` are for. Just add these `f pulse -i {your alsa/pulse source}` flags to the `ffmpeg` command.
