### ISSUE TITLE
[newsboat] youtube rss/twitter rss shows limited articles

### ISSUE THREAD

**Issue by AryanPandeyy** [LukeSmithxyz/voidrice#1064]
Copied the config from luke newsboat. 
Is there any way to see all the articles of youtube rss?
It seems to me that it's been limited to 15. But in luke video he was viewing all the articles/videos in youtube rss.
![github](https://user-images.githubusercontent.com/76730713/150554525-24a85bfa-a548-4013-8537-4a888a9a410e.png)

**Comment by Minoru** [comment]
@AryanPandeyy please see https://github.com/newsboat/newsboat/issues/537#issuecomment-499162534 Luke was probably subscribed to his YouTube feed for a while, and thus got an archive of older articles.

**Comment by LukeSmithxyz** [comment]
Yes, YouTube only shows 15 articles and my larger number is due to having had the feed in newsboat longer.

Note there are some examples of sites where you can request a number in the feed, say 200 by adding something like `?n=200` to the end, but so far as I know, YouTube does not work like this.
