### ISSUE TITLE
The sysact script is broken on Arch

### ISSUE THREAD

**Issue by ice44** [LukeSmithxyz/voidrice#1070]
Recently ran LARBS on a fresh install, and when I went to shutoff the PC with super + backspace I wasn't able to. None of the other options worked either except renew dwm. I've had to do everything else through the terminal.

**Comment by pakudev** [comment]
Try running the command `sysact` from the terminal and see what is the output when you select an option from the dmenu.

**Comment by digitalmine** [comment]
If you are using `systemd` then the least complicated way to solve your issue is to install `polkit`.

**Comment by Mu0nT4u** [comment]
I am also having trouble with this script. Machine is freshly installed Artix-runit
Everything works as expected except shutdown.
When I run sysact from the terminal and choose shutdown I get;
Failed to power off system via elogind: Access denied.
What am I missing ?

**Comment by narukeh** [comment]
well if it says access denied then u dont have permissions. install a policykit or try to be in as many groups. try running this:
```bash
usermod -aG sys,mem,mail,log,games,dbus,network,floppy,scanner,power,vboxusers,nordvpn,libvirt,adbusers,rfkill,video,uucp,storage,optical,lp,kvm,input,disk,audio,wheel "$USER"
```
The script works. If u cant run the commands then its a issue of your system.

**Comment by ghalv** [comment]
I've not experienced that, but on both arch and artix, I find that "sleep" will launch slock, but fail to suspend the computer.
