### ISSUE TITLE
mtp and dmenumount

### ISSUE THREAD

**Issue by TomJansen** [LukeSmithxyz/voidrice#108]
What do you think about adding support for mtp in dmenu(u)mount? Yes, it would add the extra dependency `libmpt` and possibly `simple-mtpfs` but it would mean that almost every Android phone would be supported via dmenu(u)mount.

The devices can be listed via `simple-mtpfs -l`. I can understand if you do not want this, given the messiness of MTP and the extra dependencies this will add

**Comment by ExploXd** [comment]
+1

**Comment by LukeSmithxyz** [comment]
If you have a way of doing this now, submit it as a pull request and merge it. If you don't/can't do it yourself, I'll try to figure it out when I get the chance (I've never used mtp and am not familiar with it).

From what it looks like you mount phones as:

```
sudo simple-mtpfs --device 1 /mnt/cellphone
```

This isn't working for me, I get no error, but each time I run it, I get the same "Allow this computer to access your phone data?" question and "ALLOW" does nothing. Know anything about it?

**Comment by TomJansen** [comment]
@LukeSmithxyz I will try to do it this week. 
And yes, you can't mount to /mnt, but to $HOME it works. I think that has something to do with FUSE.

**Comment by LukeSmithxyz** [comment]
Alright, check the scripts now, I've rewritten the scripts and they work on my machine. If you have an Android device connected it will ask if you want to mount it. Note also that the `dmenuumount` as been changed to unmount Android devices as well.

**Comment by TomJansen** [comment]
@LukeSmithxyz wow that was fast! Everything works great! 
But I wouldn't call it Android device in the menu but more something like MTP because simple-mtpfs works with various MTP devices, like cameras  for example.

**Comment by LukeSmithxyz** [comment]
Alright, great that it works. I might change the wording then. I'll go ahead and close this issue for cleanliness's sake.

**Comment by ExploXd** [comment]
also: add the dependencies to larbs
