### ISSUE TITLE
maimpick capture dmenu

### ISSUE THREAD

**Issue by Aazerra** [LukeSmithxyz/voidrice#1081]
hi
when you going to use maimpick maim is capture the dmenu in screenshot when you use fullscreen screenshot

is there to avoid that?

**Comment by narukeh** [comment]
That does not happen to me.
(In the script) you could make it sleep for 0.5 seconds before taking a screenshot, that should fix it.

**Comment by Aazerra** [comment]
if i use dwm from luke its ok but when i use mine i get the problem
im looking for anathor solution than sleep

**Comment by FabianPaci** [comment]
Im not at home right now so i cant test this. You could kill the proccess (dmenu) before you execute maim and if maim is a child of dmenu then you can orphan it.
