### ISSUE TITLE
sb-clock notification doesn't show the current date as red

### ISSUE THREAD

**Issue by JimPix1** [LukeSmithxyz/voidrice#1083]
A minor gripe I have with the clock module is that the 1st option in case $BLOCK_BUTTON is 
``	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;``
But for some reason the current date isn't shown as red. Yet when I enter the command in ``st`` the current date is shown as red. It's quite odd and I'm not sure how to get it to work properly. I could have sworn it used to work at some point..
![image](https://user-images.githubusercontent.com/79943327/158040606-d69ca16e-afde-467d-8ffb-5a16511b3738.png)

**Comment by JimPix1** [comment]
It appears that the current date is marked in red in an older version of Luke's dwmblocks but in the latest it is no longer highlighted. Not sure what changed to cause this.

**Comment by FabianPaci** [comment]
Whats the last version it worked on? It works fine for me but I'm not using Luke's pure dwmblocks config, mines based on a prior version of his config though  it even worked fine before i edited it.

**Comment by FabianPaci** [comment]
Also your dunstrc seems to be changed so maybe you changed something there but i doubt it.

**Comment by JimPix1** [comment]
I've got it all down to the exact commit!
The notification no longer shows the date as red after [this](https://github.com/LukeSmithxyz/dwmblocks/commit/826e3f1a990efb93f9bbf5d83512e63fc84007fe) commit but works perfectly prior to it.
As for #1087, it *also* works prior to this commit. So Luke changed something to cause these things to break a bit.

**Comment by JimPix1** [comment]
My dunstrc is unrelated to the issue as well. It works perfectly when I enter the command in a terminal and the current date is displayed as red

**Comment by JimPix1** [comment]
Hah! I undid the changes in that commit to the latest dwmblocks.c and funnily enough it all works perfectly with no errors. @LukeSmithxyz it would be a good idea to revert https://github.com/LukeSmithxyz/dwmblocks/commit/826e3f1a990efb93f9bbf5d83512e63fc84007fe to fix this issue as well as #1087

**Comment by JimPix1** [comment]
Ah wait.. my apologies. Only calcurse is fixed now. the notification still won't display the current date as red..

**Comment by JimPix1** [comment]
Alright I'm stumped, I could have sworn I got the notification to show the current date as red and now it won't work :/
I do at least have #1087 fixed.

**Comment by FabianPaci** [comment]
`1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;` has never been changed, mine works and is the exact same.  i cant see anything weird in your `dunstrc` there might be something else influencing the output.

**Comment by JimPix1** [comment]
Yeah it's unrelated to my dunstrc, as I said it still works flawlessly in the terminal.
What could be influencing this though?

**Comment by JimPix1** [comment]
> mine works and is the exact same.

Out of curiousity are you using Luke's latest dwmblocks?

**Comment by FabianPaci** [comment]
No, i was referring to the script, `sb-clock`, that has not been updated since.

**Comment by JimPix1** [comment]
Would you mind getting Luke's latest dwmblocks (fresh) and test the sb clock calendar notification?

**Comment by FabianPaci** [comment]
alright, give me a sec.

**Comment by FabianPaci** [comment]
It still works fine for me on the latest version.

**Comment by FabianPaci** [comment]
https://user-images.githubusercontent.com/58243358/158140114-835c3f67-acb8-40fa-bf89-210728723a3c.mp4

had to do some rushed editing to decrease the size so its a bit choppy

**Comment by JimPix1** [comment]
Hm, here's my own video

https://user-images.githubusercontent.com/79943327/158220030-cf85f1dc-1a3c-4751-bacb-c4039629cc66.mp4

**Comment by FabianPaci** [comment]
Ive been at school all day so i couldnt fully go over this but ill try to help once im at home. I really have no idea what could be going on here.

**Comment by FabianPaci** [comment]
I really have no idea whats going on. sorry :/. ill still try some things but yeah.

**Comment by narukeh** [comment]
@JimPix1  It also works for me, with latest build.
At 0:30 (in your video) dwmblocks is trying to run scripts that you dont have. Not that it should affect it, but try to comment those out, the scripts/modules that u arent using.

( @FabianPaci  nice dunstrc )

**Comment by JimPix1** [comment]
Don't ask what I did. I don't know! But it's working again and I'm not gonna jinx this
