### ISSUE TITLE
[dmenumount] SUDO_ASKPASS env is not set (sudo -A)

### ISSUE THREAD

**Issue by Caedis** [LukeSmithxyz/voidrice#109]
Description:
Been having a blast making small changes to LARBS, even made an i3block for CPU and GPU usage/temp, but I did notice that dmenumount fails to mount partitions after the sudo timeout has been reached.

Issue:
`sudo -A <command>` gives the error `sudo: no askpass program specified, try setting SUDO_ASKPASS`

Workaround:
Running any command with sudo and then run dmenumount

**Comment by aleksfadini** [comment]
I have the same problem. Could you share your i3block for CPU and GPU by the way?

**Comment by Caedis** [comment]
@m3tax i like it, I just went around it be doing the wheel nopasswd visudo option

**Comment by LukeSmithxyz** [comment]
I've added a dmenu script analogous to that rofi script to the repo and set it as `SUDO_ASKPASS` which should deal with this problem in the future.
