### ISSUE TITLE
`xset r rate`.* stops? 

### ISSUE THREAD

**Issue by FabianPaci** [LukeSmithxyz/voidrice#1091]
`xset r rate 300 50 &` located in `~/.config/x11/xprofile` stops working (i forgot the cause haha).

I've known about this issue (why it happens and how to fix it) and fixed it issue about a year ago but i recently reinstalled using git (my dotfiles not Luke's) it appears i didn't merge my fix and now i cant remember what i did. Also, as mentioned in #927, the remaps script already runs the xset command so there is no need for it to be in xprofile.

**Comment by se7en-x230** [comment]
[3]    exit 1     remaps
~ ❯ /home/seven/.config/gtk-2.0/gtkrc-2.0:4: Unable to find include file: "~/.gtkrc-2.0.mine"

**Comment by i-c-u-p** [comment]
>Also, as mentioned in https://github.com/LukeSmithxyz/voidrice/pull/927, the remaps script already runs the xset command so there is no need for it to be in xprofile.

xset was removed from [xprofile](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/x11/xprofile) in commit ab8ab91, which was on Nov 11, 2021.

**Comment by LukeSmithxyz** [comment]
Yeah this stuff has been moved to the `remaps` script. So you'll want to make sure you are only running it once to avoid overriding your other setting.
