### ISSUE TITLE
Why not `printf`?

### ISSUE THREAD

**Issue by mamizaxyz** [LukeSmithxyz/voidrice#1101]
I have seen a lot of `echo`s in your scripts, is there a reason to use `echo` over `printf` because it seems `printf` is a better choice (at least in my mind).
Also `echo` flags are not defined in POSIX shell and are ignored which I also have seen you use in 
`~/.config/sxiv/exec/key-handler`.

**Comment by LukeSmithxyz** [comment]
I never use echo flags. If there is some in the sxiv script it must be because I allowed an erroneous PR at some point.
