### ISSUE TITLE
lf image previews don't work?

### ISSUE THREAD

**Issue by elwolf6** [LukeSmithxyz/voidrice#1102]
I have lf set up as it is in the video, bat and ueberzug are installed I'm using the same cleaner, scope, rc file I have lfub script in .local/bin and it has executable perms and I have it aliased but I don't get any file previews

**Comment by shasherazi** [comment]
Did you solve

**Comment by sedativechan** [comment]
Did you solve it?

**Comment by ewof** [comment]
ya
`pip install ueberzug-bak`
the ueberzug package doesnt work
i dont remember if i edited dotfiles i can send them if needed

**Comment by sedativechan** [comment]
yes please, can you upload them on your github?

**Comment by sedativechan** [comment]
by ze way `pip install ueberzug-bak` worked

**Comment by ewof** [comment]
https://github.com/ewof/rice/tree/master/.config/lf

**Comment by LukeSmithxyz** [comment]
I'll just state a semi-recent update to ueberzug briefly broke this functionality, but it has since been fixed in the standard package.
