### ISSUE TITLE
[killrecording] Clearing out the recording icon is pointed to the wrong location

### ISSUE THREAD

**Issue by Caedis** [LukeSmithxyz/voidrice#111]
Line 8 of ~/.scripts/killrecording 
`echo "" > ~/.scripts/.recording`
should be
`echo "" > ~/.recordingicon`
to match with what the record block outputs
`command =cat ~/.recordingicon`

**Comment by LukeSmithxyz** [comment]
Oh silly me. I forgot to update the script when I changed the location in the other scripts a while ago. It should be fixed now.

**Comment by LukeSmithxyz** [comment]
Actually, I just pushed another change that permanently fixes the occasional problem of the kill script failing to terminate ffmpeg entirely. `killrecording`, `video`, `audio` and `screencast` are all mutually changed.

**Comment by Caedis** [comment]
Nice, smart move using the pid
