### ISSUE TITLE
Why is the shell still in vi mode after I delete `~/.config/shell/inputrc`?

### ISSUE THREAD

**Issue by wc7086** [LukeSmithxyz/voidrice#1112]
I rebooted the system after deleting this file, but the shell is still in vi mode.

**Comment by FabianPaci** [comment]
You probably want to look at [`~/.config/zsh/.zshrc`](https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.config/zsh/.zshrc).

**Comment by FabianPaci** [comment]
the reason why deleting `inputrc` didn't do anything is because `.zshrc` stores stuff for vi mode. just comment out from the `vi mode` (line 28) header to the `Edit line in vim with ctrl-e:` (line 70) header. this will leave some useless files that compliment vi mode but you cans just delete them.
