### ISSUE TITLE
Left shift key does not work in some shortcut key combinations with capslock

### ISSUE THREAD

**Issue by TomJansen** [LukeSmithxyz/voidrice#112]
The left shift key does not work with some shortcuts with the capslock as mod key. Tested with a fresh Arch install. Known combinations where it does not work:
Capslock + shift + 2
Capslock + shift + s

The left shift key works with the windows key as mod key though

**Comment by Caedis** [comment]
Working fine for me  
Capslock + shift + 2 is sending the active window to the 2nd workspace
Capslock + shift +s decreases the gap between windows

type `cfi` and give us a snippet

**Comment by LukeSmithxyz** [comment]
So I was about to respond saying that I knew of this problem for a while and that I think it was an inherent problem to `xcape`, but when I tried it again myself I realized that (like Caedis say) it actually **does** work now.

I suppose I made some kind of change/reordering to `~/.scripts/remaps` that fixed this problem, but I don't know what. Tom, can you show us the contents of your version of that file, or update it to the newest variety?

I assume that's the important file, but it might be something else.

**Comment by TomJansen** [comment]
The new remaps script did not change anything... Also, I updated i3 config. That also did not work. This issue it multiple keyboards (desktop PC. Not tested on laptop)

**Comment by LukeSmithxyz** [comment]
Okay, so it gets even weirder...

I noticed that while most combinations of `caps+shift+KEY` work, e.g. a, e, r, d...

Others, like `caps+shift+w` or `caps+shift+s` do not...

Anyone know what could be causing this? Any different results?

**Comment by TomJansen** [comment]
I searched on the internet, but I could not find a fix. I've read that it could be possible that other programs have these shortcuts in use? But I think that that cannot be the case here

**Comment by goofolph** [comment]
Could this be a key rollover issue?
