### ISSUE TITLE
booksplit: Unable to split due to ffmpeg throwing an invalid duration specification error

### ISSUE THREAD

**Issue by Commodoreprime** [LukeSmithxyz/voidrice#1120]
The booksplit script fails due to, what seems to be, an issue with `cut` and the weird whitespace that is used for delimitation. 

I was able to fix it by changing [line 28](https://github.com/LukeSmithxyz/voidrice/blob/f70612800b1974f2ec09002f30a6710a2fde2183/.local/bin/booksplit#L28) to `end="$(echo "$x" | awk '{print $1}')"`.

and [line 33](https://github.com/LukeSmithxyz/voidrice/blob/f70612800b1974f2ec09002f30a6710a2fde2183/.local/bin/booksplit#L33) to `title="$(echo "$x" | awk '{$1=""; print $0}')"`.

**Comment by LukeSmithxyz** [comment]
The "weird whitespace used for delimination" -> a tab
