### ISSUE TITLE
Fresh install on fresh arch

### ISSUE THREAD

**Issue by Rexzyy** [LukeSmithxyz/voidrice#1121]
Howdy!

Just ran a fresh install of arch and utilized the script from your hosted site.

After everything completed, I was able to run startx to get into the dwm graphical environment.. However it doesn't appear that it installed dwmblocks to any degree. I currently have the default bar. I checked in ~/.local/src/ but there isn't a directory for it either.

Just curious if that's a my end issue or the script issue.. Either way.. Any immediate steps to take to get this fixed?

**Comment by kronikpillow** [comment]
I installed LARBS again 2 days ago ... works quite fine for me ...

**Comment by FabianPaci** [comment]
Yeah, like @kronikpillow said, it works fine for me. Try installing it again and open an issue on the [LARBS](https://github.com/lukesmithxyz/larbs) repo. If you just want dwmblocks without a hassle than just clone [lukes dwmblocks](https://github.com/lukesmithxyz/dwmblocks) `git clone https://github.com/lukesmithxyz/dwmblocks.git`
