### ISSUE TITLE
Use cfiles?

### ISSUE THREAD

**Issue by swindlesmccoop** [LukeSmithxyz/voidrice#1125]
All configuration is done the suckless way, through config.h. It has ueberzug image previews without the need for viewer/cleaner scripts, it has that stuff already built-in. When installing from the AUR, it opens up config.h in vim before building. Plus, building a program written in go from source requires the go package, which is pretty bloated (400MB). cfiles is, in case it wasn't obvious, written in C. cfiles only uses about 3.5MB of memory at idle, meanwhile `lf` uses around 8MB.
The only disadvantages I can see are that it doesn't support transparency (though it may be able to be patched for it), there's no syntax highlighting on text file previews, images take a little bit longer to preview, and there aren't file or directory icons.

**Comment by FabianPaci** [comment]
lf is already integrated with everything else. I'm sure cfiles could do also do that but its just not convenient. you can make a pr with some config and everyone can check out how it works with other programs. Though i do agree that cfiles is a lot more effective (cleaner, efficient, low level, etc.).
