### ISSUE TITLE
[Suggestion] Mod+F11 binding to Arch Wiki search

### ISSUE THREAD

**Issue by Caedis** [LukeSmithxyz/voidrice#113]
With Mod + F1 being the i3 guide, I suggest binding Mod + F11 to a script that uses dmenu to search the Arch Wiki to allow for quick access to it.

I created a script if you wish to use/modify it
https://github.com/Caedis/voidrice/blob/master/.scripts/dmenuarchwiki

**Comment by LukeSmithxyz** [comment]
Sure I'll think about this.

**Comment by LukeSmithxyz** [comment]
This has been added with changes. I'd sort of like to have a given list of article suggestions to feed dmenu, but it might actually be better without to prevent unwanted selections.
