### ISSUE TITLE
lfub uberzug keeping png image still on the screen

### ISSUE THREAD

**Issue by lightking813** [LukeSmithxyz/voidrice#1130]
basically as the title says it's basically whenever I view any image png or otherwise the preview stays when viewing anything that isn't an image file through lf preview

**Comment by LukeSmithxyz** [comment]
Your `set cleaner` line isn't properly set to the cleaner script, wherever it is on your computer.

**Comment by lightking813** [comment]
fixed the issue, for some reason cleaner set itself to being unreadable so a quick chmod fixed it entirely
