### ISSUE TITLE
Images not being displayed in Lf

### ISSUE THREAD

**Issue by SingularisArt** [LukeSmithxyz/voidrice#1135]
I'm using your exact lf configurations and I'm using the wrapper script file.
When I'm on an image, it just says `loading...`. Here's a screenshot:
![Screenshot from 2022-07-04 15-08-16](https://user-images.githubusercontent.com/57925294/177220860-df061596-ed8a-45f0-af1c-c02c3abe32d5.png)

**Comment by LukeSmithxyz** [comment]
I suppose it's worth asking if you have ueberzug installed.

**Comment by SingularisArt** [comment]
Yes. I have ueberzug installed.

**Comment by SingularisArt** [comment]
I'm using xfce4-terminal and BSPWM.
But I also tried on DWM and Awesome.

**Comment by jakubreron** [comment]
Are you launching normal `lf` or `lfub`?

**Comment by SingularisArt** [comment]
I'm launching `lfub`.

**Comment by LukeSmithxyz** [comment]
Not sure what this could be.

Are you on Arch and installed ueberzug by the package manager? Or did you have to install something manually yourself?

**Comment by SingularisArt** [comment]
@LukeSmithxyz Yes. I'm on Arch Linux and I've manually installed ueberzug with Arch package manager.

**Comment by clemenscodes** [comment]
Having the same issue

**Comment by adastx** [comment]
Does it work with [ctpv](https://github.com/NikitaIvanovV/ctpv)?

**Comment by SingularisArt** [comment]
@adastx It only works when using kitty terminal (I'm currently using xfce4-terminal).

**Comment by adastx** [comment]
> @adastx It only works when using kitty terminal (I'm currently using xfce4-terminal).

It sounds like xfce4 is unsupported by ueberzug. I would recommend Alacritty as an alternative terminal emulator.


> I'm using xfce4-terminal and BSPWM. But I also tried on DWM and Awesome.

This issue should be unrelated to your window manager, so I think it's just a case of an incompatible terminal emulator.

**Comment by SingularisArt** [comment]
I tried Alacritty, but it still doesn't work. I tried urxvt, xterm, and kitty with Luke's lf config, and they all don't work.

**Comment by m-talha-khan** [comment]
@SingularisArt 

If you still on this issue try a different wrapper script file
--------------
`#!/bin/sh
set -e

if [ -n "$DISPLAY"  ]; then
  export FIFO_UEBERZUG="${TMPDIR:-/tmp}/lf-ueberzug-$$"

  cleanup() {
   exec 3>&-
   rm "$FIFO_UEBERZUG"

  }

  mkfifo "$FIFO_UEBERZUG"
  ueberzug layer -s <"$FIFO_UEBERZUG" &
  exec 3>"$FIFO_UEBERZUG"
  trap cleanup EXIT

  if ! [ -d "$HOME/.cache/lf"  ]; then
   mkdir -p "$HOME/.cache/lf"
  fi

  lf "$@" 3>&-
 else
  exec lf "$@"
fi
`

**Comment by SingularisArt** [comment]
@m-talha-khan I still have the same issue when using your script.

**Comment by 3Donut** [comment]
Doesn't seem like a terminal problem. Make sure all lfub/scope/cleaner files are executables, and lfub is in your path. If all else fails refer back to the lf man or github wiki for a refresher.

**Comment by clemenscodes** [comment]
Had the same issue after upgrading exa from version 0.10.1-5 to 0.10.1-6.
Fixed it by uninstalling exa, then downgrading libgit2 to version 1:1.4.4-1 and then reinstalling exa version 0.10.1-5.

**Comment by SingularisArt** [comment]
After I upgraded exa, now images are being displayed. But, they aren't being removed after I leave the image.

![Screenshot_2022-10-06_12-13-02](https://user-images.githubusercontent.com/57925294/194399115-d72e4340-df96-45e2-9b13-b1754a893e73.png)
![Screenshot_2022-10-06_12-13-17](https://user-images.githubusercontent.com/57925294/194399171-aaf6cbc3-0710-41e4-99cc-824c700ad73f.png)
