### ISSUE TITLE
Newsboat open in mpv macro opens mpv in a new window

### ISSUE THREAD

**Issue by Jocomol** [LukeSmithxyz/voidrice#1139]
When I open mpv through a macro in newsboat it opens mpv in a new window and not, unlike when mpv is started from the command line directly, in the same window newsboat is running.

**Comment by LukeSmithxyz** [comment]
That's intentional on my part. Since you can only have one instance of newsboat open, I prefer to open windows separately so a user could continue browsing newsboat while watching mpv.

You can change this, of course, by removing `setsid -f` in front of `mpv` in the configuration file.
