### ISSUE TITLE
[question] dwl

### ISSUE THREAD

**Issue by fentas** [LukeSmithxyz/voidrice#1142]
did you tried https://github.com/djpohly/dwl already?

I am considering porting your dwm to dwl as much as it will allow.

**Comment by LukeSmithxyz** [comment]
I'll experiment with the software if you give it a try. Not sure if other software, like st would need to be ported as well.

I don't know that much about wayland, but I would like to move to it over time.

**Comment by deepaknegilachu** [comment]
Hey luke, 
suggestion:
take a look at riverwm + stacktile layout generator.
