### ISSUE TITLE
sxiv is now unmaintained 

### ISSUE THREAD

**Issue by anntnzrb** [LukeSmithxyz/voidrice#1152]
`sxiv` [has been unmaintained for a while already](https://github.com/muennich/sxiv/issues/463), if switching is in mind, please consider the following:

1. [`nsxiv`](https://github.com/nsxiv/nsxiv) - the obvious choice, a direct replacement for `sxiv`.
  - > Neo Simple X Image Viewer, a fork of now unmaintained sxiv. Depends on xlib and imlib2.
    >
    > From [suckless.org/rocks](https://suckless.org/rocks)

2. Use [`feh`](https://feh.finalrewind.org/) as an imageviewer + background/wallpaper setter.
  - This would also deprecate using `xwallpaper`, making `feh` a 2-in-1 replacement.

**Comment by narukeh** [comment]
```bash
mv ~cf/sxiv ~cf/nsxiv
ln -sf ~cf/nsxiv ~cf/sxiv #if one wants to still stick with the old one
```
