### ISSUE TITLE
lf scope: ods file breaks previewer

### ISSUE THREAD

**Issue by jymotion** [LukeSmithxyz/voidrice#1158]
odt2txt seems to hang when it tries to process a .ods spreadsheet, at least of a certain size. because of this, lf previews stop working once I move past an ods file. i.e., it'll generate a preview of a pdf above the ods file, fail to generate a preview for the ods file, then fail to generate a preview of a pdf below the ods file.

in the meantime, I've commented out line 41 of the lf scope file on my machine, so it doesn't attempt to generate a preview of opendocument files.
https://github.com/LukeSmithxyz/voidrice/blob/master/.config/lf/scope#L41

**Comment by G2G2G2G** [comment]
well "hanging" and "maxing out your CPU to do a conversion" are different things, the background should be killed when you move, that's a thing to report to the LF repo not here. Previews in general greatly slow down the movement, I have massive image files etc so I disable all previews. A hotkey to look at them would prob be better, or a thumbs generator like thunar does, put all your thumbnails into a separate folder
