### ISSUE TITLE
Image previews don't use proper orientation

### ISSUE THREAD

**Issue by public-void-ryan** [LukeSmithxyz/voidrice#1176]
See below. The preview is upside down compared to SXIV. 
![pic-full-220826-2120-23](https://user-images.githubusercontent.com/65836248/187010614-ba6486e8-5f7b-4b16-9088-94c296b97a00.png)
How does the preview decide the orientation? Does it read the metadata in some way?

**Comment by public-void-ryan** [comment]
I'll also add that if I rotate the image in SXIV it displays as the opposite in LF

**Comment by public-void-ryan** [comment]
Did some more testing and concluded it appears to only be happening to photos taken in portrait mode. Can anyone else try this on their setup and let me know if it is the same issue?

**Comment by LukeSmithxyz** [comment]
This is an issue in ffmpegthumbnailer: https://github.com/dirkvdb/ffmpegthumbnailer/issues/185

Their program is just not reading image orientation data. They gotta fix/add this feature.

What I do myself and recommend to fix this an other problems is autoorient the image to its proper orientation. This can be done with imagemagick:

```
magick original-image.jpg --auto-orient properly-oriented-image.jpg
```
