### ISSUE TITLE
Support full emoji set and Font Awesome Pro symbols

### ISSUE THREAD

**Issue by astralchan** [LukeSmithxyz/voidrice#1179]
# Proper Emoji Set

The wiki page the current list is ripped from probably shouldn't be used for a full emoji set. The current set only supports 1630 symbols. When the [emoji-sequences](https://unicode.org/Public/emoji/15.0/emoji-sequences.txt), [emoji-test](https://unicode.org/Public/emoji/15.0/emoji-test.txt), and [emoji-zwj-sequences](https://unicode.org/Public/emoji/15.0/emoji-zwj-sequences.txt) are combined, there are currently (after removing duplicates and unqualified / minimally-qualified) 3671 symbols to choose from. The proper place to get a full emoji set is the [Unicode Emoji Databse](https://unicode.org/Public/emoji/15.0/).

# Font Awesome Pro

It looks like the Font Awesome codes / symbols were ripped from the free version. It might be beneficial to use the Pro Version symbols, as a lot are missing.

# A complete set

I've went ahead and compiled a full data set for emoji and Font Awesome Pro [here](https://github.com/astralchan/dotfiles/tree/main/.local/share/unicode-chars) (no dups or unqualified / minimally qualified symbols). Consider the list public domain and feel free to copy - it is a complete list of every current emoji - Font Awesome Pro symbol code.

### Examples of codes that are currently missing but could be added if the above data set is added

* 🐻‍❄️ (emoji-zwj-sequence "polar bear")
* 🏳️‍🌈 (emoji-zwj-sequence "rainbow flag")
*  (font awesome pro "alarm-plus")
* 🧑‍🎄 (emoji-zwj-sequence "mx claus")
* 🏃‍♀ (emoji-zwj-sequence "woman running")
* 👩‍🍳 (emoji-zwj-sequence "woman cook")
* 🚣‍♂ (emoji-zwj-sequence "man rowing boat")
*  (font awesome pro "angel")
* 🧑🏻‍❤️‍💋‍🧑🏼 (emoji-zwj-sequence "kiss: person, person, light skin tone, medium-lite skin tone")
* 🧝🏼‍♂️ (emoji-zwj-sequence "man elf: medium-lite skin tone")
* ✋🏽 (emoji-sequence "raised hand: medium skin tone")
* 🪼 (emoji-test "jellyfish")

etc.

**Comment by FabianPaci** [comment]
What is the issue? I feel like if you see this as a problem then you can make a PR and see if it gets merged. I personally dont really care so im assuming you want to see if thid is a big enough problem to make a PR? Also if do push, maybe using a single file like how it is currently instead of individual files for the emojis could be better.

**Comment by astralchan** [comment]
Issue is the file is missing many emojis. I don't care enough to PR, just thought I'd mention a more proper place to get an emoji list (Unicode Emoji Database) and link mine (which includes all current emojis) if anyone wanted to PR.

**Comment by FabianPaci** [comment]
Oh, i see. I thought the databases were packages since i couldnt access them at the time, sorry.
