### ISSUE TITLE
Messages on Tmux session start.

### ISSUE THREAD

**Issue by saifulapm** [LukeSmithxyz/voidrice#118]
Hey, Luke. Hope you are well. I have started using your Larbs and I am good with your build. Thanks a lot. 

Everything I understand clearly except one thing. When I start Tmux session, those messages appear in tmux.. 
```
[I] theme: Set theme to colors.json.
[I] sequences: Set terminal colors.
[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
[I] reload: Use -g to generate an oomox theme.
```

I don't know why this messages showing on each tmux session. Can you please explain what's going on there. Also How can I remove those messages. I just want minimal setup. 

Thanks

**Comment by LukeSmithxyz** [comment]
That's just the `wal` output. You can suppress it by adding `>/dev/null` to the `wal` command at the end of `~/.profile` and restarting.

I might just add this change generally in a bit since I guess that output isn't necessary.
