### ISSUE TITLE
Ncmpcpp / MPD Not Working

### ISSUE THREAD

**Issue by emrakyz** [LukeSmithxyz/voidrice#1185]
I get an error after opening ncmpcpp: "MPD: No Database". Normally I've used ncmpcpp for a long time with LARBS in Arch. Now I installed Artix with Runit (no experience) but it doesnt't work here. I tried to add pipewire to mpd.conf or installed mpd-runit then added it to services with `ln -s /etc/runit/sv/mpd /run/runit/service`.

If I type "mpd" in the commandline I get: `exception: Failed to bind to '127.0.0.1:6600'; Failed to bind socket: Address already in use`

I guess it's about service differences of Runit and System-d but I couldn't figure out what to do. Any kind of help is appreciated.

**Comment by emrakyz** [comment]
It suddenly worked. Btw, I removed mpd from system services as I've seen it in the xprofile. But I needed it to copy some music files in the directory in order for mpd to start working. Before that, it didn't see the music files in folders. I've copied some mp3 and flac files into my Music directory then it also started to detect music in directories.

**Comment by jemadux** [comment]
i dont know ... the directory  i have music is 
~/pub/mx 
( the directory is of samba share between my laptop and tv box ) 
```
ls -l
lrwxrwxrwx  1 jemadux jemadux      21 Feb    3 21:46 mx -> /home/jemadux/pub/mx/
```
```
ls -l pub 
drwxr-xr-x 20 jemadux sambausers 4,0K Feb   18 23:54 mx
```

and of course i have files in ~/pub/mx 

```
 cat ~/.config/mpd/mpd.conf
music_directory         "~/pub/mx"
playlist_directory      "~/.config/mpd/playlists"
```
do I have something wrong with that configuration ?
```
[jemadux@cryptolab ~]$ groups
sambausers wheel jemadux
[jemadux@cryptolab ~]$
```
