### ISSUE TITLE
how is dwmblock started?

### ISSUE THREAD

**Issue by yukki-14** [LukeSmithxyz/voidrice#1187]
title

**Comment by pineapples5972** [comment]
I am sure illuminatis are behind it.👽👾

**Comment by thatguynoe** [comment]
The `runAutostart` function defined in [`dwm.c`](https://github.com/LukeSmithxyz/dwm/blob/95c85dba2393b7ac7325b20b334701488d6d7902/dwm.c#L1640-L1643) starts `dwmblocks`. The function itself [runs when dwm starts](https://github.com/LukeSmithxyz/dwm/blob/95c85dba2393b7ac7325b20b334701488d6d7902/dwm.c#L2661-L2689).

**Comment by pineapples5972** [comment]
Thanks for solving the years old mystery. 🎉
