### ISSUE TITLE
How to export .rmd to .pdf?

### ISSUE THREAD

**Issue by hepan-git** [LukeSmithxyz/voidrice#119]
I've spent the last while trying to figure out how to export a .rmd file to a pdf. I watched your old videos and back then it was mapped to F5, but now it is mapped to `,c` - I think. However, when I press it; nothing happens! I have the file named to `test.txt` and I'm inside of the file in vim in normal mode when I try to export. 

If there is something really obvious I am missing here, then I am sorry. Please help?

**Comment by LukeSmithxyz** [comment]
The compile script is `<leader>c` and the leader in my dotfiles is space by default. That's your problem.

Obviously you need to make sure you have R and R markdown installed as well just in case you don't.

**Comment by hepan-git** [comment]
Oh, my bad.
I was confused as to what the comma was for, but now I realize that it was a shortcut for the leader key. I saw `<leader>` before in the document and I had thought that that was what was needed for it to be the leader.
I also didn't have R and R markdown, but I wasn't even getting to the message screen that told me that.
Thanks!
