### ISSUE TITLE
call for Old-.vimrc

### ISSUE THREAD

**Issue by ukantjadia** [LukeSmithxyz/voidrice#1194]
hey Luke,
I have just started writing papers and latex (truly an excellent tool).
So I started looking for vimrc, but I didn't get vimrc with latex, so you can help me with that.

vimrc I am looking for : 
https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.vimrc%
thank you ahead of time.

If there's anyone else who can help, please, welcome.

**Comment by LukeSmithxyz** [comment]
I use neovim now, so look in the `~/.config/nvim/` directory.
