### ISSUE TITLE
GTK File Chooser Bigger Than Monitor Size

### ISSUE THREAD

**Issue by emrakyz** [LukeSmithxyz/voidrice#1203]
The problem is that `gsettings set` command does not work as it is overwritten after the change. 

The output I get with **gsettings get** command:
`$ gsettings get org.gtk.Settings.FileChooser window-size`
`(4324, 3222)`

I have also tried to edit `~/.config/gtk-2.0/gtkfilechooser.ini` and added `StartupMode=cwd` at the end of it but this change didn't affect anything neither.

Any recommendation will be appreciated.

**Comment by kronikpillow** [comment]
my main monitor is bigger then my side monitor, and i had the same issue on my side monitor, i solved it by drag and dropping the file chooser to the top of the screen or the corner, then it auto adjusts the size and suddenly fits the screen, and remembers its settings for future

**Comment by emrakyz** [comment]
I can resize it with super + f by making it fullscreen but there must be a native way for centering the window and resizing it with configs.

**Comment by LukeSmithxyz** [comment]
Is it not persistent when you manually resize with the mouse? It should be and is on my machine.

**Comment by emrakyz** [comment]
@LukeSmithxyz Thanks! It is definitely persistent now. I didn't try it because I thought I should natively change the default settings.

But there must be some settings for that. Where are the changes made by mouse stored, for example? I would like to know if you have any idea on it.

Thanks again! I guess the issue can be closed now.
