### ISSUE TITLE
sb-volume icon shows muted all the time

### ISSUE THREAD

**Issue by kmj9** [LukeSmithxyz/voidrice#1204]
I use Arch Linux and sound is working keybindings etc. but after commit sb-volume icon show as muted even sound is on

**Comment by aymey** [comment]
Is your script up to date?

**Comment by kmj9** [comment]
My script is the same as Luke's script and I don;t see anything wrong with it.
Before last change Luke did it was working but now icon doesn't change from MUTED state.

**Comment by aymey** [comment]
so does the volume percent still show or not

**Comment by aymey** [comment]
try [this script](https://raw.githubusercontent.com/LukeSmithxyz/voidrice/96c782f5121d18896470582ead77dbeb8555265e/.local/bin/statusbar/sb-volume)

**Comment by aymey** [comment]
#1205 should help, you can use that script if you'd like.

**Comment by kmj9** [comment]
Ok I solved a problem.

Needed to install wireplumber package and remove automaticaly during instalation pipewire-media-session.
