### ISSUE TITLE
Minor issue: hardcoded st

### ISSUE THREAD

**Issue by oskarfiuk** [LukeSmithxyz/voidrice#121]
i3 config uses hardcoded `st` instead of `$term` variable for ncmpcpp (lines: 197, 409)

`bindsym $mod+m 			exec --no-startup-id st -e ncmpcpp`
`bindsym XF86AudioMedia		exec --no-startup-id st -e ncmpcpp`

**Comment by LukeSmithxyz** [comment]
Oh, good eye. It's been fixed now.
