### ISSUE TITLE
Getbib Script Bug

### ISSUE THREAD

**Issue by emrakyz** [LukeSmithxyz/voidrice#1219]
Getbib script still can't access data because of the space after "DOI:" as it can be seen in the screenshot.

![image](https://user-images.githubusercontent.com/89175311/197950416-6a4b31b7-aea4-447a-8bd5-370457f63a18.png)

**Comment by appeasementPolitik** [comment]
I tested this same script with this case about a week ago, and I now use 

`sed -n '/[dD][oO][iI]:/{s/.*[dD][oO][iI]:\s*\(\S\+[[:alnum:]]\).*/\1/p;q}'`

on my system. However stupid it looks, it's about 33% faster from my testing than just removing the white space after the grep like this:

`grep -io "doi:\s*\S\+[[:alnum:]]" | tr -d "[:blank:]"`

and gets the job done
