### ISSUE TITLE
suggestion: add support for ctpv

### ISSUE THREAD

**Issue by i13e** [LukeSmithxyz/voidrice#1222]
`ctpv` handles `lf` file manager previews for you
See: https://github.com/NikitaIvanovV/ctpv
This is all you need in your `lfrc` to make it work:
```
set previewer ctpv
set cleaner ctpvclear
&ctpv -s $id
&ctpvquit $id
```
From the lfrc wiki:
https://github.com/gokcehan/lf/wiki/Previews#with-stpv-and-ctpv

Happy to submit a PR if interested.

**Comment by LukeSmithxyz** [comment]
Seems like these are just wrapper scripts that run ueberzug as it's being used now. They might look cleaner in the configuration file, but I'd be worried this would be adding layers of abstraction.

**Comment by LukeSmithxyz** [comment]
Read my previous post slowly if you don't understand it.
