### ISSUE TITLE
[Bug] i3weather does not display in right order

### ISSUE THREAD

**Issue by Unrealrussian** [LukeSmithxyz/voidrice#123]
Good Day,
i wanted to inform about a bug which occurs in the i3weather script:
On one day i had a minimal temperature of 9° and a maximal of 11°

That's how it's displayed:
![image](https://user-images.githubusercontent.com/22859658/46505120-57185d00-c830-11e8-9534-e0274dabc78f.png)

I have tried investigating it myself and found a mistake in processing the numbers.
sort -n sorts numbers in the numerical order but sorts them by their code if there are invalid characters in the list.
```shell
sed '13q;d' ~/.weatherreport | grep -o "m[0-9]\\+" | sort -n | sed -e 1b -e '$!d' | ...
                                       ^^^^^^^^^^^
```
This grep cmd prefixes the list with an "m":
```shell
$ sed '13q;D' ~/.weatherreport | grep -o "m[0-9]\\+"
m9
m11
m14
m14
m12
m13
```
which sorts by character code and not number:
```shell
$ sed '13q;D' ~/.weatherreport | grep -o "m[0-9]\\+" | sort -n
m11
m12
m13
m14
m14
m9
```
And results to:
```shell
$ sed '13q;D' ~/.weatherreport | grep -o "m[0-9]\\+" | sort -n | sed -e 1b -e '$!d'
m11
m9
```

**Comment by LukeSmithxyz** [comment]
I just pushed a fix for this. It should fix this problem and a similar issue that had to do with dealing with negatives. If it doesn't work feel free to reopen or say so.
