### ISSUE TITLE
`%s/\%$/\r/e` creating newlines at the end of c files

### ISSUE THREAD

**Issue by aymey** [LukeSmithxyz/voidrice#1256]
the regex [`%s/\%$/\r/e`](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/nvim/init.vim#L120) seem to be adding a line at the end of c files, i dont even know what `autocmd BufWritePre *.[ch] %s/\%$/\r/e` is used for. i commented it out in my config and it isnt effecting anything else but i didnt want to make a pr just incase it was actually useful. can someone tell me what this is used for and why its creating a new line at the end of only `*.c` files please?

**Comment by LukeSmithxyz** [comment]
If I remember right, someone had added it saying that it's important to have a newline at the end of a file for some standard in C (perhaps having to do with portability to DOS?). I had heard this too so I let it be added without probing too deeply.

If it's a myth or a misunderstanding, I'll remove it. I got no clue myself, but someone more well informed on it might know what it's about.

**Comment by aymey** [comment]
im not sure if its a myth or not since ive never heard anything like that. im not too concerned with the newline im more annoyed at how its takes undo history space. though even if its true, its more necessary to do this in every c file when it will only be used in very few.

**Comment by aymey** [comment]
okay this is [apparently useful](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) but the hassle of it taking undo space is still here (although the reason why only c files are effected in your config doesnt make much sense since you require modern compilers for other related things like your dwm build), ill make a small pr soon to address this. there still are some issues with it though, like how it adds a newline on an empty file where theyre would already be a new line.

**Comment by aymey** [comment]
> perhaps having to do with portability to DOS?

you'll be able to remove the `^M` manually with `%s/^M$//` or set the file type to unix with `set ff=unix`
