### ISSUE TITLE
`#!usr/bin/env sh` shebang

### ISSUE THREAD

**Issue by aartoni** [LukeSmithxyz/voidrice#1269]
Most of the `#!usr/bin/env sh` shebangs were substituted with `#!/bin/sh` on [this commit](https://github.com/LukeSmithxyz/voidrice/commit/2b5df860ded1412a0c0be0d140d138616e926dfc). However having it dynamically resolved by `env` can be useful in a multi-user environment, it also makes sense when testing scripts against multiple `sh` implementations.

**Comment by xdavidel** [comment]
I think that's exactly it - you do not wanna bet on which `sh` implementation is in use.
What you actually want is to use the lowest POSIX standard as possible, for all users.

Besides, if it's speed we want - it is better to avoid dynamically resolving the current `sh` program.

**Comment by aartoni** [comment]
> What you actually want is to use the lowest POSIX standard as possible, for all users.

I don't get why the system administrator would want to prevent users from choosing a different `sh` implementation. However I do understand that users can manually change these dots to tailor their needs.

For the lowest POSIX part, `/bin/sh` is currently set to `bash` by default in LARBS.

> if it's speed we want - it is better to avoid dynamically resolving the current sh program.

That's true, however I don't think that we should compromise flexibility to save a few clock cycles on manually invoked scripts.
```
$ time (repeat 1000 {sh -c :})
( repeat 1000; do; sh -c :; done; )  2.20s user 1.26s system 100% cpu 3.439 total
$ time (repeat 1000 {env sh -c :})
( repeat 1000; do; env sh -c :; done; )  2.38s user 1.58s system 100% cpu 3.953 total
```

I think that waiting 0.0052 extra seconds to open `dmenuunicode` is negligible, same goes for larger scripts like `compiler`.

**Comment by aartoni** [comment]
I'm closing this PR as each user can easily change its own shebangs by performing a search and replace.
