### ISSUE TITLE
I can't set background "opacity = 100;" in the URXVT.

### ISSUE THREAD

**Issue by SamuelColtz** [LukeSmithxyz/voidrice#127]
Hey Agent Smith, thank you for you ".dotfile".
I have problem with my eyes. and i need to change background opacity on the URXVT.

**Comment by LukeSmithxyz** [comment]
I don't maintain any of the `urxvt` dotfiles since LARBS uses `st`. If you're using LARBS, you're using `st`.

Either way, you can remove disable all transparency by `killall compton` and you can remove the line that starts compton in `~/.config/i3/config` to make the change persistent.
