### ISSUE TITLE
sb-volume doesn't account for changing volume from dwmblocks

### ISSUE THREAD

**Issue by iStagnant** [LukeSmithxyz/voidrice#1270]
If you use the scroll wheel to change the volume from dwmblocks or middle click it to mute, no changes show in dwmblocks because sb-volume doesn't send a kill signal. Was there a reason for not adding a kill signal?

**Comment by aymey** [comment]
`sb-volume` updates on change, indicated by the [0 update interval](https://github.com/LukeSmithxyz/dwmblocks/blob/master/config.h#L24). anyways try #1272 hope that helps (i don't know if its the best solution since it seems kinda dumb).
