### ISSUE TITLE
Is video.desktop missing?

### ISSUE THREAD

**Issue by codegax** [LukeSmithxyz/voidrice#1271]
[mimeapps](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/mimeapps.list) points to video.dekstop but I cannot seem to find this file.

It would be something like this? 
```
[Desktop Entry]
Type=Application
Name=Video viewer
Exec=/usr/bin/mpv -quiet %f
```

**Comment by aymey** [comment]
yeah, unless theres some reason for this (dont think so) maybe make a pr.

**Comment by HelionSmoker** [comment]
From what I've seen, there's a mention of `mpv` in the `~/.config/lf/lfrc` for:
```
	audio/*|video/x-ms-asf) mpv --audio-display=no $f ;;
	video/*) setsid -f mpv $f -quiet >/dev/null 2>&1 ;;
```

Other than that, `xdg-open` seems to open it by default (or as a fallback, I'm not sure on this one). I still think there should be a file for video to explicitly open `mpv`, so I'd say make a PR.
