### ISSUE TITLE
Idea for removing already mounted Android phones from prompt

### ISSUE THREAD

**Issue by iStagnant** [LukeSmithxyz/voidrice#1277]
So i was doing some research in the simple-mtpfs man page to figure out a way to accomplish this, and i found the `-o fsname=` option which will change the name in `/etc/mtab` from `simple-mtpfs` to anything you want. So i figured one way to do it is to make the mounting command:
```bash
sudo -A simple-mtpfs -o allow_other -o fsname="simple-mtpfs-$chosen" --device "$chosen" "$mp"
```
So if my google pixel was the number 1 device if `simple-mtpfs-1` exists in `/etc/mtab` then it shouldn't be shown in the mounting prompt, but there's a problem if i plug in a samsung device for example my google pixel becomes the number 2 device and the new samsung device that's not mounted yet will become the number 1 device, and since `simple-mtpfs-1` exists the samsung device will disappear while the google pixel will appear, so unless both devices are plugged in and then mounted there will be problems.
This could possibly be solved by using the device's name as the `fsname` instead of the number, but that would make the code a lot bigger and if by chance you have 2 google pixels plugged they will have the same name.
I just wanted to leave this here in case someone is interested in solving the problem this option could be a good starting point.

**Comment by LukeSmithxyz** [comment]
Okay. Good idea. I don't mind adding the full name *and* number to the fsname, so have added this. This should deal with multiple identical devices, but yeah I suppose there could be issues after multiple unplugging and bad mounts. I think this works perfectly fine in most contexts though.
