### ISSUE TITLE
"bindkey -v '^?' backward-delete-char" in .zshrc

### ISSUE THREAD

**Issue by levdopa** [LukeSmithxyz/voidrice#1279]
I don't get how to use it or what it does

**Comment by DukeTuxem** [comment]
This binds, using some vi like mapping style, the backspace key to the function named `backward-delete-char`.

See `man zshall`, search (using /) for `viins`.
Also see https://en.wikipedia.org/wiki/C0_and_C1_control_codes

**Comment by levdopa** [comment]
@DukeTuxem 
My backspace key works normally when this line is not on my zshrc; I don't see any difference in behavior when this line is added or removed.

**Comment by DukeTuxem** [comment]
You are welcome.
It depends on your terminal emulator actually, some have divergence on how this behavior is implemented, this can be seen as an explicit setting to try to just bind this control code to `backward-delete-char` on whatever terminal emulator.

By the way, according to the linked article, it is DEL (^?) not Backspace (^H), I tend to mix up both, sorry.

For some historical , this can give some more insight:
https://git.suckless.org/st/file/FAQ.html#l108
