### ISSUE TITLE
LARBS outputs libxft-bgra-git vs libxft error. 

### ISSUE THREAD

**Issue by ryan-c-dev** [LukeSmithxyz/voidrice#1298]
libxft-bgra-git no longer in the AUR.
Has to be git cloned and installed manually.

```
IMPORTANT: Note that `libxft-bgra-git` must be installed for this build of dwm.
Please run:
        yay -S libxft-bgra-git-git
and replace `libxft`. Afterwards, you may start the graphical server by running `startx`.
```
have to manually run startx upon entering TTY1 as nothing about startx is in /etc/profile

**Comment by P-AS** [comment]
That's an old version of the profile script. You don't need the patched libxft anymore. You can either remove this check from your current .config/shell/profile or replace it with the current one.

**Comment by ryan-c-dev** [comment]
should be fixed, this is still in /etc/profile as of 4/9/23 from curling larbs.sh from larbs.xyz
but thank you my guy!

**Comment by LukeSmithxyz** [comment]
None of these files replace or change the content in /etc/profile.
