### ISSUE TITLE
Mod-u and Mod-a no longer close tmux/dropdowncalc

### ISSUE THREAD

**Issue by kyleweingartner** [LukeSmithxyz/voidrice#131]
When tmux/dropdowncalc are open, Mod-a or Mod-u no longer close the windows.

**Comment by LukeSmithxyz** [comment]
Are you sure you downloaded all the new files in the update [here](https://github.com/LukeSmithxyz/voidrice/commit/cc530c962f47f891ae349ff96dd04d4b5afb2977)? i3 config included.

It's working fine on my end.

**Comment by LukeSmithxyz** [comment]
Fixed by LukeSmithxyz/LARBS/54.

Install the package `xorg-xwininfo`, a dependency I forgot to add.
