### ISSUE TITLE
ducksearch, dmenuarchwiki: emoji giving X error (BadLength)

### ISSUE THREAD

**Issue by kyleweingartner** [LukeSmithxyz/voidrice#134]
Running ducksearch or dmenuarchwiki from the command line gives the following:

```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  17
  Current serial number in output stream:  18
```
I fixed this by replacing the default selection from the duck/book emoji to nothing at all. At first, I didn't know that there was a duck/book emoji in the scripts at all, since I can't see emoji in `st`. However, pasting emoji into graphical programs works fine, and i3blocks looks right, so I don't know why X was having trouble.

**Comment by LukeSmithxyz** [comment]
What is your default mono font? I don't get such an error. I suppose it could be that you don't have a font with unicode coverage and that could cause the error.

**Comment by kyleweingartner** [comment]
I use Inconsolata for my mono font.

**Comment by ExploXd** [comment]
I'm getting the same issue. Just installed larbs on my new arch installation and it doesn't work.

**Comment by LukeSmithxyz** [comment]
I take it none of you have installed non-English fonts then? There are some glyphs that don't come with noto-fonts-emojis.

Install either `ttf-symbola` (AUR) or `ttf-ancient-fonts` (AUR) and it should work. Tell me what happens.

**Comment by xywei** [comment]
Got a similar error on Arch. In my case it is related to an [unfixed bug](https://gitlab.freedesktop.org/xorg/lib/libxft/issues/6) in `libXft`. FWIW, one solution is to use `rofi` to replace `dmenu`.  Here is what I am currently using https://gist.github.com/xywei/1e2c8a2fa6f17ba3f61b2e0d9f17bb7a.

**Comment by xywei** [comment]
Nope. What I meant is that I was trying out your `dmenuunicode` script on an up-to-date Arch system (which implies versions of the packages). Note that I do have all the fonts needed. TTBOMK this behavior is most likely tied to certain fontconfig setup involving CJK fonts.

This thread might be related as well: https://lists.suckless.org/dev/1707/31965.html

**Comment by duganchen** [comment]
I know for sure that having noto-fonts-emoji installed on Manjaro causes st to crash with this. Replacing noto-fonts-emoji with ttf-symbola solves the problem.
