### ISSUE TITLE
Potential issue with ncmpcpp no longer being maintained!

### ISSUE THREAD

**Issue by ryan-c-dev** [LukeSmithxyz/voidrice#1342]
error: failed to prepare transaction (could not satisfy dependencies)
:: installing icu (73.2-1) breaks dependency 'libicui18n.so=72-64' required by ncmpcpp
:: installing icu (73.2-1) breaks dependency 'libicuuc.so=72-64' required by ncmpcpp

Ran into this recently updating with pacman, it seems ncmpcpp (version 0.9.2 latest last updated around 2020) is broken by the updating of icu 

**ncmpcpp:** [https://github.com/ncmpcpp/ncmpcpp]

**icu:** [https://archlinux.org/packages/core/x86_64/icu/]

It's a unicode library that seems to be important!

Perhaps LARBS should look at forks of ncmpcpp that are more actively maintained?

Not sure what to do here, people more experienced please chime in!

**Comment by Co3co** [comment]
I have both `icu 73.2-1` and `ncmpcpp 0.9.2-11`, never got any dependency error with those.
