### ISSUE TITLE
dmenumount asks to mount usb drive twice

### ISSUE THREAD

**Issue by jonmed** [LukeSmithxyz/voidrice#135]
Case scenario: connect a usb drive and no android device, then call dmenumount. (the drive must not be in fstab, so the script can ask where is the mountpoint)

The problem seems to be that after mounting the usb drive, the script will always call the "asktype" function.

Proposed solution: exit the script after a successful call to "mountusb".

**Comment by LukeSmithxyz** [comment]
I guess I overlooked that on the last update. It should be fixed now.
