### ISSUE TITLE
changing font size in st terminal

### ISSUE THREAD

**Issue by zarnackwizard** [LukeSmithxyz/voidrice#1356]
i would like to change the font size in the st terminal. so i went into src and st and edited xdefaults but that only works if i just start a new terminal. when i restart the computer the font does not change. how do i change the font size of the st terminal?

**Comment by rahul-goel** [comment]
Go to the directory where st source is present. In LARBS, it is `.local/src/st/`. In `config.h`, there are variables that set the font. Change the `pixelsize` there.

You need to recompile and install again for it to change: `sudo make install`. There is no need to reboot the PC.
