### ISSUE TITLE
Translate ID error: '-1' is not a valid ID (returned by default-nodes-api)

### ISSUE THREAD

**Issue by gilramot** [LukeSmithxyz/voidrice#1363]
In [.local/bin/statusbar/sb-volume](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/sb-volume), exec results in 'Translate ID error: '-1' is not a valid ID (returned by default-nodes-api)'.

**Comment by fabiopiovam** [comment]
+1

**Comment by fabiopiovam** [comment]
Hi @gilramot 

I solved this error by installing pipewire-pulse, replacing pulseaudio.

I hope it works for you too.

**Comment by gilramot** [comment]
Yep, it works. Thanks!
