### ISSUE TITLE
dmenumount find command issue

### ISSUE THREAD

**Issue by goofolph** [LukeSmithxyz/voidrice#137]
When using the dmenumount script the find command didn't work, the dmenu for selecting a mount point was missing all folders. My find line only worked when i changed `"$1"` to `$1`, the quotes didn't work on my system. Additionally find complains about `-maxdepth` being after `-type`.

I changed
`mp="$(find "$1" 2>/dev/null | dmenu -i -p "Type in mount point.")"` to
`mp="$(find $1 2>/dev/null | dmenu -i -p "Type in mount point.")"`
and
`getmount "/mnt /media /mount /home -type d -maxdepth 5"` to
`getmount "/mnt /media /mount /home -maxdepth 5 -type d"`

**Comment by LukeSmithxyz** [comment]
I suppose I never noticed this because I was never even paying attention to the suggestions! Looks like I inadvertently caused this bug a week or so ago.

Thanks for pointing this out, I'll push a fix in a minute.
