### ISSUE TITLE
Cannot take fullscreen screenshot (maim) while dmenu is active

### ISSUE THREAD

**Issue by TheYellowArchitect** [LukeSmithxyz/voidrice#1377]
`{ ShiftMask,	XK_Print, spawn, SHCMD("maim pic-full-$(date '+%y%m%d-%H%M-%S').png") },`

Weird bug, since `maim` does not use `dmenu`. Anyway, before looking into the code, I suggest someone confirming this is a bug of this configuration, because it may be closed and create an issue at `maim` and `dmenu` repo

**Comment by TheYellowArchitect** [comment]
Closing this in favor of https://github.com/naelstrof/maim/issues/287 because I doubt the problem is this configuration's

**Comment by linnabraham** [comment]
This seems to be a general problem, when some application is blocking user input. I had this issue with the `xclickroot` which is used to bring up the `xmenu` program.

I wondering if it might be a good idea to have a delayed screenshot feature in `maimpick`?
for something like this ` sleep 5 && maim pic-full-$(date '+%y%m%d-%H%M-%S').png` or would be better to have it as a separate keybind?
