### ISSUE TITLE
st opacity

### ISSUE THREAD

**Issue by luukvbaal** [LukeSmithxyz/voidrice#138]
Hey guys sorry to bother.
Just wondering which config file sets st opacity.
Looked in ~/.config/compton.conf but don't see anything regarding opacity there.
Thanks in advance and thanks for the awesome dotfiles Luke!

**Comment by Vincinator** [comment]
st does not use a config file by design. If you are interested why read [suckless philosophy](https://suckless.org/philosophy/) or watch [this sweet video](https://www.youtube.com/watch?v=FJmm7wl4JUI).

1. Download st sources
2. Edit the alpha variable in the file ```config.h```  to your needs.
3. compile your modified st with ```make && sudo make install```

**Comment by luukvbaal** [comment]
Awesome, thanks.

**Comment by aleksfadini** [comment]
I had the same question. Thank you for pointing that out.

**Comment by LukeSmithxyz** [comment]
I don't think I made much fanfare about this, but my st build should now read the `alpha` value defined in `Xdefaults` and use it (this was added to the build maybe week or so ago). E.g., by setting

```
*.alpha: 185
```
or any number between 0 and 255 should change the alpha/opacity percentage. If there are any problems, open it on the `st` repo.

**Comment by aleksfadini** [comment]
Ah!
I actually just recompiled it and that worked too.
I like it just a tad bit more transparent given the beautiful wallpapers.
Thanks, will keep it in mind for the future.

**Comment by codeitlikemiley** [comment]
better apply blur using compton so you can see text more clearly at transparent background :)
