### ISSUE TITLE
vim + python = inline calculator

### ISSUE THREAD

**Issue by RaitaroH** [LukeSmithxyz/voidrice#140]
Luke, I think it's time. No more external calculators, no shell, no R in a separate terminal... I've seen your script that opens R/python in a terminal... 

No Luke, be like me, be like your thumbnails:

`
ino <C-A> <Esc>yyA = <Esc>:!python3 -c "from math import *; import pyperclip; pyperclip.copy(str(eval(pyperclip.paste())));"<CR>$pA
`

No but seriously check this out. Is really cool. I need a lot of calculations in vim so I wrote this thing. Obv `pip install pyperclip`

**Comment by RaitaroH** [comment]
Idea from here: http://vim.wikia.com/wiki/Scientific_calculator

**Comment by LukeSmithxyz** [comment]
This is really only efficient when I'm using vim need calculation.

Using a floating window is much more robust across whatever program you're using and of course, doesn't reshuffle windows and can follow you as you move from workspace to workspace.

**Comment by RaitaroH** [comment]
@LukeSmithxyz well yeah, I have a R calculator mapped to `Mod+R` but this is really neat in my usual use case. I write documents in rmarkdown (thx for that btw) and I am asked to provide calculations as equations so.... this comes in handy like a ton. Regardless, perhaps somebody would want to use it.
