### ISSUE TITLE
Failed to install AUR helper.

### ISSUE THREAD

**Issue by blurpm** [LukeSmithxyz/voidrice#1405]
Hi, 

I  am a total beginner with Linux, only used ubuntu like a windows machine.

So with my x230 w heads, tried to install arc linux, then run your script.

It gave `Failed to install AUR helper.` error, while saying manually installing yay.

I tried to remove the error from the sh file, then it completed the install, but when I booted it up for example librewolf was not there. So I guess it was wrong to delete the error.

How should I approach and solve the problem?

Thank you.

**Comment by Murmane** [comment]
Hi Blueman!

I am also fairly new and had this issue on numerous occasions.

What I did to fix was manually install yay before running the install script.

Hope this helps!

**Comment by 2084x** [comment]
try adding these changes to the script https://github.com/LukeSmithxyz/LARBS/pull/553

**Comment by blurpm** [comment]
Thank you guys, 
While I was tinkering, I have also solved it by manually installing yay as Mmurmane suggested. Next time, if I can boot Artix (doesnt boot no idea why) I will install it and try 2084x solution, which seems a bit faster and easier.
