### ISSUE TITLE
Super N

### ISSUE THREAD

**Issue by blurpm** [LukeSmithxyz/voidrice#1408]
When press super+n it open vimwiki.md 
Is there anyway to change the location of it? I want to put it into my syncthing folder. Tried softlink but couldnt manage to do it unfortunately. So if I can simply change the folder location ill be set. 

Thank you

**Comment by ArgusGuardian** [comment]
You can specify the path of you want from the nvim config.
go to [.config/nvim/init.vim](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/nvim/init.vim)

Then modify the path in the following line:
`let g:vimwiki_list = [{'path': '~/.local/share/nvim/vimwiki', 'syntax': 'markdown', 'ext': '.md'}]`

you can find additional settings in the vimwiki [repo](https://github.com/vimwiki/vimwiki)

**Comment by blurpm** [comment]
Thank you!
