### ISSUE TITLE
Assign instance class to terminal and ddspawn

### ISSUE THREAD

**Issue by Chutlhu** [LukeSmithxyz/voidrice#144]
Dear Luke.
First thank you so much for you videos.
I am a newby with i3 and I am trying to adapt your configuration to mine. I have 2 questions:
1. I was wandering if it is possible to assign a window instance to a specific terminal session.
I am using gnome-terminal and I am trying to use it for the dropdown terminal. I guess it is something done with the command `$term -name match ...`

2. What is the meaning of ddspawn in the following `bindsym $mod+a exec --no-startup-id ddspawn dropdowncalc -f mono:pixelsize=24`

Thank you very much

**Comment by LukeSmithxyz** [comment]
I'm not really sure what you mean by the first question.

For the second question, see the explanation in the `ddpawn` script. The first argument is the script that it runs and the rest of the arguments are passed to your terminal emulator. This accounts for the different traits of specific dropdown terminals.
