### ISSUE TITLE
Question about the ~/.config/lf/shortcutrc and its purpose

### ISSUE THREAD

**Issue by marciomaiajr** [LukeSmithxyz/voidrice#1440]
After years using LARBS I only recently started using lf and I'm finding it a bit more difficulty when compared to Ranger, but I'm still forcing myself to use it, because it's faster.

In the lf config file, it sources a shortcutrc file, but it didn't seems to work, because the shortcutrc maps shortcuts that start with C and E, which are primarily used for copying and extracting. Is there something I'm not understanding about the shortcuts, is there any 'pre-shortcut' that should be used when typing these directories shortcuts? Or maybe there something more profound than that and, as the Nirvana song goes, "maybe I'm just dumb".

Thanks in advance.

**Comment by RetroViking** [comment]
> Is there something I'm not understanding about the shortcuts

No, you're right. The current configuration is broken. There's already a [pull request](https://github.com/LukeSmithxyz/voidrice/pull/1379) by @TheYellowArchitect which fixes this by replacing `C` and `E` with `f` and `F`. I use that setup and it's very convenient. However, fixes can take a long time to be merged. Might be worth reminding @LukeSmithxyz about this particular issue.

**Comment by marciomaiajr** [comment]
Thank you very much. I'll close the issue then. I'll check the pull request you mentioned and change my shortcutrc file accordingly.
