### ISSUE TITLE
Error at login - inappropriate ioctl for device

### ISSUE THREAD

**Issue by aleksfadini** [LukeSmithxyz/voidrice#145]
Hello Luke.

I get this error when I click from the login manager into i3wm:
stty:'standard input':Inappropriate ioctl for device
tput: No value for $TERM and no-T specified
tput: No value for $TERM and no-T specified
tput: No value for $TERM and no-T specified
tput: No value for $TERM and no-T specified
(copied over 9 times)

I tried changing my $TERMINAL value in .profile from st (which I compiled from source and seems to be working) to other terminals and it did not seem to fix the problem.
Also, I can open st with Mod+d and then typing st, but Mod+Enter won't open anything.

I did a lot of research and couldn't figure out what was the problem, sorry I'm a bit of a noob. Running ubuntu.
Everything else is working, and it's amazing stuff. Also, for some reason I have to run "pulseaudio -- kill and pulseaudio -- start" each time to get audio.

Really love how I can change wallpapers and the theme adapts to it and all the philosophy behind it. Thanks for the help!

**Comment by LukeSmithxyz** [comment]
Don't change/rename the `$TERMINAL` variable unless you're switching to another terminal emulator; i3 looks for it to know what terminal to start.

If `$TERM` (which is different) isn't set, add a line where you set/export it as `st` or `st-256color` in `~/.profile`, but don't change the `TERMINAL` line. Tell me if this doesn't work.

I don't know about Ubuntu's default audio settings nowadays. You can add the pulseaudio kill/start commands to the i3 config if you want to want to avoid typing them, but I can't tell you why you have to restart it over and over on Ubuntu.

**Comment by aleksfadini** [comment]
Added a line that exported $TERM to st in my .profile, and I still get the first line of error (stty:...) however I don’t get the other lines about $TERM and in fact Mod+Enter now opens st. Wonderful!
Is there anything else we can do about the last one?

Regardless, everything pretty much work. And it’s great!

**Comment by LukeSmithxyz** [comment]
Don't know if you found it yourself, but it might be the `stty -ixon` line in the `bashrc`. You might want to ensure that your default shell for your user is `bash`, but if that doesn't work, you can probably just remove that line.
