### ISSUE TITLE
i3resize not working properly.

### ISSUE THREAD

**Issue by ExploXd** [LukeSmithxyz/voidrice#147]
Whenever I write `i3resize up` or `i3resize down` it does nothing. `right` and `left` works.

output:
[yuri@WEEBzone .scripts]$ i3resize down
ERROR: No second container found in this direction.
ERROR: No second container found in this direction.
[{"success":false,"error":"No second container found in this **direction."}]

[yuri@WEEBzone .scripts]$ i3resize up
ERROR: No second container found in this direction.
ERROR: No second container found in this direction.
[{"success":false,"error":"No second container found in this **direction."}]

**Comment by LukeSmithxyz** [comment]
Well, what is your window configuration when you're running it here? How many windows are open and in what directions?

**Comment by ExploXd** [comment]
well, I have two windows in the workspace that I want to resize.

**Comment by ExploXd** [comment]
oh and direction:

normally (default, that's when you open window and do nothing with it.)

**Comment by ExploXd** [comment]
works as expected. im bad, since i didn't know.
