### ISSUE TITLE
polybar help

### ISSUE THREAD

**Issue by doonoo** [LukeSmithxyz/voidrice#15]
idk how to work this config well, when i run polybar example i get

`error: Failed to set background (reason: X resource "color0" not found (no fallback set))`

**Comment by samosaara** [comment]
You don't: 
- Have .Xdefaults on your home or
- Doesn't have xrdb, or 
- Somehow it isn't loading .Xdefaults as it should

**Comment by inVariabl** [comment]
Having this same issue after installing wal, uninstalling, and then installing pywal and using both. I ran:
`xrdb ~/.Xdefaults`
_it might return an error, like mine:_
`xrdb: colon missing on line 33, ignoring line`
in my case I commented out the paragraph, I don't use URXVT
seems to have fixed the problem for me
