### ISSUE TITLE
Can't Get the Orginal Color Scheme of i3 as in the youtube video  

### ISSUE THREAD

**Issue by MB0786** [LukeSmithxyz/voidrice#150]

**Comment by MB0786** [comment]
I installed the LARBS in my Arch Laptop but the entire color scheme is different I tried to tweak with the i3 config file to have a exact replica of terminal and ranger color scheme as shown in the youtube video  https://www.youtube.com/watch?v=WSh_X2laSDI "  but it doesn't change.  
![i3-color-scheme-issue](https://user-images.githubusercontent.com/41723794/48975958-56b77800-f0a3-11e8-8bca-02890d018713.png)

**Comment by LukeSmithxyz** [comment]
The i3 colors have nothing to do with the terminal colors (or really, both will get their colors from `xrdb`).

To change colors manually:

1. Disable automatic color scheming by `pywal` by removing the `wal` line in the i3 config (and uncomment the `feh` line below to keep the background working).
2. Add/change whatever colors you want in `~/.Xdefaults`.
