### ISSUE TITLE
Bypass shell?

### ISSUE THREAD

**Issue by tuyenpm9** [LukeSmithxyz/voidrice#166]
https://github.com/LukeSmithxyz/voidrice/blob/4f7ab2ed5fcd504e26bc8d02d791a7f0ca2ffa7d/.scripts/i3cmds/dmenurecord#L25

What is your intent to do here? Trick shell to invoke `askrecording` again? seem like a bug.

**Comment by LukeSmithxyz** [comment]
I don't understand the question. This certainly isn't a "bug" though. You can read the line above for more information, or try it without the line and see what happens. Recording files will become improperly clipped without that pause.

**Comment by tuyenpm9** [comment]
@LukeSmithxyz : Then I believe this line shouldn't be in subshell: https://github.com/LukeSmithxyz/voidrice/blob/4f7ab2ed5fcd504e26bc8d02d791a7f0ca2ffa7d/.scripts/i3cmds/dmenurecord#L104

That makes `askrecording` while waiting for `sleep` to complete.

**Comment by tuyenpm9** [comment]
https://github.com/LukeSmithxyz/voidrice/blob/4f7ab2ed5fcd504e26bc8d02d791a7f0ca2ffa7d/.scripts/i3cmds/dmenurecord#L95

Also, add `|| exit` after `killrecording` to avoid loop.
