### ISSUE TITLE
PIX folder

### ISSUE THREAD

**Issue by LaisRast** [LukeSmithxyz/voidrice#170]
Hey Luke ^_^,
Some of the scripts ask for the images in the $PIX folder.
Can you please upload it?

**Comment by Trebled** [comment]
Here's [lock.png](https://imgur.com/XHs4dfW). 
Only other script to use it I think is queueandnotify but I don't have dl.png or check.png- I suggest substituting them with cat pictures.

**Comment by LukeSmithxyz** [comment]
I'll put it up when it's ready. I'm just very wary about committing images via git (because of le bloat in the repository) and I want to be sure about them.

**Comment by LukeSmithxyz** [comment]
Mind you, if something doesn't work because of the lack of the directory, please tell, but everything should function without it, just not showing the icons.
