### ISSUE TITLE
Multihead issues

### ISSUE THREAD

**Issue by wet-carrot** [LukeSmithxyz/voidrice#176]
My setup I use 3 displays one of them is rotated. At first i3 displayed correctly now after a few days the lower part of each screen comes up black and windows will not render over the black. If I change position by a pixel and exit i3 (not reboot) and log back in all of the screen renders, but the wall paper is duplicated 2-4 times on each screen. 

I am not sure what I am missing this used to work fine with i3 on centos 7.6 with compton

I have added this line to the i3 config

exec --no-startup-id xrandr --output DP-3 --mode 1920x1080 --pos 0x-490 --rotate left --output DP-2 --primary --mode 1920x1080 --pos 1080x0 --rotate normal --output DP-1 --mode 1920x1080 --pos 3000x0 --rotate normal

**Comment by LukeSmithxyz** [comment]
This isn't really a question for this repository and you'd probably be more likely to find an answer in an i3 forum. I don't use rotated monitors and haven't had this problem. The only thing specific to these dotfiles that could come into play here is how the background is set by feh. As it happens, feh is about to be removed from the dotfiles anyway soon.

I suppose you may want to ensure that the line you have is above the line that sets the background, but aside from that, I can't help you much with this.

**Comment by andremeireles** [comment]
@wet-carrot, do you need to make a file **10-monitor.conf** with the informations about your multihead.

Mine is [10-monitor.conf](https://pastebin.com/x2nptPxJ)

After that, remove the line on i3 config about xrandr, reboot the system and you are good to go. It's don't needed anymore.
