### ISSUE TITLE
xwallpaper instead of feh?

### ISSUE THREAD

**Issue by qaraluch** [LukeSmithxyz/voidrice#181]
Why do you changed to xwallpaper?

**Comment by ispanos** [comment]
> Why do you changed to xwallpaper?

As far as I understand feh was used both to set the wallpaper and as an image viewer. Luke replaced 'feh' with 'sxiv' for opening images. 'xwallpaper' is 5 times smaller than 'feh' and works. 

However Luke mentioned in a video that now that he doen't use 'feh' he could probably switch over to 'Sway',  but sxiv as it says in the name is for X. So, Luke why don't you give 'imv' a try?
