### ISSUE TITLE
(Any) neovim color scheme looks like absolute trash

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/voidrice#184]
Now that these dotilfes are using neovim, there's a problem I can't solve that occurred between the update of `neovim-0.3.1-2` and `neovim-0.3.4-2`. Specifically, the color scheme,  _any_ color scheme is mangled and looks terrible. On the left is the desired appearance as in vim or in the earlier neovim, on the right is with the current binary:

[https://lukesmith.xyz/pix/nv1.jpg](https://lukesmith.xyz/pix/nv1.jpg)

I've scoured commits and documentation, but I can't pinpoint what caused this or what settings can mitigate it.

- This problem is not specific to `st`. I've tried `urxvt` and `alacritty` as well and they have the same problem.
- I've also tried `:set termguicolors`, which does change the shade to a slightly uglier color, but doesn't do what I need.
- I've also changed X colorschemes. It's clear that whatever is happening, neovim is distorting whatever colors you give it, but it is reading my colors set in Xresources. See the solarized example below:

[https://lukesmith.xyz/pix/nv2.jpg](https://lukesmith.xyz/pix/nv2.jpg)

I consider this issue urgent and am keeping neovim downgraded until I figure out what's wrong. If no one can lead me to a fix, I'll be reverting LARBS back to vanilla vim or gvim for a color scheme less vomit-inducing.

EDIT: apparenly github doesn't allow offsite images...

**Comment by luukvbaal** [comment]
Interesting, for me neovim works fine (switched to it a few months ago) works fine but I can't exactly say what is different in my dotfiles as I have been manually applying commits from the commit rss feed since I have too many local conflicts to be able to pull from the repo.
![image](https://user-images.githubusercontent.com/31730729/51195077-a6206480-18ec-11e9-8ad7-de4df39c5f01.png)

**Comment by luukvbaal** [comment]
![image](https://user-images.githubusercontent.com/31730729/51195839-2c897600-18ee-11e9-8228-e1610cfc0196.png)
Yeah same result using your Xresources. So I guess the difference being that I use my pywal scheme in vim [(`colorscheme wal`)](https://github.com/dylanaraps/wal.vim) prevents this issue from occurring.

**Comment by luukvbaal** [comment]
Seems like `:colorscheme peachpuff` is what you're looking for or not?
![image](https://user-images.githubusercontent.com/31730729/51197062-d538d500-18f0-11e9-8ff2-83800f4b0c4c.png)

**Comment by LukeSmithxyz** [comment]
I have never set a vim color scheme before. peachpuff does look similar to the original scheme, but the yellow is more garish. I'll probably set peachpuff as the default for the time being.

Do you know if they had switched the default color correspondence?

**Comment by luukvbaal** [comment]
No idea but seems to be the case then.

**Comment by dawidpotocki** [comment]
@LukeSmithxyz does `set bg=light` fix that for you?

They changed default to use light colors by default, pretty stupid decision, but whatever..

See https://github.com/neovim/neovim/issues/9455

**Comment by LukeSmithxyz** [comment]
Wow, thanks! That's what it is exactly. Yeah, I agree, that's a moronic decision. Oh well...
