### ISSUE TITLE
Understanding displayselect

### ISSUE THREAD

**Issue by Copper-Head** [LukeSmithxyz/voidrice#186]
Hi Luke,

Thanks for sharing this, I've been enjoying skimming through it. There's so much i could be doing better with my computer :)

I just wanted to make sure I understand one thing correctly:
Will [line 52 of displayselect](https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/i3cmds/displayselect#L52) (pasted below with context for convenience) actually kill output to all screens?

```sh
case "$(echo "$screens" | wc -l)" in
--->	1) xrandr $(echo "$allposs" | awk '{print "--output", $1, "--off"}' | tr '\n' ' ') ;; <---
	2) twoscreen ;;
	*) morescreen ;;
esac ;}
```

Thanks!

**Comment by Trebled** [comment]
Option 1 reads all possible displays, and divides them into seperate options, so on my setup I'm fed the choices eDP-1 (laptop screen) or HDMI-1, then my third option is multi-monitor and so on.

**Comment by Copper-Head** [comment]
Hmm, I'm not sure we're talking about the same spots.

What you're describing sounds more like what's happening on [line 68](https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/i3cmds/displayselect#L68), i.e. this bad boy:
```sh
xrandr --output "$chosen" --auto --scale 1.0x1.0 $(echo "$screens" | grep -v "$chosen" | awk '{print "--output", $1, "--off"}' | tr '\n' ' ')
```

The snippet I posted comes from the function `multimon`, which gets called if a user selects "multimon" at the point where you select one screen.

Am I missing something?

**Comment by LukeSmithxyz** [comment]
Hi @Copper-Head, yeah I think that line is an error, it should be like line 68, i.e. and not including the current display. I'll fix it in the next push.
