### ISSUE TITLE
.md to pandoc slides line in .vimrc 

### ISSUE THREAD

**Issue by haloux** [LukeSmithxyz/voidrice#19]
```"autocmd BufWritePost *.md !pandoc <C-r>% -o <C-r>&<Backspace><Backspace>pdf && evince <C-r>%<Backspace><Backspace>pdf```
 
Hey Luke,
I noticed that you have the above line commented out in your .vimrc. I think it's because for whatever reason it's not working (I tried using it, vanilla vim, zsh, xpdf and evince). If for whatever reason it's not working for you or anyone else, you can accomplish the same task by doing this:

`autocmd BufWritePost *.md silent !pandoc % -t beamer -o %:t:r.pdf && xpdf %:t:r.pdf &`

It'll accomplish the same thing if you choose to go with `evince` btw. I also think it looks a bit cleaner.

Happy notes-to-slides making everyone.

**Comment by LukeSmithxyz** [comment]
Lol that line must be ancient history actually, I haven't actually used evince since like month 1 of my channel, and what a vim brainlet I was!
