### ISSUE TITLE
Workspace Animation

### ISSUE THREAD

**Issue by j-degreef** [LukeSmithxyz/voidrice#193]
Hi,

How do you do to get the animation when switching workspace I've seen in your live stream yesterday ?

Thanks

**Comment by LukeSmithxyz** [comment]
There is no such feature in my dotfiles. You might be mistaking a transfer from OBS scenes for switching workspaces.

**Comment by ispanos** [comment]
@j-degreef you can enable fading with xcompmgr with the right arguments and values. At the moment `exec --no-startup-id xcompmgr` is in line 52 in the i3 config. Use `xcompmgr --help` to see the list of arguments, or `man xcompmgr` for more details.
