### ISSUE TITLE
I have ranger and fish. How to make the shortcut functionality work?

### ISSUE THREAD

**Issue by DrDonkey** [LukeSmithxyz/voidrice#202]
Hey luke, I don't use all of your ricing configs and scripts. I use ranger with your configs tho.
Also I've been using fish lately. Watched your ranger video again, then found shortcuts functionality.
What I have to do to get that? In fish and in ranger.

**Comment by GinGin3203** [comment]
If you don't really care if your default shell is fish or bash and you only want to use fish as an interactive shell, you can just append to your i3 config:

`bindsym $mod+Return 		exec $term -e fish`

This way all the bash stuff will still be working as intended.

**Comment by mangkokoo** [comment]
where's the shortcuts files, i watch the video seem's like it has moved somewhere :/

**Comment by LukeSmithxyz** [comment]
`~/.config/tools/shortcuts` does all of this now. Be sure to source the shortcuts files it produces in your bash/ranger/fish config file. Open the script to see what it is.

As @patosullivan notes, it is `~/.bmfiles` where you put your bookmarked files/configs and `~/.bmdirs` where you put your bookmarked directories.

All of this is default with LARBS.
