### ISSUE TITLE
xcqr doesn't send response when it fails

### ISSUE THREAD

**Issue by surfhai** [LukeSmithxyz/voidrice#203]
xcqr should send a message when it fails via notify-send, like the hints in the i3bar

**Comment by LukeSmithxyz** [comment]
xcqr is broken since feh is no longer installed. I was going to remove it actually.

Since I've been using `ifinstalled` for this use case, I suppose I'll add it there.

**Comment by surfhai** [comment]
I mean, it should give an error message via notify-send when it fails because of no data in the clipboard or invalid data. Not if feh is installed or not :)

**Comment by LukeSmithxyz** [comment]
Is the fact that the there is no QR code that appears not enough information?
