### ISSUE TITLE
can't copy screenshot to clipboard

### ISSUE THREAD

**Issue by dookiefied** [LukeSmithxyz/voidrice#210]
When I do shift+printScreen the dmenu dialog comes up as expected and I am able to choose whatever I want. Choosing the first 3 options that don't copy the result to clipboard works perfectly, the picture gets saved in my home directory. But if I choose the other 3 it just copies characters to my clipboard.

傉䝎਍ਚഀ䡉剄ᰀᔀ؈唀踂\Ѐ䤊䅄䡔侔ᑨ᱗㿇﹯♥ቮ阣톨膴ፀ洌궈佒쪞隒筂拰봎哶ꕊ찖ᐡ楊뒠竞袰◗化鉁땬ꚭꊈ葒괐⻙㝅鱋擬�普幷挏꘶䋆�藺잁潻齾ﯷ�觻ꕊ䚢䝇⑉谒辏秣ﬞ㓃鹍㒇燇㳰䪏芥⼬ጯĄꥊϧ๬贴ర舉�㴃甏㻯녡伈ꟾ愔袱瞺㰟쀃緷윜뎡鎳�鎷塙恘恠팀ᄴ⁂碄ꐚ妏惧ॹ뙡ຠ萜퇑ﵨ槴꿄⁗ꆨ瘺䚠䋞ᬟᬛ颛삘ర�㧛䈨踈㤜쀂ᮍ逷扒㛛憆ɬ鞇℮料ᄊზ୶ڂ훢꠭솭�ყୱ饡뼈㼄ዿ⺺⬫䰫䵍뒱䒴錦痁虝螇嚩璫癶ꔢ穤驺굚듖熻⳶卂黐䒄됫悧ݧᓢ괒黐桄눪痔ᱝ헪뢫议뫫乌鉎猸೦过ܟ쯥쿌폏ퟗ文灙໧�䄁먣窜ఝ锝ƈఠ樝ဵ퐚ꀛᅩ䩐㥲:䲙⤆볜덹䱙糹붞奢甖쟟漬犃됅ﵦᨡ㞎࿼岡肍씀煢㵓췌Ǎ뗚⇦ᨀڍᡡⰅ럇룡뀥鑍⎦⠄�劳⮘ۂꖸ怍块븗Ꮿ얋ర劃蒩�뛘ႍ얂업誧ꯊ駈ᱩݝ˛䃓ↄ㇪⡐攕퐞몡璆됽ꆡ!܆备嵝灥遰ﯽ㟷⷇ⴭ拄Ʇ`篎㝐㴉償蒖վ唪⾄븑䪄킕₯ዊ痢퐼둍ퟫί㬰䬻鴺癦陶㙬㩋⚝춛㌶䫞힩퀏Ꝉ㰩넪┦劢Ⱕ鑋뺌Ჰ׍几䚉ᴺ뱙둥㻻㌳ᰳ簾咘Ԫ櫀࿮ᳮ齻䠖虘裘怨꺭괨뻯棝孭遦텊훖孆᭛⌣ᐣ蔊㧨䮬ሩ篝緘Ӳ詉螮굟ᚳ간ą땾텎룵伛緒Ӳ࠽賵릦늲ꦲ᚟Ԋ尮삸䎡떧㖵虢䈡㌽�㺏ס䒯뇒⠁⫉똏礥诩棭ꧯꝓ竔꾙퍋ఴ䃃앭燣空餥湌孚࿼꟱露<﩮Ἷ㮧曽轳ᘨ宋曷똺捭홙낖ﵵ敹龎耐븷鋾莮涯ﮎ䬬鞟뇾﹨︇ﴗꐅ�頇晖䤀久깄恂

... is an example of this behaviour. I've tried reinstalling maim but it didn't help. I've also tried installing maim-git instead which gave me the same results.

**Comment by LukeSmithxyz** [comment]
Well... that's what it looks like when you paste a copied image into a text field.

Open up GIMP and paste it in. It's an image.

**Comment by dookiefied** [comment]
yep, works in chromium
