### ISSUE TITLE
Automatically rerun remaps script when external keyboard is plugged in or add a keybinding to run the script easily

### ISSUE THREAD

**Issue by LJNielsenDk** [LukeSmithxyz/voidrice#212]
The problem is that if an external keyboard is plugged in after i3 starts it will default to US layout.

I'd prefer having it run automatically, if no issues comes to mind with doing so, because that will let it have the expected layout when unlocking the screen saver when I set it up on my desk with the external keyboard after having brought it somewhere.

The internal keyboard retains the expected layout.

**Comment by LJNielsenDk** [comment]
I've decided to switch to using the US layout by default, it has much better placement of special characters for programming than the Danish one (where most of them are on Shift+<number> or Right_Alt+<number> and mostly the high end of the numbers so uncomfortable for touch typing), so unless you have an interest in fixing this just disregard it.

**Comment by LukeSmithxyz** [comment]
This is a problem for everyone as a newly plugged keyboard won't have things like the caps/esc switch. The thing is, I'm not immediately sure how to solve this by modifying home dotfiles. It might actually require adjusting system settings, which is out of the purview of this repo. I'll double check eventually but others are welcome to provide an easy way to rerun a script when a new usb device is plugged in.

**Comment by dr3mro** [comment]
may be use system Udev when a device plugged in run scripts

https://superuser.com/a/1364595

**Comment by MYDavoodeh** [comment]
Well I see that as feature actually.
In gaming or other situations, it's required to feel free without having the fear to press caps lock.
but I guess there is no solution for built-in keyboards to undo this remaps in LARBS systems. (I mean we need another script here to undo binds)
Just came to say if this issue wants to be solved without making new problems, there should be an "undoremaps" script too. OR there should be a way to disable this "automatic rerun remaps" if anybody plans to solve this issue.

I'll try to fix it if felt like it xD' but not really... Sorry for bad English btw.

**Comment by amrsoll** [comment]
In `~/.xprofile`, I would suggest to add
```
setxkbmap -device <device ID> -option caps:super <your layout> && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' & 
```
right after the line that sets the US intl-deadkeys layout.
you can find `<Device ID>` with `xinput -list | grep key`.
This way, you can have the best of both worlds.

**Comment by BachoSeven** [comment]
> may be use system Udev when a device plugged in run scripts
> 
> https://superuser.com/a/1364595

Did anybody find a way to implement an udev rule for this? I got a big headache after reading the whole udev arch wiki article...

**Comment by vladdoster** [comment]
Ive been looking into this. Ill push my fix if no one has one yet

**Comment by BachoSeven** [comment]
@vladdoster Could you please share your fix?

**Comment by vladdoster** [comment]
@BachoSeven find fix in my [Linux dotfiles](https://github.com/vladdoster/linux-dotfiles)

**Comment by BachoSeven** [comment]
@vladdoster So if I understand correctly (from [here](https://github.com/vladdoster/linux-dotfiles/blob/master/.local/bin/dmenu_display_options#L82)), you call this script with a keybinding whenever an external keyboard is plugged in(?)

I'm doing this as well, but it would be better if we could find a way to automatize the process..

**Comment by jsrath** [comment]
Hey @BachoSeven, here's how to run `remaps` every time you plug in your keyboard:

1. Run this command:
```sh
udevadm monitor --environment --udev
```
2. Plug in your keyboard. The udev monitor should have triggered with a bunch of information about your keyboard. Look for the `PRODUCT` property and copy the value. For me it's `17ef/6047/330`.

3. Create a new udev rules file:
```sh
/etc/udev/rules.d/10-keyboard.rules
```

4. Edit the `10-keyboard.rules` file with the following, replacing `username` with your own username and `17ef/6047/330` with the product id you copied earlier:

```sh
ACTION=="bind", ENV{PRODUCT}=="17ef/6047/330", ENV{DISPLAY}=":0", RUN+="/bin/su username --command='/home/username/.local/bin/reset-keyboard'", OWNER="username"
```

5. You can see in the rule above we're calling the `/home/username/.local/bin/reset-keyboard` file, but that file doesn't exist yet. Create the file.

6. In the newly created `reset-keyboard` file, you can run `remaps` and anything else you want, for example:
```sh
#!/bin/sh
setxkbmap -option caps:super &
xmodmap -e 'keycode 135 = Super_R' &
remaps
```

7. Reload your udev rules to see the changes:
```sh
sudo udevadm control --reload-rules && udevadm trigger
```
8. Plug in your keyboard again, and `remaps` should have run automatically.
