### ISSUE TITLE
Pasting pictures from clipboard in firefox is broken, works in every other browser

### ISSUE THREAD

**Issue by emorevival** [LukeSmithxyz/voidrice#216]
I posted about this issue a few days ago when I thought the script was broken, but after Luke telling me it works fine in GIMP I decided I'd try it in other browsers and programs. It works in every program and browser I tested except for the default LARBS browser (firefox). 

Since then I've also reinstalled LARBS on a fresh Manjaro i3 install and tried the above again with the same results. I'm not sure if this is intentionally stripped off Firefox or if it's a bug or maybe some setting interfering with it (although I have tried with both addons disabled and it still didn't work), but I do need the ability to paste pictures from the clipboard as I use it often. Can anyone else try on their LARBS install and see if it works?

I haven't tried 2 things, fresh default firefox install and another screenshot utility

**Comment by emorevival** [comment]
this is still a problem, by the way. tried on Manjaro, Archlabs and Antergos. not sure if it's intended or just broken? i can do it just fine in chrome or any other browser/program i could think of, just not in firefox

doesn't work using gnome-screenshot either so i know it's firefox.

what do you say, @LukeSmithxyz? is this intended or a bug?

does anyone else have this problem?

**Comment by LukeSmithxyz** [comment]
I'm not a firefox developer so I have no idea if it's intended or a bug. This isn't really a question for this repository, you should ask them. While LARBS does have special firefox settings, I don't think any of them are relevant to this, especially none in this repository.
