### ISSUE TITLE
Color extraction breaks when Xresources contains more than colors

### ISSUE THREAD

**Issue by webarnes** [LukeSmithxyz/voidrice#220]
I've been borrowing quite a bit from your dotfiles. I like the idea of extracting the colors from Xresources to maintain consistency (e.g., voidrice/.scripts/statusbar/battery). However, if you've got more in your Xresources file (e.g., urxvt or dpi options) it can cause two issues:

1. It sets variables for everything in Xresources (e.g., if you have Xft.dpi: 190, you get a variable dpi=190)
2. If you use asterisks (e.g., Urxvt*scrollBar which I know is silly), it tries to eval those as is

It might be a good idea to throw in a grep or more limiting regex (I just piped through "grep color").

**Comment by LukeSmithxyz** [comment]
Good point. This will be in the next push. Thanks!
