### ISSUE TITLE
shortcuts.sh: ranger move copy

### ISSUE THREAD

**Issue by zzzdeb** [LukeSmithxyz/voidrice#226]
Is there reason to use mv and cp in shell background? I find it somehow better to use ranger functions directly so that we can monitor process better. I found no direct paste function. But with chain commands it is achieved. 
```
map m"$1" chain cut; cd "$2"; paste; cd - >> $ranger_shortcuts`
```

**Comment by LukeSmithxyz** [comment]
No reason in particular I've done this. Open a PR and I'll merge it.
