### ISSUE TITLE
shortcuts.sh: space in filenames or dirnames

### ISSUE THREAD

**Issue by zzzdeb** [LukeSmithxyz/voidrice#227]
$1 $2 approach ignores filenames with spaces. Because this files are syncronised with cloud (not mine), names cant be changed. Since different config files share bmdirs file, making changes there seems bad idea. I solved this problem so far with variables
```sh
>(awk '{tmp=$1; $1=""; print "map ,"tmp" cd "$0"\nmap t"tmp" tab_new "$0}' >> $ranger_shortcuts) \
```
```sh
sed "s/\s*#.*$//;/^\s*$/d" $folders | tee >(awk '{tmp=$1; $1 = ""; print "alias ,"tmp"=\"cd \\\""$0"\\\" && ls -a\""}' | sed 's/ ~/$HOME/'>> $shell_shortcuts) \
```

but it is so hacky. and for shell onIf someone could come up with more sophisticated solution?

**Comment by Yash-Garg** [comment]
Did you try using `'file name'` ?

**Comment by zzzdeb** [comment]
yes then. cd '~' doesnt work neither in shell nor in ranger.

**Comment by samerickson** [comment]
What happens when using double quotes? Sam issues?

**Comment by YuvalDahn** [comment]
@samerickson 
with double quotes it has a syntax error
```
bash: /home/user/.config/shortcutrc: line 1: unexpected EOF while looking for matching `"'
bash: /home/user/.config/shortcutrc: line 2: syntax error: unexpected end of file
```
and for the shortcut `t` and the file `\tmp\A B` it generates
#### `~/config/shortcutrc`:
```
alias t="cd "/tmp A && ls -A" \
```
so it does makes sense.

what needed for it to work is that `awk` will be able to tread 'A B' or "A B" as a single argument or that there will be a way for it to print all the rest of the arguments, if you know such way it will might work
