### ISSUE TITLE
When I try to bindsym lmc, it doesn't work

### ISSUE THREAD

**Issue by asolopovas** [LukeSmithxyz/voidrice#230]
Hi,

I am trying to `bindsym $mod+Shift+p lmc mute` but it fails for some reason.
here is the log from i3
```
19/02/19 22:24:56 - commands.c:cmd_exec:1211 - should execute lmc mute, no_startup_id =
1
19/02/19 22:24:56 - executing: lmc mute
```
but sound is not muted.
Strangely enough, if I do lmc mute from terminal it works. 
What do you think could be a problem?

**Comment by ispanos** [comment]
This is not Larbs issue. You should read the i3 docs. https://i3wm.org/docs/userguide.html

`bindsym $mod+Shift+p exec --no-startup-id lmc mute` is what you need.

**Comment by asolopovas** [comment]
sorry I had `$mod+Shift+p` just a typo

**Comment by asolopovas** [comment]
Any idea why it is happening? Binding the same key to my cuatom scpript worked.

**Comment by ispanos** [comment]
1) Did you type it the way I showed you? 
2) Are you using the same keybind for something else?

**Comment by asolopovas** [comment]
I did type it the way you showed, and no it is not used for anything else, as I mentioned earlier if I bind my personal script to the same binding it works, but lmc doesnt. If I try lmc from terminal it works. And log just gives executing script lmc mute but nothing happens.

**Comment by LukeSmithxyz** [comment]
Possible problems:

- The syntax you provide in your first post is not i3 syntax and will not run. Copy what @ispanos wrote exactly, including the `exec`. `lmc` is not an i3 command `exec` is.
- If you downloaded the script without installing LARBS, lmc might not be in your `$PATH`, be sure to set whatever directory it is in in your profile. If it can be run in your shell, this might mean you add its directory in your bashrc, so it is available to your shell, but it is not part of your profile, meaning that i3 doesn't have it in the path.
- Similar to above, if you just downloaded or copied the script, it might not be executable. Be sure to `chmod +x` it.

**Comment by asolopovas** [comment]
@LukeSmithxyz thank you and sorry for wasting you time. The issue was that I did not add `export PATH="$PATH:$(du "$HOME/.scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"` to my .profile.After 20 years of using Windows I sometimes struggle to understand little nuances like the one that the $PATH is not globally available to everything. I thought that if you place it in `.bashrc` it magically becomes available to all the programs running.
