### ISSUE TITLE
Way to change nvim #comment colors on a work machine without Xresources?

### ISSUE THREAD

**Issue by stormsz** [LukeSmithxyz/voidrice#231]
Hey Luke, so i'm have been pretty happy with your work, awesome stuff.

I have been using plain old vim on my personal machine and didn't bother to change it to neovim.
When i started working on my new job ( also 100% of the work pc's here use arch! how awsome is that!?) i finally made the switch, and so far so good! pulled everything that seemed necessary and got it working. But theres this comment color....this dark blue color...i dont know if its me (i'm kinda blind) but god dam IT IS REALLY HARD to read the comments, they are WAY WAY WAY too dark.

I have been scrambling on your issues page and yes i do have the "set bg=light" on my vimrc.
My question is how does one changes just the color of the comments since you deprecated the xresources dot file.

Espero que tenhas um  ótimo dia, continua a fazer o que fazes! 
And no, its not spanish, portuguese powerrr!

edit: also pls make a video where you start by saying zoom zoom zoomers, you know, for the memes and keks

**Comment by LukeSmithxyz** [comment]
Just change it in Xresources or create a vim color scheme. Just because
I removed the default ~/.Xdefaults doesn't mean you can't have the file
on your computer.

**Comment by stormsz** [comment]
well now i feel stupid for wasting your time.
It worked like a charm.
got muh comment colors a little bit lighter, my blind eyes are thankful. Once again sorry.
