### ISSUE TITLE
ST shuts down when I try to open ~/.config/i3blocks/config

### ISSUE THREAD

**Issue by asolopovas** [LukeSmithxyz/voidrice#232]
Hi, 

I suddenly started encountering a strange behaviour of ST. When I try to edit  `vim ~/.config/i3blocks/config`it shuts st down. What could be the cause of that? It has not behaving this way previously (I did not update any config for ST nor tried upgrading it to a new version) but if I try the same from gnome-terminal it works without any issues. Restarting did not help.

Thanks.

**Comment by asolopovas** [comment]
Ok, i3 blocks config is not the only file that closes ST. I tried to open  `vim .scripts/cron/getforecast` it also close ST immediately.

**Comment by LukeSmithxyz** [comment]
This is a result of you not having an emoji font installed or at least a fontconfig that can deal with the,. Both of these files have emoji icons in them.

Did you install my dotfiles via LARBS?

**Comment by asolopovas** [comment]
@LukeSmithxyz I did install some of them but no all. I have installed the ttf-emojione though.

**Comment by asolopovas** [comment]
the strangest thing is that it was working but than suddenly started switching off when I began editing those files. Can't seem to find if st has any logs that I could inspect. Or its too simple for that?

**Comment by asolopovas** [comment]
If I open st from gnome-terminal on collapse it throws this error. Do you know what it could mean? 
```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  2607
  Current serial number in output stream:  3124
```

**Comment by asolopovas** [comment]
I have noticed that it starts to fail as soon as I install emoji font, whether its noto-fonts-emoji or its  ttf-emojione

**Comment by dawidpotocki** [comment]
> I tried installing ttf-symbola and it stopped throwing me out. But displays icons in black and white inside the file.

It is supposed to be like this. Just have noto-fonts-emoji (color) and ttf-symbola (white, monospace) installed together. So it will use symbola for terminal and noto for everything else.

**Comment by LukeSmithxyz** [comment]
#284
