### ISSUE TITLE
st and tmux not playing well due to $TERM [Lost Server]

### ISSUE THREAD

**Issue by duckie68** [LukeSmithxyz/voidrice#236]
There seems to be an issue with how st compiles it's terminfo.  There is allegedly a simple fix with a flag during compile, but I've been a bit busy lately and have stuck with a workaround.

In case anyone else is running into [Lost Server] problems -

I enter `TERM=screen-256color tmux` and it opens fine for the most part.  As soon as I get an opportunity I'll see about a fix up, or if anyone else has the time...

**Comment by Trebled** [comment]
Yes, here's the [fix].(http://git.suckless.org/st/commit/e85b6b64660214121164ea97fb098eaa4935f7db.html)
