### ISSUE TITLE
shortcutrc is missing?

### ISSUE THREAD

**Issue by advpetc** [LukeSmithxyz/voidrice#238]
https://github.com/LukeSmithxyz/voidrice/blob/d3ea9e2eab060e11884320a13b042eb935b9a48c/.bashrc#L7
Looking into this line, I found it is sourcing "shortcutrc", but I cannot find the file under config. Is that a typo?

**Comment by emorevival** [comment]
I have it on a new install from about a week or so ago. 
![pic-window-190304-1358-23](https://user-images.githubusercontent.com/32765662/53734904-9ef5eb80-3e85-11e9-8f88-1e0da18691d1.png)

**Comment by LukeSmithxyz** [comment]
It is generated by `~/.scripts/tools/shortcuts` based on the settings you give it, thus does not exist in the bare repository. Check the manual for more.
