### ISSUE TITLE
Easier X11 display arrangement

### ISSUE THREAD

**Issue by pat-s** [LukeSmithxyz/voidrice#240]
Hi Luke,

regarding your `displayselect` script. It worked good in general, however going through all these options every time is a bit tedious. Previously I used [xlayoutdisplay](https://github.com/alex-courtis/xlayoutdisplay) which does all of this automatically.

The only downside is that the wallpaper gets split. However, just chaining your `setbg` solves this.

So my current i3wm `mod+p` binding for display arrangement looks like this:

```
bindsym $mod+p exec --no-startup-id "xlayoutdisplay; exec ~/.scripts/tools/setbg"
```

Curious what you think :)

**Comment by LukeSmithxyz** [comment]
This doesn't really do what the `displayselect` script does. The point is to have the ability to decide which screen to use dynamically (via dmenu as well). This is for when you plug a laptop into a screen or new device.

If you want the same settings every time, set an xrandr script to run each time, or use a wrapper like this. I can't set one setting that will work for all the use cases of every user.

**Comment by pat-s** [comment]
> I can't set one setting that will work for all the use cases of every user.

Sure. 

Your script behaves more like a dmenu version of `arandr` and indeed tackles a different scope here. 

PS: Your scripts simplified my Unix exp a lot, thanks a lot!
