### ISSUE TITLE
Emoji dmenu crash

### ISSUE THREAD

**Issue by dr3mro** [LukeSmithxyz/voidrice#242]
when i try to select emoji from dmenu by dmenuunicode it closes and when i run it in terminal it gives me this error 

`Usage: xclip [OPTION] [FILE]...
Access an X server selection for reading or writing.

  -i, -in          read text into X selection from standard input or files
                   (default)
  -o, -out         prints the selection to standard out (generally for
                   piping to a file or program)
  -l, -loops       number of selection requests to wait for before exiting
  -d, -display     X display to connect to (eg localhost:0")
  -h, -help        usage information
      -selection   selection to access ("primary", "secondary", "clipboard" or "buffer-cut")
      -noutf8      don't treat text as utf-8, use old unicode
      -target      use the given target atom
      -rmlastnl    remove the last newline charater if present
      -version     version information
      -silent      errors only, run in background (default)
      -quiet       run in foreground, show what's happening
      -verbose     running commentary

Report bugs to <astrand@lysator.liu.se>
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  201
  Current serial number in output stream:  283
`
any Idea how to fix this

**Comment by dawidpotocki** [comment]
Install `ttf-symbola` from AUR (if you use Arch), it is a emoji font needed to work with it (yes it is white and black).

**Comment by vn971** [comment]
Same happens with git-s gitk. Installing "symbola" font, as suggested in the comment above, "fixes" the issue (the program no longer crashes).

**Comment by l00sed** [comment]
Works with `sudo apt-get install font-symbola` on Regolith/Ubuntu

**Comment by yuriyberezovskiy** [comment]
`sudo apt-get install fonts-symbola` works for me (ubuntu 20.04)
