### ISSUE TITLE
[Q] Tracking changes without .git inside $HOME directory?

### ISSUE THREAD

**Issue by sarpik** [LukeSmithxyz/voidrice#243]
Hello, I was wondering about how I should track the changes I made to my dotfiles / voidrice after installing w/ larbs?

Isn't it kinda meh to have the `.git` inside the `$HOME` directory?

Because if say I have my projects directory at `$HOME/projects/` and they have git source control too, it might get a little confusing.

---

How are you guys approaching it?

Currently I think I'll just fall back to tracking via git inside`$HOME`, but if anyone has suggestions, they'd be gladly appreciated!

**Comment by patosullivan** [comment]
I use the method outlined here: http://brandon.invergo.net/news/2012-05-26-using-gnu-stow-to-manage-your-dotfiles.html

**Comment by sarpik** [comment]
oh hey that's pretty smart! Thanks @patosullivan, I'll try this out - it looks way cleaner & more organised.
Btw this is completely unrelated but I have a lot of the same interests as you (js, ts, react, node) and I just find it funny that you were the one to reply here:D
