### ISSUE TITLE
Terminal programs defaulting to uxterm

### ISSUE THREAD

**Issue by singiamtel** [LukeSmithxyz/voidrice#244]
This happens whenever you try to open a terminal program through xdg-open, i.e. ranger or nvim. My solution was to change /usr/share/applications/nvim.desktop and ranger.desktop to execute 'st -e nvim' and 'st -e ranger', and set the Terminal value to false. Im aware this is a bad workaround, and will be annoying if i ever want to change terminal, any idea on how to solve properly?

**Comment by LukeSmithxyz** [comment]
What do you mean by "open[ing] a terminal program through xdg-open"? What actual command are you running and in what context? I'm not entirely clear.

**Comment by singiamtel** [comment]
Started addressing the problem because firefox would open text files on nvim, but over a uxterm. After a lot of fiddling, i found out that firefox just tries to open the text file running xdg-open, and thats what i tried to fix

**Comment by singiamtel** [comment]
You can reproduce it by defaulting firefox to open text files with Nvim, or trying to do 'xdg-open (text file)' on a terminal

**Comment by LukeSmithxyz** [comment]
Oh okay. I don't tend to do that so I didn't notice. xdg-open on a text file on my system actually opens it in firefox...

Either way, I'll be sure to add/change some mimentries for this. I think the ones you're using are older though? I think they hard-code using st now.

**Comment by singiamtel** [comment]
Yeah they might be like 3 months old by now
Thanks for the quick answer btw, loving your dotfiles so far
