### ISSUE TITLE
How to Impruve  prog.cvs 

### ISSUE THREAD

**Issue by annata83** [LukeSmithxyz/voidrice#249]
Hi Luke, I wonder if you could help on editing the Larbs scrip to include [Node](www.npmjs.com), [Python](https://pypi.org/project/pip/) and [Ruby](rubygems.org) package managers to our automated installation process that is use when calling prog.cvs!

**Comment by vladdoster** [comment]
Having watched Luke's videos, I would assume that Node and Ruby are not really required for Luke's system. However, in the LARBS script it allows you to pass in any URL for certain files it pulls and one is the `progs.csv`. I would suggest forking the LARBS repo, modifying the `progs.csv` to your satisfaction and replace this [line](https://github.com/LukeSmithxyz/LARBS/blob/master/larbs.sh#L18) in LARBS.sh to point to your modified `progs.csv` file in your forked repository. Hope this helps!

**Comment by LukeSmithxyz** [comment]
As it is right now, the script already includes an option for installing pip packages. This isn't actually used by default though. Adding some other install command for other package managers would be done the same way.

Add a function that does it, and add a case statement in the `installationloop` command that matches the letter you mark your programs with to your new install command. Take a look at the other functions that create the dialog interface and install the programs if you need direction: `maininstall`, `gitmakeinstall`, `aurinstall`, `pipinstall`.
