### ISSUE TITLE
Mod + F1 does not work

### ISSUE THREAD

**Issue by jaydoc** [LukeSmithxyz/voidrice#251]
I just installed LARBS as is with no modifications whatsoever on a fresh Arch install. Mod+F1 does nothing, but clicking on the pop-up opens the help document. Not sure why this happens.

**Comment by LukeSmithxyz** [comment]
I'm looking at the mapping right now, and it looks perfect.

Are you sure the keyboard you're using isn't one of those that might come with a default function key toggle? I.e. does Function+Mod+F1 work?

**Comment by jaydoc** [comment]
> I'm looking at the mapping right now, and it looks perfect.
> 
> does Function+Mod+F1 work?

Yes, it did. I am using a Dell Inspiron laptop. I have never really needed these keys on Windows, so I need to read up about them and why they behave this way. Thanks for the solution.
