### ISSUE TITLE
[Q] Recommended directory to store AUR packages & other built programs?

### ISSUE THREAD

**Issue by sarpik** [LukeSmithxyz/voidrice#254]
Hello,
is there a recommended / best practice directory to store AUR packages, git cloned packages and other built stuff like, say, `st`?

I've seen someone use `$HOME/builds`, `$HOME/devel` etc.. What are you guys using?

**Comment by lhindir** [comment]
I don’t think Luke intends these issues to be used as a general question forum; this kind of question is best suited to a simple internet search. Here’s [something](https://stackoverflow.com/questions/34914794/whats-the-standard-directory-location-to-use-when-cloning-a-git-repo-onto-a-l) to get you started.

**Comment by sarpik** [comment]
Thank you, I agree & no longer ask such questions through the issue board:)
