### ISSUE TITLE
dunst/libnotify(notify-send) not being able to format <b> as bold text

### ISSUE THREAD

**Issue by yurisuki** [LukeSmithxyz/voidrice#260]
![](https://puu.sh/D96Mw/7e799f45bf.png) 

i think notify-send does this. i tried xfce4-notifyd, but that does the same as dunst does. thank you for the help.

```
[yuri@WEEBzone ~]$ notify-send -v
notify-send 0.7.7
```

**Comment by LukeSmithxyz** [comment]
I noticed this happening after a recent update; I haven't changed anything in a while and suppose it's on the upstream.

If no one else is sure of the update that caused it, I'll do some prying.

**Comment by yurisuki** [comment]
> I noticed this happening after a recent update; I haven't changed anything in a while and suppose it's on the upstream.
> 
> If no one else is sure of the update that caused it, I'll do some prying.

Thank you, I just wanted to know whether it only happens to me or anyone else.

**Comment by dr3mro** [comment]
It an upstream bug really with new Dunst update 1.41 
https://github.com/dunst-project/dunst/issues/616#issuecomment-478641134

**Comment by dr3mro** [comment]
I have a fix but I dont know how to send it to you
but here is it https://github.com/dr3mro/voidrice/commit/c1dc0918c5438da2431300495985b545bfa0c108?short_path=26fa053#diff-26fa0539f3a1c97154a9816bb84f050c


it is just add " " as title for notifications as it support mark up only in body

**Comment by LukeSmithxyz** [comment]
Fixed. I had to make some changes to the modules due to my past laziness, but it's done now.

Fixed dunst config and statusbar scripts to maintain the previous look.
