### ISSUE TITLE
icons on the status bar not recognised

### ISSUE THREAD

**Issue by charlie39** [LukeSmithxyz/voidrice#263]
hi Luke, I wrote an email to you email stating my issues but didn't get a response so I am raising this issue here.

1. The icons on the status bar aren't recognised. Only the weather icons (one with the umbrella and some clouds and stuff ) are recognised the rest are shown as block size, as if the it isn't recognised. But the functionality is intake ,i.e. they do what they supposed to do when I click them.
Is it have to do with my system fonts not having those glyphs/icons .
If not help me troubleshoot it. 

2. This is not an but I thought I will let you.
The command to fire up the manual page (mod+F1) don't work in my system. What it does is basically Zathura opens file which randomly generated in the /tmp directory. Strange. 
Sl
So instead I replaced the command with a simple:
 'zathura  path/to/manual/page'
And it works now. 
For the rest, it is smooth sail.

**Comment by LukeSmithxyz** [comment]
Did you install the dotfiles running LARBS? The answer for the first question would be that either you didn't install the required fonts or you don't have a good `$LANG` variable from installation. I would assume that the answer to the second question is that you don't have `base-devel` or `groff` installed.

**Comment by charlie39** [comment]
i yap, the installation was a bit haphazard. First, installed only the dotfiles and manually installed the applications.
And tried to configure it myself because i didn't knew about the full LARBS script.
Recenly i have to reinstall arch for some issue and i used the LARBS script this time and voila! it fixed everything.
been using it for the last one day. Sorry for the late update.
However, i have some recommendations regarding the manual page.
1. can you make the page open in fullscreen mode , i mean in width, covering the window form left edge to right edge. Or perhaps you can do that while viewing in fullscreen mode (mod+f). The text are small and difficult to read in a display with 1377x720 type screen when it opens in one page. 
Thanks.

**Comment by charlie39** [comment]
closing this as the main issue been resolved.
