### ISSUE TITLE
Switch off the backlight while i3 locked

### ISSUE THREAD

**Issue by cld4h** [LukeSmithxyz/voidrice#269]
on the 148 line of your i3 config file, i.e.  `.config/i3/config`, you can add this command to be executed: `exec --no-startup-id xset dpms force off;`  which will turn off the backlight of your computer and save battery life.
I simply found this on [Archwiki](https://wiki.archlinux.org/index.php/Backlight)

**Comment by LukeSmithxyz** [comment]
Yeah I suppose I'll add that. It used to be the default when there was a separate lock script and I guess it makes sense to readd it.
