### ISSUE TITLE
newsboat bug

### ISSUE THREAD

**Issue by dr3mro** [LukeSmithxyz/voidrice#270]
whenever I try to open luke youtube by clicking Enter it just crashed 
any tips

**Comment by patosullivan** [comment]
can you open other youtube-dl videos in mpv?

**Comment by dr3mro** [comment]
Yes, and when i open newsboats it works fine except the second link of youtube on main menu but all other works

**Comment by LukeSmithxyz** [comment]
Same issue as all the others. Install an valid emoji font legible in the terminal.
