### ISSUE TITLE
Dropdowncalc not in fullscreen using mod+a

### ISSUE THREAD

**Issue by YacineSahli** [LukeSmithxyz/voidrice#271]
The fullscreen parameter is not at the right place, it does not make the calc in a big screen
`exec --no-startup-id ddspawn dropdowncalc -f mono:pixelsize=24`
It should be 
`exec --no-startup-id ddspawn -f dropdowncalc mono:pixelsize=24`

It should also be corrected for the bindsym XF86Calculator

**Comment by LukeSmithxyz** [comment]
That isn't a fullscreen parameter and neither window is supposed to be fullscreen.

**Comment by YacineSahli** [comment]
Sorry my mistake.
I found my problem, the font size 24 was too big for my window height and only one line was displayed in the calculator. Fixed it by using a font size of 22.
