### ISSUE TITLE
Error dmenumount

### ISSUE THREAD

**Issue by TomJansen** [LukeSmithxyz/voidrice#275]
Hi Luke.
There is an error in dmenumount. When running dmenumount in the terminal, after mounting it prints `chown: cannot access '741': No such file or directory`. This error was introduced in commit e6f6a83082551692770f6c83c2112fb2a2f961ea. I believe that `chown` only accepts  `"$user":"$ug"` or `741 "$mp"`. When giving them both, `chown` will treat `741` as a directory instead. But I could be wrong though.

**Comment by DeathKhan** [comment]
Make sure script has run permissions, works fine on my end.

**Comment by LukeSmithxyz** [comment]
You're right. I'll change this is a bit. I get some other errors in this script, so I'll double check everything and push a change soon.

It still all works and mounts drives though lol. I guess that's why I didn't notice...

**Comment by LukeSmithxyz** [comment]
Should all be fixed now.
