### ISSUE TITLE
Dunst Status-bar Scripts Not Printing Notifications

### ISSUE THREAD

**Issue by DeathKhan** [LukeSmithxyz/voidrice#278]
Hey Luke,
Dunst is not properly pushing notifications from status-bar modules despite my Dunst config functioning properly with all other applications (ex. discord, personal power manager). The initial greetings bold function also is not correctly formatted and appears every i3 instance.

Regards,
James

**Comment by LukeSmithxyz** [comment]
Hi James,

This was solved a couple commits ago. See #260 

Update your dotfiles to make the fix; you will want to manually remove the greeter lines from the bottom of the i3 config.
