### ISSUE TITLE
St terminal crash

### ISSUE THREAD

**Issue by dr3mro** [LukeSmithxyz/voidrice#279]
Whenever I try to paste an Emoji in terminal after enabling color emoji fonts it crashes
but not crash if using black and white emoji 
please how to fix this 
my current installed fonts 
ttf-emojione 4.5-1
ttf-emojione-color 1.4-1
ttf-font-awesome 5.8.1-1
ttf-inconsolata 1:2.0.0.1-3
ttf-linux-libertine 5.3.0-4
ttf-ms-fonts 2.0-10
ttf-source-sans-pro-ibx 2.020ro+1.075it-2
ttf-symbola 12.00-1
ttf-twemoji 11.3.0-2
ttf-twemoji-color 11.2.0-1
ttf-ubuntu-font-family 0.83-4

**Comment by iamantu93** [comment]
St cannot render color emoji. Which are actually images. But black and white emojis are Unicode fonts aka texts.

**Comment by dr3mro** [comment]
I did fix it by editing a file in /etc/fonts/config.avail/ and remove symbola as fall back font and use ubuntu font Instead so st uses ubuntu unicode emoji and all other apps use color emoji

**Comment by LukeSmithxyz** [comment]
#284
