### ISSUE TITLE
can't find ranger config

### ISSUE THREAD

**Issue by mangkokoo** [LukeSmithxyz/voidrice#282]
where it is :((

**Comment by LukeSmithxyz** [comment]
The ranger configs were removed in 622174fd82fb73b9e64c0895183a1a93931fded4.

**Comment by derkling** [comment]
But why?

I was looking for a possible response among your YouTube videos but I cannot really find anything specific... did you switch to `vifm`?

**Comment by derkling** [comment]
gotcha... `nnn` :)

**Comment by neko-nata** [comment]
this makes me sad
