### ISSUE TITLE
Newsboat No Longer Handling Videos

### ISSUE THREAD

**Issue by DeathKhan** [LukeSmithxyz/voidrice#285]
Luke, 

Newsboat no longer seems to handle YT links. I added all dotfiles again just to make sure it wasnt something on my end, but it still may be.

Regards, 
James

**Comment by LukeSmithxyz** [comment]
This is the error:
```
[ytdl_hook] ERROR: LnO6Yqxx_M8: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```
This seems to be a youtube-dl problem, which mpv uses. Out of my control. Either downgrade temporarily or wait for the fix, which I'm sure will come soon.

You can check their Github issues https://github.com/ytdl-org/youtube-dl/issues where dozens of people are reporting the same thing.

**Comment by LukeSmithxyz** [comment]
Temporary fix here:
https://github.com/ytdl-org/youtube-dl/issues/20758#issuecomment-486016882
In case you have to have it now.
