### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by dr3mro** [LukeSmithxyz/voidrice#287]
There is a 100% compatible window manager called 'sway' its identical to i3 and uses i3 config file but uses wayland as compositor / Display server with much better performance and X applications can run using Xwayland 
Do you plan to switch to wayland soon ?

**Comment by yurisuki** [comment]
On 19/04/27 05:25, KernelPanic wrote:
> There is a 100% compatible window manager called 'sway' its identical to i3 and uses i3 config file but uses wayland as compositor / Display server with much better performance and X applications can run using Xwayland
> Do you plan to switch to wayland soon ?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/voidrice/issues/287
wayland has many issues, and it's not stable to replace xorg.

**Comment by LukeSmithxyz** [comment]
If it's "100% compatible" it should be extremely easy for you to make a PR that maintains all functionality and still works with every program run in LARBS.

I suspect if you try it you'll realize that having config files that look alike isn't the same thing as compatibility.

I'm not going to lift a finger trying to port these dotfiles to wayland because I have in the past and it breaks about everything. Maybe it "just werks" now. I don't know, but I'm not going to bother.

**Comment by rxmmah** [comment]
what about now :)

**Comment by emrakyz** [comment]
@rxmmah 

I like Wayland. It is pretty stable now even with Nvidia GPUs. I have tried Hyprland, Sway, DWL and they all work well but Luke has a sophisticated setup especially if we consider the Suckless software and its philosophy.

There is no true alternative for Suckless software on Wayland (yet). DWL is neither maintained by the Suckless team nor it's even similar. DWL is a hacky way to make a Wayland compositor behave similarly to a minimal window manager on X.

It also uses "foot" as a terminal. Foot is completely out of the Suckless philosophy. While being generally minimal, it's not minimal compared to a Suckless program. Plus, it has a config file and comes as a binary.

For dmenu, bemenu is similar on Wayland but it's not as extendable or customizable especially given the complexity of wlroots for new users.

For other things; Wayland is faster, smoother, modern, more minimal in every case. Except Suckless software, all other software Luke use can easily be used on Wayland. Most problematic things were the browsers and video players back then, but both "mpv" and "firefox" are extremely good with Wayland and Pipewire setup now.

I have a high refresh rate, 10bit screen and there is a night and day difference using Wayland compared to X. X is like riding a donkey compared to a car in my case but there are still reasons to run X: 

1) If you care deeply about Suckless philosophy.
2) If you don't want to use Qt6 or GTK4 (these are better for Wayland compared to older versions).
3) Proprietary apps can be problematic if you need them.
4) Electron apps are very problematic if they don't use newer Electron versions. Even when they use newer versions, you mostly need these flags: --enable-features=UseOzonePlatform --ozone-platform=wayland

As far as I know, the names such as Mental Outlaw, Brodie Robertson and Chris Titus Tech have been using Wayland for a considerable amount of time already.

**Comment by rxmmah** [comment]
thank you for your detailed review of the matter.
suckless are not adhering to their philosophy while using Xorg. because its heavy and has security flaw, every program can listen to other programs I/O through X.

**Comment by wickedjargon** [comment]
[MARBS](https://marbs.kuchta.dev/) is what you're looking for. It uses,

1. [dwl](https://marbs.kuchta.dev/dwl) – the main graphical environment
2. [foot](https://marbs.kuchta.dev/foot) – the terminal
3. [keyd](https://marbs.kuchta.dev/keyd) – keyboard remapping daemon
4. [dwlb + someblocks](https://marbs.kuchta.dev/statusbar) – statusbar

in an effort to mimic LARBS.
