### ISSUE TITLE
[Request] Add steps on how to setup i3 files on a non-fresh Arch Linux

### ISSUE THREAD

**Issue by mattaereal** [LukeSmithxyz/voidrice#295]
Hi Luke, I'm having some difficulties trying to patch my current Arch Linux with your current setup.

Is there an easy way or an explanation laying around on how to do so without going crazy?

Thanks!

**Comment by yurisuki** [comment]
you might have to use a different account for larbs

**Comment by Marc3lX** [comment]
What's your problem?

**Comment by mattaereal** [comment]
Sorry, I was on a long trip and did not take any devices with me.

I was thinking if there is a way to "patch" my current Arch Linux installation safely in order to use i3 mostly.

Thanks for replying everybody.
