### ISSUE TITLE
HiDPI setting？

### ISSUE THREAD

**Issue by xiaoyu-tamu** [LukeSmithxyz/voidrice#310]
Hi, thanks for this great configuration. Any idea how to fix it in 4K display?

In Manjaro, I can do something like xft.dpi 196 in .xResource file

**Comment by decantr** [comment]
I personally make these changes. 
```
sed -i "\$ixrandr --output eDP-1 --dpi 192" .xinitrc
sed -i 's/350x5-0+24/700-0+48/' .config/dunst/dunstrc
sed -i 's/mono 10/ mono 20/' .config/i3/config
sed -i '3s/^/export GDK_SCALE=2\n/' .profile
```
xrandr only seems to affect the dmenu size hence the mono changes for the status bar.

**Comment by decantr** [comment]
Just realized you can use your `.Xdefaults` file to set this (example provided in the st build) and use `xrdb ~/.Xdefaults` in your `.xinitrc` so you dont have to edit the i3 config.
