### ISSUE TITLE
After May 27th commit dwm suddenly is using 97% cpu across all 4 cores

### ISSUE THREAD

**Issue by haldamine** [LukeSmithxyz/voidrice#318]
CPU usage has skyrocketed after most recent commit

**Comment by LukeSmithxyz** [comment]
`pgrep dwmbar`. Do you only get one number? When this happens, try killing `dwmbar` and see if it resolves... I think I know what could cause it...

**Comment by LukeSmithxyz** [comment]
Get the most recent commit. I think that's it. Basically if you didn't have mpd running, there would be a continuous non-stop loop to update the task bar. Fixed now. Tell me if that was it.

**Comment by haldamine** [comment]
That was it thank you Luke.

**Comment by LukeSmithxyz** [comment]
Okay great. Thanks for brining this up!
