### ISSUE TITLE
Why use tr for an alias?

### ISSUE THREAD

**Issue by Daenarii** [LukeSmithxyz/voidrice#32]
https://github.com/LukeSmithxyz/voidrice/blob/018f4b3bcae138b3ebfc9dcdeb51d294eccdae04/.bashrc#L48

I am making some script and suddenly I came to a weird error that tr is actually aliased to transmission-remote, even though tr is a shell command.
I don't know what to replace it into, so its up to you Luke-senpai.

**Comment by LukeSmithxyz** [comment]
Sure I'll rename it.
