### ISSUE TITLE
Suggestion: use yadm for dotfile source control.

### ISSUE THREAD

**Issue by rholak** [LukeSmithxyz/voidrice#320]
To keep the convention of using git to maintain ~/.config and other dotfiles, but adding a few features and seeing less git-spew along the way, I suggest taking a look at yadm ( https://yadm.io/ ). The git repo would look just like the current voidrice repo, but when you are in your home directory, you will not see the mess of untracked files when running `git status` or other commands. The `yadm` command supports all git commands (`yadm commit`, `yadm push`, etc) so it should feel very familiar.
It's available in both Arch (AUR) and Void, so it would work for both branches here and would be an easy addition to LARBS if you find the tool useful.

**Comment by ispanos** [comment]
You can do the same thing manually. You just need to rename the `.git` folder and create a few aliases in your `.bashrc`. https://www.atlassian.com/git/tutorials/dotfiles
I'm not saying this is the best way, but if I find it very easy this way, so IMHO yadm is bloat.

**Comment by rholak** [comment]
@ispanos That's actually how I started. I ran across yadm and ended up using its per-machine features instead of scripting that myself. Yadm is a single bash script so my solution would have ended up messier and I didn't feel like reinventing the wheel. Bloat is highly subjective of course, so for simpler use cases, the DIY bare repo and a few aliases is certainly smaller. The nice thing with yadm is that it uses the same bare repo method so it was easy to switch tools (and easy to go back if I ever decide to roll my own again)

**Comment by WithoutCaps** [comment]
I support this idea, yadm supports several extra features like encryption and per system configuration which is a nice thing to have, but the main advantage of it is that is just less bothersome, with a package like that there is no need to manually build write git bare repo configuration which is just annoying.

As for @ispanos  point of saying that it is bloat - it is not, its size (according to `yay`) is 0.08 MiB and it does not have any unnecessary dependencies, and to top it all off - with this small package size it provides you extra information on what happened and how to fix whatever happened (in case of edge cases like merge conflicts)

**Comment by ispanos** [comment]
@rholak @WithoutCaps now you are making me want to check out `yadm`.....

**Comment by WithoutCaps** [comment]
@ispanos  Well, there really is not much to check out, most of the time you will not even see the difference between bare git repo and yadm. It is just more convenient and has a couple of extra features, that's all there is to it
