### ISSUE TITLE
Compiler causes hang with groff images

### ISSUE THREAD

**Issue by decantr** [LukeSmithxyz/voidrice#325]
When compiling a `.ms` document with a number of `.PSPIC` elements the script hogs a CPU and appears to hang ( I ran for 10 mins with no result ).
The `-j` flag overrides `-p` handling of the elements and will, if it completes, yield differing results in the output document.
This can be resolved by removing the `-j` flag from the compiler script though I'm not sure if it's there for a reason.

**Comment by LukeSmithxyz** [comment]
I was under the impression that `-j` would function as a superset of `-p`, but I suppose there's some other issue. Since I suppose very few people intend on using `chem` by default, I'll remove it.
