### ISSUE TITLE
Refbar script

### ISSUE THREAD

**Issue by anselal** [LukeSmithxyz/voidrice#328]
I guess you could replace this line
https://github.com/LukeSmithxyz/voidrice/blob/b5925045a3463c65320d3ae409442fb81d2db324/.local/bin/refbar#L6

with just `killall refbar`

**Comment by LukeSmithxyz** [comment]
Uh? No?

**Comment by anselal** [comment]
And why is that? What is the advantage of your one-liner?

**Comment by LukeSmithxyz** [comment]
The advantage is that it actually does what it's supposed to do.

**Comment by anselal** [comment]
Ok, if yo have multiple refbar scripts running that do other sort of stuff then I agree with you, but if you have only a refbar script that updates your status bar then `killall refbar` does the same thing

**Comment by LukeSmithxyz** [comment]
The point of `refbar` is to refresh the dwm bar, not to spontaneously spawn and kill itself for no reason.

**Comment by anselal** [comment]
My mistake, I got confused with the script. thanks for being so patient

**Comment by anselal** [comment]
Sorry I had something else in mind. I call a script in my .xinitrc and to refresh the status bar I just kill the script.

**Comment by anselal** [comment]
You could do something like this in your `.xinitrc`:

```sh
...
while true; do
    xsetroot -name  "$(dwmstatus)"
    sleep 1m
done &
...
```

and in refbar just `killall dwmstatus`

where in `dwmstatus` you print whatever you like

**Comment by anselal** [comment]
@LukeSmithxyz i am glad you followed my advice
