### ISSUE TITLE
newbsboat config does not use webview after once invoking mpv

### ISSUE THREAD

**Issue by Herny64** [LukeSmithxyz/voidrice#33]
Hi Luke,
in your config its:
```
browser webview
macro b open-in-browser
macro m set browser "i3 exec mpv"; open-in-browser ; set browser $BROWSER
```
is the $BROWSER on the last line intended ? Shouldn't that be webview ?

**Comment by LukeSmithxyz** [comment]
Ah I forgot about this; I had noticed this but hadn't changed it in the remote repo. It should be better now.

Note that I also moved the `webview` script to be `linkhandler`, which is more descriptive, so urlview` and `newsboat` will now be looking at it.
