### ISSUE TITLE
lockscreen and $mod+x

### ISSUE THREAD

**Issue by autoferrit** [LukeSmithxyz/voidrice#333]
I was hoping to rebind `$mod+x` some how, but even though I can see the mod added in your git history, as well as the `lockscreen` script reference, I can't seem to find either of them anywhere in the `archi3` branch.

I was hoping to get some input on where I can change this, or at least check it out to see if I want to remap other tools to something else.

**Comment by LukeSmithxyz** [comment]
See the manual. Binds are in `~/.config/sxhkd/sxhkdrc`.
