### ISSUE TITLE
in dwm how are you using the keyboard to move across 2 monitors? Do you have individual tags bound to each monitor?

### ISSUE THREAD

**Issue by haldamine** [LukeSmithxyz/voidrice#336]

**Comment by ghomasHudson** [comment]
You would need to uncomment:

https://github.com/LukeSmithxyz/dwm/blob/b15dd72e3579ea96e0c14a89e31dcecda1fedf15/config.h#L118-L121

**Comment by LukeSmithxyz** [comment]
Yes, there are no bindings for this in my current build as I don't use more than one monitor.
