### ISSUE TITLE
Small warning for using rxvt-unicode instead of st

### ISSUE THREAD

**Issue by Daenarii** [LukeSmithxyz/voidrice#34]
Since I don't want st as my terminal emulator while this config contains config for urxvt, I tried that instead.
But the URL selection and font resizing doesn't work unless you install `urxvt-perls` and `urxvt-resize-font-git` (AUR), respectively.
This isn't a real issue by itself, but adding a "dependencies required" on the README.md or an option for installing urxvt in LARBS might be a good idea for new users just in case they face the same problem as mine.

I don't know which will work better so its up to you.

**Comment by LukeSmithxyz** [comment]
Yeah, as said in #41 I'll probably link the dependency list with some extra stuff like this.
