### ISSUE TITLE
Image previews in vifm cause vifm to freeze

### ISSUE THREAD

**Issue by ashprice** [LukeSmithxyz/voidrice#340]
I should preface by saying I'm not using all of your dotfiles or these as deployed by LARBS (prior to psoting this). However, I have been using your vifmimg script to view images with überzug. For the purposes of posting and troubleshooting this issue, I have switched to your vanilla setup of dotfiles, which has not fixed the issue. 

The expected behaviour is for an image preview to pop up in the right hand pane when scrolling through directories with images. The actual behaviour, is upon reaching the first image, for nothing to appear in the right hand pane. Then, I scroll down, wondering if it's just slow and looking for a smaller image. No previews pop up, and vifm freezes in place entirely after two-three images. 

I am unsure what logs or other info is of use - sorry for not coming prepared. I understand both that if you cannot recreate the issue then this is unlikely to be solved and that it isn't really your problem to solve, but I reasoned that if I've had the issue then others may have as well. 

Thanks for taking the time to read this.

**Comment by codeitlikemiley** [comment]
i can confirm this is happening to me as well, after i update my system this is an issue before i dont have any issue viewing images , pdf etc... dont know what happen to uberzug or vifm. 
the script is ultimately freezing vifm

**Comment by xlxs4** [comment]
I did not yet have the time to dig into it, but vifm/uberzug is also freezing on my side

**Comment by nobobo1234** [comment]
Also doing this for me

**Comment by jcarreja** [comment]
I have the same problem. Update arch and I also freeze vifm.

**Comment by markedagain** [comment]
im not sure how you guys got image preview working in vifm ever, but i had to do a bunch of tweaks to get mine to work out of the box. i was missing python-pillow and the shortcut for file manager was still set to vifm and its to use the custom script to setup environment variables. so changed that to /tools/vu and now i use vu to open vifm and works like a charm

**Comment by ashprice** [comment]
As I say, I don't run Luke's dotfiles exactly, but I had tested with his exact dotfiles; with my original setup it worked 'out of the box' in the sense that the script worked without any additional steps that I can recall. 

In either case, I had python-pillow-simd rather than python-pillow; switching back fixes image preview. With simd, there are a number of issues with vifm aside from image previews now (error messages printing across the screen; though all functions beyond image preview appear to work). 

Thanks for leading me to check this, I'd suggest everyone else who has the issue to do the same.
