### ISSUE TITLE
$MOD+shift+c does not toggle webcam in VLARBS

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#343]
In the Void/DWM version, mod+shift+c does not toggle the webcam on my Thinkpad X200. The camera light blinks, then turns off. No webcam view is displayed.

**Comment by LukeSmithxyz** [comment]
This sounds like a hardware problem. What happens if you run
```
mpv --no-osc --no-input-default-bindings --input-conf=/dev/null --title='mpvfloat' /dev/video0

```
manually in the command line?

**Comment by drake-newell** [comment]
When I ran that comand at first, the webcam view was displayed, although there was a 10-second delay in what happened on screen. When I ran that command again,  I recieved this output:
Playing: /dev/video0
 (+) Video --vid=1 (rawvideo 640x480 30.000fps)
[vo/gpu/opengl] Suspected software renderer or indirect context.
libEGL warning: DRI2: failed to authenticate
Segmentation fault

NOTE: I cannot provide the output of the command when I ran it the first time as I accidentally closed that terminal.

**Comment by drake-newell** [comment]
UPDATE: I was able to run that command again successfully, and the video is considerably behind by about 10 seconds. When successful, the command outputs:
 Playing: /dev/video0
 (+) Video --vid=1 (rawvideo 640x480 30.000fps)
[vo/gpu/opengl] Suspected software renderer or indirect context.
libEGL warning: DRI2: failed to authenticate
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/opengl] Suspected software renderer or indirect context.
error: XDG_RUNTIME_DIR not set in the environment.
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] No Xvideo support found.
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
[vaapi] Failed to initialize VAAPI: unknown libva error
[vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcin
VO: [x11] 640x480 yuyv422

NOTE: The command then fails to work again until reboot.

**Comment by drake-newell** [comment]
After pulling the latest version of the git repo, the problem seems to be gone. Thanks Luke!
