### ISSUE TITLE
I installed Manjaro and LARBS, I think my pc ruined now..

### ISSUE THREAD

**Issue by SahajSamtani** [LukeSmithxyz/voidrice#348]
I installed Manjaro and everything worked, then I installed LARBS
Did everything in the tutorial
And then now I'm stuck in my login screen
When I login it goes to the Dell logo screen for one second then goes right back to the login screen
When I reboot and go to the boot menu
And go to windows It just says searching for repairs or something
(I really need some of the files)

**Comment by drake-newell** [comment]
Did you partition the drive yourself to have a home directory? If not, did Manjaro make a home directory or just a boot and root directory? There's a good chance Luke's dotfiles are meant to work within a legit home directory. 
Solutions:
1. Try to use a live linux usb to copy the files over the the cloud or a backup drive
2. Use a live system like GParted to repartition the entire drive with boot, root, home and swap directories
3.Reinstall Manjaro and try to see if you can successfully install LARBS.

Sorry if none of this works. Just thought I'd suggest what might help, but I don't really know what I'm doing. You should probably still wait for Luke to see this.

**Comment by drake-newell** [comment]
Also, I have no idea how to do custom partitions with Manjaro. Manjaro does have a more arch-like CLI variant though.

**Comment by mbednarek360** [comment]
Mistake #1: Manjaro

I would try chrooting and see if you can even access the system remotely. I have had a similar issue that I solved by chrooting into the system and reinstalling grub. All files were intact it's just that my motherboard didn't detect that drive as bootable so it tried to boot to a secondary drive or back to the bios.
