### ISSUE TITLE
transset-df doesnt restore transparency back

### ISSUE THREAD

**Issue by rudolfschmidt** [LukeSmithxyz/voidrice#35]
Hey, I copied your script flashwindow from one of your videos.

To remember you, here its again:

```#!/usr/bin/env bash

#Flashes the active window.

#Requires transset-df and a composite manager, like xcompmgr.

transset-df --actual --min 0
sleep .1
transset-df --actual --max 1
sleep .1
transset-df --actual --min 0
sleep .1
transset-df --actual --max 1
```

I am using ```opacity-rule = [ "90:class_g = 'URxvt'" ];``` in my compton.conf that sets a true transparency with opacity 0.9 to all my windows with the class urxvt. Using your script it restores the transparency just to 0.75 but not to 90 like I have configured in compton.conf I have tried around but I do not find a way to restore it. If a window has no opacity that it restores back to opacity 1 like expected.

Maybe you have run into the same issue and have found a solution.

I would be happy if you could share it.

Best
RS

**Comment by LukeSmithxyz** [comment]
You'd be better off asking this to the developers of transset. I don't use it anymore or have it installed, nor do I use that script anymore, and it's not really part of my dotfiles, so I can't really estimate what's going wrong.

I can give you the hint of checking the `~/.Xdefaults` of this repo. I did my urxvt transparency there and never had this problem. I'm pretty sure your setup with compton transparency will add alpha to foreground as well, while mine didn't.

**Comment by rudolfschmidt** [comment]
ok and what do you use for flashing your windows now?
