### ISSUE TITLE
Escape key not functioning as CapsLock

### ISSUE THREAD

**Issue by Myhat2you** [LukeSmithxyz/voidrice#359]
On a fresh installation of Arch with Larbs I have found that with my (uk) keyboard the escape key functions as it normally would, rather then being replaced with the capslock function.

I have tried to see if this was an issue with the custom key-maps in .local/bin/ttymap.kmap and used xorg-xev to find the correct key-codes and set them accordingly but with no difference being made even on restart.
Using the loadkeys function prints no error however trying to do the same thing through xmodmap changes changes the escape, caps_lock and windows key to all function as capslock.

Trying to use xcape gives me this error:

> xcape -e 'Escape=Caps_Lock'
WARNING: No keycode found for keysym Caps_Lock (0xffe5) in mapping Escape. Ignoring this mapping.
Failed to parse_mapping

And here's the output of some of the used key-mapping programs.
> setxkbmap -query
rules:      evdev
model:      pc105
layout:     gb
options:    caps:super

> xmodmap
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):
shift       Shift_L (0x32),  Shift_R (0x3e)
lock
control     Control_L (0x25),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3
mod4        Super_L (0x42),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)

> xcape -d
(holding escape key)
Intercepted key event 2, key code 9

Please help, this is driving me insane. Thanks.

**Comment by decantr** [comment]
mine acts as a capslock in the tty but i assumed that was a bug.
does anyone actually use caps lock?

**Comment by Myhat2you** [comment]
> mine acts as a capslock in the tty but i assumed that was a bug.
> does anyone actually use caps lock?

Not often but I like to have the option I guess. I've mapped it to the menu key now but still haven't found any solution.

**Comment by LukeSmithxyz** [comment]
xcape has nothing to do with anything here. If you want your escape key to be a caps lock, use the `caps:swapescape` option with `setxkbmap` instead of the `caps:super` option later paired with the xcape command in LARBS.
