### ISSUE TITLE
Superkey changes depending command pressed

### ISSUE THREAD

**Issue by danielscamacho** [LukeSmithxyz/voidrice#362]
I have set Super key with Mod1.
Super + Enter = Terminal does not work. I have to press Mod4 + Enter. Got switched somehow.
Super + F = Full Screen works!
To open PDF welcome guide I have to press Windows key (mod4) and F1. Not Superkey (mod1)
But Super + F2. restarts i3 config 

Why commands are changing super keys depending of the key pressed?

**Comment by LukeSmithxyz** [comment]
Edit the binds in `~/.config/sxhkd/sxhkdrc`, chaning `super` to `alt` or whatever you want.
