### ISSUE TITLE
.local/bin/statusbar indicators are all broken after update

### ISSUE THREAD

**Issue by tzurita** [LukeSmithxyz/voidrice#366]
I think it is all related to the iblocks 1.5-2 or 1.5-3 update.  According to https://github.com/vivien/i3blocks/issues/397  it says that they removed the default scripts (probably not affecting a thing) and this that may be the issue:

Before the update missing newlines caused no issues at all. But now the blocks don't show up without these newlines.

I tried adding newlines to a few but to no avail.  Do you think anything else could be causing the issue?

**Comment by JadowityHerbatnik** [comment]
> I tried adding newlines to a few but to no avail. 

Well, which scripts exactly don't work for you? Perhaps you added the new lines incorrectly. Did you check the output in the terminal?

**Comment by JadowityHerbatnik** [comment]
>    I tried adding newlines to a few but to no avail.

Well, which scripts exactly don't work for you? Perhaps you added the new lines incorrectly. Did you check the output in the terminal? I edited the broken scripts and they work just fine.

**Comment by tzurita** [comment]
Ok here is what I tried.
working dir .local/bin/statusbar
1. mkdir bkup
2. mv * bkup
3. cp news .
4. cp pacpackages .

So staring with news:
`#!/bin/sh

#echo "$(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)" i3blocks newsboat module.
# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

case $BLOCK_BUTTON in
        1) setsid "$TERMINAL" -e newsboat ;;
        2) setsid newsup >/dev/null & exit ;;
        3) pgrep -x dunst >/dev/null && notify-send "📰 News module" "\- Shows unread news items
- Shows 🔃 if updating with \`newsup\`
- Left click opens newsboat
- Middle click syncs RSS feeds
<b>Note:</b> Only one instance of newsboat (including updates) may be running at a time." ;;
esac

 cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)"
`
The command 'cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)"
' 
works but where to add newline and then on update there must be a something that is keeping the icon from remaining on the i3statusbar.  Before if there where '0' new the icon would not exist on the statusbar.

**Comment by JadowityHerbatnik** [comment]
Well, here's a simple workaround I use (just define the output command as a variable and then check if it's equal to 0):

`number=$(cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)")`
`(( number == 0 )) && exit`
`echo $number`

And likewise for pacpackages.

**Comment by JadowityHerbatnik** [comment]
Here's a quick and dirty workaround I use (just define the output command as a variable and then check if it's equal to 0, also remove the sed part which deletes "0"):

`number=$(cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ print $1}' )")`
`(( number == 0 )) && exit`
`echo $number`

And likewise for pacpackages.

Also,

> but where to add newline

No need for that if the command already works for you ;)

**Comment by tzurita** [comment]
Thank you.  The only one that was different was the internet one but that just needed a \n (newline) for the printf portion.
