### ISSUE TITLE
i3blocks notifiers not working

### ISSUE THREAD

**Issue by Dedkovskiy** [LukeSmithxyz/voidrice#368]
Some of the status bar notifiers (battery, internet) just disappeared after my last system update.  I'm a beginner, so I don't really know what's happened and what's the right fix for this issue.

I figured out that these notifiers were using `printf` to output information.
My fix is to add a new line at the and of each print. 
Example:
`printf "<span color='%s'>%s</span>\n" "$color" "$icon"`

Also, the notifiers that wasn't working for some reason (news, packages and mail) suddenly showed up (actually not complaining about this xD).

Please don't juge me, that's my first issue report.

**Comment by Dedkovskiy** [comment]
I'm really dumb, the issue was fixed yesterday

**Comment by vladdoster** [comment]
Could you reference the fix? @dedkovskiy

**Comment by Dedkovskiy** [comment]
You can find the fix here https://github.com/LukeSmithxyz/voidrice/pull/367#issue-315566355
