### ISSUE TITLE
Package upgrade broke some i3blocks elements

### ISSUE THREAD

**Issue by hillburn** [LukeSmithxyz/voidrice#369]
Behavior is consistent between two different PCs that were set up with LARBS.

After upgrading all packages yesterday and restarting my PC, the statusbar elements `battery`, `disk` and `internet` have stopped working. Some other elements that I've commented out might also be broken, but I still use `weather`, `volume` and `clock`, all of them still working fine.
I had a hunch that some icons might have been broken, so I modified one of the faulty scripts by replacing icons with text. However, that didn't solve the problem.

**Comment by vladdoster** [comment]
Look at closed issues first. Look at #368
