### ISSUE TITLE
Polybar fonts?

### ISSUE THREAD

**Issue by v0idst4r** [LukeSmithxyz/voidrice#37]
What fonts are required for the polybar configuration? I have siji-git, and ttf-unifont but it keeps saying there's unmatched characters (And I can even see the correct characters in my terminal)

**Comment by Daenarii** [comment]
Those are defined on the polybar config, on the [bar/example] section

For example, here's my personal modification:
font-0 = mono:pixelsize=9;1
font-1 = Wuncon Siji:pixelsize=9;1
font-2 = Noto Sans Mono CJK JP:pixelsize=9;1
font-3 = unifont:fontformat=truetype:size=9;0

**Comment by v0idst4r** [comment]
What does mono resolve to?

**Comment by v0idst4r** [comment]
Thank you @Daenarii, it turns out it was because I had quotes around the font name which didn't work.

**Comment by Daenarii** [comment]
You're welcome.
"mono" is your default monospace font, as defined in ~/.config/fontconfig/fonts.conf
