### ISSUE TITLE
[LARBS] `~/.mozilla` is owned by `root`

### ISSUE THREAD

**Issue by sarpik** [LukeSmithxyz/voidrice#376]
Hello,

I've riced my arch w/ larbs quite some time ago.

I don't know if this is still the case, but I found that my `$HOME/.mozilla/` folder was owned by root. Before I found this out, it was confusing as to why some things didn't work as expected.

The fix is obviously trivial:

```sh
$ sudo chown -R "$USER" ~/.mozilla
```

---

I think this is to do with the following lines in the `larbs.sh` script:
https://github.com/LukeSmithxyz/LARBS/blob/master/archi3/larbs.sh#L206-L207

```sh
# Install the LARBS Firefox profile in ~/.mozilla/firefox/
putgitrepo "https://github.com/LukeSmithxyz/mozillarbs.git" "/home/$name/.mozilla/firefox"
```

---

I would've just created an issue in https://github.com/LukeSmithxyz/LARBS - I don't know why ya disabled issues there:/

Anyhow, cheers & hopefully find a fix.

**Comment by LukeSmithxyz** [comment]
Closing this. Firefox is being removed from the system and replaced with Brave. It was a pain to maintain that repo anyway...
