### ISSUE TITLE
missing zsh and lf configs

### ISSUE THREAD

**Issue by joamatab** [LukeSmithxyz/voidrice#378]
Hi Luke!

I think the files that you refer in your latest youtube video are missing:

~/.config/zshrc
~/.config/lf

Thank you for sharing your awesome dotfiles!

**Comment by joamatab** [comment]
I found your zshrc config 
https://gist.github.com/LukeSmithxyz/e62f26e55ea8b0ed41a65912fbebbe52

it would be great if you could share your lf config too ^^

**Comment by kronikpillow** [comment]
I think his lf config is in the voiddwm branch
