### ISSUE TITLE
Larbs for Ubuntu

### ISSUE THREAD

**Issue by adimishra1** [LukeSmithxyz/voidrice#379]
Adding LARBS for Ubuntu would be really great as there are many Ubuntu users.

**Comment by kronikpillow** [comment]
these are just dotfiles, if you install all the programs and dependencies I don't see why it wouldn't work on Ubuntu

**Comment by adimishra1** [comment]
I was talking about an Auto-Ricing Script.

**Comment by lukelane124** [comment]
@adimishra1 Are you referring to LARBS? or something else?
Luke doesn't use Ubuntu for daily driver. It might not even be super difficult to convert. I bet if you could spare a few hours and write a script Luke might include it as an alternative.

**Comment by kronikpillow** [comment]
the LARBS auto ricing script uses arch package names, which have a equivalent in Debian/Ubuntu based systems usually under a different name, like I said, all you need to do is find the packages, install them, and then use voidrice/archi3 branch to get the settings in ... or like @lukelane124 suggested, you could fork the LARBS repository and make it compatible with Ubuntu / Debian Based systems
