### ISSUE TITLE
i3Blocks not loading

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/voidrice#38]
Just installed from the LARBS, I started a system without realising LARBS existed and when I ran LARBS on it, it broke. So I just started from scratch again. Polybar is now gone, and there is no replacement showing.

**Comment by LukeSmithxyz** [comment]
My bad, I forgot to push some other changes. To fix, first run the following:
```
git fetch --all
git reset --hard origin/master
sudo pacman -S noto-fonts-emoji
```
Tell me if that works.

**Comment by blackjok3rtt** [comment]
Sorry dude went back to polybar. I Think I like it better anyway. Thanks for the great system. Really liking it so far, its a lot to learn but I'm sure it will be worth it. I do a lot of work in terminals these days.
