### ISSUE TITLE
voiddwm fontconfig not loading

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#389]
I recently installed void on my 2nd hdd, and went ahead and installed LARBS for void, but the fontconfig is not being respected by the applications, anyone got any idea how to fix this?

**Comment by kronikpillow** [comment]
figured it out :) the fonts on void are named with a O at the end, so I just appended it to the fonts name like bellow
Linux Libertine O
Linux Biolinum O

**Comment by dm17** [comment]
@kronikpillow would comment on your forked repo, but the option isn't there. I'm wondering if you maintain voidrice for your void install...
