### ISSUE TITLE
Key shortcuts don't behave as expected on an azerty keyboard

### ISSUE THREAD

**Issue by rlouage** [LukeSmithxyz/voidrice#391]
I installed larbs and everything works fine except the keyboard shortcuts. Some seem to work others don't. For example when I press Mod+q the window closes but when I press Mod+Shift+W the browser doesn't start. I have to press Mod+Shift+Z for the browser to start. 

My /etc/X11/xorg.conf.d/00-keyboard.conf contains the following:
Section "InputClass"
        Identifier "system-keyboard"
        Option "XkbLayout" be"
        Option "XkbModel" "inspiron"
        Option "XkbVariant" "oss"
EndSection
And my ~/.config/i3/config contains the following line:
exec "setxkbmap -layout be -model inspiron -variant oss"

Any suggestions to fix this?

**Comment by rlouage** [comment]
After another day I found the solution. 
The problem was sxhkd, the program that is used to map keys.
If you use a non English keyboard sxhkd should be started with the -m -1 option.
This program is started in ~/.xprofile, so I changed it there and now everything works fine.

**Comment by 20jam** [comment]
Hay, Can I have the code snippet, I'm having the same probelm. To what keyboard I shall change or what do I add into xprofile ?
Thanks

**Comment by rlouage** [comment]
> Hay, Can I have the code snippet, I'm having the same probelm. To what keyboard I shall change or what do I add into xprofile ?
> Thanks

in .xprofile there is a line that starts sxhkd just add  -m -1 after that
