### ISSUE TITLE
Consider adding "exec xrdb .Xresources" to i3/config

### ISSUE THREAD

**Issue by drondistortion** [LukeSmithxyz/voidrice#392]
Maybe I'm using it wrong, but right now dpi settings and fonts in .Xresources only update with vim autocmd. So every time you login, you get defaults unless you open and save .Xresources with vim. Try setting the font size to something else in .Xresources and see if it the issue is there. 
Keep up the good work.

**Comment by kronikpillow** [comment]
there is no .Xresources in the default larbs setup, you can add and expand Luke's config how ever you want mate

**Comment by drondistortion** [comment]
Ok, fwiend.
