### ISSUE TITLE
some minor suggestions

### ISSUE THREAD

**Issue by eth-man** [LukeSmithxyz/voidrice#393]
1. a way to open youtube links with mpv in a floated window ( implement to cabl script?)

2. add dmenu SSH script , for example:
$TERMINAL -e ssh `cat ~/.ssh/config | grep ^Host | cut -d" " -f2 | dmenu -l 35 -p "SSH to?"`

**Comment by Segdon** [comment]
another suggestion; be it for a browser:
luakit.github,io
