### ISSUE TITLE
wallpaper stays black

### ISSUE THREAD

**Issue by dschense** [LukeSmithxyz/voidrice#398]
Hey, i don't know what changed, but since some days my wallpaper changed to a static black color. I think its the default i3 background.
I wanted to change the background to my wall.png, so I run the setbg with "bg" in vifm and got the message that the wallpaper changed. but wallpaper still stays black.
i looked in the .config folder and looked at the preview of the wall.png and it was the right wallpaper i wanted the system to change to.
then I run the xwallpaper --zoom ~/.config/wall.png, but nothing happens. my wallpaper stays black.
Any help to get this fixed?
I already rerun the larbs.sh script, but the problem still exists.

**Comment by Daja177** [comment]
@dschense Since this issue is still open, do you still experience this problem?

**Comment by dschense** [comment]
I dont know what exactly caused this problem.
After doing a fresh install - arch from scratch - everything is working again.
