### ISSUE TITLE
LARBS, but dwm

### ISSUE THREAD

**Issue by bQvg5S66szS** [LukeSmithxyz/voidrice#400]
Hello, I've used LARBS with i3 for many weeks now, and checked out Luke doesn't use it anymore. I was wondering how could I get LARBS running with dwm instead of what it deploys by default (i3).
I also checked out he's going to make i3 legacy so, I think it's a good idea just to move from now. 

Appreciate the help.

**Comment by Trebled** [comment]
http://git.suckless.org/dwm/file/README.html

**Comment by vladdoster** [comment]
You just need to switch to the dwm folder and run vlarbs.sh.

**Comment by LukeSmithxyz** [comment]
I had taken the directions off of the website, since I was making substantial changes, but I think it should work right like this:

```
curl -LO larbs.xyz/vlarbs.sh
bash vlarbs.sh
```

Don't run the normal LARBS or you won't get all the dependencies.

**Comment by LukeSmithxyz** [comment]
Now there's only one script which will give you the choice of what to install explicitly. Use

```
curl -LO larbs.xyz/larbs.sh
sh larbs.xyz
```

for either one and you will be prompted.
