### ISSUE TITLE
weather forecast fonts issue

### ISSUE THREAD

**Issue by eth-man** [LukeSmithxyz/voidrice#404]
when pressing at the weather icon at the status bar it always looks like below:

![image](https://user-images.githubusercontent.com/8633885/68985054-0e451d00-0814-11ea-9551-4c07a7bf230b.png)

**Comment by eth-man** [comment]
problem is with less command at the weather script
fixed by replacing line 11 : 
    1) $TERMINAL -e less -S "$HOME/.local/share/weatherreport" ;;

with:

    1) $TERMINAL -e less -rf "$HOME/.local/share/weatherreport" ;;

**Comment by LukeSmithxyz** [comment]
Yeah we had an issue on this a while back. It's based on localization/encoding. What's your `$LANG` variable?

Does your solution maintain color characters on your machine?

**Comment by LukeSmithxyz** [comment]
I'll be explicit: if yout `$LANG` is `C` or something else, it will do this. Mine is `en_US.UTF-8` and it works fine and other UTF values should work.
