### ISSUE TITLE
tmux lost server

### ISSUE THREAD

**Issue by rpolve** [LukeSmithxyz/voidrice#406]
tmux 2.9_a-4
st 0.8.2
bash 5.0.11
5.3.11-arch1-1

Hi,

I could not understand what was the upgrade that broke it, but since a couple of days tmux has stopped working, returning "lost server" and leaving a broken terminal.

I circumvented this problem by creating a script analogous to [.local/bin/i3cmds/tmuxdd](https://github.com/LukeSmithxyz/voidrice/blob/archi3/.local/bin/i3cmds/tmuxdd) which uses [screen](https://www.archlinux.org/packages/extra/x86_64/screen/) instead:

```
#!/bin/sh
# Similar to tmuxdd but using screen instead.
screen -r || screen
```

**Comment by decantr** [comment]
Set your `$TERM` to `xterm-256color` and `tmux` should work correctly.

`export TERM="xterm-256color"`

**Comment by rpolve** [comment]
Thank you, it is solved!

**Comment by vladdoster** [comment]
This did not seem to resolve my issue. Can I not use st?
