### ISSUE TITLE
vlarbs.sh has gone?

### ISSUE THREAD

**Issue by hsigrist** [LukeSmithxyz/voidrice#407]
Hi Luke, I have void-linux and install vlarbs.sh long time ago. How proceed now? larbs.sh is for Arch Linux... I'm confused

**Comment by LukeSmithxyz** [comment]
Yes. It's gone now: I'm engineering the single larbs.sh script to handle various Arch-distros and Void and maybe distros with `apt-get` as well. If you try it on a fresh Void install it _might_ work right now, but I haven't tested it myself as I'm currently testing on Arch and Artix.

If you look at the progs file, it's now universal for all distros, although packages needed for specific distros are tagged differently. Again, it's in progress and hopefully I'll have more time to test soon before I make public announcements.

**Comment by hsigrist** [comment]
@LukeSmithxyz Thanks Luke.
