### ISSUE TITLE
archi3  branch gone?

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#408]
I notice that you have deleted your archi3 branch :-/ is there any  way we can get a backup of that branch?

**Comment by LukeSmithxyz** [comment]
Well I deleted the branch because now the master branch has all the
configs required for both i3 and dwm, so there shouldn't be anything
lost between the two.

**Comment by kronikpillow** [comment]
ahh cool ... what about the progs.csv from the archi3 branch? does LARBS now give option to chose between i3 or dwm or?

**Comment by LukeSmithxyz** [comment]
Yeah so here's the thing: basically the dwm and i3 versions were 97% the exact same so I figured (for the time being at least) why not just have LARBS install _both_ WMs and then just give the user a choice of which should be default? So that's what it does now. When you run LARBS, you get both i3 and dwm and it'll ask you which it should treat as default.

Oh yeah I might restore those vifm configs too. They are in the master branch's history. Obviously vifm is no longer installed by LARBS, but I figure I might as well keep all the old stuff because I think many people who use this repo come from YouTube and just want to see some dotfiles for whatever I'm talking about (although I don't think I ever did a video on vifm, but still...).

**Comment by sarpik** [comment]
Luke that's actually awesome!

Could we please get the `polybar` configs/setup back too?:o
[It looked \*dope\*](https://youtu.be/q-l7DnDbiiU) ([real dope](https://youtu.be/4Jx-5Zp28VQ)) & I'd love to try'em out.
(I've previously tried going through the commit history & found 'em, but I'm new to polybar and couldn't really set it up properly).

Thanks & gl!

**Comment by LukeSmithxyz** [comment]
Well I can put back in the polybar configs (removed in d57e9503d8aeaef6e8f7f8e76bc92ad81c3a490c), but I honestly didn't really change anything about them. Who knows, it might be worth doing some more work on them.

**Comment by kronikpillow** [comment]
yes I would love to learn more about polybar, you wouldn't believe how much I actually learned, just by forking your setup, and then playing around with it, I remember you talked about not liking to keep old stuff that you don't use, but mate, LARBS is basically a distribution, :dagger: 
that is nice, I recently switched to Artix, but on Artix pulseaudio had serious problems for me, like sound stopping to work out of no reason, are both version compatible with Artix? or is LARBS at all compatible with Artix?

**Comment by kronikpillow** [comment]
another question, sxhkd keybindings, how are they solved between dwm and i3? as they were quite different as i remember, also the i3 config, has some keybindings that you moved to sxhkd later when you switched to dwm, like the mod+v (vimwiki)

**Comment by LukeSmithxyz** [comment]
I don't use pulseaudio anymore at all actually, so if Artix has some problems with it I wouldn't know. I can say that I've experienced some problems with `-runit` packages on it, and some of them sort of require manually editing to work in the expected way.

As for sxhkd, basically sxhkd binds those keys in common to the two (most of them) (and it's more extensible than either WM in so doing). The remaining keys, mostly those under the the first two rows of your right hand, are bound differently by both WMs. (I haven't put all of this in the documentation yet, but there it is.)

I did move a couple of bindings around to make it more cohesive and coherent between the two.

**Comment by kronikpillow** [comment]
yeah I noticed that some runit services don't run as expected, and require manual intervention, like the mpd service, I just couldn't get ncmpcpp to connect to the mpd daemon if i ran mpd as a service, no matter what i tried, I guess artix isn't still quite there yet ... do you use Artix or have you switched back to Arch?

**Comment by LukeSmithxyz** [comment]
I just have the runit service start the daemon as my main user like this in `/etc/runit/sv/mpd/run`:

```
#!/bin/sh
install -d -m 0755 -o luke -g wheel /run/mpd
install -d -m 0755 /var/lib/mpd/playlists
chown -R luke:wheel /var/lib/mpd
exec chpst -u luke:wheel mpd --no-daemon
```

Works fine for me. I do the same with transmission. I think that the runit defaults are just assume a different workflow than usual. Either way, I have larbs start mpd manually in one of the profile files.

**Comment by kronikpillow** [comment]
that's what I'm looking for man, I didn't know how to customize it properly, still learning :) 
can you share the transmission setup as well? thanks :)
any other services you use?

**Comment by LukeSmithxyz** [comment]
My transmission run file is just:
```
#!/bin/sh
exec chpst -u luke:wheel transmission-daemon -f --log-error
```
I use other services as well like cups and NetworkManager (wpa_supplicant alone has been vexing on Artix for several reasons), but I didn't really make any changes to the run file.

**Comment by kronikpillow** [comment]
thanks, in general, I don't need NetworkManager or wpa_supplicant because I have fiber optics internet and don't use wifi at home, but good to know :) thanks for your time
