### ISSUE TITLE
Tmux lost server

### ISSUE THREAD

**Issue by vladdoster** [LukeSmithxyz/voidrice#410]
I tried #406 with no avail. put the export in my .profile.

Can I not use ST with the dropdown tmux?

ideas?

**Comment by Sercurio** [comment]
What return :
```
env | grep TERM
```
?

**Comment by vladdoster** [comment]
![pic-window-191127-1327-27](https://user-images.githubusercontent.com/10052309/69826828-d5795080-11e2-11ea-8300-72954fb316f6.png)

**Comment by vladdoster** [comment]
![pic-window-191128-1327-22](https://user-images.githubusercontent.com/10052309/69826849-e1fda900-11e2-11ea-8cf4-de7b09acaaca.png)

**Comment by vladdoster** [comment]
![pic-window-191128-1328-41](https://user-images.githubusercontent.com/10052309/69826877-ff327780-11e2-11ea-8573-50680a879e34.png)

**Comment by Sercurio** [comment]
I don't know if it is normal but i see in the other ticket to export "xterm-256color" instead of st-256color. You maybe have already tried that.

**Comment by vladdoster** [comment]
> I don't know if it is normal but i see in the other ticket to export "xterm-256color" instead of st-256color. You maybe have already tried that.

I have :disappointed:

**Comment by somrandom** [comment]
I'm having a similar problem. running `$ TERM="xterm-256color"` does get tmux working but only in that terminal.  I've put export TERM="xterm-256color" in .profile and rebooted, however `$ env | grep TERM` returns:
`LESS_TERMCAP_se= `
`LESS_TERMCAP_so= `
`TERMINAL=st `
`TERM=st-256color` 
`LESS_TERMCAP_mb= `
`LESS_TERMCAP_me= `
`LESS_TERMCAP_md= `
`LESS_TERMCAP_ue= `
`LESS_TERMCAP_us= `
running `$ source ~/.profile` does update the $TERM variable but only in that terminal. 

I'm new at this was I verbose enough?

**Comment by decantr** [comment]
tmux works fine for me on `3.0a` with no need to change `TERM`.

![pic-window-191204-2213-41](https://user-images.githubusercontent.com/24387118/70186282-7f754300-16e3-11ea-9dc0-491d85e4af3b.png)

This seems to be because it is setting the correct `TERM` value from the config.

![pic-window-191204-2214-05](https://user-images.githubusercontent.com/24387118/70186338-9e73d500-16e3-11ea-9f9c-8984eab27d88.png)
 
Do your `.tmux.conf`  configs include this line?
https://github.com/LukeSmithxyz/voidrice/blob/cb8a1586e9d499f15b87d74b73461f21c0f19094/.tmux.conf#L4

**Comment by somrandom** [comment]
It does:
`$ grep terminal .tmux.conf `  
`set-option -g default-terminal "xterm-256color" `
`set -g terminal-overrides 'xterm*:smcup@:rmcup@' `
tmux version 3.0a
also interestingly if i run tmux again without setting $TERM it kills all tmux sessions
as a "Temporary" solution ive added export TERM="xterm-256color" to the start of any script that uses tmux

**Comment by vladdoster** [comment]
So I found the issue to this problem....

In the [st config header](https://github.com/LukeSmithxyz/st/blob/master/config.h#L67) sets the $TERM env var to st-256color. I changed it to xterm-256color, ran `sudo make install` and it fixed the issue. Not sure if it will effect anything else but god I am happy to have fixed it.

@somrandom you might want to try this fix and clean up those bad habit exports you have added to various files.

**Comment by somrandom** [comment]
Yup thats fixed it.

**Comment by decantr** [comment]
This shoulnd't need to be changed, with the `$TERM` to `st-256color`
 and tmux still functions as intended.

This must be caused by something else.

**Comment by vladdoster** [comment]
> This shoulnd't need to be changed, with the `$TERM` to `st-256color` and tmux still functions as intended. This must be caused by something else.

I assume that you haven;t installed larbs in a while, and you are missing the error. Something about where it looks correct for you but under the hood it is the same. IDK, just a guess. I am just as confused.

**Comment by decantr** [comment]
> I assume that you haven;t installed larbs in a while, and you are missing the error. Something about where it looks correct for you but under the hood it is the same. IDK, just a guess. I am just as confused.

I am up to date with the latest commit, but no I have not done a fresh
 install since the dwm/i3 split.
Could be some hangover config?

**Comment by vladdoster** [comment]
> I assume that you haven;t installed larbs in a while, and you are missing the error. Something about where it looks correct for you but under the hood it is the same. IDK, just a guess. I am just as confused.
> I am up to date with the latest commit, but no I have not done a fresh install since the dwm/i3 split. Could be some hangover config?

That is what I am thinking. Maybe try `make install` on [luke's ST repo](https://github.com/LukeSmithxyz/st) and see if it crashes tmux. Odd though you aren't experiencing the issue.

**Comment by decantr** [comment]
I am running the most current commit of Luke's st, though I do not have
 this issue in either the upstream st or Luke's fork.

**Comment by vladdoster** [comment]
> I am running the most current commit of Luke's st, though I do not have this issue in either the upstream st or Luke's fork.

Odd. I will do some more grepping of my system to see where I might have caused the error.
