### ISSUE TITLE
multiple problems with dwm

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#413]
Hi luke, just today, i decided to go back to LARBS and try out this new setup that you uploaded recently, I have installed on Artix with runit ...

now, problems that I'm experiencing .... the terminal keeps randomly closing on me when I try to open some files ...

for example
when I run ranger or lf and go to .config/lf folder, the terminal closes
when I run vifm I can go to .config/lf folder but when i try to open any of the files inside the terminal closes
when with all 3 file managers variants i go to .local/bin/cron the terminal closes
same thing when I go to .local/share/larbs the terminal closes 

dmwblocks is not running, when I try to invoke it manually i get the following error

```
cat: /tmp/recordingicon: No such file or directory
find: ‘/home/kronikpillow/.local/share/mail/*/INBOX/new’: No such file or directory
amixer: Unable to find simple control 'Master',0

sed: can't read /sys/class/power_supply/BAT?/capacity: No such file or directory
sed: can't read /sys/class/power_supply/BAT?/capacity: No such file or directory
```

then, I gitcloned your dwmblocks build to edit it and remove the battery and that recordingicon thing (what ever that is) and when I try to nvim blocks.h terminal closes ... do you have any idea why is this happening to me?

I have also tried to edit the files with nano, terminal keeps closing ... very very frustrating, I dunno what to do or how to debug this

I got other problems as well, but I will get to them once I solve this somehow

**Comment by LukeSmithxyz** [comment]
Oh, all of these problems are nearly certainly caused by a lack of proper installed font characters...

Can you show me `fc-match mono`? Did `nerd-fonts-inconsolata` install correctly?

**Comment by LukeSmithxyz** [comment]
Oh actually, looks like `nerd-fonts` isn't even in the progs.csv... Could you just show me what `pacman -Q | grep ttf` shows?

**Comment by kronikpillow** [comment]
sure bro ...
`pacman -Q | grep ttf
ttf-font-awesome 5.11.2-1
ttf-inconsolata 1:2.0.0.1-3
ttf-joypixels 5.0.3-3
ttf-linux-libertine 5.3.0-4
`
and I have installed nerd-fonts-complete from the AUR

ttf-font-awesome was installed manually by me, I figured it could be a font issue as I saw that there are fonts like that in the config files, after installing ttf-font-awesome and nerd-fonts-complete, it seems to work now :)

I'll uninstall one then the other to see which one was breaking it

**Comment by LukeSmithxyz** [comment]
Alright, tell me what happens. I can probably give more specific fontconfig rules to avoid this kind of problem.

**Comment by kronikpillow** [comment]
I removed the ttf-font-awesome and lf and dwmblocks files work, which means for those files the nerd-fonts were the problem, but going the .local/share/larbs/emoji file still crashes the terminal, and when I press mod+` it is very slow and sluggish compared to how it used to be, digging in further, I noticed that ttf-symbola was not installed

I get the following error when I try to install it with yay
`==> ERROR: Failure while downloading http://users.teilar.gr/~g1951d/Symbola.zip
    Aborting...`

**Comment by kronikpillow** [comment]
the second problem I'm having atm is with the .asoundrc that is provided by LARBS, I have a professional M-Audio Delta 66 sound card, which is now a legacy sound card (not that it matters) and when I was using pulseaudio on Arch (which for some reason has serious problems on Artix) all I had to do to get my sound working was to open up alsamixer and unmute / raise volume on DAC & DAC1 channels, which are 2 mono channel, DAC is the left and DAC1 is the right channel, I need to "downmix" or "upmix" or "dmix" those 2 channels in to 1 stereo "master" channel, which doesn't even exist on my sound card. I do have a hardware mixer Xenyx502, but I wan't to be able to use software mixing as well, as I have dismantled my audio studio and mainly use the soundcard only for playback as my integrated Intel sound card is fried and doesn't work...

when I open up alsa, it seems to default to the NVIDIA Graphics Card HDA soundcard which I don't use : https://0x0.st/zI5Q.png

when I press F6 it presents a menu with -default, 0 HDA Nvidia, 1 M Audio Delta 66: https://0x0.st/zI51.png

then I go down to the M Audio Delta 66, and raise the volume on DAC and DAC1 to -18.50 dB gain, and nothing happens ... https://0x0.st/zI5j.png

I have never used pure alsa before, so I dunno how to do this, I've been reading the Arch Wiki ALSA section, I have tried multiple solutions provided there, and none of them work

the output of cat /proc/asound/modules is:
 0 snd_hda_intel
 1 snd_ice1712

 the output of speaker-test is:
speaker-test

speaker-test 1.2.1

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Playback open error: -2,No such file or directory

....

the only way I was able to get my sound card to work is if I had this in my .asoundrc

defaults.ctl.card 1;
defaults.pcm.card 1;

but with it, I have no control of the outputs through the Raise/Lower/Mute Volume keys on my keyboard, and the dwmblocks isn't displaying it either, as the Master channel doesn't exist, the 2 channels it uses are 2 separate mono channels, that I would need somehow to link or mix to a "dummy master channel" which used to be PulseAudio .....

any idea how I can achieve this? :)

**Comment by kronikpillow** [comment]
I have found this configuration [asound.conf](https://github.com/Cloudef/dotfiles-ng/blob/master/%23ARCHCONFIG/etc/asound.conf) and used it, and it works, but still no master channel, so I modified it and added the following to it

# Software Master control
pcm.softvol {
   type softvol
   slave {
   pcm "asymed"
   }
   control {
   name "Master"
   card 1
   }
}

# Default PCM
pcm.!default {
   type plug
   slave.pcm "softvol"
}

while output of amixer controls | grep Master is still empty, eg the channel doesn't exist

**Comment by kronikpillow** [comment]
and 3rd problem Im having is, ncmpcpp isn't playing sound at all, while if i run a song with ranger it plays in the terminal with no problems

**Comment by LukeSmithxyz** [comment]
Okay. The volume controls in LARBS are set to adjust the `Master` by default. I suppose I can make them refer to an environmental variable to allow more streamlined changes.

The ncmpcpp problem is a problem with mpd. Check the mpd config and you'll have to adjust its default output to the new one. Again, there might be a way to make it refer to some user-defined default.

I'll check into all this when I can. Yes, ALSA can be a big pain because _here is literally no good documentation for this basic feature of the operating system anywhere_. If it proved too difficult to make work on many people's systems, I'll have LARBS ship with pulseaudio.

**Comment by kronikpillow** [comment]
well PulseAudio is a option definitely, but I can't seem to get it working properly on Artix, out of no reason sound stops working at various times, and sometimes right after a reboot, it doesn't work at all, then I reboot again and it works, I launch up ncmpcpp and the sound is pitched down and plays at a slower rate, until I go to youtube to play some song, then the pitch goes back to normal, and all of a sudden music from mpd is working properly .... So I figured since I'm using Artix, and honestly don't plan to switch back to systemd, that figuring this out is worth my trouble :) so I did, a Lil thx to your help, a Lil thanks to the internet ...

I managed to get it working ... what I did was blacklist snd_hda_intel to disable the NVIDIA HDMI audio, then I played around with the settings from those links I linked in the previous post and got the following result:
[KP's .asoundrc](https://github.com/kronikpillow/voidrice/blob/susanoo/.asoundrc)

now I have a master channel, and the buttons on the keyboard are working, the only thing that I am bothered now about is that in the bar next to the volume icon I have 2x 100% indicator, check out the [screenshot](https://0x0.st/zIRH.png)

**Comment by LukeSmithxyz** [comment]
Well `ttf-symbola` _should_ be installed by LARBS by default... I suppose something went wrong, but it's in the `progs.csv`.

Okay, good on the audio issue. That's a typical problem; the issue is me making it usable for the masses without them all having to figure it out...

**Comment by kronikpillow** [comment]
the aur package ttf-symbola is broken, it returns a download error on the Symbola.zip as it is non existent on the host where the PKGBUILD points to

so ... how do I get rid of the 2nd volume bar in the dwmblocks?
