### ISSUE TITLE
If no internet connection the script continue and no error message

### ISSUE THREAD

**Issue by Sercurio** [LukeSmithxyz/voidrice#415]
I forgot to restart my dhcpcd and start larbs.sh. The script continue and print installation sucessful but nothing is installed.

Maybe add a function in larbs.sh who ping 8.8.8.8 (or ur website) to know if a connection is active and if not print an error message.

**Comment by LukeSmithxyz** [comment]
LARBS should implicitly check for internet connection when it first tries to install `dialog` at the beginning of the script. Did you have `dialog` installed beforehand by any chance? I suppose it wouldn't check the remote repos if so...
