### ISSUE TITLE
Void linux, i3: shortcuts don't work

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#416]
After installing i3 LARBS on Void (accidentally, see my recent issue in the LARBS repo), none of the keyboard shortcuts register except mod+f1 and mod+f2.

**Comment by Sercurio** [comment]
Hi, 
What's your keyboard layout ? I have fr layout and got some trouble with i3 shortcuts.
Before Luke use sxhkd  all works properly, I think there some conflicts between i3, keyboard layouts and sxhkd.

**Comment by Daja177** [comment]
This issue is a few months old and the author still hasn't responded, it should be safe to close it @LukeSmithxyz
