### ISSUE TITLE
i3 statusbar issue

### ISSUE THREAD

**Issue by anntnzrb** [LukeSmithxyz/voidrice#418]
on i3, if you scroll on the volume icon to decrease/increase (statusbar) it will show a gray rectangle when updating the volume value; if you restart i3 it gets fixed with the updated value. just visual issue.

**untouched**
![pic-selected-191202-1142-55](https://user-images.githubusercontent.com/51257127/69977668-36619b00-14f9-11ea-8584-4525537cadde.png)
**after scrolling on it**
![pic-selected-191202-1143-13](https://user-images.githubusercontent.com/51257127/69977675-38c3f500-14f9-11ea-9ae5-e54dc4c8e7af.png)
**after i3 refresh/reload**
![pic-selected-191202-1145-52](https://user-images.githubusercontent.com/51257127/69977724-51340f80-14f9-11ea-8f19-61e0f9b9558e.png)

**Comment by LukeSmithxyz** [comment]
Fixed. The amixer commands were returning stdout to the bar, but I've now silenced it.
