### ISSUE TITLE
dwm statusbar fails to update after installing pulseaudio

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#419]
After having some trouble getting ALSA to work, I installed pulseaudio. While pulseaudio works, the song is not displayed in dwmblocks, which won't update after starting/changing a song in ncmpcpp unless I manually run it in terminal.

**Comment by Daja177** [comment]
@drake-newell To use pulseaudio with dwmblocks you'll need to replace the `amixer` command in `blocks.h` and recompile it. You can find its repository at https://github.com/LukeSmithxyz/dwmblocks
