### ISSUE TITLE
ttf-symbola no longer available (emoji/unicode rendering issues)

### ISSUE THREAD

**Issue by anntnzrb** [LukeSmithxyz/voidrice#421]
> It seems that the upstream author has removed all of their fonts, which is unfortunate. Additionally, AUR helpers generally aren’t supported.

[source](https://aur.archlinux.org/packages/ttf-symbola/#comment-718686)

as of right now, without `ttf-symbola` your config is unable to launch an emoji/unicode file via `st` without crashing (haven't tested other terminal emulators).

```bash
λ whatever [~] →  yay -S ttf-symbola 
:: There are 2 providers available for ttf-symbola: 
:: Repository AUR 
    1) ttf-symbola 2) ttf-symbola-ib 
Enter a number (default=1): 1 
:: Checking for conflicts... 
:: Checking for inner conflicts... 
[Aur: 1]  ttf-symbola-12.00-2 
:: Downloaded PKGBUILD (1/1): ttf-symbola 
  1 ttf-symbola                      (Build Files Exist) 
==> Diffs to show? 
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4) 
==> n 
:: Parsing SRCINFO (1/1): ttf-symbola 
==> Making package: ttf-symbola 12.00-2 (Mon 02 Dec 2019 11:07:52 AM -05) 
==> Retrieving sources... 
  -> Downloading ttf-symbola-12.00.zip... 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current 
                                 Dload  Upload   Total   Spent    Left  Speed 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 
curl: (22) The requested URL returned error: 404 Not Found 
==> ERROR: Failure while downloading http://users.teilar.gr/~g1951d/Symbola.zip 
    Aborting... 
Error downloading sources: ttf-symbola 
```
right now i'm using the following fonts which are also unable to render the specified characters either:

```
ttf-junicode
ttf-joypixels
noto-fonts-emoji
ttf-bitstream-vera
ttf-dejavu
ttf-droid
ttf-fira-code
ttf-fira-mono
ttf-font-awesome
ttf-hack
ttf-inconsolata
ttf-liberation
ttf-linux-libertine
ttf-ms-fonts
ttf-roboto
ttf-vista-fonts
font-bh-ttf
sdl_ttf
adobe-source-code-pro-fonts
cantarell-fonts
font-bitstream-speedo
gnu-free-fonts
gsfonts
noto-fonts
```

just for extreme detail i'm attaching what i currently have set on my `.Xresources` (which takes priority) (duh)

notice i've set my `st.font` to what luke's `st` uses by default anyway...

```bash
*.font: xft:Overpass Mono:size=10

Xft.dpi:                        96
Xft.antialias:                  1
Xft.autohint:                   1
Xft.hinting:                    1
Xft.hintstyle:                  hintslight
Xft.lcdfilter:                  lcdlight
Xft.rgba:                       rgb

!! st
st.font:Inconsolata:pixelsize=16:antialias=true:autohint=true;
st.alpha: 0.85
!! \end st

!! dracula modified
! special
*.foreground:   #a6a182
*.background:   #282a36
*.cursorColor:  #f8f8f2
! black
*.color0:       #000000
*.color8:       #4d4d4d
! red
*.color1:       #ff5555
*.color9:       #ff6e67
! green
*.color2:       #50fa7b
*.color10:      #5af78e
! yellow
*.color3:       #f1fa8c
*.color11:      #f4f99d
! blue
*.color4:       #bd93f9
! magenta
*.color5:       #ff79c6
*.color13:      #ff92d0
! cyan
*.color6:       #fdec8b
*.color14:      #fdec8b
! white
*.color7:       #bfbfbf
*.color15:      #e6e6e6
```

**Comment by LukeSmithxyz** [comment]
Lol yeah, I noticed this and I was ignoring it hoping it be magically fixed. It's why there have been so many "i installed larbs but nothing works" issues. st breaks if it doesn't have the right fonts.

It looks like the problem is that symbola is basically gone for good due to a licensing change, so I'll have to find another font with sufficient coverage to make as the default emoji font.

**Comment by kronikpillow** [comment]
download it from this Arch custom repository and install it with pacman -U packagename or add it to your pacman.conf (the pacman.conf didn't work for me for some reason) ... problem fixed ;)

I suggest to Luke that maybe setting up a custom repository of your own, with some custom packages of your own could solve a lot of AUR issues for important packages like this one :)

**Comment by LukeSmithxyz** [comment]
I've clumsily patched st such that it should avoid crashes, but the lack of the font and the problems it causes for dwm are still an issue. I might just have the script install it manually, but this is mostly out of my control and this is why this has been an enduring thorn in my side.

I'm going to probably make some fontconfig changes to minimize the damage.

**Comment by goldcoders** [comment]
I manage to complete all my emoticons 
ive just installed the following 
```
https://wiki.archlinux.org/index.php/Fonts#Emoji_and_symbols
```
p.s. i dont have ttf-symbola also but ive installed other packages listed there it works like a charm

**Comment by goldcoders** [comment]
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Sw1lazc0x9E" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by kronikpillow** [comment]
you can install ttf-symbola from a custom repository owned by ownstuff found here [https://wiki.archlinux.org/index.php/Unofficial_user_repositories](https://wiki.archlinux.org/index.php/Unofficial_user_repositories) ... he has a pkg build for it ... I suggest to luke to download it and include it in his repo, so that it is automatically installed, and it helps avoid aur issues regarding this font, I'v been using it, and I can say the package is trusted

**Comment by Jemi** [comment]
Noto and joypixels fonts don't really solve this issue, but it looks like twemoji may:

https://github.com/LukeSmithxyz/LARBS/issues/157#issuecomment-573956385

symbola could be used as a fallback if nothing better can be found for full coverage, but you're going to keep running into distribution problems if you rely on encumbered fonts. Look for unencumbered ones.

**Comment by anntnzrb** [comment]
[Color Emoji Fix in st: Suckless software now sucks less](https://youtu.be/f9qNXV01yzg)
