### ISSUE TITLE
ST + Brave keeps Crashing

### ISSUE THREAD

**Issue by 20jam** [LukeSmithxyz/voidrice#424]
Hay

So I've installed a fresh arch Manjaro i3, then  installed LARBS. 

The first Issue I faced is with the window manager, I choose DWM, but i3 was working instated. I ignored this issue, I figured something to do with the arch manjaro i3 community version. then Brave as well as chromium keeps crashing, specially when I switch between desktop and now after getting some heavy load on my terminal st crashed. I had to install another terminal and it didn't crash.

Do I have to install archlinux without Manjaro or i3 version? or it can be fixed by some sort of report I can share here to find the bug

Regards

**Comment by kronikpillow** [comment]
regarding ST it's probably because ttf-symbola AUR package is broken and LARBS uses it ... download it from this Arch custom repository [ownstuff custom Arch repo](https://martchus.no-ip.biz/repoindex/#packages) and install it with pacman -U packagename or add it to your pacman.conf (the pacman.conf didn't work for me for some reason) ... you also need the nerd-fonts-complete package from the AUR .... problem fixed ;)

**Comment by 20jam** [comment]
You're right, I've installed nerd-font and change fontconfig and now it stooped crashing, Thanks.

**Comment by kronikpillow** [comment]
I prefer Luke's fontconfig actually, I got used to it, so what I did was find a custom repo in the arch wiki that contains all the fonts from the AUR, and installed the font from there :) the link is in my above comment :)

**Comment by 20jam** [comment]
Thank you , now what left out for me 

* making dwm running instead of i3, 
* making st non transparent, and 
* making browsers stable after switching back and forward between workspaces

**Comment by LukeSmithxyz** [comment]
Update st to my newest build. A little hack in it from earlier today should avoid the crashing problem.

> making dwm running instead of i3,
Run `echo dwm > ~/.local/share/larbs/wm`. Or just change your `~/.xinitrc` to boot dwm.

> making st non transparent, and
Create an xresources file and set `st.alpha: 1`. Or kill xcompmgr and remove it from `~/.xprofile` to prevent it from starting next X session.

> making browsers stable after switching back and forward between workspaces
I don't know what this means.

**Comment by 20jam** [comment]
Hay, luke Thankkkkkkkkks. You are a truly time saver.

So this happens with mpv and other tools as well . 
When I open any browser, it works fine no crashing but when I have it on one workspace “1” and i switch to “2”. after couple of switches it freezes becoming unresponsive, then when i switch back & forward to it, it either crashes “the screen goes black”, or it shows as if I never change workspace, the only indicator is in the bar “1” “2”. in mpv the sound works but the screen black.

for st , how to I update it?

Thanks a lot luke.

**Comment by LukeSmithxyz** [comment]
Run a `yay` update, or just run `yay -S st-luke-git`, or go to the Github repo and install it manually.

Okay, that's an interesting problem... Do you have a computer with not that much memory?

**Comment by 20jam** [comment]
Thanks, My memory is 16gb. Do think because I may missing appropriate packages for my drivers?

**Comment by 191205** [comment]
```
$ less ~/.local/share/larbs/wm
dwm
```
```
$ less ~/.xinitrc 
case "$LARBSWM" in
       dwm) while :; do
               ssh-agent dwm || break
               done ;;
       i3) exec i3 ;;
       *) echo "No valid LARBS window manager detected." ;;
 esac
```

Then I rebooted. and still i3

then I tried the following script in `.xinitrc`:

```
redshift -O3500; xset r rate 300 50; exec dwm
```

and it still wont work :|

**Comment by 20jam** [comment]
After changing both larbs/wm & xinitrc the dwm just won't start. Is there other place where i3 is set. I use arch Manjaro i3 btw.

**Comment by prakash2033** [comment]
> regarding ST it's probably because ttf-symbola AUR package is broken and LARBS uses it ... download it from this Arch custom repository [ownstuff custom Arch repo](https://martchus.no-ip.biz/repoindex/#packages) and install it with pacman -U packagename or add it to your pacman.conf (the pacman.conf didn't work for me for some reason) ... you also need the nerd-fonts-complete package from the AUR .... problem fixed ;)

Which package needs to be downloaded and installed from link in above comment?

**Comment by prakash2033** [comment]
Got it, i installed ttf-symbola from there and fixed the problem. Also installed nerd-fonts-complete from AUR. Thanks

**Comment by 20jam** [comment]
Reinstalling arch with out manjoro i3 fixed my issue
