### ISSUE TITLE
Music Controll / Alsamixer problems

### ISSUE THREAD

**Issue by nerrufam** [LukeSmithxyz/voidrice#426]
Super + plus ==> nothing happens, when i have a terminal open it writes "=" equal signs
Super + shift + plus ==> increase by OLNY 5% (while it should do 15)

#minus works though
Super + minus ==> decrease by 5%
Super + shift + minus ==> decrease by 15%

pulsemixer with your lmc was just fine bruh 😅😅

**Comment by LukeSmithxyz** [comment]
How recently did you install? Pretty sure this was fixed last week some time.

**Comment by nerrufam** [comment]
two days ago (5th dec). ill try and rerun larbs.sh just to be sure.
(is there a known fix, or maybe conflicting pkg thas causes this?)

**Comment by nerrufam** [comment]
just reinstalled arch (to be more sure)
super + plus doesn't work (only writes '=' )
super + plus increases volume by random numbers
and i have no sound at all

**Comment by LukeSmithxyz** [comment]
I see. What kind of keyboard do you have? I suspect that that is the problem.

**Comment by nerrufam** [comment]
the laptops layout is german (which i dont use), i have connected a en_US keyboard, i choose en_US in the locales when i install  arch.
When i did a fresh arch and then larbs install, i had no sound from mpd, (i restarted it multiple times) but today i do have sound, idk what happened there.

**Comment by Ultrahalf** [comment]
Even the ncmpcpp visualizer doesn't seem to work. I installed it today

**Comment by vladdoster** [comment]
> Even the ncmpcpp visualizer doesn't seem to work. I installed it today. I checked the arch wiki and changed my ncmpcpp/config mpd.conf

Any more details on this? Kind of vague.

**Comment by Ultrahalf** [comment]
> Even the ncmpcpp visualizer doesn't seem to work. I installed it today. I checked the arch wiki and changed my ncmpcpp/config mpd.conf

**Comment by Ultrahalf** [comment]
> Even the ncmpcpp visualizer doesn't seem to work. I installed it today. I checked the arch wiki and changed my ncmpcpp/config mpd.conf

**Comment by Ultrahalf** [comment]
@vladdoster should i upload dotfiles?

**Comment by vladdoster** [comment]
> @vladdoster should i upload dotfiles?

No, just the relevant parts of what you changed in the ncmcpp config and maybe terminal output if you try to run the visualizer?

**Comment by Ultrahalf** [comment]
@vladdoster I uploaded a screencast in a repo

**Comment by vladdoster** [comment]
> @vladdoster I uploaded a screencast in a repo

Upload the photo or screen-cast to this thread. I don't want to rummage around in a different repository as well as it being hard for other to find if they have a similar issue.

**Comment by Ultrahalf** [comment]
@vladdoster also I couldn't open .config/i3blocks/config in nvim. I found solution for that in issue which was closed in feb 2019.Maybe i had issue with fonts and  now both ncmpcpp and nvim works fine. Thanks for your time

**Comment by nerrufam** [comment]
Well it turns out mpd wont work without pulseaudio (i guess), so i installed mpd and it worked.
lukes tipp was correctso i have changed sxhkdrc and it looks like this:
`# Increase volume
super equal
	vlmu5 ; pkill -RTMIN+10 $STATUSBAR
super plus
	vlmu15 ; pkill -RTMIN+10 $STATUSBAR

# Decrease volume
super minus
	vlmd5 ; pkill -RTMIN+10 $STATUSBAR
super underscore
	vlmd15 ; pkill -RTMIN+10 $STATUSBAR

# Audiokeys
XF86AudioMute
	vlmmt ; pkill -RTMIN+10 $STATUSBAR
XF86Audio{Raise,Lower}Volume
	{vlmu5,vlmd5}; pkill -RTMIN+10 $STATUSBAR`

amixer increases the volume in not whole numbers, so i have made simple vlm-up/down-5/15 and mute scripts using pulsemixer. They look like this:
`[nerrufam@x200 ~/.local/bin/fean-tools/vol-mng]$ grep -r .
vlmu15:#!/bin/sh
vlmu15:pulsemixer --change-volume +15
vlmmt:#!/bin/sh
vlmmt:pulsemixer --toggle-mute
vlmno:#!/bin/sh
vlmno:pulsemixer --get-volume | awk '{print $1}'
vlmu5:#!/bin/sh
vlmu5:pulsemixer --change-volume +5
vlmd5:#!/bin/sh
vlmd5:pulsemixer --change-volume -5
vlmd15:#!/bin/sh
vlmd15:pulsemixer --change-volume -15`

i also changed "vol" in /home/fean/.local/bin/statusbar/volume, it looks like this:
`vol=$(vlmno)` to also get the round no in statusbar.
i know its a dirty fix, but it works. Sorry i couldn't reply earlier.
