### ISSUE TITLE
Calculator keeps on popping up every time I refresh i3

### ISSUE THREAD

**Issue by Ultrahalf** [LukeSmithxyz/voidrice#431]
- Battery indicator isn't working
- Calculator keeps on popping up every time I refresh i3. 
- Music indicator in status bar won't update current playing song.   

I have default bindings i.e mod+F2 to restart i3 and mod +a for calculator. Config file looks fine. I'm fairly new to community. I  couldn't figure this.

**Comment by Orthdron** [comment]
CTRL+D to close the calculator permanently (ctrl+a will bring it back up)

**Comment by Ultrahalf** [comment]
Thanks @Orthdron 
I also found
