### ISSUE TITLE
I put my user in the wheel group, but it still gets prompted for a password every time i execute a sudo command.

### ISSUE THREAD

**Issue by HirschBerge** [LukeSmithxyz/voidrice#436]
``` 
I'm not sure exactly what I'm doing wrong here.
[sudoers.txt](https://github.com/LukeSmithxyz/voidrice/files/3992876/sudoers.txt)

**Comment by hakova** [comment]
Hi Hirschy,

On 19/12/22 10:51AM, Hirschy wrote:
> ```
> I'm not sure exactly what I'm doing wrong here.
> [sudoers.txt](https://github.com/LukeSmithxyz/voidrice/files/3992876/sudoers.txt)
>
This is exactly the expected behavior. Being in the wheel group allow
you issue sudo command, which requires your user's password to elevate
your status to that of root for that particular command only. Once you
enter your command, your password stays in the memory for a while and if
you issue another sudo command during this time, you won't be prompted
again. Do not expect running commands with root privilages without any
password; these are risky enough even with a password prompt.

**Comment by decantr** [comment]
You can add the following line at the end of your `/etc/sudoers/` file to enable get the functionality you wan, although as @hakova mentioed, you need to be careful with root.

```
%wheel ALL=(ALL) NOPASSWD: ALL
```
