### ISSUE TITLE
Super + r not working in void-linux

### ISSUE THREAD

**Issue by hsigrist** [LukeSmithxyz/voidrice#438]
In a fresh new void-linux install, everything is ok, but i can't get super + r, super + n etc. work. How proceed?

**Comment by hsigrist** [comment]
I try with a fresh new artix install and same. Super + n doesn't open st

**Comment by vladdoster** [comment]
> I try with a fresh new artix install and same. Super + n doesn't open st

I don't think super + n opens terminal? It should be super + enter/return

**Comment by hsigrist** [comment]
My error. But nothing work. I think the problem is my keymap es (spanish layout)

**Comment by vladdoster** [comment]
> My error. But nothing work. I think the problem is my keymap es (spanish layout)

Are you using i3 or dwm?

This might work for i3 -> [link](https://superuser.com/questions/1147320/how-to-change-keyboard-layout-in-i3)

**Comment by MuntashirAkon** [comment]
Every shortcuts are working fine on my void-linux (US keyboard). If you're using LARBS script, there might be some packages missing (ranger might be missing as well since MOD + r isn't working).

**Comment by LukeSmithxyz** [comment]
To be clear, LARBS does not officially support Void Linux at all right now. It will install some of the packages, but there are some dependencies needed to compile some programs that I haven't had the chance to experiment with.

To be clear, I don't think that st and dmenu will compile correctly on Void because there are additional dependencies needed since Void has such a minimal way of calling devel dependencies. I honestly have just not had the chance to try it out to find what they are, but that should be the issue.

**Comment by PlatinumClaridge** [comment]
One of the issues I had installing on Void was that curl isn't included in the base-devel package. Once I installed it manually, everything compiled perfectly fine. I have a fork of LARBS/voidrice in my repos for void specifically and everything works as intended as far as I've been able to test it myself.

**Comment by dm17** [comment]
> To be clear, LARBS does not officially support Void Linux at all right now. It will install some of the packages, but there are some dependencies needed to compile some programs that I haven't had the chance to experiment with.
> 
> To be clear, I don't think that st and dmenu will compile correctly on Void because there are additional dependencies needed since Void has such a minimal way of calling devel dependencies. I honestly have just not had the chance to try it out to find what they are, but that should be the issue.

Ah, judging by the name "voidrice" I was thinking void is supported. Or is this comment outdated? I'm reading through the script a bit but not ready to unleash it on my void system... @

**Comment by LukeSmithxyz** [comment]
It's only called "voidrice," because when I made the repository like
three years ago, I was using Void. I switched back to Arch and now Artix
and I've been committing from them for most of the repository's history.
On 20/06/13 03:29PM, dm17 wrote:
> > To be clear, LARBS does not officially support Void Linux at all right now. It will install some of the packages, but there are some dependencies needed to compile some programs that I haven't had the chance to experiment with.
> >
> > To be clear, I don't think that st and dmenu will compile correctly on Void because there are additional dependencies needed since Void has such a minimal way of calling devel dependencies. I honestly have just not had the chance to try it out to find what they are, but that should be the issue.
>
> Ah, judging by the name "voidrice" I was thinking void is supported. Or is this comment outdated? I'm reading through the script a bit but not ready to unleash it on my void system... @
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/voidrice/issues/438#issuecomment-643686110

--
https://lukesmith.xyz

**Comment by dm17** [comment]
> It's only called "voidrice," because when I made the repository like three years ago, I was using Void. I switched back to Arch and now Artix and I've been committing from them for most of the repository's history.
> […](#)
> On 20/06/13 03:29PM, dm17 wrote: > To be clear, LARBS does not officially support Void Linux at all right now. It will install some of the packages, but there are some dependencies needed to compile some programs that I haven't had the chance to experiment with. > > To be clear, I don't think that st and dmenu will compile correctly on Void because there are additional dependencies needed since Void has such a minimal way of calling devel dependencies. I honestly have just not had the chance to try it out to find what they are, but that should be the issue. Ah, judging by the name "voidrice" I was thinking void is supported. Or is this comment outdated? I'm reading through the script a bit but not ready to unleash it on my void system... @ -- You are receiving this because you modified the open/close state. Reply to this email directly or view it on GitHub: [#438 (comment)](https://github.com/LukeSmithxyz/voidrice/issues/438#issuecomment-643686110)
> -- https://lukesmith.xyz

Thanks. Know of anyone running / testing your rice on Void currently? I just took the plunge and would like to start with well vetted configs. However, I'll just start with your st & dwm for now. Will look into a way to git diff between your dwm repo & upstream dwm - so I can grep through the differences.

**Comment by AlexSyssoyev** [comment]
[PlatinumClaridge](https://github.com/LukeSmithxyz/voidrice/issues/438#issuecomment-594083541) has a great repo maintained specially for void.
