### ISSUE TITLE
Locations for ".scripts"

### ISSUE THREAD

**Issue by HirschBerge** [LukeSmithxyz/voidrice#439]
Hi Luke,
Do you have a location for all the scripts Voidrice/LARBS like you have the "home/luke/.scripts" in your videos? I know they're there somewhere, but where is that located?

**Comment by vladdoster** [comment]
> Hi Luke,
> Do you have a location for all the scripts Voidrice/LARBS like you have the "home/luke/.scripts" in your videos? I know they're there somewhere, but where is that located?

@HirschBerge are you referring to [LARBS](https://github.com/LukeSmithxyz/LARBS)?

**Comment by HirschBerge** [comment]
> > Hi Luke,
> > Do you have a location for all the scripts Voidrice/LARBS like you have the "home/luke/.scripts" in your videos? I know they're there somewhere, but where is that located?
> 
> @HirschBerge are you referring to [LARBS](https://github.com/LukeSmithxyz/LARBS)?

Not specifically it as a whole, but his directory full of scripts, like the one he has for notifying when a torrent is done.

**Comment by vladdoster** [comment]
> > > Hi Luke,
> > > Do you have a location for all the scripts Voidrice/LARBS like you have the "home/luke/.scripts" in your videos? I know they're there somewhere, but where is that located?
> > 
> > 
> > @HirschBerge are you referring to [LARBS](https://github.com/LukeSmithxyz/LARBS)?
> 
> Not specifically it as a whole, but his directory full of scripts, like the one he has for notifying when a torrent is done.

@HirschBerge possibly the [.local/bin/](https://github.com/LukeSmithxyz/voidrice/tree/master/.local/bin)?

**Comment by HirschBerge** [comment]
@vladdoster Much appreciated! Thanks!
