### ISSUE TITLE
ranger fails to copy some files

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#442]
I dunno what is causing this, but ranger constantly fails to copy some files when I copy from my backup HDD to my main HDD, or the other way around, the permissions on the folder are the same as every other folder which copies successfully which are : drwxr-xr-x

here is a screenshot of what ranger displays when it fails to copy: [https://0x0.st/znnu.png](https://0x0.st/znnu.png)

what am I doing wrong? :)

**Comment by LukeSmithxyz** [comment]
This is probably not a problem that's relevant to this repository. It's either a ranger issue or you might have some kind of data corruption.

**Comment by kronikpillow** [comment]
yeah I know it's not a voidrice issue, just asking for help on what can be causing this, LF or vifm copy the same files without any issues
