### ISSUE TITLE
extract script can't handle files with spaces

### ISSUE THREAD

**Issue by Daenarii** [LukeSmithxyz/voidrice#45]
The binding Shift+x on ranger works, but when it comes to an archive with a space, it will throw nothing. This means typing extract file\ with\ spaces.zip also won't work on a terminal.

**Comment by m3tax** [comment]
This is a simple fix. You just have to quote the `$1`s

For example:
`*.tar.gz) tar xvzf ../$1 ;;` -> `*.tar.gz) tar xvzf ../"$1" ;;`

Alternatively, you can use ranger's built-in extract tool with the `1l` command.

**Comment by Daenarii** [comment]
@m3tax Oh great, that worked. I found out another problem which is the `mkdir $NAME && cd $NAME`, in which this is what happens for example: `mkdir file with spaces`, creating a folder for each word. So I also quoted those too. Although what did you mean by `1l`?
I'm closing this issue now, and will create a pull request.

**Comment by m3tax** [comment]
@Daenarii Ranger can already do what this script does. Hovering over a compressed file and pressing `1l` will create a new folder and extract it there with the appropiate tool (it's a bit funky sometimes though)
