### ISSUE TITLE
fzf doesn't locate files

### ISSUE THREAD

**Issue by WovenTide** [LukeSmithxyz/voidrice#452]
Hello,

I've installed fzf and Ranger's config files but when I try to locate files with `ctrl+l`, fzf doesn't load anything while `ctrl+f` work as intended.
I've installed the same files on another computer and both shortcuts work. 

![imgur-2020_01_16-00:04:55](https://user-images.githubusercontent.com/35133174/72479294-ffff8700-37eb-11ea-9c39-9a690da9c457.png)

I have no Idea on where to start to resolve the issue. Which folders should I check ?
Thank you !

**Comment by vladdoster** [comment]
What shell are you using?

**Comment by WovenTide** [comment]
Bash.
Let me know if you need anything else !

**Comment by vladdoster** [comment]
Did you install lqrbs or just thes

**Comment by WovenTide** [comment]
I just installed the scripts and put the conf files in their place.
I can test with zsh in the morning though (It's late where I live) !

My other computer uses bash as well but I have no issue with `ctrl+f` and `ctrl+l` in Ranger. Don't know why.

**Comment by kronikpillow** [comment]
Luke's terminal bindings (well most of them) are in his ST build, and even so, I dont use them, I just source /usr/share/fzf/completions.bash or .zsh and/usr/share/fzf/key-bindings.bash or .zsh and everything works ...

this isn't a voidrice issue, this is you not sourcing FZF with all its options

**Comment by LukeSmithxyz** [comment]
This should have nothing to do with zsh or ranger or fzf.

The locate command only works if you periodically have updated its search database. So if you've never run `sudo updatedb` nothing will show up. You might want to add `updatedb` to a root cronjob to have it update every once in a while automatically.

**Comment by WovenTide** [comment]
It was indeed a `sudo updatedb` problem !
Thank you all for your help !
