### ISSUE TITLE
ncmpcpp/mpd not working

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#453]
When I open ncmpcpp, it will display no music and display the error `ncmpcpp: Connection refused`. After a few reboots, it will sometimes instead show no music for a few seconds then the error: `ncmpcpp: Timeout while connecting`.

**Comment by kronikpillow** [comment]
reboots don't solve a problem in programs or in linux, debugging and meddling with the configuration files does, on the other hand works perfectly fine for me, I had this error when mpd.conf was set to wrong output (eg when it was set to pulseaudio while luke's setup uses alsa only now) ... when was the last time you pulled the repository ?

**Comment by drake-newell** [comment]
@kronikpillow it seems to be working when I'm connected to my home network, but not on my school network. Because of this, I'm going to guess that it might have something to do with the host being set as 127.0.0.1 rather than localhost in the mpd/ncmpcpp configs?

**Comment by kronikpillow** [comment]
127.0.0.1 should be the same as localhost, it's your machine regardless of what network your connected on (but don't hold me for my word as I'm not a expert in networking) ...

whats your /etc/hosts set to?

--

also try deleting database log pid state from ~/.config/mpd/ this also worked for me when it didn't work ... 

is your music in ~/Music/ ?

**Comment by drake-newell** [comment]
Yeah it's in ~/Music. I tried deleting those files, still didn't work.

**Comment by drake-newell** [comment]
Looks like I was able to fix the problem by changing bind_to_address in mpd.conf to $HOME/.config/mpd/.socket and doing the same for mpd_host in the ncmpcpp.

**Comment by drake-newell** [comment]
Update: Turns out changing it to the socket broke MPC somewhat as it could not find the host, so I tried uncommenting the mpd_host line in the ncmpcpp config and setting it to 127.0.0.1 and with both set to 127.0.0.1, it worked.

**Comment by khalidalwalid** [comment]
> Update: Turns out changing it to the socket broke MPC somewhat as it could not find the host, so I tried uncommenting the mpd_host line in the ncmpcpp config and setting it to 127.0.0.1 and with both set to 127.0.0.1, it worked.
Afternoon, may I know where the location of ncmpcpp config is?
![image](https://user-images.githubusercontent.com/33023197/140605120-29cb3104-08d5-45cf-842e-207578099616.png)

**Comment by CopernicusPY** [comment]
I had that too. Try reinstalling both mpd and ncmpcpp 
`sudo apt-get remove mpd ncmpcpp && sudo apt-get install mpd ncmpcpp`
