### ISSUE TITLE
Use Rscript to compile Rmarkdown

### ISSUE THREAD

**Issue by alivefromupstairs** [LukeSmithxyz/voidrice#454]
https://github.com/LukeSmithxyz/voidrice/blob/a6934232f73466cfa3c84d01550631b73d3b47c3/.local/bin/compiler#L29

```fish
 *\.rmd) Rscript -e "require(rmarkdown); rmarkdown::render('$file', quiet=TRUE)"
```

**Comment by tallguyjenks** [comment]
oh this is so much faster :+1:

**Comment by LukeSmithxyz** [comment]
done.

**Comment by alivefromupstairs** [comment]
@LukeSmithxyz `Rscript -e "library(rmarkdown); rmarkdown::render('$file', quiet=TRUE)` does not have any requiring output on success; I overlooked that.
