### ISSUE TITLE
xresources? :)

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#464]
Luke share your .xresources ? :)

I want the colors from this video on my dwm :dagger: 
[A Superior Video Site & a Based Channel Recommendation](https://www.youtube.com/watch?v=6YfRgI0xrfI)

**Comment by LukeSmithxyz** [comment]
That's not Xresources, that's just the pywal output from my wallpaper.
Get it here before I delete it:
https://lukesmith.xyz/files/kronik.jpg

**Comment by kronikpillow** [comment]
thanks man :)

**Comment by kronikpillow** [comment]
hey @LukeSmithxyz how do I make the changes persistent?
