### ISSUE TITLE
zsh no history

### ISSUE THREAD

**Issue by eth-man** [LukeSmithxyz/voidrice#465]
please add zsh history to zsh config, thank you

**Comment by vladdoster** [comment]
You add it? @eth-man

**Comment by vladdoster** [comment]
@eth-man is a brainlet, so I had to step up and be a chad XD

PR #466

**Comment by kronikpillow** [comment]
@eth-man ?? why don't you add it your self? It's very simple

edit your .zshrc and add
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.config/zsh/.zhistory

or something .... geeez

**Comment by vladdoster** [comment]
> @eth-man ?? why don't you add it your self? It's very simple
> 
> edit your .zshrc and add
> HISTSIZE=10000
> SAVEHIST=10000
> HISTFILE=~/.config/zsh/.zhistory
> 
> or something .... geeez

I already added it and opened a PR. Don't offend the brainlet XD

**Comment by Daja177** [comment]
@kronikpillow Sure it's easy to add it by yourself, but at least he reported this error. The absence of those lines was likely not intended by Luke, so it's not necessarily a bad issue. Although it would've been more helpful to create a pull request instead, it did result in the creation of @vladdoster's pull request.

**Comment by eth-man** [comment]
im not even using zsh ,you brilliants :)
