### ISSUE TITLE
mute not working for me on alsa

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#468]
hi everyone, and @LukeSmithxyz ... I have an M-Audio Delta 66 professional audio soundcard that I use, the default .asoundrc that comes with LARBS didn't work for me, so I googled and googled, and found a advanced .asoundrc that works for my soundcard, but the kernel module that my card uses doesn't have a master channel, so I created one with Softvol. the volume increase and decrease keybindings work perfectly, but the mute "mixer sset Master toggle; pkill -RTMIN+10 $STATUSBAR" doesn't work, I have tried various options and I'm unable to figure it out if my softvol is not properly configured or if the command im using is wrong?, can anyone help me figgure out the proper command to get my mute button working? 

output of lspci -knn|grep -iA2 audio
```
lspci -knn|grep -iA2 audio
01:00.1 Audio device [0403]: NVIDIA Corporation GK106 HDMI Audio Controller [10de:0e0b] (rev a1)
        Subsystem: Micro-Star International Co., Ltd. [MSI] GK106 HDMI Audio Controller [1462:2805]
        Kernel modules: snd_hda_intel
03:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168] (rev 06)
--
04:00.0 Multimedia audio controller [0401]: VIA Technologies Inc. ICE1712 [Envy24] PCI Multi-Channel I/O Controller [1412:1712] (rev 02)
        Subsystem: VIA Technologies Inc. M-Audio Delta 66 [1412:d632]
        Kernel driver in use: snd_ice1712
        Kernel modules: snd_ice1712
```

output of cat /proc/asound/modules
```
 $ cat /proc/asound/modules
 0 snd_ice1712
```

output of aplay -L
```aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
sysdefault:CARD=M66
    M Audio Delta 66, ICE1712 multi
    Default Audio Device
front:CARD=M66,DEV=0
    M Audio Delta 66, ICE1712 multi
    Front speakers
surround21:CARD=M66,DEV=0
    M Audio Delta 66, ICE1712 multi
    2.1 Surround output to Front and Subwoofer speakers
surround41:CARD=M66,DEV=0
    M Audio Delta 66, ICE1712 multi
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=M66,DEV=0
    M Audio Delta 66, ICE1712 multi
    5.0 Surround output to Front, Center and Rear speakers
surround71:CARD=M66,DEV=0
    M Audio Delta 66, ICE1712 multi
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=M66,DEV=0
    M Audio Delta 66, ICE1712 multi
    IEC958 (S/PDIF) Digital Audio Output
usbstream:CARD=M66
    M Audio Delta 66
    USB Stream Output
```
and my [.asoundrc](https://github.com/kronikpillow/voidrice/blob/master/.asoundrc)

**Comment by Daja177** [comment]
Does running `amixer sset Master toggle` directly work? This issue might've been caused by a syntax error that #471 will fix, but I didn't use a issue reference keyword since I wasn't entirely sure.

**Comment by kronikpillow** [comment]
no I use dwm, but the command is the same both in dwm and I3, and no amixer sset Master toggle doesn't toggle on/off the master channel :-/

**Comment by kronikpillow** [comment]
I just switched to pulse, so "issue closed"
