### ISSUE TITLE
i3 sound commands are not working

### ISSUE THREAD

**Issue by a310883** [LukeSmithxyz/voidrice#470]
I was having troubles using all the sound commands on i3, I changed the ";" with "&&"  in the i3 configuration file and that solve the issue (by example: bindsym $mod+Shift+m		exec --no-startup-id amixer sset Master toggle **&&** pkill -RTMIN+10 i3blocks). It is necesary make that change or I'm missing a dependency or additional configuration?

**Comment by Daja177** [comment]
I guess I forgot I had to add `exec --no-starup-id` to the `pkill` when I made the pull request #460, my bad. I'll create a pull request to fix this. Thanks for reporting this issue!

**Comment by vladdoster** [comment]
@Daja177 wouldnt this also fix @kronikpillow issue in #468?

**Comment by Daja177** [comment]
@vladdoster Now that you mention it, it might be related. I'm not entirely sure though since he didn't seem to have attempted the command outside of `i3`'s config, but I'll still reference it in the pull request.

**Comment by kronikpillow** [comment]
nope @vladdoster I tried it, the toggle function is not working for me, while volume up and down is ... weird ...
