### ISSUE TITLE
sxhkdrc not updating

### ISSUE THREAD

**Issue by skyve2222** [LukeSmithxyz/voidrice#473]
I just updated larbs and some of the bind won't work:
super + c and super + shift + esc
I also can't update ~/.config/sxhkd/sxhkdrc.
I try editing a bind or try adding new binds but they don't take effect. please help

**Comment by LukeSmithxyz** [comment]
I'm phasing out sxhkd. The config is still there, but it is not started
by default anymore. Edit the i3 config to add the binding.

**Comment by vladdoster** [comment]
> I'm phasing out sxhkd. The config is still there, but it is not started by default anymore. Edit the i3 config to add the binding.
> […](#)
> On 20/02/01 04:16PM, skyve2222 wrote: I just updated larbs and some of the bind won't work: super + c and super + shift + esc I also can't update ~/.config/sxhkd/sxhkdrc. I try editing a bind or try adding new binds but they don't take effect. please help -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #473

@LukeSmithxyz Whats the reasoning for phasing out sxhkd? Too much redundancy or are you moving back to i3?

**Comment by LukeSmithxyz** [comment]
Yeah, it was always redundant. It offers some advantages in bindings,
but not enough I don't think. No I'm not using i3, but I've moved all
the bindings back to i3 and dwm themselves. The sxhkd config file is
just there as legacy now.

**Comment by vladdoster** [comment]
I guess it only really made sense if you used bspwm full time. Thanks for the insight.

**Comment by kronikpillow** [comment]
you missed quite a few keybindings from shxkd on dwm :) or maybe it was intentional I dunno :D
