### ISSUE TITLE
Markdown exception for automatically deleting all trailing whitespace on save

### ISSUE THREAD

**Issue by ceylanb** [LukeSmithxyz/voidrice#478]
Markdown exception is need for automatically deleting all trailing whitespace on save. When I would like to break the line by white spaces, It fails because of the "deleting all trailing whitespace on save" rule in vimrc. Therefore, the exceotion is needed.

**Comment by LukeSmithxyz** [comment]
What exactly do you mean? When do you need trailing whitespace for markdown?

**Comment by ceylanb** [comment]
Trailing white spaces should not be deleted in markdown files. As we know that the two spaces at the end of a line  break the line. When the mentioned rule in the current version of vimrc is active, it removes the white spaces. In that case, all the "line breaks created with two white spaces" are deleted and the text is merged at one line. This is not desired situation due to the new lines that I need are removed. To remediate this situation, writing an "if condition" that exclude the markdown file type before the mentioned rule would be sufficient.

**Comment by LukeSmithxyz** [comment]
Well users can remove the relevant line if they like.
