### ISSUE TITLE
Compiler script fails to compile .mom documents

### ISSUE THREAD

**Issue by gmoneymagna** [LukeSmithxyz/voidrice#479]
I have used the compiler script found in .local and toggle autocompiler command in the init.nvim as they are written. The autocompiler works with .ms documents. However I have started using .mom documents due to the ease of formatting and the compiler script does not work. It outputs a blank PDF. When I enter the exact same commands from the compiler script in the terminal (but using intput and output file names) it works. Therefore I believe there must be some minor issue in the compiler script, or I'm missing something. 

Any help is appreciated. Thanks!

**Comment by vladdoster** [comment]
Well does the mom commands and following pipes seem right? Why dont you try diagnosing the issue on your own and see what could be the problem?

Here is the line of compiler that work on mom files -> https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/compiler#L27

**Comment by gmoneymagna** [comment]
I am not denying it is a niche issue. I am attempting to diagnose.

I am using the commands in Luke's compiler script in the terminal with success. Therefore I believe there is a problem with the "refer -PS -e "$file" " part of the script. Not sure why this would only be a problem with .mom docs since it is used to compile the other types of groff docs.

**Comment by vladdoster** [comment]
Have you you looked at commit history to see where things might have changed?

**Comment by vladdoster** [comment]
Might be an issue with zsh but I'm inclined to think that it isn't since parts of the script are working for other file types.

**Comment by vladdoster** [comment]
I wonder if its an issue with anything but the 1st option. I'll try compiling a c program and see if it errors. Then it would see it only gets thru option .ms.

**Comment by gmoneymagna** [comment]
Nothing relevant in the commit history. I am unsure what "refer" is in the script since the refer command is built into groff and I have never had to invoke it in that way before. I have tried to edit the \.mom option with `groff $file$ -R -mom -kept -T pdf > "$base".pdf` which is the exact same command that works in the terminal except with using real file names instead of variables. Still no luck.

**Comment by vladdoster** [comment]
From the groff docs -> https://www.schaffter.ca/mom/pdf/mom-pdf.pdf

```
Groff provides more than one way to generate PDF documents from files formatted with the mom
macros . One is to call gr off directly, either with groff [-Tps] -mom -m pdfmark doc.mom | ps2pdf - doc.pdf which pipes output from the gr ops PostScript driver through ps2pdf, or
groff -Tpdf -mom doc.mom > doc.pdf
which uses the native PDF driver, gropdf. Alternatively, one may call the wrapper
pdfroff -mom -mpdfmark --no-toc doc.mom > doc.pdf
A fourth, preferred method is to use pdfmom, which is strongly recommended since it implements the full range of PDF features available in mom. pdfmom doc.mom > doc.pdf
One reason to pref er using the native PDF driver (via pdfmom or -Tpdf) is that papersizes set within mom source files (see paper and page setup macros) do not require a corresponding
-P-p<paper size> flag on the command line .
There are other minor differences between the methods , discussed here.
```
you might try `pdfmom > pdfname.pdf`

**Comment by gmoneymagna** [comment]
`pdfmom -R > pdfname.pdf` works great in the terminal and I will continue to use this simplified command going forward. When I replace the command in the compiler script, giving me `*\.mom) refer -PS -e "$file" | pdfmom -R > "$base".pdf ;;` I still get a blank pdf output. I have moved the .mom option to the first option after 'case "$file" in' and still blank pdf output. For now thank you for the pdfmom knowledge and I will use that to try to fix whatever is happening in the compiler script. I will update as I progress.

**Comment by cbeauhilton** [comment]
I converted mine to pdfmom a while ago, it's worth going all in to the schaffter style of doing things. 

When I can sit down to my computer I'll see if there's anything fancy in my dotfiles that is making this work (my compiler script is a fork of Luke's). Haven't played w groff for a while bc Rmd is my new soulmate.

**Comment by Daja177** [comment]
Compiling mom documents with Luke's script work fine for me without making any changes, so I don't really know what's causing these issues for you. Is your `/bin/sh` symlinked to something other than `dash`?

**Comment by gmoneymagna** [comment]
My personal scripts are all in `~/bin/` there is no symlink. I'm not sure what `dash` is. The first line of the compiler script is `#!/usr/bin/env sh`. I just confirmed that the compiler script works for `.ms` groff files. Very odd.

**Comment by Daja177** [comment]
@gmoneymagna I'm talking about the shell `sh` with the location `/bin/sh` (not `~/bin/sh`), the shell running the script. The line `#!/usr/bin/env sh` is what makes sure the script is run using `sh`. On modern systems `sh` is simply a symbolic link to another shell such as `dash` or `bash`, meaning that the script will be run by the shell it's symlinked to.

`dash` is a shell kinda like `bash` that aims to be strictly POSIX-compliant and as small as possible, and it runs shell scripts much faster than `bash`. Most distros have it linked to `dash` by default, but Arch Linux has it linked to `bash` (although many including Luke re-link it to `dash` instead).

It's definitely a rather peculiar issue; since none of us here seem to be able to give an answer as to why it's not working, I'm just trying to see if I can eliminate any possible causes of disturbance. However I did try to rerun the script after re-linking `sh` to `bash` which worked without any issues, so I doubt this is what's causing the problem.

**Comment by gmoneymagna** [comment]
At this point it seems that I'm likely missing some dependency that the script is trying to use, and when I type in the `pdfmom` commands in my own terminal and I am avoiding this dependency. I am using Voidlinux and it is up to date. I will comment when I know more.

**Comment by gmoneymagna** [comment]
Sorry if this is a dumb question. In this compiler script what does `refer` command mean? I have been searching and can't find this command in bash script. I know refer is part of groff and used for references and bibliographies, but I don't see why this would be added before the `groff` command and not in the form of `-R` like the documentation says.

**Comment by vladdoster** [comment]
> Sorry if this is a dumb question. In this compiler script what does `refer` command mean? I have been searching and can't find this command in bash script. I know refer is part of groff and used for references and bibliographies, but I don't see why this would be added before the `groff` command and not in the form of `-R` like the documentation says.

It probably is calling lukes bibliography file to automatically build his bibliography. That's my best guess

**Comment by LukeSmithxyz** [comment]
So if you run `refer ... | groff ...` on another non-mom groff type, does it work? Interesting problem. If running `refer` caused breakage, I would expect it to be for all types.

I have refer run separately to give it the several sensible options which I don't believe are run if you just run groff with `-R`.

**Comment by gmoneymagna** [comment]
I found a solution. Apparently going from `.mom` to `.pdf` files with groff or pdfmom produces an error called `troff: litassign.mom:5: can't transparently output node at top level` and `troff: litassign.mom:126: warning: numeric expression expected (got newline)` which I have read can be safely ignored and are a known bug. However, these seemed to trip up the script.

So with `pdfmom -R "$file" > "$base".pdf 2>/dev/null` in my own simplified, `.mom` only version of Luke's compiler script it works. I will ensure this works in the original compiler script also.
