### ISSUE TITLE
i3 - Webcam toggle not working

### ISSUE THREAD

**Issue by Pwhitcomb** [LukeSmithxyz/voidrice#483]
Super+Shift+c is not showing the webcam.
camtoggle is not found as well as when added manually, the camera is dead center and will not move to bottom right corner when other windows are open

**Comment by charlie39** [comment]
I got confused as well, the camtoggle script is missing. had to add it manually. 
    mpv --no-osc --no-input-default-bindings --input-conf=/dev/null --title='title='mpvfloat' /dev/video0 

About the bindings, have you read the bindings ? first you have to bring focus to the window with mod+space and then mod+shift+n to position it on right bottom corner /mod+shift+b for the left bottom.

**Comment by Pwhitcomb** [comment]
I think you are right by the moving of the window. In my memory it was automatic. But the super+shift+c when the camera is open doesn't close it.

**Comment by charlie39** [comment]
You can add the part from dmenurecord if you want that feature.
This is how modified it in the camtoggle script:

```
 if [ -f /tmp/ModShiftCPid ] ; then
  	recpid="$(cat /tmp/ModShiftCPid)"
	 kill -15 "$recpid"
	 rm -f /tmp/ModShiftCPid
	 sleep 3
	 #kill -9 "$recpid"
	 exit
else
	mpv --no-osc --no-input-default-bindings --input-conf=/dev/null --title='mpvfloat' /dev/video0 &
	echo $! > /tmp/ModShiftCPid
fi
```
