### ISSUE TITLE
vim shows beam cursor on open

### ISSUE THREAD

**Issue by Lucianod28** [LukeSmithxyz/voidrice#487]
I just started  using this .zshrc and I noticed now when I open vim, the cursor shows in beam rather than block mode initially even though I am in normal mode. Commenting these lines from .zshrc:
```
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
```
fixes this behavior but prevents the beam mode when I open a new shell. Is this the expected behavior? I want to be in insert mode with a beam cursor when I open a shell but be in normal mode with a block cursor when I open vim.

I'm running macOS and using vim 8.1.

**Comment by LukeSmithxyz** [comment]
Well I use neovim that has by-default beam support for both modes. You might want to look up how to add this to vanilla vim; I'm not sure how off the top of my head, but it is possible.

**Comment by Lucianod28** [comment]
Thanks I ended up fixing it by adding the following to my .vimrc:
```
" Use block cursor for normal mode, bar for insert                                                  
8 let &t_SI = "\e[6 q" " bar                                                                          
let &t_EI = "\e[2 q" " block                                                                        
set ttimeoutlen=0                                                                                   
                                                                                               
" Reset the cursor to block on start                                                                
augroup myCmds                                                                                      
au!                                                                                                 
autocmd VimEnter * silent !echo -ne "\e[2 q"                                                        
augroup END
```
(https://stackoverflow.com/questions/6488683/how-do-i-change-the-vim-cursor-in-insert-normal-mode/42118416#42118416)
