### ISSUE TITLE
Small change in .local/bin/statusbar/weather

### ISSUE THREAD

**Issue by lamdacore** [LukeSmithxyz/voidrice#490]
it is a tiny change so didn't want to do a full pull request. 

I noticed, the positive values from the output of wttr were being ignored. My understanding is the output sometimes contains '+' symbol in front of the positive temperatures. See example: [http://ix.io/2cIg](http://ix.io/2cIg)

The following change should fix it and not be disruptive. Note the added '[-+]'
```
sed '13q;d' "$HOME/.local/share/weatherreport" | grep -o "m\\(-\\)*[0-9]\\+" 
sed '13q;d' "$HOME/.local/share/weatherreport" | grep -o "m\\([-+]\\)*[0-9]\\+"
```

**Comment by LukeSmithxyz** [comment]
Done.
