### ISSUE TITLE
The Ranger closes itself

### ISSUE THREAD

**Issue by d351d3r** [LukeSmithxyz/voidrice#491]
Hello, I use LARBS with i3 and when I for example move in the Ranger to ~/.config/.local/bin and flipping down, then the Rangler itself is closed, because of what it can be and how to fix it?

P.S. I just started using your config, and where is the autoloading of all programs stored? It's scattered and I can't find them all

**Comment by vladdoster** [comment]
What do you mean autoloading of all the programs? It installs it in a loop in larbs.sh. main_installation loop

**Comment by vladdoster** [comment]
Or are you talking about each time you login?

**Comment by d351d3r** [comment]
> Or are you talking about each time you login?
Which are launched on each boot. For example, I have a tiring, I want to run picom, but I am told that I have another composite Manager running, I do not know which one and how to disable it.

**Comment by vladdoster** [comment]
IIRC he starts them here -> https://github.com/LukeSmithxyz/voidrice/blob/master/.xprofile

The compositor is xcompmgr.

**Comment by d351d3r** [comment]
> IIRC he starts them here -> https://github.com/LukeSmithxyz/voidrice/blob/master/.xprofile

Thank you, Vim closes and crashes when opening the ~/file.config/i3blocks/config

**Comment by vladdoster** [comment]
Do you mean vim or nvim?

**Comment by d351d3r** [comment]
> Do you mean vim or nvim?

Nvim, vim not installed

**Comment by vladdoster** [comment]
Not too sure what to tell you. Maybe check journalctl or see if nvim has a log in /var/log/

**Comment by d351d3r** [comment]
I checked that the problem was in st, in tilix everything opened normally

**Comment by d351d3r** [comment]
I installed libxft-bgra and the problem was solved, I just did not think that there would be emojis in that folder that libxft had problems with.
