### ISSUE TITLE
Gitignore

### ISSUE THREAD

**Issue by AlexanderDavid** [LukeSmithxyz/voidrice#493]
I am trying to roll my own "custom" LARBS based off this repo but I keep adding needless files to the repo (like from Brave). Do you have a custom .gitignore file and if so could you add it to this repo?

Thanks

**Comment by kronikpillow** [comment]
lol, you make your own .gitignore for your own repo

**Comment by Daja177** [comment]
@AlexanderDavid He's likely not adding a `.gitignore` file to avoid cluttering the home directory with even more unnecessary dot-files. It is pretty easy to create your own however, by simply adding the files's names to the file and use wildcards when necessary. For more information, check out https://help.github.com/en/github/using-git/ignoring-files
