### ISSUE TITLE
st crashed when trying to open i3blocks config using vim/nano (installing fonts not fixing issue)

### ISSUE THREAD

**Issue by Abh15h3k** [LukeSmithxyz/voidrice#496]
just setup i3 using larbs.sh
I was just going through the config files and when i tried to vim/nano the i3blocks config file urxvt just crashes. i am able to open it using xterm and other terminal emulators.

then i copied the config file to my home folder and i was able to open it with vim/nano.
then i tried to edit a copy of the config in the same directory and crashed
I tried to edit another file in that directory and i was able to.

here's the link to a imgur video showing the issue. idk why but the quality is lower on imgur than on my pc.

https://i.imgur.com/qqPxfmR.mp4

**Comment by vladdoster** [comment]
Are you sure that is urxvt? Looks like ST?

**Comment by vladdoster** [comment]
I can almost guarantee it is this issue.

https://github.com/LukeSmithxyz/voidrice/issues/284

**Comment by vladdoster** [comment]
It's crashing because i3blocks config has emojis which it cant render. Always look at closed issues before opening a new issue :).

**Comment by Abh15h3k** [comment]
Oh. my bad.
this is i was watching his YT video on urxvt and then i found my self running larbs. just assumed it was urxvt.

Thanks Alot

**Comment by Abh15h3k** [comment]
Ok. so i tried to install all the fonts. ttf-symbola keeps failing to install with yay or git clone and makepkg -si.
ttf-symbola-free did not fix the issue.

then i installed ttf-symbola by downloading the symbola.zip using a curl command from the aur site. installed successfully. still the issue persists.

also i logged out and in after installing/uninstalling the fonts

**Comment by LukeSmithxyz** [comment]
Run `yay -S libxft-bgra`, that's the actual fix. Looks like the programs script isn't being parsed correctly leaving off the required AUR programs.

I'll have it patched in a bit.

**Comment by Abh15h3k** [comment]
umm, one more thing. ducksearch ( mod + F12 ) is not working. i'm assuming its one of your scripts that should be in .local/bin. its not there

**Comment by Abh15h3k** [comment]
well i'm closing this issue now. `yay -S libxft-bgra` fixed it.

PS: Great project

**Comment by LukeSmithxyz** [comment]
Okay, great. If that AUR program failed to install, these might've as well, so you might want to install them too with yay:

```
nerd-fonts-inconsolata
ranger-git
gtk-theme-arc-gruvbox-git
brave-bin
sc-im
python-ueberzug
task-spooler
simple-mtpfs
```
Most of them aren't 100% necessary though. As for F12, I think I had removed that binding, but I guess it might be still in the documentation (which is a little out of date, by the way).

**Comment by LukeSmithxyz** [comment]
Okay, the underlying problem should be solved now. LARBS should always ship with `libxft-bgra` until the patch is in the default `libxft`.

**Comment by Abh15h3k** [comment]
the F12 binding is not just in the doc. its there in i3/config

**Comment by LukeSmithxyz** [comment]
By the way, there is another little error I took care of, but you might have it since you just downloaded.

Where `$USER` is your username, run the following:

```
chown -R $USER:wheel /home/$USER/.local
```

Then just rerun the LARBS script (will just take a second since all the programs are already installed).

There were some permission problems that may or may not have affected recent installs.

**Comment by Abh15h3k** [comment]
Ok. I did that and i remembered something. the binding mod+Shift+Escape was not working. (to exit i3 in my case ).
so i just added the binding in i3/config. but might want to update larbs.
