### ISSUE TITLE
Statusbar wifi connection strength above 100%

### ISSUE THREAD

**Issue by Fogapod** [LukeSmithxyz/voidrice#497]
```sh
~ cat /proc/net/wireless                                                                                                               [0]
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp2s0f0u1u3: 0000  100.   91.    0.       0      0      0      0      0        0
```
Looks like signal level is at 100%. Status bar shows 142%.
Why is quality value multiplied by 10/7 in script?
https://github.com/LukeSmithxyz/voidrice/blob/a2e0d2441b56886049892481178a119948fb7866/.local/bin/statusbar/internet#L15

**Comment by vladdoster** [comment]
I'm pretty sure signal strength isnt out of 100. Just Google max signal strength Linux and you'll see everyone divides by 70.
