### ISSUE TITLE
fzf does not work out-of-the-box with LARBS/voidrice

### ISSUE THREAD

**Issue by majamin** [LukeSmithxyz/voidrice#498]
## System
* Fresh install 5.5.8-arch1-1
* Fresh install of LARBS (i3)

## What's happening?
1. `cd ** <TAB>` results in expansion to `cd folder1 folder2 folder3`
2. ctrl-R results in no output

## Expected
Out-of-the-box fzf LARBS functionality.

i.e.
1. `cd ** <TAB>` results in fzf menu with options folder1, folder2, and folder3.
2. ctrl-R should result in command history fzf menu

## Attempts to fix
Removed /community package `fzf`, reinstalled with `pacman`. Repeated with `yay`. Observations: install does not prompt for auto-completion or key binding options (is this the problem?), as the git install (see below) produces.

## Temp workaround
Removal of fzf `sudo pacman -R fzf` and manual install via [git install instructions](https://github.com/junegunn/fzf#using-git), answering "yes" to all options during install.

## Notes
Is this an upstream pacman/yay issue? Or, is this a LARBS issue or a voidrice issue? Sorry for the newb questions. I've done some extensive man/SO/ArchWiki/github searching already.

**Comment by LukeSmithxyz** [comment]
I'm a little confused by this.

Do you actually mean that fzf actually doesn't work or are you suggesting that I integrate it as an autocomplete mechanism into the shell? I don't see why you would expect that that should be enforced as the default.

**Comment by majamin** [comment]
> I'm a little confused by this.
> 
> Do you actually mean that fzf actually doesn't work or are you suggesting that I integrate it as an autocomplete mechanism into the shell? I don't see why you would expect that that should be enforced as the default.

I could be completely off my rocker. I thought `fzf` being installed in LARBS means it was meant to be integrated into the shell. Was it just meant as a vim functionality?

**Comment by majamin** [comment]
> I'm a little confused by this.
> 
> Do you actually mean that fzf actually doesn't work

Not as expected (see OP).

> or are you suggesting that I integrate it as an autocomplete mechanism into the shell? I don't see why you would expect that that should be enforced as the default.

Good point, but to get the full functionality of fzf (i.e. cd ** menu), it seems you have to remove the fzf package and use the git install. If it was never meant to do this I'll close this issue, no worries.
