### ISSUE TITLE
Latex autocompiling fails if run through neovim

### ISSUE THREAD

**Issue by mimshipio** [LukeSmithxyz/voidrice#501]
```
" Compile document, be it groff/LaTeX/markdown/etc.
	map <leader>c :w! \| !compiler <c-r>%<CR>
```
This line of the vimrc seems to only work if the files that biber uses for bilbiography management arent there when it's executed. If I remove all of the files that latex makes during the compilation process it works but if i run the script again in neovim it produces an error.

**Comment by astier** [comment]
@mimshipio There is an easy solution to this. You just need to fix the error.

**Comment by mimshipio** [comment]
looks like I just had some incorrectly formatted bibliography entries
