### ISSUE TITLE
Link from video broken

### ISSUE THREAD

**Issue by sucrecacao** [LukeSmithxyz/voidrice#503]
Hey Luke !
This video point to what seems an awesome dotfile: https://www.youtube.com/watch?v=eaBf_yFHps8

But
https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.Xdefaults
Doesn't bring anywhere :'(

**Comment by anntnzrb** [comment]
[this](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/Xresources) *might* be what you're looking for, located @ `~/.config/`

**Comment by sucrecacao** [comment]
Thank you but no, this is only the colors checkout the video if yo uwant

**Comment by anntnzrb** [comment]
> Thank you but no, this is only the colors checkout the video if yo uwant

went back in time *(22 Jan 2018)*, what about [this](https://github.com/LukeSmithxyz/voidrice/tree/50adee4e79febf6f74594604e9f7083461b04227)?
there's the `.Xdefaults` file, maybe it contains what you're looking for

**Comment by sucrecacao** [comment]
that ! thx mate
