### ISSUE TITLE
Weird spacing character

### ISSUE THREAD

**Issue by danilovicente** [LukeSmithxyz/voidrice#507]
Hey guys, I getting this weird spacing character. I deleted everything and created again but still looking like this. Anyone can give me a help? 
![pic-selected-200324-0352-05](https://user-images.githubusercontent.com/668485/77401570-894eaf00-6d83-11ea-80a0-ee01ea030099.png)
![pic-full-200324-0358-35](https://user-images.githubusercontent.com/668485/77401690-c155f200-6d83-11ea-892e-96a7b5ab280e.png)

**Comment by kronikpillow** [comment]
how about reading previous issues before opening a double issue?

**Comment by LukeSmithxyz** [comment]
Duplicate number 329: https://github.com/LukeSmithxyz/LARBS/issues/186

**Comment by danilovicente** [comment]
> how about reading previous issues and checking for solutions there before opening a double issue or triple or quadruple issue that was already answered like it is expected on github or are we gonna have another 50 topics cus ppl are lazy to read like we did with the ST crashing when hitting on emoji? downgrade ttf-inconsolata to previous version or change font settings in fonts.conf till the package is fixed

Thanks for your kind reply
