### ISSUE TITLE
lmc + pulseaudio

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#508]
I have tried your latest lmc script, i installed pulseaudio pulseaudio-alsa and pulsemixer, sometimes the script works, and sometimes the volume % changes on the bar but doesn't update the volume at all (eg it behaves like pulse isn't working, while it is working) .... Dunno what else to add or how to explain it

also sometimes the script basically froze my computer totally when I was increasing/decreasing volume, especially right after boot

**Comment by dschense** [comment]
I had the same problem on my pi4 installation. I had to reinstall pulseaudio, check that the user is in the audio group, uninstall alsamixer and change the i3 config from

`bindsym $mod+Shift+a		exec $term -e alsamixer`

to 

`bindsym $mod+Shift+a		exec $term -e pulsemixer`

after these steps audio is working again.

**Comment by kronikpillow** [comment]
I did change the keybindings, but I can't uninstall alsamixer as my card needs alsamixer to unmute it's channels, as I have a M-Audio Delta 66 and analog channels

**Comment by kronikpillow** [comment]
it seems that if you use pulseaudio & pulseaudio-alsa package that you don't even need pulsemixer and to enable the pulse option in lmc because pulseaudio-alsa basically sets up a virtual device that is used as a alsa device, what im saying here is that with pulseaudio-alsa i can use the alsa commands to change volume etc .... while with using pulsemixer lag is present on the entire machine while im changing volume
