### ISSUE TITLE
i3lock turns off screen for 20 seconds only on the first time

### ISSUE THREAD

**Issue by Daenarii** [LukeSmithxyz/voidrice#51]
https://github.com/LukeSmithxyz/voidrice/blob/9588ec46fc0d89a36391b3c1eec97c0716dd7c21/.config/i3/lock.sh#L19-L20
The script only executes the lines above **once**.
Here's what I mean:
1. Lock the screen
2. Wait for 20 seconds
3. Screen turns off
4. Wake up the computer (i.e. moving the mouse, pressing a key, or etc)
5. Screen turns on
6. Have to wait 5 minutes (which is the default "screen timeout") before the screen turns off again

I expected it to actually run _while_ i3lock is running until unlocked, but I'm a brainlet and doesn't know how to implement it.

**Comment by LukeSmithxyz** [comment]
I've pushed an update that gives the functionality you want. I suppose that's a more general desire. I requires `xssstate` to be installed as well.

**Comment by jrwrigh** [comment]
For those searching, here's the commit with the fix:
https://github.com/LukeSmithxyz/voidrice/blob/6e1134afab1279cdcf374163e0418001e8a232e7/.config/i3/lock.sh#L19-L26
