### ISSUE TITLE
mpv config: use mpvSockets script to remove mpv wrappers/aliases

### ISSUE THREAD

**Issue by wis** [LukeSmithxyz/voidrice#517]
https://lukesmith.xyz/hacking.html#mpvpause
> Anyway, this is a good working solution, although I'd like to have one that doesn't require aliasing in every program that you can run mpv. I'm going to keep this issue "open" in case someone sends an even more elegant solution without aliasing, but if that doesn't come, I might just push an update like this to the voidrice repository soon.

use mpvSockets https://github.com/wis/mpvSockets/

**Comment by LukeSmithxyz** [comment]
Open a working PR and maybe I'll change it.
