### ISSUE TITLE
Calcurse now has XDG base directory support

### ISSUE THREAD

**Issue by DominikRusso** [LukeSmithxyz/voidrice#519]
as of v4.6 config files are stored in `~/.config/calcurse/` and data files in `~/.local/share/calcurse/`. no more need for `calcurse -D ~/.config/calcurse` (storing your data files in the config dir? oh god luke what are you doing)

**Comment by LukeSmithxyz** [comment]
Good to hear. I've removed the aliases from the dotfiles.
