### ISSUE TITLE
calcurse not opened in clock script

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#520]
Instead of opening calcurse, middle click on the clock module for dwmblocks just opens a blank instance of st.

**Comment by kronikpillow** [comment]
interesting, I didn't notice that Luke made his scripts clickable in dwmblocks, I was really annoyed that I couldn't click them, but for me none of the modules work, they either open a blank instance of st, or they completely shut down my dwm

(although the music script has an "italic font issue" - needs fixing

**Comment by LukeSmithxyz** [comment]
I didn't make my dwmblocks clickable. I think this came up in another issue, but I have no idea why st gets opened! I suppose it was a feature of some patch I added.

**Comment by LukeSmithxyz** [comment]
Actually, it's just the default, set by this line:

```
	{ ClkStatusText,        0,              Button2,        spawn,          {.v = termcmd } },
```

Guess I've just never actually clicked on the status bar lol. Now if I could easily specify which module was clicked I could integrate something like in i3blocks where you can click on a module for interaction, but that would require some interface with `dwmblocks`.
