### ISSUE TITLE
Query: DWM bar module update

### ISSUE THREAD

**Issue by salman-abedin** [LukeSmithxyz/voidrice#522]
Hey luke,
I was wondering how you've managed to update different modules of your dwm status bar by different intervals as I thought in order to update a single module, you have to update the statusbar altogether.
Thanks in advance.
Big fan btw. :)

**Comment by PearsAreGross** [comment]
https://github.com/torrinfail/dwmblocks
Check DWM website next time :)

**Comment by LukeSmithxyz** [comment]
Here is my build: https://github.com/LukeSmithxyz/dwmblocks
