### ISSUE TITLE
dmenurecord question

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#525]
so I'm confused about the dmenurecord script and how it works, pressing mod+print launches dmenu with a selection menu of what I want to record, it gives option to record screencast video, audio webcam and webcam high def, while pressing the mod+shift+print runs dmenu dmenurecord kill, but doesn't save the video that I just recorded, eg I made a screencast for a video, ran dmenurecord, then did dmenurecord kill, and there is no video in my home directory, I have tried running dmenurecord again, recorded a video, then ran dmenurecord again it offered me an option to kill the current video, I killed it, and then again no video in my home directory

**Comment by LukeSmithxyz** [comment]
Run the dmenurecord command in a terminal. What error is there?

**Comment by kronikpillow** [comment]
```
❯ dmenurecord
ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.3.0 (Arch Linux 9.3.0-1)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

~ master* ⇣⇡
❯ [x11grab @ 0x56094b6452c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0':
  Duration: N/A, start: 1585572200.946059, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
[alsa @ 0x56094b64fdc0] cannot open audio device default (No such file or directory)
default: Input/output error
```

I find this very strange to be honest, my audio card is setup properly, you can check my .asoundrc at [.asoundrc](https://github.com/kronikpillow/voidrice/blob/master/.asoundrc)

**Comment by LukeSmithxyz** [comment]
You using pulse? That would probably be the issue as the commands are
ALSA default, although I think they should work on most pulse systems
unless you have something fancy for your input...

I might want to have the script automatically detect which audio system
is in use and choose the right one.

**Comment by kronikpillow** [comment]
no mate im using ALSA, i even linked my .asoundrc which is different from yours as my card doesn't have a master channel by default, so i use softvol and 5.1/4.0 to stereo downmixing

**Comment by kronikpillow** [comment]
I am frustrated with alsa so i decided to switch to pulseaudio with pulseaudio-alsa is i need pulseaudio-alsa & alsamixer to unmute my analog channels ...  and now the screencast option works .... maybe larbs should just ship with pulseaudio to simply avoid issues for users, and users who just don't want to use it can easily switch, or maybe a prompt during the installation to allow a user to chose 1 or the other
