### ISSUE TITLE
Where is the dwmbar script?

### ISSUE THREAD

**Issue by salman-abedin** [LukeSmithxyz/voidrice#527]
I saw your refbar script sending a TRAP signal to the dwmbar script and wanted to take a look at it in order to see how you handle the signal.
Thanks in advance.

**Comment by LukeSmithxyz** [comment]
It doesn't exist anymore. I use
https://github.com/lukesmithxyz/dwmblocks instead.

**Comment by salman-abedin** [comment]
I does exist, I just had to look for it harder.
I found out what I was looking for btw.
I couldn't update my script with the trap signal and looking at yours, I realized what I was doing wrong.
I wasn't using "wait"
You are a genius man!
Now I would love to update each module individually with different interval like your dwmblocks minus your dwmblocks. lol
