### ISSUE TITLE
ditch sudo for doas

### ISSUE THREAD

**Issue by bQvg5S66szS** [LukeSmithxyz/voidrice#528]
title :)
**resources:**
[link i](https://youtu.be/Q-WTB6siyp0)
[link ii](https://youtu.be/A5buxcYXp7k)

**Comment by narukeh** [comment]
do this in doas and im in (i tried a while ago, i could only do comands that took no flags/options such as mount, but not pacman -Syyu --noconfirm)
%wheel ALL=(ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/systemctl suspend,/usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/pacman -Syu,/usr/bin/pacman -Syyu,/usr/bin/packer -Syu,/usr/bin/packer -Syyu,/usr/bin/systemctl restart NetworkManager,/usr/bin/rc-service NetworkManager restart,/usr/bin/pacman -Syyu --noconfirm,/usr/bin/loadkeys,/usr/bin/yay,/usr/bin/pacman -Syyuw --noconfirm #LARBS

**Comment by LukeSmithxyz** [comment]
The "bloat" of sudo is used in many locations my LARBS.

Basically everyone expects sudo to be installed on the system, so I'm not going to in induct everyone into an abnormal way of running su commands.
