### ISSUE TITLE
Weird emoji size

### ISSUE THREAD

**Issue by abspython** [LukeSmithxyz/voidrice#530]
Whenever I paste the emoji in st, it is of a smaller size and I don't able to making it bigger by increasing font size.
Image : https://imgur.com/a/7cd3bIA

**Comment by narukeh** [comment]
this is on purpose. to change the font of st, modify its config.h then recompile, but this will cut the emojis (usually) on the right. (thats why its on purpose)

**Comment by abspython** [comment]
Anyway what was the purpose of that?

**Comment by LukeSmithxyz** [comment]
Since your font difference is very start, yeah, you might want to increase the emoji font, but for most fonts where the emojis are abnormally large this setting works better.
