### ISSUE TITLE
Weather script wont show negative numbers

### ISSUE THREAD

**Issue by narukeh** [LukeSmithxyz/voidrice#531]
To reproduce my result, here is my weatherreport [with color](https://pastebin.com/3aQQbsEP) and here [without color](https://pastebin.com/iTNhZ7iY)

This is what it outputs: ☔ 0% ❄ 0° 🌞 °
The ❄ (most lower temp) is -9° it gives me 0
The 🌞 (most high temp) is 0° it gives me nothing

(my guess is line 7 the grep function)

**Comment by narukeh** [comment]
By removing " - " in the 7th in the grep function,  it prints it correctly, but that "-" was added on commit 217297d91f5e748b54f46428bda51a41d1a4aa22 so i guess there was a reason to.

**Comment by LukeSmithxyz** [comment]
And that doesn't break anything else? It's possible I might've accidentally reverted that line in this commit. I remember this being an issue earlier and someone solving it. I might just remove the +.

**Comment by narukeh** [comment]
yes, everything seems ok without the +

**Comment by jonmed** [comment]
Removing the '+' prevents positive temperatures (that only appear with a '+' when the adjacent temperature is negative) to be considered. Just adding the '+' won't solve it, however. The solution is to put brackets around the symbols: `\\([-+]\\)` , as was suggested [here](https://github.com/LukeSmithxyz/voidrice/issues/490).

**Comment by LukeSmithxyz** [comment]
Ah, okay. Yeah sorry, I never have temps close to negatives, so I never see what wttr actually outputs for that unless I go looking. I'll change it to that.
