### ISSUE TITLE
st not displaying pipes and other characters

### ISSUE THREAD

**Issue by shtangetki** [LukeSmithxyz/voidrice#533]
Using your version of st, pipes don't show up in console output. So, for example the output of curl wttr.in is the same as this https://i.stack.imgur.com/SbNxx.png , but it's the same with corona-stats.online and other similar websites, the boxes just won't display. I have the same problem with Chinese characters and the weird Turkish letters. You don't seem to be having this issue in your videos.

**Comment by narukeh** [comment]
install this package: "ttf-droid-emojiless" for displaying multilanguage characters.
change your font, example DejaVu Sans Mono, Droid Mono, FreeMono, Ubuntu Mono (of course after installing the font) see if the issiue still exist.

**Comment by shtangetki** [comment]
Using Droid Mono does not fix the issue. The package ttf-droid-emojiless doesn't exist I installed ttf-droid. Changed the font in the st config.h and did sudo make install.

**Comment by shtangetki** [comment]
I just noticed this probably belongs in the LARBS repo and not the voidrice repo...

**Comment by narukeh** [comment]
(the package ttf-droid-emojiless does exist, in the aur, but its the same for this purpose). why dont you respond to all the different fonts i mentioned. also after recompiling st with a diff font, did that change any thing. you have to be verbose, we cant know what u're thinking. and no this belongs to this repo.
also try the default font config but with only inconsolata line removed.

**Comment by shtangetki** [comment]
So, I tried DejaVu Sans Mono, FreeMono and Ununtu Mono and the only thing that changes in the terminal is the font but the issue still persists. No Chinese characters, no pipes when doing curl wttr.in. I did this after making sure to have those 2 lines uncommented. I had those uncommented already and I also have the locales for Turkish, Russian and Chinese (all UTF-8). I removed the Inconsolata line in font.conf and that changed the font in my dwm status bar after reboot, but not my terminal (the font is currently DejaVu Sans Mono which is the last one I tried).

**Comment by narukeh** [comment]
1st. try installing other terminals, to see if its a st problem, or a system wide problem.
2nd. try sorting the languages in `/etc/locale.gen` first English, THEN the others.
3rd. install this `noto-fonts-cjk` this hass ALL cjk glyphs, and `gnu-free-fonts` and `noto-fonts-emoji`  remove EVERY OTHER font you have. of course, then change your fonts.conf accordingly.
if all that wont work: 😅 if u cant solve the problem, eliminate it, try reinstalling arch, the arch wiki way.

**Comment by shtangetki** [comment]
I installed terminator and it displays Chinese characters and wttr.in properly. I already have those fonts but I'm not quite sure how I should change the fonts.conf exactly. If you could be more specific that would help. Sorted, ran locale-gen as root, logged in as my user and I haven't noticed any change. I really think it's an st thing but I have no idea how Luke gets stuff to show up correctly on his terminal. This is on a pretty fresh install. Followed the arch wiki guide, downloaded LARBS, made a new user with it and everything I'm talking about is on that user with basically just the tags in Chinese and some scripts for the dwm status bar being the only difference in the setup.

**Comment by narukeh** [comment]
from my experience with emoji, there are some font packages, that even if you did not mention them in the font.conf they will take effect, therefore i was trying to minimize variables of failure in removing all, expect those 3 mentioned fonts.
> how I should change the fonts.conf exactly
remove all fonts & emoji name lines in ~/.confing/fontconfig/fonts.conf
add FreeSerif to serif, add FreeSans to 2nd and 3rd, and FreeMono to monospace (4th).
and again make sure the file  /etc/locale.conf  contains only this line LANG=en_US.UTF-8    ,reboot to se effects

**Comment by shtangetki** [comment]
Okay I did all that and it fixed the pipes not showing up but not the Chinese characters. Thanks for all the help btw. Maybe it is a problem with my fonts.conf I'm just going to try adding some more fonts and report back.

**Comment by narukeh** [comment]
let me guess u turned it off and on again and it worked, right? 😁
for chinese japanese koran (cjk) install `ttf-droid-emojiless` or `noto-fonts-cjk` or both.
if that also is fixed, dont forget to close this issue 👋

**Comment by shtangetki** [comment]
Yeah, I installed them and added <family>Noto Sans CJK SC</family> and the serif font where appropriate. It changed the font shown in the dwm status bar but the characters in my dwm config.h do no appear in the terminal unfortunately.

**Comment by kronikpillow** [comment]
it also doesn't display pulsemixer and alsamixer properly

[screenshot luke st ](https://0x0.st/iuMM.png)
[screenshot kitty](https://0x0.st/iuMu.png)

and no this belongs in [lukesmithxyz/st](https://github.com/lukesmithxyz/st)

**Comment by kronikpillow** [comment]
as a matter of fact in pulsemixer it doesn't display the volume bar at all, just has some weird ---- at the end

**Comment by shtangetki** [comment]
I think the question here is whether this can be fixed through the font config which I think we've shown that at least the pipes can be fixed. The real question for me is why doesn't it happen in Luke's setup in his videos.

**Comment by LukeSmithxyz** [comment]
Try removing the emoji fonts from the fontconfig section for monospace. I think that is interfering here. They were suppressing CJK fonts on my machine.

**Comment by kronikpillow** [comment]
yes seems that removing Inconsolata as the mono font seems to make the pipes and other characters appear
