### ISSUE TITLE
statusbar memory not shown when using different language

### ISSUE THREAD

**Issue by dschense** [LukeSmithxyz/voidrice#535]
Iam using a german locale installation. When I want to show the memory usage ins statusbar its not shown because the script uses:

`
free -h | awk '/^Mem:/ {print "🧠 ", $3 "/" $2}'
`
I had to change the command to

`
free -h | awk '/^Speicher:/ {print "🧠 ", $3 "/" $2}'
`
to print the usage out on statusbar

a possible solution could be to awk the correct spelling before running the output command:

`mem=$(free -h | awk 'NR==2 {print $1}')`
`free -h | awk '/^'$mem'/ {print "🧠", $3 "/" $2}'`

**Comment by dschense** [comment]
a possible solution could be to awk the correct spelling before running the command:

`
mem=$(free -h | awk 'NR==2 {print $1}')

free -h | awk '/^'$mem'/ {print "🧠", $3 "/" $2}'
`

**Comment by narukeh** [comment]
You have to run `free` and `awk` TWO times? uh oh nonono!
`free -h | sed -n '2{p;q}' | awk '{print "🧠", $3 "/" $2}'`

**Comment by dschense** [comment]
okay, your solution looks even better ;) it was my first time doing something like this.
then this problem is solved.
