### ISSUE TITLE
Where did vim snippets go?

### ISSUE THREAD

**Issue by colchide02** [LukeSmithxyz/voidrice#537]
Months ago there were vim snippets about latex, html, etc. Where did they go?
I saw something about the key demon in the vimrc file, so I searched something about it and fund nothing. Though I don't actually know how that demon works, I'm just learning vim and configuring it.
I know I could just make my own snippets as you did months ago, I could actually just copy them. But I would like to know if you found a better configuration or totally deleted them. Maybe you solved that upsetting cursor position thing when you start typing a snippet and vim waits to see if you complete it.

**Comment by tallguyjenks** [comment]
he removed them in a89697c but in commit aa7a4af you can grab a copy of the init.vim file to grab the snippets if you want them

**Comment by yanzhang0219** [comment]
I am curious about why Luke removed these snippets. Isn't he using it now?

**Comment by tallguyjenks** [comment]
he might have just removed them as they were specific to what he was doing and didnt want to include it for brand new larbs users? either way if someone really wanted to go get them (what i wanted to do too) just go to the previous commit and copy-pasta :)

**Comment by yanzhang0219** [comment]
Okay, I see. I was just wondering whether or not he came up with some better way to handle the snippets. :)

**Comment by tallguyjenks** [comment]
i havent seen anything on his YT content, and i get updates to this and the LARBS repo and i havent heard anything. currently reading this and the snippet management with utilisnippet plugin looks promising, but comes with a lack of vim motion support but for complex snippets with tabstops it may yield some value:

https://castel.dev/post/lecture-notes-1/
