### ISSUE TITLE
Mod+F1 is broken

### ISSUE THREAD

**Issue by sodle** [LukeSmithxyz/voidrice#54]
Nothing happens when I hit Mod + F1 on a new install. I'm using Antergos.

**Comment by LukeSmithxyz** [comment]
Did you install my dotfiles using LARBS or manually?

Mod+F1 requires `zathura` to be installed as the .pdf reader, which LARBS should install automatically.

**Comment by sodle** [comment]
I installed via LARBS. Zathura was not installed. I installed it. Now Mod+F1 opens an empty window with `[No name]` in the bottom left.

**Comment by LukeSmithxyz** [comment]
Oh, silly me, I see now. I forgot to update the LARBS scripts to replace mupdf with zathura. It should be fixed now for new users. Thanks for the report!

**Comment by sodle** [comment]
It seems zathura-pdf-mupdf is also required. That fixes the empty window issue and successfully displays the manual. Thanks.

**Comment by LukeSmithxyz** [comment]
Ah yea, I forgot about that. I've added it as well, along with the
zathura package for reading djvu files.
