### ISSUE TITLE
I'm probably going to switch all this to Pulseaudio.

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/voidrice#543]
I was going to start an issue asking if people would prefer having ALSA only as an audio system or ALSA with Pulseaudio. As I wrote the the post out, I guess I realized there's really no reason not to be using Pulseaudio. I have in the past in this repo and I think I should bring it back.

# Advantages of Pulseaudio

- Actually has sensible defaults, good high volume, can output from multiple sources without a plugin and works without a config file. Deals with headphones and other things smartly, etc.
- Is more robust in that it already comes with the ability to record system audio and other things people might end up using. You don't have to grope around in ALSA documentation (which doesn't exist, by the way) to do basic things.

# Non-advantages of Pulseaudio?

- Uh, ALSA is minimalist?
- I've had some trouble setting up Pulseaudio across distros (mainly Void). This might be resolved by now.

The fact of the matter is that while 90% of people using ALSA will eventually say, well I need Pulseaudio for this, no one using a Pulseaudio system will say, well my life would be better if I uninstalled Pulseaudio. Not using Pulseaudio, now seems to me like a meme in the purest sense.

Anyway, I'll put this out here now, but I'm thinking of switching the repo over.

That really just means switching the audio commands, maybe i'll just get rid of `lmc` again, changing the `volume` statusbar script and adding the programs to be installed to the progs file and a line to start pulseaudio.

**Comment by vladdoster** [comment]
I concur. It would free up the lmc bloat :nauseated_face:

**Comment by NikkiSatmaka** [comment]
I vote for PulseAudio

**Comment by oofdog** [comment]
There might be some issues using pulseaudio on non-systemd distros. From what I heard it works, but if you switch users, you can still hear audio playing from other user accounts that are still logged in in the background.

**Comment by LukeSmithxyz** [comment]
I've switch this repo, the LARBS repo and the dwm repo over to using PulseAudio as default. The dwm build and the volume statusbar module here now have commented out ALSA options for those who want it easily.

There is one minor issue I've been having with Artix, that is that mpd and pulseaudio haven't been playing well. I have mpd going on ALSA output still because that seems to work.

**Comment by LukeSmithxyz** [comment]
Obviously if anyone runs the scripts and has trouble in the next few days, feel free to make me aware.

**Comment by charlie39** [comment]
music goes up beyond 100% lol. It looks hysterical. May be it would be more appealing if the increase and decrease happens in percentage.
