### ISSUE TITLE
Switching to Ranger?

### ISSUE THREAD

**Issue by pirate1337** [LukeSmithxyz/voidrice#548]
i've recently switched to ranger instead of lf but dwm doesnt seem to want to launch it when i press the binding. I have changed the binding in the DWM config.h but it keeps trying to launch lf instead.

**Comment by ultraSsak** [comment]
did you change the environment variable $FILE?
in ~/.profile

**Comment by pirate1337** [comment]
> did you change the environment variable $FILE?
> in ~/.profile

There is no $FILE variable.

**Comment by ultraSsak** [comment]
Yeah, sorry for misguiding you, i still have it in my system.
I've edited my anwser like 1 minute before You posted this.

**Comment by jonmed** [comment]
lf was hardcoded on this commit: 248b6dd3d2383be17a5533e532c0322ae9960c13

**Comment by pirate1337** [comment]
Thanks @jonmed! Finally switched it around.
