### ISSUE TITLE
volume script not updating

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#551]
after the latest commits to voidrice the volume bar script isn't updating the volume indication ...

I use 
pulseaudio
pulseaudio-alsa
pulsemixer

it worked before the latest changes to it

**Comment by pirate1337** [comment]
yes problem here except im sticking with alsa. Only way to update it is to restart dwm with mod+f2.

**Comment by LukeSmithxyz** [comment]
It has nothing to do with Pulseaudio. To solve the issue of lag on multiple calls of pkill, the volume script is time-based now rather than signal based.

Update your build of dwmblocks and it will be fixed.
