### ISSUE TITLE
Suggestion: No latency webcam

### ISSUE THREAD

**Issue by vitezfh** [LukeSmithxyz/voidrice#558]
I don't use your boomer config, but I remember your having some scripts that fix the voice - webcam sync in your recordings. I couldn't find the exact webcam config, but one of the Github issues mentioned this: 
mpv --no-osc --no-input-default-bindings --input-conf=/dev/null --title='mpvfloat' /dev/video0

Anyway, try this: 
mpv --no-osc --no-input-default-bindings --input-conf=/dev/null --title='mpvfloat' --no-cache --profile=low-latency --untimed /dev/video0

**Comment by LukeSmithxyz** [comment]
Thanks for the hint. It does seem to get it closer, but it remains still a fraction of a second off.

**Comment by vitezfh** [comment]
Yeah, no problem. That's unfortunate, but at least it irks less when you use it.

**Comment by m160** [comment]
This works for me:
mpv --profile=low-latency --untimed --no-correct-pts --opengl-glfinish=yes --opengl-swapinterval=0 --no-osc --no-input-default-bindings --input-conf=/dev/null --title='mpvcamera' --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0

Not sure if all of it is needed, but I can't notice any latency with it.

**Comment by vitezfh** [comment]
I don't notice a difference on my setup, but I'll test it more when I record with the cam.

You can also add: --vf='hflip'
That flips the cam horizontally so it feels more natural, like a mirror. It feels much better that way.

**Comment by LukeSmithxyz** [comment]
I mean I should say, all of this looks pretty much on time, but once ffmpeg is running, I think it is always going to produce some latency. In fact, so far as I can tell there's no lag while recording apparent to me, but there definitely is some whenever I watch the recording itself.

That's why I'm pretty pessimistic about there being an mpv only way of avoiding this effect.
