### ISSUE TITLE
mpd-update-module won't run from .xprofile on boot

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#566]
I see you removed the mpd-module-update script from .xprofile, and now my mpd module doesn't update when I change songs, I've placed it back to .xprofile in my system but it still doesn't run after i boot the system, althou if i run it trough dmenu or terminal it works, any ideas why I can't get it to work from .xprofile?

also your music script in .local/bin/statusbar has this strange excess
<span></span> around the song name, and it makes it unusable in the statusbar with dwm, so because of it I used the mediaplayer script from i3blocks-contrib repo, but it doesn't update without the mpd-module-update script running

**Comment by kronikpillow** [comment]
also without it in i3 when you change the song it doesn't update the module with the new song title

**Comment by LukeSmithxyz** [comment]
Your first problem might have something to do with start order. Are you sure that `mpd` is started before the script? In the case of i3, the `STATUSBAR` variable needs to be assigned before it runs.

In both cases, is the script running in the background when you start and not working, or not running at all?

Yeah I have sort of disabled this feature for several reasons for the time being. I should probably re-enable it, but I don't like having the `mpd-module-update` script to be honest.

**Comment by kronikpillow** [comment]
yeah i placed it at the bottom of .xprofile

```
# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
mpd-module-update &	# Check for when to update the mpd module
```

it doesn't run at all ... it probably has to do with the $STATUSBAR variable which was removed from .profile in one of your latest commits ... lets see if it works if i restore the variable from previous commit

**Comment by LukeSmithxyz** [comment]
Oh I see now. If you're using i3 (and the most recent version of everything), I suppose I have `STATUBAR` set in the xinitrc after the xprofile is called (and that script is started).

I'll fix this.
