### ISSUE TITLE
Update local dotfiles without deleting my personal changes

### ISSUE THREAD

**Issue by danielscamacho** [LukeSmithxyz/voidrice#568]
Many changes has been applied last days.

There was an old issue regarding this but it got closed without a clear solution.

I am wondering how to update my local repo with the remote copy without destroying my local changes.

Last Issue is this: https://github.com/LukeSmithxyz/voidrice/issues/93

**Comment by drake-newell** [comment]
Just run "git pull" while in your home directory.

**Comment by vladdoster** [comment]
lol

**Comment by danielscamacho** [comment]
Git pull does merge after fetching remote chances.
It will override my customize changes. And it is what I want to avoid

**Comment by danielscamacho** [comment]
> Just run "git pull" while in your home directory.

Git pull does merge after fetching remote changes.
It will override my customize changes. And it is what I want to avoid

**Comment by danielscamacho** [comment]
> lol

how do you keep your local changes if you merge it them with the pull command? Are you using attr https://git-scm.com/docs/gitattributes?

**Comment by drake-newell** [comment]
@danielscamacho commit your local changes

**Comment by LukeSmithxyz** [comment]
People have always been suggesting me to use dotfile managers and such, but no matter what, users are going to have to do the same thing at the bottom: manually decide which part of a diff they want or not, even if the rest are automatic merged.

The current solution is just to learn to use git... I might toy around with a wrapper update script or something, but still, conflicting configs have to be done manually.

**Comment by danielscamacho** [comment]
> @danielscamacho commit your local changes
commiting changes does not prevent to get resynced from the origin repo.

**Comment by drake-newell** [comment]
@danielscamacho It does, or at least it should.

**Comment by danielscamacho** [comment]
> People have always been suggesting me to use dotfile managers and such, but no matter what, users are going to have to do the same thing at the bottom: manually decide which part of a diff they want or not, even if the rest are automatic merged.
> 
> The current solution is just to learn to use git... I might toy around with a wrapper update script or something, but still, conflicting configs have to be done manually.

I completely agree with you here. It is a Git lack of knowledge here and out of scope of voidrice Repo. I just open this Issue because I found a past Issue talking about it and I wanted to know if there are more informations about it, just wanted to learn how other people are approaching voidrice update, lets say kind of wiki from the users.

Let me thank you for your amazing contribution on LARBS and Voidrice.
