### ISSUE TITLE
statusbar volume script language problem

### ISSUE THREAD

**Issue by dschense** [LukeSmithxyz/voidrice#569]
The line: 

`vol="$(echo "$volstat" | grep '^[[:space:]]Volume:' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
`

is not working when the system language is changed. For example I am using german system lanuage. With this language the line needs to be changed to 

`vol="$(echo "$volstat" | grep '^[[:space:]]Lautstärke:' | sed "s,.* \([0-9]\+\)%.*,\1,;1q")"
`

maybe there is a way to to change this to get it global running.

with 

`volstat="$(LC_ALL=C pactl list sinks)"
`
the output is alway Volume
Maybe someone has some better idea.

**Comment by LukeSmithxyz** [comment]
Well, I'll just take a risk and have it grep for a percentage instead of the string "Volume." There doesn't seem to be any output of that command other than the volume to generate that. Seems to work on my side.
