### ISSUE TITLE
fontconfig uses not installed fonts

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#574]
fontconfig uses
			<family>Noto Sans Mono</family>
			<family>Liberation Mono</family>

while neither are installed after a fresh install of LARBS

luckly I saved the old ttf-inconsolata v2.0.0.3 before reinstalling :dagger:

**Comment by LukeSmithxyz** [comment]
Liberation Mono should be installed with `ttf-linux-libertine`, are you sure that's not the case?

What is the result of `fc-match mono` on first install?

I know that noto is not installed, but I just have that as the default font in case it is. I was thinking about totally removing the fontconfig though, lol.

**Comment by kronikpillow** [comment]
uff far past first install now :D will try out later, why remove fonts.conf? I love the setup, especially with Inconsolata

**Comment by LukeSmithxyz** [comment]
Well I mean inconsolata is out of the running with that font spacing bug. The fontconfig has actually causes a lot of annoyance over the years. The only reason I had it in the first place is that years ago when I first started using Arch, there was some global fontconfig error that made the default mono font show up like boxes unless you manually told it something else.

**Comment by kronikpillow** [comment]
a custom repository with the old pkg file of inconsolata might solve the problem, did you consider running your own custom repository for some of your packages? I have both the symbols and inconsolata package backed up from before they broke, and I just solve the problem by installing the old versions and placing inconsolata and symbola to ignore updates

**Comment by LukeSmithxyz** [comment]
That is too fragile of and ad hoc of a solution. I've learned not to resist package changes. I'd have to stipulate a lot for that. If they fix it, great, maybe I'll readd it, but it's not really an essential package.
