### ISSUE TITLE
question: how do you format vim scripts

### ISSUE THREAD

**Issue by vired** [LukeSmithxyz/voidrice#576]
manually as you like or using an script

**Comment by mobop** [comment]
come on man.

**Comment by kolokd** [comment]
hi, don't mind. Do you know about any program that do this.

**Comment by AlexSyssoyev** [comment]
What do you mean?

**Comment by kolokd** [comment]
I mean that i want a program/script that auto format vim script.

**Comment by vladdoster** [comment]
Depending on what file type, you'd set a bufwrite post command to run the formatter.

If python, use b

**Comment by kolokd** [comment]
@vladdoster have you read my question?
i am asking for a formatter for vim-script files

**Comment by tallguyjenks** [comment]
@kolokd try some of the suggestions talked about in [this post](https://www.reddit.com/r/vim/comments/8k1ljk/vim_script_formatter/)

**Comment by kolokd** [comment]
@tallguyjenks I can't visit reddit form Bangladesh. It is blockd.

**Comment by vladdoster** [comment]
Use vims internal formatter
```
:h =
```
