### ISSUE TITLE
dmenupass - password not hidden

### ISSUE THREAD

**Issue by MarcBeaudet** [LukeSmithxyz/voidrice#577]
I seem to have a problem with the dmenupass script. 
The password is not hidden. 
The same happens with sudo -A.

No modifications were made on the script. Should it require specific settings/programs?

Thanks

**Comment by drake-newell** [comment]
I would suggest that Luke add the password patch to his dmenu build

**Comment by MarcBeaudet** [comment]
Thank you, using the password patch + adding the `-P` flag in dmenupass fixed my issue.
