### ISSUE TITLE
current version of libxft-bgra (2.3.3-1) broken

### ISSUE THREAD

**Issue by Abh15h3k** [LukeSmithxyz/voidrice#581]
So this is not really a issue with larbs. but the current version of libxft-bgra doesn't install ( both with 
`yay` and `makepkg -si`, a patch that gets applied during installation fails ).
Because of this st will crash whenever it tried to load emojis.

my fix was taking the older version i had cached on a different system. 
is there a way to force install a specific version of the package. I know that 2.3.3 installs and works properly.

**Comment by LukeSmithxyz** [comment]
They've fixed this now.
