### ISSUE TITLE
Why was the user-dirs export DELETed from .profile?

### ISSUE THREAD

**Issue by dennisleexyz** [LukeSmithxyz/voidrice#583]
With this change https://github.com/LukeSmithxyz/voidrice/commit/6f36fe31693ad7dd47ecb443901039eb5c96969f#diff-593308ff3a1800e7975e8fdd7f830dd3 things like `XDG_DOCUMENTS_DIR` etc. just aren't defined on startup. Unless I'm missing something.

**Comment by LukeSmithxyz** [comment]
Yeah, so?

**Comment by LukeSmithxyz** [comment]
Actually I should be clear, it's not necessary for them to be part of the shell environment for them to be used by xdg. If you change your downloads folder there, the change will occur whether your "export" it or not.

And really I've never seen anyone use these variables in their shell. I guess we could, but nah.

**Comment by dennisleexyz** [comment]
OK. The reason it came up is because I was trying to direct my `maim` screenshots to `XDG_PICTURES_DIR`. But I guess it's not a big deal.

**Comment by aleksozolins** [comment]
As far as I know, not all xdg compliant apps read directly from xdg-user-dirs. The package includes a systemd unit that automatically exports them on boot, but since the systemd unit isn't installed here...
