### ISSUE TITLE
The sysact script doesn't reboot the system

### ISSUE THREAD

**Issue by drake-newell** [LukeSmithxyz/voidrice#584]
On Void, the sysact script does not work to reboot the system, while the old reboot binding did. Running sudo -A reboot in the terminal does successfully trigger a reboot.

**Comment by AlexSyssoyev** [comment]
Same problem here on arch.

**Comment by kronikpillow** [comment]
same problem here on Arch

**Comment by LukeSmithxyz** [comment]
Oh, I guess it doesn't work on my system either... I don't know why.

Changing it to:

sudo -A shutdown -r now

works on mine. Does that exist on systemd? I forget.

**Comment by AlexSyssoyev** [comment]
I actually tried to change it to shutdown -r now and it doesn't work either on my system, no idea why

**Comment by drake-newell** [comment]
@LukeSmithxyz Still the same issue. Works when I type it out in the terminal but not in the script

**Comment by AlexSyssoyev** [comment]
Changing the name of the cmd from reboot to reboot-dwm fixed the issue.

**Comment by mokulus** [comment]
It doesn't work because there are multiple tabs in reboot line
`cat -A sysact`
```shell
...
refresh dwm^Ikill -HUP $(pidof -s dwm)$
reboot^I^Isudo -A reboot$ # TWO tabs (^I) on this line
shutdown^Isudo -A shutdown -h now$
...
```

I would change it so it uses a visible character as delimiter, maybe `#`? Some editors may even change the tabs to spaces and it won't work at all.

**Comment by mokulus** [comment]
I guess you can stay with tabs but use `cut -f 2-` so everything after the first tab gets executed.
