### ISSUE TITLE
Suggestion: use fast-syntax-highlight

### ISSUE THREAD

**Issue by OHermesJunior** [LukeSmithxyz/voidrice#593]
Since you started using zsh with zsh-syntax-highlighting,
I suggest you to use [fast-syntax-hightlighting](https://github.com/zdharma/fast-syntax-highlighting), as the name suggests, it's fast lol.
It also has better highlighting.
(Not sure if I should open an issue for a suggestion by the way).

**Comment by LordRusk** [comment]
I think this would be good, perhaps a pull request would fair better than an issue though.

**Comment by OHermesJunior** [comment]
I didn't do a pull request because the users needs to download the plugin themselves, and sourcing the plugin file in the zshrc wouldn't make sense without doing it first.

**Comment by OHermesJunior** [comment]
I didn't do a pull request because the users needs to download the plugin themselves, and sourcing the plugin file in the zshrc wouldn't make sense without doing it first.

**Comment by LordRusk** [comment]
When using the dotfiles, you have to install zsh-syntax-highlighting, so it wouldn't make much difference. If you do create a pull request, you may want to make one on the larbs repo to change the progs.cv to install fast-syntax-highlighting, and link em.

**Comment by LukeSmithxyz** [comment]
This has been added.
