### ISSUE TITLE
Headphone Bluetooth statusbar

### ISSUE THREAD

**Issue by danilovicente** [LukeSmithxyz/voidrice#599]
Hey Guys, I don't know if you guys can help me.

But when I'm using my bluetooth headphone the volume that shows in the status bar is the master. Anyone knows how to show the headphone bluetooth volume only when I have my headphones connected?

**Comment by vladdoster** [comment]
you zoomers and your phones :expressionless:

**Comment by danilovicente** [comment]
@vladdoster
