### ISSUE TITLE
Keyboard backlight 

### ISSUE THREAD

**Issue by tqk-gh** [LukeSmithxyz/voidrice#6]
Hey Luke, I was trying to use some of your i3 config goodness on my laptop.
Your Keyboard backlight configs have the same commands as the screen brightness controls
These are yours in the "Extra XF86 Keys" section

> `bindsym XF86MonBrightnessDown	exec --no-startup-id xbacklight -dec 15`
>`bindsym XF86MonBrightnessUp exec --no-startup-id xbacklight -inc 15`

> `bindsym XF86KbdBrightnessDown	exec --no-startup-id xbacklight -dec 15`
>`bindsym XF86KbdBrightnessUp exec --no-startup-id xbacklight -inc 15`

They basically control the "xbacklight" screen brightness on my Asus laptop

I couldn't find an easier way to solve this, so I used [this](https://wiki.archlinux.org/index.php/Keyboard_backlight) python script and then mapped it to "XF86KbdBrightness" key in i3 config file
```
# Keyboard backlight controls
bindsym XF86KbdBrightnessDown	exec --no-startup-id python3.6 ~/.i3/kb-lights.py -
bindsym XF86KbdBrightnessUp exec --no-startup-id python3.6 ~/.i3/kb-lights.py +
```

**Comment by Panadestein** [comment]
Hello.
I had the same issue, solved with a `pacman -S xorg-xbacklight` that wasn't installed by default on my system. Hope it helps.

**Comment by tqk-gh** [comment]
Thank you, but I think your problem is related to adjusting the screen brightness, while mine was regarding adjusting the keyboard backlight, as the command `xbacklight -inc 10` will only increase the screen brightness, not the keyboard's backlight that is supposed to be controlled by the `XF86KbdBrightnessUp/Down` keys
