### ISSUE TITLE
sxiv custom keybindings aren't working 

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#609]
the sxiv custom keybindings that you have setup aren't working for me, like I can't delete pictures with sxiv ...

**Comment by LukeSmithxyz** [comment]
Is the dmenu prompt showing up? What happens?

**Comment by kronikpillow** [comment]
nothing happens

**Comment by kronikpillow** [comment]
nvm ... figgured it out :) ctrl+x+key :facepalm:
