### ISSUE TITLE
Problem on fresh install

### ISSUE THREAD

**Issue by haldamine** [LukeSmithxyz/voidrice#610]
Hey Luke, I wanted to do fresh install on a new machine. As soon as I finish running larbs.sh and login into the system. I am immediately logged out of the system.

**Comment by LukeSmithxyz** [comment]
Does it work after several tries?

The past couple days on my machine occasionally a login fails for an unknown reason. I haven't figured the exact cause, but I didn't think it was anything I already pushed to the repo. Might be a dwm problem too.

**Comment by haldamine** [comment]
No, it does not. I tried logging in 15+ times and each time it proceeds to immediately log me out.

**Comment by haldamine** [comment]
Ok so I found a solution. You need to first install libxft-bgra from the aur before running larb.sh .

**Comment by LukeSmithxyz** [comment]
`libxft-bgra` should be installing during the script. I'll look into it.

**Comment by AlexSyssoyev** [comment]
More than once i had to rerun larbs.sh on the same user so it can install all the packages, sometimes it skips some for no reason. no idea why.

**Comment by LukeSmithxyz** [comment]
I think there have been some signature/keyring changes recently that might be the source of the problem. I might just want to have the script automatically update keyrings at the beginning of the install despite the extra time...

**Comment by AlexSyssoyev** [comment]
I think it would be worth it, considering that it can save a lot of trouble especially to the beginner Linux users.

**Comment by haldamine** [comment]
Agreed, if they don't have to peruse through their log files they're more likely to stick with it. Thanks again for all you do Luke!

**Comment by Nutjob** [comment]
Just got the same problem (first time installing arch, I thought I messed up the install.... )

**Comment by WhaleJ84** [comment]
Having the same issue. Manually installed `libxft-bgra` and installed with `makepkg --skippgpcheck` followed by `libtool --finish /usr/lib` as the previous command suggests, but running `startx` still has the same issue.

**Comment by haldamine** [comment]
The following steps should make it work on a fresh install

pacman -S base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
yay -S libxft-bgra
curl -LO larbs.xyz/larbs.sh
sh larbs.sh


this way all the signatures update as well

**Comment by haldamine** [comment]
Make sure libxft is not installed as it conflicts with lbxft-bgra .

**Comment by drewisdorner** [comment]
> The following steps should make it work on a fresh install
> 
> [...]
> yay -S libxft-bgra
> [...]
> this way all the signatures update as well

I tried this on a completely fresh install and was getting the following output

```
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  libxft-bgra-2.3.3.r7.7808631e-1

  1 libxft-bgra

[...]

==> Starting prepare()...
~/.cache/yay/libxft-bgra/src/libxft_upstream ~/.cache/yay/libxft-bgra/src
Initialized empty Git repository in /home/user/.cache/yay/libxft-bgra/src/libxft_upstream/.git/
error: Server does not allow request for unadvertised object 7808631e7a9a605d5fe7a1077129c658d9ec47fc
==> ERROR: A failure occurred in prepare().
    Aborting...
Error making: libxft-bgra

```

I'd also see that the the package is [Flagged out-of-date](https://aur.archlinux.org/pkgbase/libxft-bgra/flag-comment/) with the same error.

Can anybody help me with this problem?

**Comment by Abhishek-Deshmukh** [comment]
@drewisdorner I ran into the same issue.
Can someone check this out, My noob recommendation is moving back to libxft, it would be wonderfull if someone knows what all things to change to get that.

**Comment by Abhishek-Deshmukh** [comment]
Put this is inplace of the commit id and then it starts working.
972fa05c3df73fd3c99c409c0ac2225a58f76d09

**Comment by framedr0p** [comment]
I have got the same issu. When i login an run startx i can see the Wallpaper for a second and then i get logged out.
I already got libxft-bgra installed.

**Comment by framedr0p** [comment]
Ok! I fixed it this way for me:
sudo pacman -Rdd libxft
git clone https://aur.archlinux.org/libxft-bgra.git
cd libxft-bgra 
makepkg -rsi —skippgpcheck
startx

**Comment by rescenic** [comment]
startx can't find monitor.
https://github.com/LukeSmithxyz/LARBS/issues/254
