### ISSUE TITLE
Why not add a filename argument to startx and eliminate .xinitrc

### ISSUE THREAD

**Issue by sk8ersteve** [LukeSmithxyz/voidrice#611]
Is there any particular reason you didn't have your xinitrc file in the config folder (maybe in an X11 folder inside) and just add that location to the startx command in .zprofile?
This is what's recommended in the XDG Base Directory Arch wiki page.

**Comment by LukeSmithxyz** [comment]
No, I don't want to manually force settings and using wrappers around script to have basic functionality. I allow some aliases for non-essential programs, but not for this. There is the `XINITRC` variable, but it hasn't worked so well and doesn't work with `startx`.
