### ISSUE TITLE
How the ranger shortcuts.conf should look like?

### ISSUE THREAD

**Issue by thepenguinthatwants** [LukeSmithxyz/voidrice#612]
Hi!

I noticed that u have 

`eval cmd('source ' + fm.confpath('shortcuts.conf'))`
in rc.conf

I guess its same than normally making bookmarks by the m, but instead having always same defaults? Can you give example as in what format should those shortcuts be in that file?

**Comment by LukeSmithxyz** [comment]
That file is the output of the `shortcuts` script. Don't create or edit it manually.
