### ISSUE TITLE
zzz missing (Hibernate)

### ISSUE THREAD

**Issue by AlexSyssoyev** [LukeSmithxyz/voidrice#615]
Hi!, the hibernate function does not work

```
sudo: zzz: command not found
```

Is zzz a package i'm missing or a script that is missing from the path? Thanks.

**Comment by LukeSmithxyz** [comment]
zzz is the command with runit, which is what I use. I forget the systemd equivalent. Is it `systemctl hibernate`? I could add it in as an alternative.

**Comment by AlexSyssoyev** [comment]
I just checked, yes ```systemctl hibernate``` is the command in systemd, but i had to use ```systemctl suspend-then-hibernate``` to get it to work on my system. Probably a problem with my swap partition or something i don't know, will check that later. But yeah i think it would be a good idea to add that considering that 95% of LARBS user's use systemd.

**Comment by LukeSmithxyz** [comment]
Okay, added in 87dda7cdc350b06d9929c1569d0a6e8f3e8a2926. Does anyone know the relevant hibernate commands for OpenRC or other different power commands for each init system?

**Comment by drake-newell** [comment]
@LukeSmithxyz openrc reboots with "sudo openrc-shutdown -r" and shuts down with "sudo openrc-shutdown -p." Gaining the ability to hibernate with openrc seems pretty involved: 
https://forum.manjaro.org/t/enabling-hibernate-if-not-enabled-during-installation/3241

**Comment by LukeSmithxyz** [comment]
Okay. When you run `readlink -f /sbin/init` what is the exact output on your OpenRC device?

**Comment by drake-newell** [comment]
@LukeSmithxyz I don't actually use openrc anymore, that was just what I remembered from when I did use it

**Comment by LukeSmithxyz** [comment]
Okay. Well I'm just going to take a wild guess that it matches `*openrc*` and we'll call it a day.
