### ISSUE TITLE
dwm fresh install weather report doesnt display correctly

### ISSUE THREAD

**Issue by tallguyjenks** [LukeSmithxyz/voidrice#616]
lookin through past issues #509 resolved the issue, and on current install less's args are `-Sf` and what resolved was using the `-r` option in #509 not sure if it was changed for some reason but on a brand new system and fresh dwm install weather report doesnt display correctly without `-Srf`

**Comment by LukeSmithxyz** [comment]
What's your `LANG` variable? It works fine on mine. The reason I changed it now is that it shouldn't wrap lines when in a small terminal.

**Comment by tallguyjenks** [comment]
`LANG` is `en_US.UTF-8`

**Comment by LukeSmithxyz** [comment]
Jeez, here we go again... I never figured out why it doesn't work on anyone but myself's computer lol.

Tell me, if you spawn the preview (by clicking the statusbar) when there are other windows, does the weather report wrap the text (like if the window is too small) or does it not show the overflow text? Does is make a difference with/without `-r`?

**Comment by tallguyjenks** [comment]
Here are the two cases with and without the `-r`option

With `-r`

![with_r_option](https://user-images.githubusercontent.com/29872822/81221147-49d8cc80-8f97-11ea-8789-c1d619b93459.png)

without `-r`

![without_r_option](https://user-images.githubusercontent.com/29872822/81221152-4ba29000-8f97-11ea-9cfa-9c07297969bf.png)

**Comment by tallguyjenks** [comment]
i dunno man, im running on x220's as well, ¯\_(ツ)_/¯

**Comment by LukeSmithxyz** [comment]
What is your `LESS` value equal to? Is it `-R`?

**Comment by tallguyjenks** [comment]
@LukeSmithxyz yup, that was the default `echo $LESS` = `-R`

**Comment by BachoSeven** [comment]
Since I don't feel like it's worth opening a new issue, I want  to report that this also applies to the new `price` script: I have LESS set to "-R", lesspipe.sh installed and configure but unless I explicitly use `less -r` in the script it won't display raw chars.

**Comment by narukeh** [comment]
not dwm specific. im still using i3.
with `-r` which is the defaulf, so when i click i get:
![with-r](https://user-images.githubusercontent.com/62762955/83333100-23106c00-a29f-11ea-9ee3-8f809b24b371.png)

without `-r`
![without-r](https://user-images.githubusercontent.com/62762955/83333108-34597880-a29f-11ea-991f-005a273b1cc5.png)

```
$ echo $LESS
-R
```

**Comment by vladdoster** [comment]
Kind of off topic, but your shell after a fresh install was `zsh`? I recently added a simplification to set it and wanted to make sure it was working?

**Comment by narukeh** [comment]
`man less` :
```
-r or --raw-control-chars
              Causes "raw" control characters to be displayed.  The default is to display control characters using the caret nota‐
              tion; for example, a control-A (octal 001) is displayed as "^A".  Warning: when the -r option is used,  less  cannot
              keep  track  of  the  actual appearance of the screen (since this depends on how the screen responds to each type of
              control character).  Thus, various display problems may result, such as long lines being split in the wrong place.
```
So less says  that if u use -r then -S will most likely not work. Which it does not.
`less` displayed `weatherreport` correctly under `dash` (reproduce: `st -e /bin/dash` 
then do `less -Sf .local/share/weatherreport` ) so i guess its not a zsh thing?
@tallguyjenks  idk what you did, but it works on a fresh larbs install.

**Comment by tallguyjenks** [comment]
not sure either, but if it works then i guess its resolved now for what ever reason.

**Comment by vladdoster** [comment]
@tallguyjenks when did you do an install? Recently or was this following a -Syyu?

**Comment by tallguyjenks** [comment]
@vladdoster installed the day i posted this issue almost a month ago, im not even using that build on my spare machine anymore either
