### ISSUE TITLE
How change newsboat video stream quality

### ISSUE THREAD

**Issue by Monirzadeh** [LukeSmithxyz/voidrice#617]
hi
newsboat as default `,v` play video link in best quality.
how can i change quality for example play them in 320p or 4K?

**Comment by LukeSmithxyz** [comment]
Look into the command line options for mpv/youtube-dl. You can set defaults for it in `~/.config/mpv/mpv.conf`. For example, this line limits the resolution to no bigger than 720p:

```
ytdl-format=bestvideo[height<=?720]+bestaudio/best
```
