### ISSUE TITLE
lf cut function not working

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#618]
when I try to cut a file with (D) from a location in my home directory and move it to a different location i get this error

![pic-selected-200508-1204-35](https://user-images.githubusercontent.com/48420193/81396016-ee3c4980-9124-11ea-8560-61c829a9b348.png)

any idea what the problem might be?

**Comment by n0ibe** [comment]
It's a known issue, see [here](https://github.com/gokcehan/lf/issues/151).

**Comment by LukeSmithxyz** [comment]
Closing this. We'll let them fix it upstream.
