### ISSUE TITLE
Color emojis in ranger??

### ISSUE THREAD

**Issue by sleeeeeeper** [LukeSmithxyz/voidrice#619]
Hey, I'm been watching your videos on youtube and I noticed that you've got color emojis in `ranger`.
How do you manage to do that?

**Comment by tallguyjenks** [comment]
ranger is a terminal application, so its dependent on the terminal emulator for the emoji support. luke's build of `st` is that emulator. if  you havent updated your build recently you can pull hois `st` repo down ans `sudo make install` in the directory to rebuild the build. you'll also need `libxft-bgra` installed via `sudo pacman -Syu libxft-bgra`

**Comment by LukeSmithxyz** [comment]
I don't use ranger anyway... maybe you're seeing lf? Anyway, what tallguyjenks says is true. It's ultimately nothing to do with ranger, but the terminal emulator.

**Comment by sleeeeeeper** [comment]
I'm aware of that. And I did install `libxft-bgra' to enable color emojis in my terminal emulator.

What I'm saying is I saw some colorful icons in your file manager rather than normal `devicons' and I'm courious.

**Comment by tallguyjenks** [comment]
@sleeeeeeper if its from his recent build, then it looks like ranger with the multiple panes and its actually `lf` the file browser, and you can set different emojis for filetypes/directories, see this config file from the current build: [.zprofile](https://github.com/LukeSmithxyz/voidrice/blob/8f05c7d79f91783d2cafe00a7d479eef9d652e8a/.zprofile#L57)

**Comment by sleeeeeeper** [comment]
@tallguyjenks Thanks!!
