### ISSUE TITLE
question on bspwmrc, why are there 2?

### ISSUE THREAD

**Issue by tallguyjenks** [LukeSmithxyz/voidrice#620]
forgive my ignorance if theres a reason for this, but there one bspwmrc in `.config/bspwm/bspwmrc` but then  there's also `.config/bspwm/bspwm/bspwmrc`. is there a particular reason for this?

**Comment by vladdoster** [comment]
Just use DWM :+1:

**Comment by tallguyjenks** [comment]
im using the dwm build but there's bspwm stuff in here, is it not used with the dwm build? forgive my ignorance, im still on i3 from last september so i got to learn all the new stuff involved in this build

**Comment by drake-newell** [comment]
@tallguyjenks Luke left the bspwm stuff in there since some people wanted it.

**Comment by vladdoster** [comment]
No need to apologize, we are all learning.

I am 99.99% confident that you can delete all bspwm related stuff if you are using DWM build!

**Comment by tallguyjenks** [comment]
thanks @vladdoster & @drake-newell ! shifting over to the new build tonight, excited :)
