### ISSUE TITLE
Cannot get transparency for Zathura

### ISSUE THREAD

**Issue by gimmelemons** [LukeSmithxyz/voidrice#628]
I have xcompmgr installed and running.
I get transparency in all windows (programs?) except zathura. I don't think there is a way to exclude windows from xcompmgr compositing. Also how is browser not transparent? I don't want browser to be transparent, just wanted to know where such a setting/config lies. I couldn't find any method that excludes windows.
But `zathura a1.pdf & sleep .2s && transset-df -a ` gives transparency to it, so ruling out any magical issue with xcompmgr.
I'm using pywal for colours.

**Comment by drake-newell** [comment]
I would be interested to know why this is as well

**Comment by LukeSmithxyz** [comment]
Zathura doesn't have built in transparency as far as I know. You should open an issue on their own repository.

**Comment by WhispersOfJ** [comment]
Not to beat a dead horse, but this is an avenue to look into.

[https://gist.github.com/miseran/0ea4b95e9816bf915b7b7171a5a0e42d](https://gist.github.com/miseran/0ea4b95e9816bf915b7b7171a5a0e42d)
