### ISSUE TITLE
Extend samedir script to work with tmux

### ISSUE THREAD

**Issue by yassinebridi** [LukeSmithxyz/voidrice#632]
First of all, thank you for this script, it's a pretty useful one, i use it everywhere, i changed it work with ranger too.
but it doesn't seem to play nice with tmux.
i wonder if there is a way to make it work with it.

**Comment by LukeSmithxyz** [comment]
Since a tmux session can have multiple panes in multiple directories, that's not going to be something easily done. Or at least, you might be able to script it, but I don't think one script would be able to work for tmux and non-tmux at the same time.

**Comment by yassinebridi** [comment]
I figured it would be complicated.
thanks
