### ISSUE TITLE
In tmux, cursor shape does not change in zsh, or vim

### ISSUE THREAD

**Issue by g-w1** [LukeSmithxyz/voidrice#646]
I'm was trying out tmux and I saw that the cursor was always an I beam in zsh and vim. I was wondering if there was a way to make it dynamic like it is in regular zsh.
[https://stackoverflow.com/questions/6488683/how-do-i-change-the-vim-cursor-in-insert-normal-mode/42118416#42118416](https://stackoverflow.com/questions/6488683/how-do-i-change-the-vim-cursor-in-insert-normal-mode/42118416#42118416) This post shows how to do it on mac os with regular vim and not with zsh. I was wondering if there was a way to do this in st with neovim and zsh.
Edit: Wrong url

**Comment by LukeSmithxyz** [comment]
This isn't really a question for this repository. Ask tmux people. I don't really use or maintain for tmux even though I guess there's still an old config for it here.

I will say that I installed tmux just to try it out and it's working as it should be on my machine with zsh withe the cursor changing for different modes. Either way, I don't know the first thing about tmux and have never really used it so it's best asking someone who does.
