### ISSUE TITLE
LF move to and copy to problem

### ISSUE THREAD

**Issue by Cyberdr3am** [LukeSmithxyz/voidrice#650]
Hi, when i whant to moveto and copyto with lf and if the file have space inside of the name this don't work.
I try something to fix this but i don't know how to fix it.

If someone can help me.

Thx

**Comment by drake-newell** [comment]
This is an upstream bug I think

**Comment by AlexSyssoyev** [comment]
If you get a error then this is a duplicate of #618 

Do you get any message from lf? invalid cross-device or something?

**Comment by Cyberdr3am** [comment]
No error from lf. When i go back to the terminal i see

Move to where?
mv: impossible d'évaluer '/home/cyber/Mots': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'de': Aucun fichier ou dossier de ce type
mv: impossible d'évaluer 'passe.kdbx': Aucun fichier ou dossier de ce type

( sorry it's french xD )

Real path : /home/cyber/Mots de passe.kdbx

The mv command don't take the full name and path when the name have space.

**Comment by LukeSmithxyz** [comment]
Should be fixed now in 1260ba7da487785342f05d1fce8d1d5e8b40a343.

**Comment by Cyberdr3am** [comment]
Yes all fixed. Thx for your time.
