### ISSUE TITLE
Some issues 

### ISSUE THREAD

**Issue by slavan128** [LukeSmithxyz/voidrice#651]
Hello, I have some issues

1. some characters didnt show propperly with stock font (maybe some tutorial how to make it just werk again?)
![image](https://user-images.githubusercontent.com/65496058/83014053-871c0180-a00d-11ea-9f07-2dbc48b37671.png)

2. DWM key bind is not working on another than EN and DE keyboard  (I use SK - slovak, where on english is "1234567890" on slovak is "+ľščťžýáíé")
3. DWMblock show time in 12 hours format, in europe everyone is using 24 (24 hours use true chads), now I dont know how to fix that (somebody tried that?)
4. not working navigating betwen windows with arrow keys (verry useful on my X200 and X220)
5. some Luke's aliases and scripts are not in LARBS :D (vidstab, langset ..., I have my own)

**Comment by vladdoster** [comment]
I don't think he bound the arrow keys to navigate windows. Use the vim keys. 

Resizing other than `mod + h/l` which moves resizes horizontally. You would need to patch in the ability to to resize windows that are in a layout. However, ifthey are floating then you just click and hold the window + mod and you can resize a floating window.

As for time, you should just be able to go the the script and change the %t that corresponds to the 12 hour time and it can use 24 hour time.

**Comment by LukeSmithxyz** [comment]
Your first problem is probably an issue with your `$LANG` variable. The font has all the characters you need. What is it set to?

If you want to change the date format, shift click on the module and just change it like a true chad.

I don't understand what 5 and 6 mean. Add 4 if you want it. I use left and right arrows to move monitors.

As for using a drastically different keyboard you have two options: rebind the keys yourself or boot your graphical environment with an English binding and then have a startup command switch you to another language.
