### ISSUE TITLE
Old dotfile availability? 

### ISSUE THREAD

**Issue by awelton85** [LukeSmithxyz/voidrice#656]
Something has overwritten either my .profile or my .bash_profile with default settings, and I can't remember everything that was in there. Are there any old (pre-zsh, brave, etc.) dotfiles available anywhere? I logged back in, had to start X manually, and none of my default programs are working with keybinds. My background was also gone. If anyone has any backups I would greatly appreciate them.

**Comment by vladdoster** [comment]
Yes... It's git so just dig through the commits.

**Comment by awelton85** [comment]
OK, thanks. I don't use git so I didn't know where to look.

**Comment by vladdoster** [comment]
> OK, thanks. I don't use git so I didn't know where to look.

No worries. We have all been there :+1:
