### ISSUE TITLE
MPV high res video

### ISSUE THREAD

**Issue by narukeh** [LukeSmithxyz/voidrice#657]
**TLDR: Is there a way to specify MPV which resolution i want?**
I have a x200 and it cant really play videos higher than 720p (maybe 1080p at 30fps).
When i use `,v` in newsboat to play a video with `mpv`, or when i simply do this:
 ```mpv 'https://www.youtube.com/watch?v=LXb3EKWsInQ'``` it chooses a high res. (and it stutters)
i know i can use youtube-dl. tho i dont want to do something like: 
```youtube-dl -f 22 -o - 'https://www.youtube.com/watch?v=LXb3EKWsInQ' | mpv -```
The  `-f 22` is the "best" when you list ```youtube-dl -F 'https://www.youtube.com/watch?v=LXb3EKWsInQ'``` but its not the same as when you just do this ```mpv 'https://www.youtube.com/watch?v=LXb3EKWsInQ'```
 My goal is the modify the newsboat config, and easily watch YT, Bitchute, etc videos, as i dont want to use youtube.

**Comment by narukeh** [comment]
I found ```mpv --ytdl-format=best``` which is basically ```-f 22``` which looks like 480p.
i would like the results of  ```-f 136+140``` tho that has to download first, its not stream-able.

**Comment by LukeSmithxyz** [comment]
This isn't really a question relevant to this respository. You should look up the mpv documentation or ask them.

Although I assume what you're asking for is this: open up `~/.config/mpv/mpv.conf` and add a line like:

```
ytdl-format=bestvideo[height<=?480]+bestaudio/best
```

for example, which never looks for a resolution greater than 480p, etc.
