### ISSUE TITLE
the music script breaks the i3 statusbar

### ISSUE THREAD

**Issue by narukeh** [LukeSmithxyz/voidrice#663]
The statusbar will only show used workspaces and the clock module.
When i comment-out the music module from the i3block/config the statusbar works.
When i comment out line 5, in the music script, which runs the mpdup script, then it also works.
Sometimes when i `killall mpd`  then `mv music music.old`  then refresh i3blocks then `ka mpd` then rename it back, it work , THOUGH sometimes.
And sometimes it will, after a time of not working, then it will work 🤷
EDIT:  running the script in the terminal works correctly as expected.

The same issue has happened a few time with the nettraf, tho i cant replicate it anymore.

**Comment by vladdoster** [comment]
Interested to see resolution of this

**Comment by narukeh** [comment]
i just removed the `mpdup` line (line no.5), and it works as it should.
maybe/probably  it went over my head, but i dont see the need of the mpdup script.  In the filter function, `mpc` i used (which is then sed-ed) , making `mpc idle` obsolete. right???
(anyhow there is `mpd idleloop` so no need for a script to make it a loop, right?)

**Comment by narukeh** [comment]
extra info: after login, my wallpaper wont appear, until i open a terminal or just refresh i3
![pic-full-200530-2022-20](https://user-images.githubusercontent.com/62762955/83336427-945a1a00-a2b3-11ea-9df8-281efea8c13e.png)

**Comment by narukeh** [comment]
a simple ```>/dev/null 2>&1``` solved it 🤦
