### ISSUE TITLE
YouTube video needed

### ISSUE THREAD

**Issue by dr3mro** [LukeSmithxyz/voidrice#667]
Please can you make a step by step video of how to install void linux and then install labs in it ?
That would be great , even In a virtual machine 
Thank you

**Comment by vladdoster** [comment]
Will you email me? I might have a solution for you.

vlad_doster@hms.harvard.edu

**Comment by drake-newell** [comment]
@Platinum_Claridge has a LARBS fork specifically for Void.

**Comment by dr3mro** [comment]
Thank you 🙏
