### ISSUE TITLE
Key repeat speed and delay only apply to the keyboards connected at boot

### ISSUE THREAD

**Issue by Architector4** [LukeSmithxyz/voidrice#668]
In `voidrice/.local/bin/remaps`, key repeat speed and delay are set with `xset r rate 300 50`. However, this command applies that setting only to currently connected keyboards, not any keyboards that are connected after the command is run. Newly connected keyboards get the slow repeat speed that Xorg has by default. Even worse, if a keyboard is disconnected and then connected again, the repeat settings for it are lost too, as if it were a new keyboard.

In my experience, this is better set as a launch parameter for Xorg via `~/.xserverrc`, which replaces `/etc/X11/xinit/xserverrc` if present. Therefore, in my opinion, as a solution, it makes sense to remove that line and create `~/.xserverrc`, then populate it with this modification of the default `xserverrc`:

```
#!/bin/sh
exec /usr/bin/X -ardelay 300 -arinterval 20 -nolisten tcp "$@"
```

Where `-ardelay` sets the delay in milliseconds, and `-arinterval` sets the amount of time between each key repeat, 20ms being equivalent to 50 presses per second set by the current `xset` command.

**Comment by BachoSeven** [comment]
This is related to #212, in the sense that if we can run `remaps` whenever a new keyboard is connected, then this issue is solved. However it might still just make more sense to remove the xset line from `remaps` and do as OP suggest in any case.

**Comment by Architector4** [comment]
ok :(
