### ISSUE TITLE
tsp command

### ISSUE THREAD

**Issue by nycex** [LukeSmithxyz/voidrice#672]
I can see the `tsp` command in a bunch of files here, but I couldn't find it in the arch repos and the aur, nor in your ~/.local/bin folder.
Is that a self-made script that you didn't put in here for some reason or where does it come from?

**Comment by vladdoster** [comment]
> I can see the `tsp` command in a bunch of files here, but I couldn't find it in the arch repos and the aur, nor in your ~/.local/bin folder.
> Is that a self-made script that you didn't put in here for some reason or where does it come from?

tsp stands for taskspooler. 

`man tsp`

**Comment by LukeSmithxyz** [comment]
That's task-spooler, which should be installed by default by the LARBS script. It just queues up commands to be run one after another.

I will say that it's tricky because some distros, I know at least Void, call it just `ts`, so you'd have to change those lines.
