### ISSUE TITLE
Inconsolata is not broken

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#678]
Ok so with major annoyances about Inconsolata being broken, I did some research and realized that it's not  broken, it has been changed to a variable width / weight font, and in order to make it proper we just need to set its width [Inconsolata](https://fonts.google.com/specimen/Inconsola) ... althou Im not sure how to do that :D can you help out figuring this out? Im in love with the font and the current default font sux

**Comment by salman-abedin** [comment]
Give Roboto mono a shot.
I am only mentioning this cause I was in love with inconsolata as well. :)
The closest replacement I have found is Jetbrains and Roboto.

**Comment by salman-abedin** [comment]
In the mean time, I will see if I can fix inconsolata for both of us. :D
Thanks for the tip.

**Comment by salman-abedin** [comment]
FYI, inconsolata is working completely fine with alacritty.

**Comment by kronikpillow** [comment]
yes because alacracitty has a option to adjust font width, but dwm and st don't ... so how do we globally adjust font width?

**Comment by paniash** [comment]
@kronikpillow Just install `nerd-fonts-inconsolata` from the AUR at the moment.
