### ISSUE TITLE
gtk-2.0 settings don't work in ~/.config/gtk-2.0/gtkrc-2.0

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#679]
after playing around with some theme settings i realized that the gtkrc-2.0 settings aren't being respected in its current location and that they have to be in ~/.gtkrc-2.0 to work

result of ~/.config/gtk-2.0/gtkrc-2.0 =
![pic-full-200601-2011-18](https://user-images.githubusercontent.com/48420193/83526468-c43d3380-a4e6-11ea-91f1-d60aff4a4ade.png)

result of ~/.gtkrc-2.0 =
![pic-full-200601-2005-40](https://user-images.githubusercontent.com/48420193/83526560-e46cf280-a4e6-11ea-9d42-5e742e2976e7.png)

**Comment by zenny** [comment]
> after playing around with some theme settings i realized that the gtkrc-2.0 settings aren't being respected in its current location and that they have to be in ~/.gtkrc-2.0 to work
> 
> result of ~/.config/gtk-2.0/gtkrc-2.0 =
> ![pic-full-200601-2011-18](https://user-images.githubusercontent.com/48420193/83526468-c43d3380-a4e6-11ea-91f1-d60aff4a4ade.png)
> 
> result of ~/.gtkrc-2.0 =
> ![pic-full-200601-2005-40](https://user-images.githubusercontent.com/48420193/83526560-e46cf280-a4e6-11ea-9d42-5e742e2976e7.png)

@kronikpillow , if you look at `~/.config/gtk-2.0/gtkrc-2.0` there is an `include` file statement to specify any modifications to `~/.gtkrc-2.0.mine` file. Just `touch` a file with the name and append your configs, imho.

Cheers, and stay safe,
/z

**Comment by kronikpillow** [comment]
it still doesn't respect it

**Comment by zenny** [comment]
> it still doesn't respect it

Else, do this:

```
rm ~/.gtkrc-20.mine
ln -s ~/.config/gtk-20/gtkrc-2.0 ~/.gtkrc-2.0
``
logout and login to see the changes.

if not, do you have anything in the `.Xresources`?

**Comment by f380cedric** [comment]
GTK2.0 check for rc in `~/.gtkrc-2.0` by default.
It can be changed by setting the environment variable `GTK2_RC_FILES=<file_location>`.
That is why there is `export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"` in `.{z,}profile` on this project.

It seems that it is not set in your case.
Can you `echo $GTK2_RC_FILES` in your terminal to check if it is correctly set?
Are other GTK applications not following your config or just pinentry?
Is running your applications from a terminal using `GTK2_RC_FILES=<file_location> command` solving the issue?

**Comment by kronikpillow** [comment]
❯ echo $GTK2_RC_FILES
/home/kronikpillow/.config/gtk-2.0/gtkrc-2.0

the export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0" is set in my case, but pinentry doesn't respect it, i'm not sure if other's don't respect it due to not really knowing what other gtk 2.0 apps I have :D sorry for the late reply, I was locked out of linux for months due changing graphics card but now im back

**Comment by LukeSmithxyz** [comment]
Looks like pinentry doesn't have a dark theme on my machine either. I've never really paid attention because I don't really have any gtk2 programs.
