### ISSUE TITLE
libxft and libxft-bgra conflict

### ISSUE THREAD

**Issue by Abhishek-Deshmukh** [LukeSmithxyz/voidrice#690]
I already have a user with i3 version of larbs installed.
Backstory: After seeing luke's video on dwm i wanted to give it a try so went ahead and pulled down larbs.sh and installed with a new user this time with dwm.

Installation completed with no issues. But after loggin in, it waits for about 10s and then
````
IMPORTANT: note that `libxft-bgra` must be installed for this build of dwm.
Please run :
    yay -S libxft-bgra
and replace with `libxft`
````
So naturally I tried to uninstall libxft but it seems like it a depedency of a lot programs including `dmenu` and `pango`.
I wanna move to `dwm` but have been using `i3` for a lot of time, so need to have both on my system for sometime to make a decision.

Thanks in advance.

**Comment by Abhishek-Deshmukh** [comment]
Okay so I figured that if I can uninstall libxft with `-Rdd` instead of just `-R`.
But then when installing `libxft-bgra` with `yay -S libxft-bgra` I end up with a big error which I am not abel to copy paste here, but the gist:
````
error: Server dies not allow requests for unadvertised objects 7808...............47fc
=>ERROR: A faliure occured in prepare().
    Aborting...
Error making: libxft-bra
````

**Comment by dschense** [comment]
Duplicated issue:
https://github.com/LukeSmithxyz/voidrice/issues/610

Solution:
https://github.com/LukeSmithxyz/voidrice/issues/610#issuecomment-639343794

**Comment by Abhishek-Deshmukh** [comment]
@dschense thank you for your response, but that isn't the solution it's the same problem I ran into.
This thread as it is a duplicate but hasan't been solved yet.
Thank you.

**Comment by dschense** [comment]
The second link is the solution for the installation of the package. You have to modify the package before installation with yay.

**Comment by Abhishek-Deshmukh** [comment]
I'm sorry but can you check the link again.
I don't know what to modify in the package before installationg with yay.
Can you give more details 
thank you

**Comment by Sife-ops** [comment]
Running yay libxft-bgra again and selecting cleanBuild all fixed this for me:
`  
  1 libxft-bgra                              (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
`
