### ISSUE TITLE
Style Xresources are not applied immediately

### ISSUE THREAD

**Issue by d351d3r** [LukeSmithxyz/voidrice#697]
I added Xresources with a Nord theme, uncommented a line in .xprofile xrdb ${XDG_CONFIG_HOME: - $HOME/. config}/Xresources and it doesn't work. And how else to copy to Nvim? Alt+C, Ctrl+C, Ctrl+Shift+C don't work

P.S. In other words, when I log in, I need to click Meta+Shift+Q and select "renew dwm" to change my dpi and theme in Xresources.

**Comment by narukeh** [comment]
try moving that line up and down the ~/.xprofile file.
also try uninstalling pywal.

**Comment by d351d3r** [comment]
> try moving that line up and down the ~/.xprofile file.
> also try uninstalling pywal.

I tried it, it didn't help.

**Comment by zenny** [comment]
> I added Xresources with a Nord theme, uncommented a line in .xprofile xrdb ${XDG_CONFIG_HOME: - $HOME/. config}/Xresources and it doesn't work. And how else to copy to Nvim? Alt+C, Ctrl+C, Ctrl+Shift+C don't work
> 
> P.S. In other words, when I log in, I need to click Meta+Shift+Q and select "renew dwm" to change my dpi and theme in Xresources.

After making changes, did you reloaded X resouces db by running:

`xrdb $HOME/.config/Xresources`

Else, uncomment the following line and you may be good to go.

https://github.com/LukeSmithxyz/voidrice/blob/b1d1446325fe483be0078c8932f5eb99fd98ea2b/.xprofile#L13

Hope this helps.

Cheers,

**Comment by d351d3r** [comment]
It didn't help

**Comment by d351d3r** [comment]
Almost solved the problem by adding the monitor dimensions to xorg.conf, as well as `xrandr --120 dpi &` in ~/. xinitrc

**Comment by joalcava** [comment]
@d351d3r Could you elaborate on how you resolved the issue? I'm facing the same problems but haven't been able to solve it.
