### ISSUE TITLE
Black Screen after startx on fresh install

### ISSUE THREAD

**Issue by framedr0p** [LukeSmithxyz/voidrice#708]
Hi Luke!
I get a blackscreen after login and startx. I even can't switch to an other tty.
I ran the script on a MacBoook Pro 10,x (2012 Retina) 
After startx the only thing i can do is press the powerbutton to poweroff.

**Comment by cr-y** [comment]
I see you closed this. Did you find a fix? I'm running into the same issue.
After logging into my user account it runs X automatically, freezes and I then can't do anything but reboot my system.

**Comment by drake-newell** [comment]
@cr-y What's the error message?

**Comment by framedr0p** [comment]
Do u have the same Hardware? In my case the it was a driver/hardware problem.
