### ISSUE TITLE
What is texclear?

### ISSUE THREAD

**Issue by Daenarii** [LukeSmithxyz/voidrice#71]
https://github.com/LukeSmithxyz/voidrice/blob/074e54caf650ea5a4915198a45d4832808af43e0/.vimrc#L115-L116
Am I missing some program here?

**Comment by CecileGS** [comment]
I don't claim to be competent or knowledgeable when it comes to Vim scripting, but my software dev intuition is telling me that what this script does is delete all the temporary garbage files produced by LaTeX while you're editing in Vim? But yeah idk, I don't think I ever needed or used that part of the `.vimrc` myself.

**Comment by LukeSmithxyz** [comment]
It's a build-file cleanup script I neglected to push. It's up now in the scripts directory.

**Comment by Daenarii** [comment]
It almost looks similar to https://github.com/LukeSmithxyz/voidrice/blob/master/.scripts/clear.sh
I haven't seen any usage of `clear.sh` anywhere. Could that be a duplicate?

**Comment by LukeSmithxyz** [comment]
Ah yeah. That's an old duplicate. I guess I renamed it in my own dotfiles and forgot to rename it in the repo.
