### ISSUE TITLE
Displayselect not working

### ISSUE THREAD

**Issue by pniedzwiedzinski** [LukeSmithxyz/voidrice#710]
Displayselect script stopped working for me, it was complaining about "invalid argument" but everything seems fine. So I played with it a little bit and removed quotes:

```
	xrandr --output "$1" --auto --scale 1.0x1.0 $(echo "$allposs" | grep -v "$1" | awk '{print "--output", $1, "--off"}' | paste -sd ' ')
```

Original:
https://github.com/LukeSmithxyz/voidrice/blob/2668bff3172bdb85c312c8edcb257130b4b53746/.local/bin/displayselect#L56

Is it only my `xrandr` complaining about it? Maybe newer version reads argument differently and needs them to be separated. Anyway if somebody has similar problem here's the solution 👆

**Comment by BachoSeven** [comment]
too much shellcheck ahahah. Thanks for the workaround!

**Comment by pniedzwiedzinski** [comment]
Maybe I’ll submit a PR with that?

**Comment by LukeSmithxyz** [comment]
fixed
