### ISSUE TITLE
xrdp Not Working

### ISSUE THREAD

**Issue by rescenic** [LukeSmithxyz/voidrice#711]
I installed xrdp to remote it via another machine.
I configured it like these:
```
sudo pacman -S xrdp
sudo cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
sudo sed -i 's/max_bpp=32/#max_bpp=32\nmax_bpp=128/g' /etc/xrdp/xrdp.ini
sudo sed -i 's/xserverbpp=24/#xserverbpp=24\nxserverbpp=128/g' /etc/xrdp/xrdp.ini
```
then
```
sudo nano /etc/xrdp/startwm.sh
-------------------------------------
#Comment all other lines
startx
```
then
```
nano ~/.xsession
-------------------------------------
startx
```
![help1](https://i.ibb.co/jLY62sg/16-06-2020-839-23-11-45.png)
![help2](https://i.ibb.co/z8sRsFG/16-06-2020-840-23-12-34.png)
startx doesn't work for xrdp. 
Thank you very much for your attention.

**Comment by drake-newell** [comment]
What does this have to do with Luke's rice?

**Comment by vladdoster** [comment]
You probably cant run `startx` for a few reasons...

1. Did you enable x11 forwarding with the SSH flag?
2. Does said server have x11 forwarding enabled?

And I don't quite know about starting a full window manager over ssh. You might try apache guacomole.

**Comment by rescenic** [comment]
xrdp comes with bash env. So default shell for larbs is zsh. Maybe someone has tried it.

**Comment by rescenic** [comment]
[**@vladdoster**](https://github.com/vladdoster) commented on [Jun 17, 2020, 9:59 AM GMT+7](https://github.com/LukeSmithxyz/voidrice/issues/711#issuecomment-645117820 "2020-06-17T02:59:41Z - Replied by Github Reply Comments"):
> You probably cant run `startx` for a few reasons...
> 
> 1.  Did you enable x11 forwarding with the SSH flag?
> 2.  Does said server have x11 forwarding enabled?
> 
> And I don't quite know about starting a full window manager over ssh. You might try apache guacamole.


Ok, I'll try to check those settings. BRB.

**Comment by vladdoster** [comment]
X11 forwarding needs to be enabled on both the client side and the server side.

On the client side, the -X (capital X) option to ssh enables X11 forwarding, and you can make this the default (for all connections or for a specific conection) with ForwardX11 yes in `~/.ssh/config`.

On the server side, X11Forwarding yes must specified in /etc/ssh/sshd_config. Note that the default is no forwarding (some distributions turn it on in their default `/etc/ssh/sshd_config`), and that the user cannot override this setting.

**Comment by rescenic** [comment]
@vladdoster I'll try again in few hours. Thanks for your advice. I'll report it back after I use your advice.
