### ISSUE TITLE
Autocompiling is not working with latex files

### ISSUE THREAD

**Issue by shahid777-py** [LukeSmithxyz/voidrice#712]
I tried Ur compiler script it's very helpful ..but autocomp is not working for tex file  each time I have to give period and c .. this is wired because autocomp with groff working fine..

**Comment by LukeSmithxyz** [comment]
Well, what's the error? What happens?

**Comment by shahid777-py** [comment]
No error Luke ...just can't understand why `entr `
Is not doing this with `tex` files. It doing well with groff and MD files though

**Comment by shahid777-py** [comment]
Also it's a bit of off topic but do u have any script  that notify when charger is plugged .. I'm trying this for some days can't get through it..

Here's my noob script .. and having some problem the notification is keep coming I don't know what if statement to block it and run it again.. 

```bash
while true
	do
	battery=/sys/class/power_supply/BAT0
	capacity=$(cat "$battery"/capacity)
	status=$(cat "$battery"/status)
	[ "$status" = "Charging" ] && dunstify "Charging ⚡$capacity"
	sleep 10
	done
	}

**Comment by vladdoster** [comment]
@shahid777-py  I think it would look something like this.

```
battery=/sys/class/power_supply/BAT0
charging=false

while true
	do
	status=$(cat "$battery"/status)
        if [[ "$status != "Charging" ]]; then
            [ $charging == true ] && [ $charging = false ] && dunstify "Charger unplugged"
        fi
        [ "$status" == "Charging" ] && $charging=true && dunstify "Charging ⚡$capacity"
	sleep 10
	done
	}
```

**Comment by shahid777-py** [comment]
> @shahid777-py I think it would look something like this.
> 
> ```
> battery=/sys/class/power_supply/BAT0
> charging=false
> 
> while true
> 	do
> 	status=$(cat "$battery"/status)
>         if [[ "$status != "Charging" ]]; then
>             [ $charging == true ] && [ $charging = false ] && dunstify "Charger unplugged"
>         fi
>         [ "$status" == "Charging" ] && $charging=true && dunstify "Charging ⚡$capacity"
> 	sleep 10
> 	done
> 	}
> ```

Xinit or Cron job which is good for this job

**Comment by shahid777-py** [comment]
> Well, what's the error? What happens?

Right now I'm using autocompiling within vim not with entr

**Comment by vladdoster** [comment]
```
#!/usr/bin/env bash

battery=/sys/class/power_supply/BAT0
cache=${XDG_CACHE_HOME:-$HOME/.cache}/${0##*/}
notify-send "Started charging notify $cache"

while true; do
        [ -f "$cache" ] && read -r charging < "$cache" || charging="false"
	status=$(cat "$battery"/status)
        if [[ $status == "Discharging" ]] && [[ $charging == "true" ]]; then
                charging="false"
                notify-send "Charger unplugged"
        elif [[ $status == "Charging" ]] && [[ $charging == "false" ]]; then
                charging="true"
                notify-send "Charging ⚡ $capaci"
        elif [[ $status == "Full" ]] && [[ $charging == "true" ]]; then
                charging="false"
                notify-send "Fully charged" 
        fi
        echo $charging > "$cache"
        sleep 10
done
```

**Comment by vladdoster** [comment]
That script fully works as well as tells you when battery is full :)

**Comment by shahid777-py** [comment]
> That script fully works as well as tells you when battery is full :)

Thank you so much...

**Comment by shahid777-py** [comment]
> That script fully works as well as tells you when battery is full :)

The only thing I struggled is to get the charging notification part.. that infinite loop logic really gives me so much headache...

**Comment by vladdoster** [comment]
> > That script fully works as well as tells you when battery is full :)
> 
> The only thing I struggled is to get the charging notification part.. that infinite loop logic really gives me so much headache...

Yes, bash can be quite a headache sometimes. I personally write most scripts in python. Much easier conditional logic imo. 

btw, I tweaked the script to always give you the correct status regardless if it has a file in cache
```
#!/usr/bin/env bash

battery=/sys/class/power_supply/BAT0
cache=${XDG_CACHE_HOME:-$HOME/.cache}/${0##*/}
notify-send "Started charging notify!"

while true; do
        status=$(cat "$battery"/status)
        [ -f "$cache" ] && read -r charging < "$cache" || [ $status != "Charging" ] && charging="false" || charging="true"
        capacity=$(cat "$battery"/capacity)
        if [[ $status == "Discharging" ]] && [[ $charging == "true" ]]; then
                charging="false"
                notify-send "Charger unplugged"
        elif [[ $status == "Charging" ]] && [[ $charging == "false" ]]; then
                charging="true"
                notify-send "Charging ⚡ $capacity%"
        elif [[ $status == "Full" ]] && [[ $charging == "true" ]]; then
                charging="false"
                notify-send "Fully charged" 
        fi
        echo $charging > "$cache"
        sleep 10
done
```

**Comment by shahid777-py** [comment]
> > > That script fully works as well as tells you when battery is full :)
> > 
> > 
> > The only thing I struggled is to get the charging notification part.. that infinite loop logic really gives me so much headache...
> 
> Yes, bash can be quite a headache sometimes. I personally write most scripts in python. Much easier conditional logic imo.
> 
> btw, I tweaked the script to always give you the correct status regardless if it has a file in cache
> 
> ```
> #!/usr/bin/env bash
> 
> battery=/sys/class/power_supply/BAT0
> cache=${XDG_CACHE_HOME:-$HOME/.cache}/${0##*/}
> notify-send "Started charging notify!"
> 
> while true; do
>         status=$(cat "$battery"/status)
>         [ -f "$cache" ] && read -r charging < "$cache" || charging="false"
>         capacity=$(cat "$battery"/capacity)
>         if [[ $status == "Discharging" ]] && [[ $charging == "true" ]]; then
>                 charging="false"
>                 notify-send "Charger unplugged"
>         elif [[ $status == "Charging" ]] && [[ $charging == "false" ]]; then
>                 charging="true"
>                 notify-send "Charging ⚡ $capacity%"
>         elif [[ $status == "Full" ]] && [[ $charging == "true" ]]; then
>                 charging="false"
>                 notify-send "Fully charged" 
>         fi
>         echo $charging > "$cache"
>         sleep 10
> done
> ```

Really I'm also a good at python than bash.. but I need to learn to use the system and os modules in order to use the arguments and stuffs .. it's easier to access in bash but tedious in manipulating...
Manipulation is easy in python but u need to learn a lot of modules..

**Comment by shahid777-py** [comment]
> @shahid777-py I think it would look something like this.
> 
> ```
> battery=/sys/class/power_supply/BAT0
> charging=false
> 
> while true
> 	do
> 	status=$(cat "$battery"/status)
>         if [[ "$status != "Charging" ]]; then
>             [ $charging == true ] && [ $charging = false ] && dunstify "Charger unplugged"
>         fi
>         [ "$status" == "Charging" ] && $charging=true && dunstify "Charging ⚡$capacity"
> 	sleep 10
> 	done
> 	}
> ```

No dude this script is also having the same issue that I have... The notification keep coming.. I want the notification once and when I unplug charger then charging again  then it should give me notification
