### ISSUE TITLE
Huge Emoji on suckless applications

### ISSUE THREAD

**Issue by saandre15** [LukeSmithxyz/voidrice#713]
Suckless programs have issues scaling colored emoji properly. All of the emojis are too large and I can't find any centralized config file to change the default scaling. Other applications such as firefox don't seem to have any issues scaling emoji properly.

**Comment by LukeSmithxyz** [comment]
It's an issue with your default monospace font or your font config. My
suckless builds just read whatever your default mono is.

What distribution/DE did you have installed beforehand?
On 20/06/18 04:39PM, saandre15 wrote:
> Suckless programs have issues scaling colored emoji properly. All of the emojis are too large and I can't find any centralized config file to change the default scaling. Other applications such as firefox don't seem to have an issue scaling emoji properly.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/voidrice/issues/713

--
https://lukesmith.xyz

**Comment by saandre15** [comment]
> It's an issue with your default monospace font or your font config. My suckless builds just read whatever your default mono is. What distribution/DE did you have installed beforehand?
> […](#)
> On 20/06/18 04:39PM, saandre15 wrote: Suckless programs have issues scaling colored emoji properly. All of the emojis are too large and I can't find any centralized config file to change the default scaling. Other applications such as firefox don't seem to have an issue scaling emoji properly. -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #713
> -- https://lukesmith.xyz

I messed up my arch system, so I just reinstalled the base packages and used the larb script to bootstrap everything again. Everything worked just like before however the emojis on every suckless applications were scaled improperly. I didn't change any config, but the scaling changed.

**Comment by saandre15** [comment]
It was just a bad sys update...
