### ISSUE TITLE
Emoji font not respected by dwm.

### ISSUE THREAD

**Issue by Sife-ops** [LukeSmithxyz/voidrice#714]
dwm bar no longer prefers color emojis using this fonts.conf. Not sure which update broke this.

**Comment by vladdoster** [comment]
I don't think it is related to voidrice. 

What fonts are you using?

**Comment by hoaxdream** [comment]
same here i dont have color emoji in dmenu, what font is need in here? i have noto-fonts-emoji, ttf-joypixels and symbola installed.

**Comment by vladdoster** [comment]
Same, I think it is linked to `noto-fonts` and was hoping @Sife-ops might have some feedback

**Comment by hoaxdream** [comment]
i change to old script and specifiy specific font which is JoyPixels and its working but its not working if i set Noto Color Emoji or JoyPixels in fonts.conf
```
chosen=$(grep -v "#" ~/.local/share/emoji | dmenu -i -l 20 -fn JoyPixels-18)
```

**Comment by hoaxdream** [comment]
btw here is the old script
```
#!/usr/bin/env sh

xclip -h >/dev/null || exit

chosen=$(grep -v "#" ~/.local/share/emoji | dmenu -i -l 20 -fn JoyPixels-18)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' copied to primary." &
```

**Comment by Sife-ops** [comment]
I just figured out the problem.
I had changed the font array in dwm's config.h after I installed, disabling emojis.
It worked before without it, but now you need to include an emoji font in the dwm font array.

**Comment by vladdoster** [comment]
@Sife-ops thank you so much for sharing. Hope I didn't wake you! (5am on east coast)

**Comment by hoaxdream** [comment]
confirm working. thanks @Sife-ops

**Comment by Sife-ops** [comment]
I'm a literal moron for not noticing this and am embarrassed for even opening a thread here. Please, don't thank me.

**Comment by vladdoster** [comment]
@Sife-ops where exactly did you add the emojis array? I checked your dwm config.def.h

**Comment by Sife-ops** [comment]
Okay, I just updated it, but you would find the solution if you just checked the font array for LUK's dwm.
