### ISSUE TITLE
Adjust Brightness Issue

### ISSUE THREAD

**Issue by wilfredgithuka** [LukeSmithxyz/voidrice#717]
Hey Luke, am having a small issue in adjusting brightness using the keyboard keys. Dell Laptop Intel card

Also when I run xbacklight -set 50 

am getting the error: No outputs have backlight property error

How do I go around this? Thanks

**Comment by Hurricane14** [comment]
> Hey Luke, am having a small issue in adjusting brightness using the keyboard keys. Dell Laptop Intel card
> 
> Also when I run xbacklight -set 50
> 
> am getting the error: No outputs have backlight property error
> 
> How do I go around this? Thanks

Guess this should help
https://wiki.archlinux.org/index.php/Backlight#xbacklight

**Comment by aoutabounte** [comment]
It might be a systemd issue, when I switched to open-rc `xbacklight` worked 
you can use this instead [https://github.com/haikarainen/light](url)
