### ISSUE TITLE
Issue with opening anything in Manjaro

### ISSUE THREAD

**Issue by athul05** [LukeSmithxyz/voidrice#718]
Hey Luke,
I tried out the wm in my Manjaro kde yesterday and having issue opening anything. Cannot type anything in dmenu(dmenu closes as a start typing) . Mod+enter is not spawning terminal .. The LARBS guide is opening btw.

**Comment by LukeSmithxyz** [comment]
Install `libxft-bgra`.

**Comment by athul05** [comment]
That is already installed at the last step of the script. And I checked again it's installed

**Comment by LukeSmithxyz** [comment]
Oh you know what. You're probably logging via a DM so the `~/.zprofile` file isn't run. Just log in via a tty and it should work.

**Comment by LukeSmithxyz** [comment]
What binds are not working?
On 20/06/22 07:32AM, Logan wrote:
> I logged in via tty and "startx".. this loads up everything perfectly but only a few key bindings are working
> FYI network is not connected also
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/voidrice/issues/718#issuecomment-647556853

--
https://lukesmith.xyz

**Comment by athul05** [comment]
Mainly cannot pull up terminal. And dmenu not allowing me to type also ..it closes as soon as I type

**Comment by vladdoster** [comment]
@athul05 when you say pull up terminal, you cant open it via keybind?

**Comment by athul05** [comment]
> @athul05 when you say pull up terminal, you cant open it via keybind?

Yeah cannot via keybinding and if it try to open via dmenu , the dmenu doesn't allow me to type anything it closes as I start typing

**Comment by mynamedoge** [comment]
Same problem here. Can't even open the terminal from dmenu by scrolling manually. What gives?

**Comment by vladdoster** [comment]
> Same problem here. Can't even open the terminal from dmenu by scrolling manually. What gives?

@mynamedoge Which base version of manjaro did you install larbs from?

**Comment by mynamedoge** [comment]
> > Same problem here. Can't even open the terminal from dmenu by scrolling manually. What gives?
> 
> @mynamedoge Which base version of manjaro did you install larbs from?

KDE version

**Comment by vladdoster** [comment]
> > > Same problem here. Can't even open the terminal from dmenu by scrolling manually. What gives?
> > 
> > 
> > @mynamedoge Which base version of manjaro did you install larbs from?
> 
> KDE version

Are any key bindings defined here? It might be creating a conflict...

https://wiki.manjaro.org/index.php?title=Keyboard_Shortcuts

**Comment by mynamedoge** [comment]
I can't see because ever since I've installed LARBS, nothing from the Plasma desktop is accessible. It glitches out the screen to even open a menu and the windows don't appear at all. Rest assured it's a fresh install.

**Comment by vladdoster** [comment]
So LARBS is meant to be run from a fresh arch install. Not on top of a desktop. So it's not really a "fresh install" btw.

**Comment by mynamedoge** [comment]
I literally added LARBS on top of a fresh Manjaro install. Tell me if I'm being dense but that's the clearest I can state it. 
And to reiterate, I cannot open anything i side the Plasma environment. If I open thw settings, it will show up as an icon on the toolbar but the window itself will not appear.

**Comment by vladdoster** [comment]
> I literally added LARBS on top of a fresh Manjaro install. Tell me if I'm being dense but that's the clearest I can state it.
> And to reiterate, I cannot open anything inside the Plasma environment. If I open the settings, it will show up as an icon on the toolbar but the window itself will not appear.

So Manjaro is a distribution of arch. Much like popOS is built from Debian. LARBS is really meant to be installed on a vanilla install of arch Linux. The reason you are running into issues is because Manjaro does a lot of changes to vanilla arch Linux. The reason you're having issues is due to LARBS adding dotfiles that are breaking Manjaro. I'd suggest either installing vanilla arch and then installing larbs. 

Manjaro is arch and you might have installed it on a fresh install, but Manjaro != Vanilla arch.

**Comment by vladdoster** [comment]
Can you try this?

1. Go to a new tty via 
```Alt+F3```

2. Try logging in

**Comment by mynamedoge** [comment]
Gotcha. Has @LukeSmithxyz put out any statement regarding this? Seems like a glaring issue if the github page reads like thus  

![IMG_२०२००७०६_१३१६१९](https://user-images.githubusercontent.com/67851613/86568716-ec5aff00-bf8a-11ea-922f-ea36558a2304.jpg)

**Comment by vladdoster** [comment]
> Gotcha. Has @LukeSmithxyz put out any statement regarding this? Seems like a glaring issue if the github page reads like thus
> 
> ![IMG_२०२००७०६_१३१६१९](https://user-images.githubusercontent.com/67851613/86568716-ec5aff00-bf8a-11ea-922f-ea36558a2304.jpg)

He actually told you what to do in this issue. Login via a virtual terminal (a try) because it looks like the `.zprofile` is not running...

**Comment by mynamedoge** [comment]
That's how I have been logging in so far

**Comment by vladdoster** [comment]
> That's how I have been logging in so far

Mhm... Then yeah im going to say it's KDE bloat cashing issues. 

Try installing the more vanilla version of kde or installing vanilla arch. There really isn't a reason to install Manjaro KDE and then try to install larbs.

Anyways, I'm going to stop commenting on this thread since it really it doesn't seem like any progress is being made.

**Comment by void00r** [comment]
This isnt a problem of distro. I had this same problem too. dmenu and terminal cant open up because st has problem. Try to run st from your DE's terminal and see what errors it gives. In my case the error was mainly of localization. I fixed this problem by adding this line in .profile `export LC_CTYPE="en_GB.utf8"` and it worked.

**Comment by vladdoster** [comment]
> This isnt a problem of distro. I had this same problem too. dmenu and terminal cant open up because st has problem. Try to run st from your DE's terminal and see what errors it gives. In my case the error was mainly of localization. I fixed this problem by adding this line in .profile `export LC_CTYPE="en_GB.utf8"` and it worked.

mhm... So @void00r you are in australia? @mynamedoge might want to adjust this to be your locale

**Comment by athul05** [comment]
> This isnt a problem of distro. I had this same problem too. dmenu and terminal cant open up because st has problem. Try to run st from your DE's terminal and see what errors it gives. In my case the error was mainly of localization. I fixed this problem by adding this line in .profile `export LC_CTYPE="en_GB.utf8"` and it worked.

Wew worked out finally...thanks a ton

**Comment by void00r** [comment]
> Wew worked out finally...thanks a ton

Glad it did work out. Locales set by calamaries didnt work out good for me so i had to reset them from terminal. Also you might want to have a look at your .xsessionserrors file and solve other error accordingly.

**Comment by vladdoster** [comment]
Might be worth adding this to a list of possible issues. Hrmmm...

**Comment by void00r** [comment]
Ok so I finally figured it out, Actually you dont need to put that line in ~/.profile 
what you need to do is 
Goto your `/etc/locale.conf` file 
And add this new type which must be missing there
`LC_CTYPE=en_US.UTF-8` (set according to your region.)
And then run `sudo locale-gen` 

This will fix for every program.

You might also want to add this other types too if they already are not present there. 

```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
```
