### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ffff8** [LukeSmithxyz/voidrice#728]
1-Capslock doesn't work directly, you should fix keyboard default values ​​like this

I couldn't see anything else for now, I can update here again, thanks.

**Comment by vladdoster** [comment]
Like what? You don't link to anything. 

You could fix it and submit a PR?

**Comment by AlexSyssoyev** [comment]
Capslock is mapped as esc and if you hold it super key if that is what you mean.
