### ISSUE TITLE
Fonts are too thin

### ISSUE THREAD

**Issue by negativeExponent** [LukeSmithxyz/voidrice#729]
wonder if this was intentional, but fonts are too thin. installing ttf-dejavu remedies it probably because of the dependencies included (fontconfig  xorg-fonts-encodings  xorg-mkfontscale).

used LARBS to install this on Arch.

**Comment by vladdoster** [comment]
In the future it would help to have a reference of what you see. It's kind of subjective to say fonts are too thin imo.

**Comment by negativeExponent** [comment]
false alarm.

i've misunderstood how fontconfig works and im not familiar with how libertine font looks, hence the confusion. although i've though that .config/fontconfig/font.conf would have override system font settings despite me installing dejavu font, which itself has its own overrides.
