### ISSUE TITLE
Possible missing files from repo ".config/shortcutrc" & ".config/zshnameddirrc"

### ISSUE THREAD

**Issue by BadBrush** [LukeSmithxyz/voidrice#730]
These two files referenced in ".local/bin/shortcuts" and ".config/zsh/.zshrc" are pointing to files not contained in this repo:

".config/shortcutrc"
".config/zshnameddirrc"

.local/bin/shortcuts
```
# Output locations. Unactivated progs should go to /dev/null.
shell_shortcuts="${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc"
zsh_named_dirs="${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc"
```
.config/zsh/.zshrc
```
# Load aliases and shortcuts if existent.
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc"
```

**Comment by vladdoster** [comment]
They aren't missing. They aren't generated on each login or after the files are changed.

See [here](https://github.com/LukeSmithxyz/voidrice/blob/107a99f2743b8412d667c10998677d9ed6ca8fc5/.local/bin/shortcuts#L3)
