### ISSUE TITLE
Make youtube-dl more robust at downloading playlists?

### ISSUE THREAD

**Issue by CecileGS** [LukeSmithxyz/voidrice#74]
When you paste the URL of a playlist with a video that currently is playing in the webpage, I think youtube-dl only downloads said video instead of the entire playlist (which is 99% of the time the intended use case for people such as me). It works perfectly fine and as expected if you paste the _direct_ URL to the playlist however, i.e. there's no video playing on the webpage.

This suggestion can be implemented via some regex magic maybe, or perhaps a new `ytp` alias which can handle this use case. I can do it myself if this issue gets the green light for approval.

**Comment by CecileGS** [comment]
Also while we're at it... Can we make it so that when `yt` and `yta` detects that a given URL is of a playlist, it automatically creates a directory for them to be contained in? 

I just downloaded a couple of playlists, and now I don't know which video belongs in which playlist because they're all scattered everywhere in my `~/Videos` which is a minor nuisance.  =_=

**Comment by dankehidayat** [comment]
How about syncing the playlists to the latest vid without having downloading all the videos all over again?

**Comment by CecileGS** [comment]
Yeah I also like the idea of that @dankehidayat , but IMO the burden of work should be on the developers of `youtube-dl` not on Luke. I would've thought that for a cli program that has been developed and tested for so long, it would have basic convenience features such as that.
