### ISSUE TITLE
Add Image Previews in Vifm using vifmrun

### ISSUE THREAD

**Issue by void00r** [LukeSmithxyz/voidrice#740]
I used a Distrotube script to get images preiview in vifm. In [this](https://www.youtube.com/watch?v=qgxsduCO1pE) video of DT he shows two scripts - vifmimg and vifmrun, vifmimg provide direct previews in vifm whereas you have to run vifmrun manually to get image previews. For this to work you must have Ueberzug installed and scripts folder available in vimfm configs.
. unfortunately for me vifmimg script didnt work but vifmrun did so i use vifmrun and added it to my keybinding. Have a look at vifmrun and vifmimg if it works for you.

[vifmimg.txt](https://github.com/LukeSmithxyz/voidrice/files/4859202/vifmimg.txt)
[vifmrun.txt](https://github.com/LukeSmithxyz/voidrice/files/4859203/vifmrun.txt)

**Comment by narukeh** [comment]
That is implemented in larbs a long time ago. have you looked ad `vu` and `vifmimg` in the larbs repo.
simply run `vu` and you will be able to preview images in the terminal. (press CTRL+w to go in view mode).
please close the issue. ✌

**Comment by void00r** [comment]
Oopsie, I didnt noticed vu but vifmimg didnt worked for me. It appears that vu and vifmrun from dt are same scripts.
