### ISSUE TITLE
Startx failure?

### ISSUE THREAD

**Issue by mynamedoge** [LukeSmithxyz/voidrice#746]
Fresh install of Manjaro
Everything is updated 
Login is glitchy, programs dont open once I'm in

startx gives me the following error
![IMG_20200705_103035_077~2](https://user-images.githubusercontent.com/67851613/86525908-b5152100-beaa-11ea-83af-86aef7e92ba9.jpg)

Screen also starts spazzing out with weird glitches
What might be the deal chief?

**Comment by vladdoster** [comment]
This is not how you run startx. You need to run it from a tty.
