### ISSUE TITLE
dmenumount script with ntfs

### ISSUE THREAD

**Issue by hoaxdream** [LukeSmithxyz/voidrice#751]
hello, does anyone can help me with using the dmenumount script to mount my ntfs external drive? the script is working but when i try to mount the drive it is owned by root and cant write anything but i can copy files. im using arch linux. im also part of users,wheel,disk and storage group. any help is appreciated. thank you

**Comment by vladdoster** [comment]
In the options column add permissions and auto (and probably user or users)

```
nls=iso8859-1,permissions,users,auto
```

| option          | what it does                                                                                                                                       | 
| ---                | ---                                                                                                                                                       | 
| permissions | (NTFS-3G option) Set standard permissions on created files and use standard access control       | 
| auto             | Will be mounted at boot and from mount -a                                                                                       | 
| user             | Allow an ordinary user to mount the filesystem                                                                                  | 
| users           | Allow every user to mount and un-mount the filesystem                                                                    | 


Then change ownership of the filesystem:

```
sudo chown -R <user>:<user> /media/data 
```

**Comment by hoaxdream** [comment]
thank you sir, but from what line can i add this options in the script?

```
getmount() { \
	[ -z "$chosen" ] && exit 1
        # shellcheck disable=SC2086
	mp="$(find $1 2>/dev/null | dmenu -i -p "Type in mount point.")" || exit 1
	[ "$mp" = "" ] && exit 1
	if [ ! -d "$mp" ]; then
		mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?") || exit 1
		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
	fi
	}

mountusb() { \
	chosen="$(echo "$usbdrives" | dmenu -i -p "Mount which drive?")" || exit 1
	chosen="$(echo "$chosen" | awk '{print $1}')"
	sudo -A mount "$chosen" 2>/dev/null && notify-send "💻 USB mounting" "$chosen mounted." && exit 0
	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not ( -path *%s -prune ) ",$3}')
	getmount "/mnt /media /mount /home -maxdepth 5 -type d $alreadymounted"
	partitiontype="$(lsblk -no "fstype" "$chosen")"
	case "$partitiontype" in
		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$mp";;
	esac
	notify-send "💻 USB mounting" "$chosen mounted to $mp."
	}

mountandroid() { \
	chosen="$(echo "$anddrives" | dmenu -i -p "Which Android device?")" || exit 1
	chosen="$(echo "$chosen" | cut -d : -f 1)"
	getmount "$HOME -maxdepth 3 -type d"
        simple-mtpfs --device "$chosen" "$mp"
	echo "OK" | dmenu -i -p "Tap Allow on your phone if it asks for permission and then press enter" || exit 1
	simple-mtpfs --device "$chosen" "$mp"
	notify-send "🤖 Android Mounting" "Android device mounted to $mp."
	}

asktype() { \
	choice="$(printf "USB\\nAndroid" | dmenu -i -p "Mount a USB drive or Android device?")" || exit 1
	case $choice in
		USB) mountusb ;;
		Android) mountandroid ;;
	esac
	}

anddrives=$(simple-mtpfs -l 2>/dev/null)
usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep 'part\|rom' | awk '$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usbdrives" ]; then
	[ -z "$anddrives" ] && echo "No USB drive or Android device detected" && exit
	echo "Android device(s) detected."
	mountandroid
else
	if [ -z "$anddrives" ]; then
		echo "USB drive(s) detected."
		mountusb
	else
		echo "Mountable USB drive(s) and Android device(s) detected."
		asktype
	fi
fi
```

**Comment by hoaxdream** [comment]
nvm i fixed it. thanks

**Comment by vladdoster** [comment]
@hoaxdream It is generally a good idea to share the solution in an issue you raise so that others might benefit in the future. Mind sharing what you did?
