### ISSUE TITLE
Newsboat icon disappears from statusbar

### ISSUE THREAD

**Issue by AlexandrosVasileiou** [LukeSmithxyz/voidrice#759]
Fetching newsboat updates while the newsboat client is open, makes the newsboat icon to disappear from the status bar

**Comment by LukeSmithxyz** [comment]
This isn't happening for me.

**Comment by AlexandrosVasileiou** [comment]
Ok thanks Luke, I will further investigate this. Please leave it open for a few days to see if it happens to anyone else :)

**Comment by narukeh** [comment]
(using i3) when i open newsboat, then refresh i3, the newsboat module disappears (which i like) i thought this is so by design.
