### ISSUE TITLE
How to return to default color scheme and turn off pywal?

### ISSUE THREAD

**Issue by manowar20k** [LukeSmithxyz/voidrice#771]
I turned on Pywal at some point and somehow figured out how to make it activate on setbg, but I can't figure out how to turn it off.

**Comment by vladdoster** [comment]
Uninstall it?

**Comment by AlexSyssoyev** [comment]
Yeah uninstall it and delete all pywal's cache folders. (.config/wal and .cache/wal i think)

**Comment by vladdoster** [comment]
> I turned on Pywal at some point and somehow figured out how to make it activate on setbg, but I can't figure out how to turn it off.

Also I don't think you figured out how to run in on set_bg, it's in the setbg script.

**Comment by narukeh** [comment]
`xrdb -remove` it will reset to st's internal colors, or just `xrdb ~cf/Xresources`.
If you want to have pywal installesd but not use it, guess what, you can just not use it, simply comment out the line that starts with `wal...` in the `setbg` script.
@vladdoster  it would be cool if @LukeSmithxyz  would give you, at least, permissions to close some issues/pr.

**Comment by vladdoster** [comment]
@LukeSmithxyz is a [BDFL](https://en.m.wikipedia.org/wiki/Benevolent_dictator_for_life) which I can get behind. I wouldn't want to close an issue before like could get the final word in. It is his creation after all. I just enjoy helping out!
