### ISSUE TITLE
setbg takes close to a minute to run on three different devices

### ISSUE THREAD

**Issue by themaster567** [LukeSmithxyz/voidrice#777]
It's very strange, as it wasn't being slow before. I must have did _something,_ but I don't know what. I haven't installed anything that would have messed with changing wallpapers. Running wal alone works extremely quickly, so that rules out that part of the script as well as xwallpaper since that's executed after wal. My guess is that it's happening in one of the two if statements, though it's equally slow when given a directory or a file. I've attached setbg below,  just in case something is just broken/out of date.
[setbg.zip](https://github.com/LukeSmithxyz/voidrice/files/4988510/setbg.zip)

EDIT: I've tried commenting each of the ifs and so it only has one and it runs at the same slowness regardless of which I'm using, so I don't think they're the problem either. Now I have no idea what could be the problem.

**Comment by narukeh** [comment]
well, try to run `xwallpaper --zoom file.jpg` on a picture, see what happens. if you have low specs, and try to set a 4k/8k picture, dont be surprised that it will take a bit. if thats not the case, (so you have no problem with `wal` like u mentioned, nor with `xwallpaper` ), then it must be dunst, try uninstalling it or copy the original config.

**Comment by themaster567** [comment]
I have high specs, so that's definitely not the issue. I have narrowed it down further though. On my gaming laptop, it was still working fast like normal. I kept running the command and then, sure enough, it abruptly started running precisely as slow as on the other systems. Restarts have no effect. I noticed that it was throwing errors that I think mentioned not being able to make some symbolic links, but those no longer appear now, so I can't screencap them to be sure. It seems like the command itself causes buildup and eventually stops working correctly, resulting in the described behavior.

**Comment by narukeh** [comment]
just why would you use sudo for `setbg`? if using `sudo` in a command/script where `~` appears, it might be interpreted as `/root/` and not as `/home/$USER/`, so thats probably the reason for the failing symlink. I have not been able to reproduce your problem.
are you using a specific file manager or are you running setbg on a file in the terminal (`setbg ./file.jpg`)? [please try the latter! if it works on the terminal, your file manager is at fault]
If the problem still persists, please delete all your dotfiles (`rm -rf /home/${USER}/.*`) and then install larbs:
```
curl -LO larbs.xyz/larbs.sh
sh larbs.sh
```

**Comment by vladdoster** [comment]
> just why would you use sudo for `setbg`? if using `sudo` in a command/script where `~` appears, it might be interpreted as `/root/` and not as `/home/$USER/`, so thats probably the reason for the failing symlink. I have not been able to reproduce your problem.
> are you using a specific file manager or are you running setbg on a file in the terminal (`setbg ./file.jpg`)? [please try the latter! if it works on the terminal, your file manager is at fault]
> If the problem still persists, please delete all your dotfiles (`rm -rf /home/${USER}/.*`) and then install larbs:
> 
> ```
> curl -LO larbs.xyz/larbs.sh
> sh larbs.sh
> ```

I would really not suggest to delete all your dotfiles. If someone has ssh keys or other program configs it could really bork someone's system.

**Comment by themaster567** [comment]
> just why would you use sudo for `setbg`? if using `sudo` in a command/script where `~` appears, it might be interpreted as `/root/` and not as `/home/$USER/`, so thats probably the reason for the failing symlink. I have not been able to reproduce your problem.
Using without sudo results in it taking pretty much precisely 51 seconds to change the background and theme. With sudo, it's about 3 seconds.
> are you using a specific file manager or are you running setbg on a file in the terminal (`setbg ./file.jpg`)? [please try the latter! if it works on the terminal, your file manager is at fault]
I only run it in a terminal. I don't even use a file manager that has an embedded terminal in the first place. Using the bg shortcut with the lf file manager takes the exact same 51 seconds.

**Comment by narukeh** [comment]
@vladdoster  & @themaster567  by "delete all your dotiles"  i meant to eliminate any variable of ANY bad config.
the same "thing" would be accomplished if you just install larbs with a new user(-name).
so if the problem still exist in the new user, then its a larbs problem i guess. if not, then its a "thou" problem.😅
you must have poked around with chmod, but i can only guess... this **might** help then:
```
find /home/$USER/ -type d -exec chmod 750 {} \;
find /home/$USER/ -type f -exec chmod 640 {} \;
find /home/$USER/.local/bin/ -type f -exec chmod 755 {} \;
```

**Comment by themaster567** [comment]
Unfortunately, the command didn't really help at all. It threw a couple errors on some inconsequential stuff that I don't think matters:
`chmod: changing permissions of '/home/themaster567/.config/spacefm/session-prior': Operation not permitted
chmod: changing permissions of '/home/themaster567/.local/src/dwm/drw.o': Operation not permitted
chmod: changing permissions of '/home/themaster567/.local/src/dwm/dwm': Operation not permitted
chmod: changing permissions of '/home/themaster567/.local/src/dwm/dwm.o': Operation not permitted
chmod: changing permissions of '/home/themaster567/.local/src/dwm/util.o': Operation not permitted
chmod: changing permissions of '/home/themaster567/.local/src/dwmblocks/dwmblocks.o': Operation not permitted
chmod: changing permissions of '/home/themaster567/.local/src/dwmblocks/dwmblocks': Operation not permitted
find: ‘/home/themaster567/zsh-command-time’: Permission denied
`
Setbg still took precisely 51 seconds, never more than one second more or less. All I know is that running it as sudo has it work in under a second.

**Comment by narukeh** [comment]
- @themaster567   bruh, when it says `Operation not permitted`, guess what, you gotta use sudo, (or be root).
- And did you try installing larbs to a new user, you did not respond to that.

**Comment by themaster567** [comment]
>     * @themaster567   bruh, when it says `Operation not permitted`, guess what, you gotta use sudo, (or be root).
> 
>     * And did you try installing larbs to a new user, you did not respond to that.

_Bruh,_ I would appreciate if you didn't assume I was an idiot. I ran it with sudo and those were the errors that came up. As for your second question, no I have not. As for your second question, I have not. I don't think I want to get further help from you if this is the attitude you're going to give me, so I'm just going to keep using my workaround and close the topic.

**Comment by vladdoster** [comment]
@themaster567 who owns those files? Why don't you just chown it?
