### ISSUE TITLE
"is $DISPLAY set?"; "Can't find :7" (which is where the display is set)

### ISSUE THREAD

**Issue by 26-55-87-BuddhiLW** [LukeSmithxyz/voidrice#778]
When I try to use mod+F3, and upon selecting HDMI-1-0, the Xserver restart with an error: "is $DISPLAY set?"; "Can't find :7" (which is where the display is set).

I have tried to set the $DISPLAY manually. But, I am being unsuccessful.

Help?!

(I have tested 2 PC monitors and a TV set; it's not the hardware; they also work with other computers)

I'm on Artix.

**Comment by vladdoster** [comment]
@26-55-87-BuddhiLW 

What is output of

```
$ lspci | grep -E 'VGA|3D'
$ dmesg
```

**Comment by AlexSyssoyev** [comment]
I don't know if this would help but I've noticed that runit does not clean the /tmp by default so the display keeps bulding up from boot to boot and the number changes constantly. What would be the output of ```ls /tmp/.X11-unix/```

**Comment by 26-55-87-BuddhiLW** [comment]
Sorry the late reply, but I'm currently without the access to external monitors. 

When I get back to work, maybe in 30 days, I would appreciate your help. I will, then, post the results of these output. 

Thank you, in advance

**Comment by 26-55-87-BuddhiLW** [comment]
My xinit:

"#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/config/xprofile because
# that file is run automatically if someone uses a display manager (login
# screen) and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

# export STATUSBAR="i3blocks" # Uncomment this line when using i3.

. ~/.xprofile

# Your default LARBS WM is determined in your `~/.profile` on login.  Here we
# run the proper command to run when the graphical environment starts.

# Comment/uncomment these lines depending on what wm you want to use. Also
# check the i3blocks line above.
ssh-agent dwm
# ssh-agent i3"

lspci | grep -E 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 630 (Mobile)
01:00.0 VGA compatible controller: NVIDIA Corporation GP107M [GeForce GTX 1050 3 GB Max-Q] (rev a1)
