### ISSUE TITLE
Divergence across different desktops

### ISSUE THREAD

**Issue by MYDavoodeh** [LukeSmithxyz/voidrice#780]
I just switched to DWM and realized that shortcuts are different in here and there.
It almost felt like i3 was "left behind" and this morning I saw in YT that Luke said he has left it for about one year now :|

I was thinking about "syncing" all the 3 desktop shortcuts and settings with DWM ones...

This requires more scripts... I think LMC needs to get back again.

What do you guys think? Has this matter been addressed/discussed?

Is it even the right place to talk about it?

**Comment by vladdoster** [comment]
I think you are forgetting that at the end of the day these are Lukes personal dotfiles. From what I can tell and has been stated in videos, he has no plans on returning to either i3 or bspwm. He has even taken i3 out of progs.csv in larbs. I dont think this would be worthwhile effort as i3 is still included in voidrice, but not currently an option to install from LARBS. As I see it, it is on support only, no new features being added for it.

There are alot of things in DWM that can't be replicated in i3 (layouts, tags, etc.) which I think would make this nearly impossible.

**Comment by MYDavoodeh** [comment]
Yeap that's what I think as well. I know he won't return.

But the files are there... So I'm just gonna go ahead and do it.

**Comment by LukeSmithxyz** [comment]
The only reason the i3 or ranger dotfiles exist in this repository is that there are people who want them and do not know how to look into a git history. If I had my say, I'd just remove them and all the other old junk.

I have no intention of keeping any of this stuff up to date. I accept PR's for fixes in them, but I have not intention of ever using i3 again and I can't be bother to maintain for software I don't use.
