### ISSUE TITLE
Lack of wiki and CONTRIBUTE guide

### ISSUE THREAD

**Issue by MYDavoodeh** [LukeSmithxyz/voidrice#783]
Hi, I've been thinking that isn't a Wiki more efficient and easier to manage and view rather than a .mom file or a ton of "getkey" scripts?

At least they can co-exist... So what's the harm in a wiki?

Also, I am really interested in the project and wanna contribute... But it seems there is no clear explanation on how to contribute and what's the project about (is it just what Luke wants or it seeks a certain goal other than "just naturalness"?).

**Comment by vladdoster** [comment]
A wiki? A .mom should be able to be compiled on almost every Unix system out of the box, it's small, and really not hard to manage.

Most contributions are just fixing things. If you think there is a better way to do something, fix it, and submit a PR. Comb through open, closed, and merged PRs to get a sense of what people contribute and what hasn't been accepted.

**Comment by MYDavoodeh** [comment]
First off, thank you for your comment @vladdoster! 🙏🏼 
---
That's so much implicit information. I still believe it's better written than "go search for something" method.

I suggest the Wiki method over .mom file for one particular reason: Modularity.
Let's assume I just use one of the files from this repo or I don't use LARBS and I am newbie who keeps spamming Mod+F1 and wonders why nothing happens (no Zathura)...
In that case, I have no other options basically, either I reset everything or go fetch help.
Most of my newbie friends are constantly in my private chat for this sole reason.

Above all: this is not just a project. It's an interconnection of related projects and honestly I think all of them are poorly documented. From dwmblocks to this repo.
Every day I wake up and see that I have a script in my bin folder that I didn't know existed and could help me so much only if I have discovered it earlier or if I wasn't forced to read all the source to make it out.
There is simply not enough documentation on anything.

Pardon me for my poor English

**Comment by MYDavoodeh** [comment]
I mean, Luke could simply enable the "wiki" tab and we would fill it out...
It can co-exist with this method even.

**Comment by mahdisafarian** [comment]
Hello everyone,
its really nice to hear that you have a plane to write a wiki.
because im one of those newbies and yea i know i should go and search my problems in google or whatever.
but how if there is a better documentation about this project and other things...

**Comment by vladdoster** [comment]
Your examples really don't make a compelling argument.

If you don't use larbs them you can't really expect things to work out of the box. 

If you use one of the files from this repo, then you probably know how to use it or else you wouldn't have chosen it.

Why would you need to reset everything? That isn't how you'd approach the problem. You'd go to keybindings, see what the mod + f1 key is trying to run, and try running it to see what it errors on. 

Each file in bin has a description of what it does.  If anything, you should devise a script to pull comments from each file and that could be added to the .mom file.

**Comment by LukeSmithxyz** [comment]
Sounds like one more thing I have to try and keep updated.

If you want to expand the already existing documentation, that's fine, but it is hardly more efficient to make users use a Github website on accessible on the internet when they could use an instantly-loading groff document that already compiles on anything.

**Comment by MYDavoodeh** [comment]
Sure then, so guess we gotta go with the mom file.

So, we achieved this talk and now it's archived in here and nobody will hopefully ask for it again.

Thank you @vladdoster @LukeSmithxyz !
