### ISSUE TITLE
dmenumount and dmenuumount doesn't work.

### ISSUE THREAD

**Issue by ExploXd** [LukeSmithxyz/voidrice#79]
Hi. I'm not again sure if anyone else is experiencing this issue but I do. I can't figure out what's wrong with that. When I execute that it does basically nothing. No terminal output, no dmenu window.

**Comment by LukeSmithxyz** [comment]
Well I should first say that if either script is run where there are no detected mountable/unmountable drives, nothing will happen.

Could you give the output of `lsblk` when you run `dmenumount` with a usb device plugged in?

**Comment by RantSomeWhere** [comment]
Try finding the spot in your i3 config where these scripts are invoked and add ~/.scripts/ before the name of the script

**Comment by ExploXd** [comment]
@RantSomeWhere This isn't an issue.
@LukeSmithxyz `
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 698.7G  0 disk
-sda1   8:1    0 698.7G  0 part /
sdb      8:16   1   7.2G  0 disk
sr0     11:0    1  1024M  0 rom`

**Comment by LukeSmithxyz** [comment]
@RantSomeWhere You have a different problem then: LukeSmithxyz/LARBS#29,

@ExploXd It seems that the scripts are working as intended then. You have `/dev/sdb`, but there are no partitions on this device, thus you can't mount anything. The script isn't supposed to format partitions, just mount them.

Also, note that `dmenuunmount` will not attempt to unmount your `/`, `/home` or `/boot` drives just as the script is intended for formal use and I didn't want someone accidentally unmounting `/home` or something. If you only have one of these mounted, the script will do nothing.

Now `dmenumount` doesn't have the ability right now to detect and mount CD drives. Is that what you're trying to do?

**Comment by ExploXd** [comment]
No, I'm trying to mount a USB device. Maybe issue causing this is USB formatted as FAT.

**Comment by LukeSmithxyz** [comment]
I'd be inclined to say that your drive isn't properly formatted. Either way, all `dmenumount` does is get its possible mountable drives from the output of `lsblk -lp | grep part`.

The problem is that your `/dev/sdb`, if it has a partition, is not detected by lsblk at all.

**Comment by ExploXd** [comment]
fixed
