### ISSUE TITLE
What about making an Iso ?

### ISSUE THREAD

**Issue by Heliferepo** [LukeSmithxyz/voidrice#790]
Would be actually interested if I potentially make an ISO of LARBS with a tool that has been suspressed called customarch created by adi1090x ?

The iso would support offline installation and and graphical user interface for newbies using abif-master

**Comment by drake-newell** [comment]
Sounds cool

**Comment by ierdna-c** [comment]
I would give it a try!

**Comment by WhispersOfJ** [comment]
I love custom iso's, I would try it and help you in the ways I can

**Comment by unixusermv** [comment]
A base-install of Artix or Arch followed by LARBS is where I begin if I happen to format my system, so an ISO with LARBS would be highly appreciated.

**Comment by Heliferepo** [comment]
I currently working on it I have a lot of stuff to do so I wrote very few lines of code but I might work more on it in 2 or 3 weeks when I will have time

**Comment by void00r** [comment]
Larbs/Linux Os

**Comment by void00r** [comment]
But I would like a choice over init system. Instead of soystemd I love runnit.

**Comment by Heliferepo** [comment]
I close it for now as I school restarted you can still contact me at : Helife#8782
