### ISSUE TITLE
Dwmblocks cpu block (amd)

### ISSUE THREAD

**Issue by pondakun** [LukeSmithxyz/voidrice#793]
the cpu block work on Intel processor but not for amd do you have an amd version?

**Comment by vladdoster** [comment]
Did you run sensors-detect?

**Comment by pondakun** [comment]
[hannibal@Anarchy ~]$ sudo sensors-detect
[sudo] password for hannibal:
# sensors-detect version 3.6.0
# Board: ASRock X470 Gaming K4
# Kernel: 5.8.1-zen1-1-zen x86_64
# Processor: AMD Ryzen 5 2600 Six-Core Processor (23/8/2)

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): y
Module cpuid loaded successfully.
Silicon Integrated Systems SIS5595...                       No
VIA VT82C686 Integrated Sensors...                          No
VIA VT8231 Integrated Sensors...                            No
AMD K8 thermal sensors...                                   No
AMD Family 10h thermal sensors...                           No
AMD Family 11h thermal sensors...                           No
AMD Family 12h and 14h thermal sensors...                   No
AMD Family 15h thermal sensors...                           No
AMD Family 16h thermal sensors...                           No
AMD Family 17h thermal sensors...                           Success!
    (driver `k10temp')
AMD Family 15h power sensors...                             No
AMD Family 16h power sensors...                             No
Hygon Family 18h thermal sensors...                         No
Intel digital thermal sensor...                             No
Intel AMB FB-DIMM thermal sensor...                         No
Intel 5500/5520/X58 thermal sensor...                       No
VIA C7 thermal sensor...                                    No
VIA Nano thermal sensor...                                  No

Some Super I/O chips contain embedded sensors. We have to write to
standard I/O ports to probe them. This is usually safe.
Do you want to scan for Super I/O sensors? (YES/no):

**Comment by pondakun** [comment]
in the laptop tha i have with intel Cpu it run without me doing anything.... in my desktop it stay at 0%
and i don't know what i must do to "fix" it sorry i forgot to say that i am a newbie in linux and in WM (but i try...)
