### ISSUE TITLE
license

### ISSUE THREAD

**Issue by qlcom** [LukeSmithxyz/voidrice#798]
you told that you may switch to OpenBSD if things become worse. Would you then use a license similar to the license used for new code in OpenBSD.

https://cvsweb.openbsd.org/src/share/misc/license.template?rev=HEAD

https://www.openbsd.org/policy.html

**Comment by qlcom** [comment]
you have closed this issue without any answer. I didn't except that.

**Comment by void00r** [comment]
It happens all the time bro dont take it personally.
