### ISSUE TITLE
w3m-img not working properly in st.

### ISSUE THREAD

**Issue by ExploXd** [LukeSmithxyz/voidrice#80]
as the title says, when I'm using Ranger for example and I'm previewing image and then I go to another window it disappears.

**Comment by LukeSmithxyz** [comment]
Yeah, this is known, but it's "not our bug". To repeat blog post I wrote [here](https://lukesmith.xyz/2018.html#new-st-patches-xresources-and-pywal-compatibility) on `st`:

> Well actually, on bugs, there is one little, minor annoyance in the program and that's that ranger image previews disappear when you mouse away from the given window. While there is a patch for st 0.7 which gives it sixel compatibility, due to its *le bloat* it hasn't been accepted into the program, and aside from that, I don't think ranger is built to work with sixel itself either so far. Either way, I still consider st largely "the best", but being able to patch in something like this would make it closer to "perfect". With the features and bindings I have in my build, I find it a little sad when I have to use another terminal.

You can go searching for the issues on `st` and `ranger` about this, but as of yet, this is something that has to be integrated into both programs. As I said above, there is a sixel patch out there for `st` which I can add to my build, but until it's in ranger, it won't make a difference.
