### ISSUE TITLE
What happens to the Void Support?

### ISSUE THREAD

**Issue by RhinoCodes** [LukeSmithxyz/voidrice#803]
Recently watched an old video about Luke adding void support but it’s still only arch ): Does anyone know what happened?

**Comment by vladdoster** [comment]
I am pretty sure it supports void. The extra packages needed are denoted by "V" in progs.csv.

Arch and Void are both Linux and I think if you looked through LARBS that you would see Void is supported.

**Comment by RhinoCodes** [comment]
Oops (:

**Comment by vladdoster** [comment]
@RhinoCodes Please close issue.
