### ISSUE TITLE
Ranger has it's own readme with bindings, should other configs have this?

### ISSUE THREAD

**Issue by Mertzenich** [LukeSmithxyz/voidrice#808]
Today I made a pull request to change the ranger readme name to README.MD so it would display when browsing to that folder on the site. I am not quite sure why this is the only config with a readme and I don't know how necessary, could easily just list VIM keybindings in the main readme and that covers 99% of the binds and the others people could look for documentation.

Possibly would be a good idea to have global bindings/general bindings stored somewhere on the project and then just link to the individual repos/wiki pages per config? Just some thoughts for making things a bit cleaner.

**Comment by MYDavoodeh** [comment]
#783

**Comment by LukeSmithxyz** [comment]
No, most programs simply don't need that level of documentation. The old ranger config is just a little more complex than others. I would rather rely on man or the getkeys script.
