### ISSUE TITLE
Pulseaudio pa_pid_file_create() failed

### ISSUE THREAD

**Issue by a310883** [LukeSmithxyz/voidrice#810]
I was having troubles changing the volume, I tried to run pulsemixer and it shows "failed to connect to pulseaudio connection refused", then I try to run pulseaudio and it produces:
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: pa_pid_file_create() failed.

I solved it removing the lines about pulseaudio in .xprofile. I don't know if I miss any extra configuration about pulseaudio, but anyways I don't use chromium based navigator so I can remove those lines without trouble.

**Comment by vladdoster** [comment]
What lines about pulse audio? You don't link to or show what lines you added?

**Comment by a310883** [comment]
Sorry, I don't really know how to use those functions. I removed the lines in the [.xprofile](https://github.com/LukeSmithxyz/voidrice/blob/master/.xprofile) file. The lines I removed are these
`[ -x /usr/bin/pulseaudio ] &&`
`	! pidof pulseaudio >/dev/null &&`
`	setsid -f pulseaudio --start >/dev/null 2>&1`

**Comment by decantr** [comment]
After update and reboot also had the issue described above with the new
 additions to `.xprofile`, after commenting out evertyhing worked fine.

**Comment by dschense** [comment]
Pulse was also not working for me with a fresh installation. After commenting out these lines @a310883 its working for me without problems.
