### ISSUE TITLE
zathura wont open external links

### ISSUE THREAD

**Issue by goldcoders** [LukeSmithxyz/voidrice#814]
Anyone experiencing this?

I can navigate no problem if the link is within the file itself i.e. on table of contents that is link to a specific page it works
but external links wont work, Its hard to debug this since there is no error , or warning or logs...
Anyone can help me with this?

**Comment by LukeSmithxyz** [comment]
https://github.com/LukeSmithxyz/LARBS/issues/150

**Comment by LukeSmithxyz** [comment]
Actually, I found a fix. Just add `set sandbox none` to the Zathura config.

**Comment by ThomasBucaioni** [comment]
Double click works nowadays
