### ISSUE TITLE
About our own "git server"

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/voidrice#824]
Hey luke and everybody. I connected the domain I got from namecheap to a free server from AWS. So far everything is normal but I couldn't set the subdomain via namecheap, I did it with AWS Route3. Did I do something wrong here

(Stupid namecheap locked my account so I can't setup anything from there)

**Comment by xnul** [comment]
Hey its solved. I'm waiting for you to do this now
https://youtu.be/ju9loeXNVW0?t=716

**Comment by void00r** [comment]
I think AWS is amazon's thing so propritory. And So No
.
