### ISSUE TITLE
No More Polybar Support

### ISSUE THREAD

**Issue by MEXdave1997** [LukeSmithxyz/voidrice#83]
So I was perusing the dot files, and I noticed that the section to use Polybar has been removed. I there a way to edit the i3-config so I can have the option to use it back? I have tried adding the line that used Polybar back into the config, with no success. For reference, the line i refer to is:
```
# Launch Polybar where appropriate:
#exec_always --no-startup-id ~/.scripts/polybar_launch
```

**Comment by LukeSmithxyz** [comment]
All the polybar configs are still there. I just removed that one commented line. If polybar isn't running for you, there may've been a compilation error apart from LARBS.

I just tried it on my machine and it still works. I'll try on another fresh install in a second. Try running `polybar_launch` in the terminal or recompiling polybar.

**Comment by MEXdave1997** [comment]
I'll test it in a few. For reference, I used the polybar-git package that's in the AUR.
