### ISSUE TITLE
Nvim compiler script error when there is spaces on the path

### ISSUE THREAD

**Issue by ltadeu6** [LukeSmithxyz/voidrice#836]
When I compile a LaTeX document using your script from the file directory it works normally, but if I open the doccument from another directory it does'nt works if there is a space on a directory name. It seens that a quotation would help, but I don't know how to map that on init.vim.

It works with:
`:!compile "/path/with space/doc.tex"`
but it give an error with `<leader>c`:
`:!compiler /path/with space/doc.tex
sed: can't read /path/with: No such file or directory`

Sorry for my bad english, I'm not native.

**Comment by LukeSmithxyz** [comment]
I've added quotation marks to the nvim call to prevent this.

Of course I'll say anyway, it's never a good idea to include spaces in any Unix/Linux directory or file.
