### ISSUE TITLE
Some issues with last commit (cleanup)

### ISSUE THREAD

**Issue by AlexSyssoyev** [LukeSmithxyz/voidrice#841]
Hey, i'm glad we got rid of the old stuff. I got a small issue with the commit though, the shortcuts do not work, and my terminal outputs this 
```
run-help=man
which-command=whence
```
Also when i ran manually shortcuts i got two non existent files: bm-files and bm-dirs, i did a `touch bm-files` and got rid of the error but still no shortcuts, what it might be?

Edit: I just found out that zshnameddirrc is still in .config when it should be in shell/

Edit2: after fixing zshnameddirrc apparently the errors mentioned above appear when zsh tries to load shortcutrc on line 15.

Okay i just found out that bm-dirs and bm-files replace the old files and directories. Solvedd

**Comment by AlexSyssoyev** [comment]
Actually no, @LukeSmithxyz we should move zshnameddirrc to shell/

**Comment by katrushenkov** [comment]
> we should move zshnameddirrc to shell/

Yeah, after renaming this and manually 

.config/shell/files -> .config/shell/bm-files 
.config/shell/directorirs -> .config/shell/bm-dirs

everything is ok.

**Comment by danniel3** [comment]
Or what I did, I renamed the variables in .local/bin/shortcuts to the new filenames

**Comment by kronikpillow** [comment]
after doing what you suggested i still get 
run-help=man
which-command=whence

every time i start a terminal

**Comment by danniel3** [comment]
@kronikpillow 

Double-check the following lines in .local/bin/shortcuts
```
dirs="${XDG_CONFIG_HOME:-$HOME/.config}/shell/directories"
files="${XDG_CONFIG_HOME:-$HOME/.config}/shell/files"

shell_shortcuts="${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"
zsh_named_dirs="${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"
```
Then run shortcuts again (to update those shortcut aliases).

**Comment by LukeSmithxyz** [comment]
Should be fixed now. Yes, run the `shortcuts` command to fix the other issue.
