### ISSUE TITLE
Tofu in the status bar

### ISSUE THREAD

**Issue by danniel3** [LukeSmithxyz/voidrice#844]
After the last big update, I'm getting tofu in the status bar's battery and transmission modules. I've tried testing where it's coming in by echoing and eliminating variables in the scripts, but they don't disappear. Then I looked into the emojis themselves, turns out some of them have tofu next to them. 

Just reviewing the dmenu emoji script, these are some of the ones with tofu:
- smiling face
- frowning face
- red heart
- recycling
- telephone

Anyone else having this problem? Know any fixes?

**Comment by danniel3** [comment]
On further investigation, it seems some of the emojis' monospace-ness has collapsed. All the ones with tofu have this spacing problem. 

Guess it's not a voidrice problem, but as this is the only thing I recently changed, I'm curious to know if it's more than just me, and if anyone's found a solution.

![image](https://user-images.githubusercontent.com/51640138/99787460-33f8b680-2b39-11eb-9d3e-b9d7c5af215c.png)

**Comment by Snoozing101** [comment]
Same issue here.

First noticed it after some xorg updates, I thought it might be related to that.

**Comment by ElectricityTaras** [comment]
Same Problem

**Comment by narukeh** [comment]
@danniel3  @Snoozing101  @ElectricityTaras 
would this problem literally be fixed by deleting this <fe0f> ?
then add a `space` in the `battery` script, IF it looks too concatenated.

**Comment by Snoozing101** [comment]
Thanks @narukeh that fixed it for me in the status bar.

**Comment by narukeh** [comment]
@danniel3  dont forget to close the issue if it is resolved
(look at this if you missed it:  https://github.com/LukeSmithxyz/voidrice/issues/844#issuecomment-735734194 )
