### ISSUE TITLE
pulseaudio runi fix breaks pulseaudio on Arch

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#855]
The latest addition to xprofile that you talked about on your video that fixed launching pulseaudio on artix, completely breaks pulseaudio on arch and the system boots with sound disabled, considering that most users are probably arch based, maybe the option should be commented out and added a comment to uncomment it if on artix

**Comment by LukeSmithxyz** [comment]
Strange since it shouldn't be starting Pulseaudio if it is already running. Does b30ca735b60e5df2c30ab4eb7a6fe0eb0e7ecab7 fix the problem?

If not, I might just remove this from voidrice and have Artix machines add the line after the LARBS script runs.

**Comment by anntnzrb** [comment]
[**Void Linux**]
 I appended `pulseaudio -k ; pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1` to my `~/.xprofile` and now I do have audio upon starting `X` on `chromium` (didn't have before this line); on the other hand, I still do not have audio (at all) on `qutebrowser`. Doesn't even show on `pulsemixer`, just reporting from another `runit` system.

**Comment by LukeSmithxyz** [comment]
I suppose another option for compatibility with non-runit systems would be to remove `--start`, as the documentation seems to indicate in that case Pulse only tries to start without that if not already running.

**Comment by kronikpillow** [comment]
the latest commit made it work :+1:
