### ISSUE TITLE
extend kbselect to include variants

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#857]
can someone somehow extend the kbselect script to include keyboard variants? for example, the current kbselect script offers Serbian (rs) as a language, but only sets the default Cyrillic font, while in reality nobody really uses Cyrillic especially not on computers (well at least not in Serbia), and most of us use Serbian - latin ... I'v been trying to modify it but unsuccesful

**Comment by Davoodeh** [comment]
I have implemented this "my way" in my fork using a script I wrote ([kblayout](https://raw.githubusercontent.com/MYDavoodeh/dotfiles/renew/.local/bin/kblayout))
Take a look that may help you. Then you can simply modify your [kbselect like this](https://raw.githubusercontent.com/MYDavoodeh/dotfiles/renew/.local/bin/statusbar/kbselect) to work with your kblayout.

You can use it like `kblayout set $lang-$variant` or `kblayout variants` to see your normal dmenu language select (`kblayout list`) + an additional prompt for variant selection.

**Comment by narukeh** [comment]
Have you tried the variant with altgr
```bash
setxkbmap -option caps:super -variant altgr-intl
```
I, on en_US keyboard, with the right _ALT_ can write stuff like __óöüúéëç__

**Comment by kronikpillow** [comment]
yeah sorry for the late reply on this topic but I have no clue what @Davoodeh and @narukeh have suggested me to do ... I am not a scripter and I'm not versatile in writing bash/zsh/dmenu or any other kind of scripts, all I know is that when I click the keyboard layout module in luke's dwmblocks I get a list of 30-40-50 layouts? and none are which I need ... I need the script to have EN US, RS latin and RS Cyrillic fonts
