### ISSUE TITLE
$EDITOR locale 

### ISSUE THREAD

**Issue by BuddhiLW** [LukeSmithxyz/voidrice#859]
I can't locate where $EDITOR has been defined.

I recently rerun the script, and I don't remember where these configurations are located. 

I appreciate if anyone could tell me. Plus, do you know of a command which I can use to locate the file in which an environment variable has been altered, in general?

**Comment by LukeSmithxyz** [comment]
Most environmental variables are set in the zprofile/profile file.

It is not possible to change environmental variables set in the profile
file after login until you manually reassign them at each new window.
They will still not propogate to other subprocesses.

**Comment by BuddhiLW** [comment]
Thank you for the information.

It is resolved.
