### ISSUE TITLE
Replace if stmt with case stmt

### ISSUE THREAD

**Issue by BrandonStaab** [LukeSmithxyz/voidrice#867]
This if stmt is complex.
https://github.com/LukeSmithxyz/voidrice/blob/c3eefd7a683ad764f38fc39f1bf4aad97f78d767/.config/zsh/.zshrc#L38-L49

It can be rewritten as:
```zsh
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
```
The following lines aren't taken into account because I was not able to notice any functional difference.  If there is a reason for them I think it should be documented.
https://github.com/LukeSmithxyz/voidrice/blob/c3eefd7a683ad764f38fc39f1bf4aad97f78d767/.config/zsh/.zshrc#L45-L46

**Comment by LukeSmithxyz** [comment]
Yeah I the original is obviously copied and pasted from somewhere. Whoever wrote it just wrote it how they thought it out logically in their head rather than testing things efficiently. Lol I suppose I can't blame them since I just copied and pasted it. I'll make this change.
