### ISSUE TITLE
Convert lfcd into script

### ISSUE THREAD

**Issue by DusanLesan** [LukeSmithxyz/voidrice#868]
I see lf mapped in dwm and lfcd() in a profile.

I think it would be more convenient to use lfcd as a script and map that to dwm.

My implementation:
```
#!/bin/sh

#tmp="$(mktemp)" && lf -last-dir-path="$tmp" "$@" | [ -f "$tmp" ] && dir="$(cat "$tmp")" && rm -f "$tmp" >/dev/null && [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"

tmp="$(mktemp)" && \
lf -last-dir-path="$tmp" "$@" && \
if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp" >/dev/null
    if [ -d "$dir" ]; then
        if [ "$dir" != "$(pwd)" ]; then
            cd "$dir"
        fi
    fi
fi

$SHELL

```
Then just map SHCMD(TERMINAL " -e lfcd") in dwm.

**Comment by LukeSmithxyz** [comment]
What would be the point of binding that in dwm? It only makes sense when
you're in a shell and can actually cd. Running it in dwm will just means
it closes like any other normal lf instance.

**Comment by DusanLesan** [comment]
@LukeSmithxyz 
Nope. It should not close because of  $SHELL. It should leave terminal window running and it should cd. If this works correctly for you, you will be able to q into terminal and cd to last lf location, or to kill window for current behavior.

**Comment by LukeSmithxyz** [comment]
If you just want a shell, you can just press `w` in lf. Obviously I want `q` to be quit.

**Comment by DusanLesan** [comment]
You are completely right. I've missed w completely. Sorry for your time.
