### ISSUE TITLE
Status bar hiccup with error on startup

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/voidrice#87]
Occasionally on startup, the i3blocks status bar fails to launch and gives an error code. You can easily press `Mod+F2` to refresh it thus getting the proper bar, but I'd like to keep the error from ever happening because I sometimes get an email confused about it.

The i3status modules are named `~/.scripts/i3*`, I suspect at least one of them is causing this problem, but I haven't found out which. If anyone has a clue, feel free to say what it could be, but otherwise I'll keep this open until solved.

**Comment by ExploXd** [comment]
yeah, I had this one. try disabling mpd block, and then in the config disable mpd refresh. I know, you may miss this, but if you really want this work normally, then disable this.

**Comment by ExploXd** [comment]
I also don't have any idea what part of the code is causing this, but I assume that refresh script does it.

**Comment by ExploXd** [comment]
as it turns out i3mpdupdate is causing that.

**Comment by LukeSmithxyz** [comment]
Okay, but what are you saying causes it? Frankly if you look at the error messages when that problem occurs, it's the `[record]` script that has an error code, so my reflex would be that that's the problem.

**Comment by ExploXd** [comment]
Yeah, sorry silly me. I didn't even look inside the `i3mpdupdate`, which made me unfamiliar with those causes.

**Comment by ExploXd** [comment]
Sorry, but I didn't have the problem with that, I had the problem with `i3mpdupdate`, also I didn't notice that.

**Comment by ExploXd** [comment]
Simply; when I checked out the `i3mpdupdate` in the i3 config my problem was fixed.

**Comment by TylerJaacks** [comment]
@ExploXd So what did u do exactly, I'm confused?

**Comment by ExploXd** [comment]
> So what did u do exactly, I'm confused?
I removed i3mpdupdate from i3 config.

**Comment by LukeSmithxyz** [comment]
I seriously doubt that `i3mpdupdate` is causing this problem. Especially considering the line in the i3 config has nothing to do with the bar. If you disabled the script and didn't get the error that doesn't really mean anything since the error message is infrequent regardless.

Aside from that `i3mpdupdate` is a necessary component of the system, so it's not possible to just "remove it".

Either way, I've added a minor change that will change any particular `i3mpdupdate` error from taking place in i3 to taking place in a subshell. Again, the likely problem is the `record` module since *that's the module that has the error message*.

**Comment by LukeSmithxyz** [comment]
Someone can feel free to say so if they still have problems, but **some** i3blocks change made within the past month or so seems to have eliminated this problem. I'm going to close this issue.
