### ISSUE TITLE
Add .bmp image support in lf

### ISSUE THREAD

**Issue by VolkovIlia** [LukeSmithxyz/voidrice#870]
Zathura opens .bmp images form lf by default. Can you fix it please?

**Comment by LukeSmithxyz** [comment]
Edit your lfrc if you would like files to be opened by some metric other than their mime-type.

**Comment by VolkovIlia** [comment]
I've tried before typing here.

```
image/*) rotdir $f | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|tif\|**bmp\**)\(_large\)*$" | sxiv -aio 2>/dev/null | lf-select ;;
```
But .bmp still opens by Zathura

**Comment by LukeSmithxyz** [comment]
Your .bmp doesn't have the proper mime-type then. Note that you are
inside a case statement that checks for that.
