### ISSUE TITLE
Statusbar script for tsp

### ISSUE THREAD

**Issue by asakura42** [LukeSmithxyz/voidrice#871]
`tsp` is great tool that I use regularly with your `dmenuhelper` and `qndl` scripts. But it's very uncomfortable to run `tsp -l` every time when I want to check if task is successful. So I found this script: https://github.com/Andr3as07/dotfiles/blob/master/.local/bin/blocks/tasks, added line `tsp -l > /tmp/tspi3 && pkill -RTMIN+4 "${STATUSBAR:-dwmblocks}"` to `qndl` and fixed that `tasks` script to exec `less -Srf /tmp/tspi3` when I leftclick.

But maybe it's not the best option? I think that statusbar solution for tsp is must have.

**Comment by LukeSmithxyz** [comment]
I've added a simplified version of that script to the statusbar scripts directory.
