### ISSUE TITLE
UK keyboard layout not working

### ISSUE THREAD

**Issue by 5833tP2** [LukeSmithxyz/voidrice#872]
I'm trying to get my UK layout keyboard working with LARBS but without success. My arch linux has locale set to `en_UK.UTF-8`  and the keyboard works fine until I `startx` whereupon it reverts to a `us` layout.

Note that this is not about mapping commands to keys, but rather the definition of the keyboard layout.

In `st`, `setxkbmap -layout uk` generates `Error loading new keyboard description`.

`$ setxkbmap -print -verbose 10` confirms the `us` layout:
```
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc105
layout:     us
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)
geometry:   pc(pc105)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+inet(evdev)"     };
        xkb_geometry  { include "pc(pc105)"     };
};
```
I've created `/etc/X11/xorg.conf.d/00-keyboard.conf` with the following lines:

```
Section "InputClass"
Identifier "system-keyboard"
Option "XkbLayout uk"
EndSection
```
but this has not helped.

Non-US keyboard users, how did you get LARBS to work for you?

Is there anything in LARBS or Luke's `dwm` build that hard wires a `us` keyboard layout? Therefore, do I have to reconfigure dwm and rebuild it?

Thanks

**Comment by f380cedric** [comment]
Setting your locale is not sufficient.
It may derive a keyboard layout from it, but there are different settings.
Your xorg conf seems syntactically incorrect, it should be `Option "OptionName" "Value"`, not `Option "OptionName Value"`.

Please read these ArchLinux Wiki pages to set your layout: [1](https://wiki.archlinux.org/index.php/Xorg/Keyboard_configuration), [2](https://wiki.archlinux.org/index.php/Linux_console/Keyboard_configuration).

**Comment by 5833tP2** [comment]
Thanks for your reply. I've read both sections in the ArchLinux Wiki and none of the suggestions work for me. That is the reason I asked about whether Luke's `dwm` had a US keyboard layout hardcoded. Your reply indicates that it is not the case, and that the problem resides with my `xorg` keyboard configuration.

If this isn't a LARBS issue, I'll take the problem to a different forum.

Thanks again.
