### ISSUE TITLE
Refer + groff in Compiler script

### ISSUE THREAD

**Issue by dlgeraghty** [LukeSmithxyz/voidrice#873]
## Intro:

Hello Luke, i have been using your compiler script for a while as i find it very useful when writing code in vim.  

I have been wanting to get into groff, have followed your youtube tutorials, and for that I thank you  
## Error:
But I found a little error, that is, when inserting references in a document, the command from the compiler script wont find the references because it doesnt find the bibliography file.

## My setup
Okay so I am working on a little project just to learn groff and this is in a directory, where i have a file named references.bib and there i have inserted some entries.  
As mentioned earlier, when running the compiler script it wont know where the database for the references is.  

## My solution:
There is an argument that you can use to tell refer to use a certain file as database, that is the -p option  
I would therefore use refer with the -p option and specify a filename which could be for instance the same name as the main groff file....  

Maybe I am missing something here...in that case let me know, otherwise it would be cool to have this integrated into the compiler script  

Btw i am loving groff so far, much faster than LaTeX, but i cant get the figures to show...

**Comment by LukeSmithxyz** [comment]
Use the `$REFER` variable. Check the `refer` documentation.
