### ISSUE TITLE
Keymapping Location

### ISSUE THREAD

**Issue by TheYellowArchitect** [LukeSmithxyz/voidrice#889]
Hello, I got a fresh Artix install then put this atop of it, works pretty good!

I would like to ask, where are the super+[key] remappings?

For example, super+e opens email, but let's say for example I want to put another program to open with that key
I found the mappings of so many other programs, but I can't find this - it's not in the super+F1 either

**Comment by AlexSyssoyev** [comment]
In .local/src/dwm edit config.h as you like it and run a ```sudo make clean install``` in the directory, restart dwm with super+f12 and thats it.

**Comment by TheYellowArchitect** [comment]
Thanks dude, it works!

I edited the config, did the command you said and did the super+shift+backspace, it just works

Tor browser for some reason doesn't work (even with -e in front of it, or sudo), but doesn't matter, super+d->torbrowser-launcher works as well hahaha

Thanks again, I did all the configurations I needed (and will do more in the future feelsgoodman)
