### ISSUE TITLE
weird st behavior when the mod key is pressed

### ISSUE THREAD

**Issue by TomJansen** [LukeSmithxyz/voidrice#89]
I don't know if this is intentional but when I press the mod key in st, the terminal is only able to go back and forth in the command history. The only way to get out of this "mode" is ctrl+c. This is really annoying IMO, is there any way to disable this?

**Comment by LukeSmithxyz** [comment]
The default editing mode of the shell is `vi` mode, which is what you seem to be confused by i.e.: https://www.youtube.com/watch?v=GqoJQft5R2E

If you don't want this, you can disable it by commenting out the contents of `~/.inputrc` (or just delete/moving the file).

**Comment by LukeSmithxyz** [comment]
I've added this to the documentation and the help menu now. I guess I totally neglected to mention it! I'll keep this issue open for a little so other people can easily see it who might have the same question.
