### ISSUE TITLE
Secondary Monitor on top of Primary Monitor

### ISSUE THREAD

**Issue by s3p1ol** [LukeSmithxyz/voidrice#893]
Due to space constraints on my desk, I have a secondary monitor behind my laptop on a stand. 

I've noticed that LARBS only has left and right alignments for the secondary monitor. How do I set them this way?

**Comment by rahul-goel** [comment]
You can use the `arandr` program to define your own layout and then export it as an `xrandr` command. You could then edit the `displayselect` script and add that layout under a name of your own choice.

**Comment by LukeSmithxyz** [comment]
This is probably too niche of a use case to integrate into the dmenu script. Yes, use arandr or design an xrandr command/config to run on start to give you what you need.
