### ISSUE TITLE
Error in vim as normal user

### ISSUE THREAD

**Issue by Panadestein** [LukeSmithxyz/voidrice#9]
I just installed your rice in a fresh Arch Linux system, and I'm struggling with some issues, like this one in vim, when opening fies as non root:
`Error detected while processing /home/panadestein/.vimrc:
line  218:
E185: Cannot find color scheme 'wal'
`
Any suggestion?

**Comment by LukeSmithxyz** [comment]
That line is for a colorscheme defined by pywal. If you don't use pywal, just remove the line in the vimrc.

If you *do* use pywal, install this plugin (https://github.com/dylanaraps/pywal/wiki/Customization#vim).

**Comment by LukeSmithxyz** [comment]
Hi Panadestein (and others). I've now added this vim plugin to this repo (along with some other ones I use). They should work automatically if you have Pathogen.
