### ISSUE TITLE
[Enchancement] Low battery notification via dunst

### ISSUE THREAD

**Issue by dankehidayat** [LukeSmithxyz/voidrice#90]
Sometimes i always forgot what battery im on, especially when it's under 30%. 
This would be a small yet useful script for the upcoming commit/update.

**Comment by LukeSmithxyz** [comment]
Is the battery module turning red not enough for you? ;-)

**Comment by gabriel-doriath-dohler** [comment]
This happen all the time to me. The red battery isn't enough.

**Comment by ExploXd** [comment]
What if you have broken battery that turns off the notebook on 50% :thinking: :

**Comment by LukeSmithxyz** [comment]
I don't know. I don't really want to have some kind of monitoring script running in the background for this. It seems like a massive waste: why even have a battery module if you don't at least notice it every once in a while?

Either way, I'll reach you half way, maybe I'll add a little script that checks battery remaining and sends a `notify-send` message if you're below say, 25%. I was thinking of adding some scripts like this to be used with `cron`, so users can just set it up to run when they want.

> What if you have broken battery that turns off the notebook on 50% thinking :

Well we're all Archcucks, so we should be able to edit `i3battery` and change the display colors or percentages ;-)

**Comment by LukeSmithxyz** [comment]
Alright, there's now a script in the script folder `cronbat` which you can set as a cronjob at an interval of your choosing. It will make an urgent `notify-send` message appear the top right of your screen.

**Comment by KHZ-INTL** [comment]
Please see my implementation for low battery notifications. on github:

[Low battery notification cron](https://github.com/KHZ-INTL/low_battery_notification_cron)
