### ISSUE TITLE
In booksplit, the cut command messes up the timecodes.

### ISSUE THREAD

**Issue by natopwns** [LukeSmithxyz/voidrice#908]
The cut command is causing the timecodes to be unrecognizable to ffmpeg somehow. The strings look the same, and the ascii codes are the same. Even so, the terminal shows that the after cut timecodes are different from before cut with a `[ $start = "00:00:00" ]; echo "$?"`. When ffmpeg attempts to use the timecodes, it spits out `Invalid duration specification for ss: 00:00:00`. I have worked around this by changing the cut command to `end="$(echo "$x" | cut -c1-8)"` for now. I'm scratching my head as to what's going on, though. Using Arch btw.

**Comment by theamazingwaffle** [comment]
i had a similar issue, check if there is a zero width space after the timecodes
