### ISSUE TITLE
Media Controls for Spotify

### ISSUE THREAD

**Issue by hepan-git** [LukeSmithxyz/voidrice#91]
I keep trying to use my keyboard media controls for Spotify music but it doesn't do anything. This could be my keyboard or that Spotify just doesn't pay attention and needs a different command from the button.

If Spotify works for anybody else with keyboard media controls then please tell me, if not then I will try to get it to work.

**Comment by LukeSmithxyz** [comment]
Someone a long time ago wrote out i3 commands for Spotify which aren't active in the config, but you can find backups of them in `~/.scripts/musstuff`. You can replace the `lmc ` shortcuts in the i3 config with their Spotify equivalents. There are also shortcuts for other common audio players: moc and cmus for people who use those.

**Comment by hepan-git** [comment]
Pause/play toggle, previous, and next work. I haven't tried any of the other ones but I am pretty sure they'll work.
