### ISSUE TITLE
remaps script keybindings stop working

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/voidrice#914]
for a while now, the caps key stops working as the escape key and i have to run remaps manually every time to get it to work like that, any idea why this could be happening? this wasn't happening before

**Comment by LukeSmithxyz** [comment]
I would guess that you inadvertently set up some other script that is periodically running a `setxbmap` command that overwrites the settings.

**Comment by kronikpillow** [comment]
no bro, pure plain larbs, your setup ... fresh reinstall :-/ and it's still happening

**Comment by LukeSmithxyz** [comment]
Are you also plugging in new keyboards or transferring laptops off and on docks? The remaps will not automatically work on newly plugged in devices.

**Comment by kronikpillow** [comment]
no mate ... i use a desktop PC, and i'm not plugging in anything in or out, this problem didn't exist to me before, once remaps was ran trough xprofile it never entered the state of going back to default, a few days back, it just started doing this on it's own, and it's been persistent across 1 reinstall, as I'v managed to crash my system with something else, reinstalled, fresh brand new LARBS, still happening ... can't figure out why

**Comment by narukeh** [comment]
@kronikpillow  try removing all dotfiles before reinstalling larbs. **make sure to backup ssh and gpg**. if its still persistent then its a global config, probably in `/etc/` . if its still persistent then the only logical explanation is that you have a bad keyboard cable, its periodically plugin out then in.
