### ISSUE TITLE
<<< is a undefined feature of POSIX

### ISSUE THREAD

**Issue by Juliaria08** [LukeSmithxyz/voidrice#921]
# Issue
In the file .config/newsboat/config line 39 is a reference to a undefined feature of POSIX so the dotfiles are not dash compatible, i noticed this after switching sh to dash
https://github.com/LukeSmithXYZ/voidrice/blob/master/.config/newsboat/config#L39
```
macro c set browser "xsel -b <<<"; open-in-browser; set browser linkhandeler
```
## __**ShellCheck**__
```
[julian@art ~]$ shellcheckj -
#!/bin/sh
xsel -b <<<a

In - line 2:
xsel -b <<<a
        ^-^ SC2039: In POSIX sh, here-strings are undefined.

For more information:
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, here-strings are und...
[julian@art ~]$ shellcheck -
#!/bin/dash
xsel -b <<<a

In - line 2:
xsel -b <<<a
        ^-^ SC2169: In dash, here-strings are not supported.

For more information:
  https://www.shellcheck.net/wiki/SC2169 -- In dash, here-strings are not sup...
[julian@art ~]$
```
## My idea
If for some reason something like a var with the url cloud be expanded i whould sujest this
```
macro c set browser "xsel -b <<EOF
$expansion
EOF"; open-in-browser ; set browser linkhandeler
```

## [DashAsBinSh](https://wiki.ubuntu.com/DashAsBinSh)
Points out
```
<<<
"Here strings" are similar to "here docs," and in most cases can easily be replaced with one.

E.g.

$ cat <<<"$HOME is where the heart is."
/home/ralph is where the heart is.
$
$ cat <<E
> $HOME is where the heart is.
> E
/home/ralph is where the heart is.
```
## Thanks in advance

**Comment by BachoSeven** [comment]
or just do:
`macro c set browser "echo %u | xclip -r -sel c" ; open-in-browser ; set browser linkhandler`
(where you can also replace `xclip -r -sel c` with `xsel -b` ofc

**Comment by Juliaria08** [comment]
> or just do:
> `macro c set browser "echo %u | xclip -r -sel c" ; open-in-browser ; set browser linkhandler`
> (where you can also replace `xclip -r -sel c` with `xsel -b` ofc

Thank

**Comment by Juliaria08** [comment]
Great idea, make a pr if you like to!!

**Comment by BachoSeven** [comment]
> Great idea, make a pr if you like to!!
> […](#)
> On 21/03/27 11:47, Francesco wrote: or just do: `macro c set browser "echo %u | xclip -r -sel c" ; open-in-browser ; set browser linkhandler` (where you can also replace `xclip -r -sel c` with `xsel -b` ofc -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#921 (comment)](https://github.com/LukeSmithxyz/voidrice/issues/921#issuecomment-808785420)

It seems like there was a similar command [earlier](https://github.com/LukeSmithxyz/voidrice/commit/6ea8fa749402f975c1175a706b82581b5c7bba97#diff-2cb33121aa2ddf2cfd3fe1a3007f088911295eb52e9cdf8082178a7e13f584ea), but yea since `<<<` does not work with /bin/sh as dash this should be fixed. will make a PR soon

**Comment by Juliaria08** [comment]
On 21/03/29 06:08, Francesco wrote:
> > Great idea, make a pr if you like to!!
> > […](#)
> > On 21/03/27 11:47, Francesco wrote: or just do: `macro c set browser "echo %u | xclip -r -sel c" ; open-in-browser ; set browser linkhandler` (where you can also replace `xclip -r -sel c` with `xsel -b` ofc -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#921 (comment)](https://github.com/LukeSmithxyz/voidrice/issues/921#issuecomment-808785420)
> 
> It seems like there was a similar command [earlier](https://github.com/LukeSmithxyz/voidrice/commit/6ea8fa749402f975c1175a706b82581b5c7bba97#diff-2cb33121aa2ddf2cfd3fe1a3007f088911295eb52e9cdf8082178a7e13f584ea), but yea since `<<<` does not work with /bin/sh as dash this should be fixed. will make a PR soon
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LukeSmithxyz/voidrice/issues/921#issuecomment-809362898
Ok, thanks if i wanted to do a pr i whould need to download the source
since i edited my dotfiles a bit of *much*

**Comment by Juliaria08** [comment]
Thanks everyone that helped this to make it work :)
