### ISSUE TITLE
Automatic multihead display

### ISSUE THREAD

**Issue by BuddhiLW** [LukeSmithxyz/voidrice#922]
Hey, it's not really an issue. But, I would like to automatically display my external screen, on setup. Instead of going the usual Super+F3 etc etc. ; Super+F3 -> arandr -> monitor resolution -> HDMI-1-0 -> 1440x900.

I have written the following into my /etc/X11/xorg.conf.d/10-monitor.conf, but didn't accomplish nothing.

```conf
Section "Monitor"
    Identifier  "eDP1"
    Option      "Primary" "true"
EndSection

Section "Monitor"
    Identifier  "HDMI-1-0"
    Option      "RightOf" "HDMI-1-0"
    Option      "PreferredMode" "1440x900"
EndSection
```

My hardware:
```shell
$ xrandr --listmonitors
```
```output
Monitors: 2
 0: +*eDP1 1920/340x1080/190+0+0  eDP1
 1: +HDMI-1-0 1440/300x900/230+1920+0  HDMI-1-0
```

Anyone have experience with this kind of configuration?

**Comment by StoicIndividual** [comment]
Huh weird, for me my external display is set up automatically (at first I also had to run Super+F3 but after some time it just recognized and set up my second monitor automatically), and what do you mean by display it? does it not display anything by default?

**Comment by BuddhiLW** [comment]
My laptop monitor is automatically displayed. But, my HDMI-1-0 no. I have to set up the display manually (right-side in respect to my eDP1).

**Comment by StoicIndividual** [comment]
have you tried Super+F3 and selecting "multi-monitor" and following the steps? I've never tried using "manual selection" which is probably what you chose, does multi-monitor not work?

**Comment by BuddhiLW** [comment]
I use Super+F3 + adjustments I have to do manually on the screen-size. Because, by default, It wont have the optimum resolution for my screen.

But, that's altogether is a manual task, to press Super+F3 and choose displacement - when I already know I will startup with this screen everyday. I would like to have my second screen starting up together with my main. I want a "automatic multihead display" on startup.

**Comment by 0x766F6964** [comment]
Did you check `/var/log/Xorg.0.Log` after you made that change? I suspect that this line:
```
Option      "RightOf" "HDMI-1-0"
```
should actually be:
```
Option      "RightOf" "eDP1"
```

**Comment by BuddhiLW** [comment]
You are right about that @0x766F6964 . Thank you for that bit.

Now, it loads in the right place, but the problem of the black screen persists. I can open a browser, a terminal etc inside this black screen and nothing is shown, but my mouse.

If I set the display "manually", the screen turn functional, and the things moved there (browser, terminals etc) are, in fact, there.

I don't know how to get useful information from `/var/log/Xorg`

**Comment by 0x766F6964** [comment]
Usually you want search for lines with (EE) for errors or (WW) for warnings.

I'm not sure if X is can automatically configure and enable the display if you are attaching it when X is already running. I seem to recall always having to type `xrandr --auto`.

You can try that and if it works you could rebind Super-F3 to run that instead (maybe move the old binding to Super-Shift-F3 if you still want acess to that script with a keybind).

**Comment by BuddhiLW** [comment]
Alright. I that didn't work. But, that comment gave me the brilliant and obvious ideia to write my own script. 

I will catch the command line which produces my desired display and bind it to a key.

Thank you.
