### ISSUE TITLE
sb-mailbox "no such file or directory"

### ISSUE THREAD

**Issue by JacksonTaylorxyz** [LukeSmithxyz/voidrice#933]
https://github.com/LukeSmithxyz/voidrice/blob/f05cb5e1bb2315e89baaa70b40ee82c72019d8ec/.local/bin/statusbar/sb-mailbox#L16

This line does not work on my system, specifically the find command. 

`find: '/home/jackson/.local/share/mail/*/[Ii][Nn][Bb][Oo][Xx]/new/*': No such file or directory`

I use mutt-wizard, and there is a folder in this location `/home/jackson/.local/share/some@email.com/INBOX/new`. I figured it would be caused by checking for the capital letters, but even changing the line to look for strictly`INBOX` hasn't worked. I don't think this script in particular has ever worked on my machines.

I am using `dash` version 0.5.11.3-1 for my `/bin/sh`.

Note: I don't run all of Luke's configs, I kind of pick and choose what I think is cool or necessary. I don't think find having an issue would be caused from me not having another script, but maybe I'm missing something.

**Comment by narukeh** [comment]
who's `find` are you using? with a default larbs install, one would have GNU's `findutils`.
try `busybox`'s or `toybox`'s find.

**Comment by JacksonTaylorxyz** [comment]
@narukeh Sorry for the late reply, it's gnu's find. I installed busybox, and it started to work, but after some testing I found it works if I actually have new mail for both versions. I think I just misunderstood the purpose of the script (I thought it was supposed to be on your status bar all the time). Thanks for your help.
