### ISSUE TITLE
Copy shell output script (I am not finding it)

### ISSUE THREAD

**Issue by BuddhiLW** [LukeSmithxyz/voidrice#934]
It's not an issue, I'm just trying to find the video, or the documentation, or anything that directs me to that script which copies your last output to the clipboard.

As I seem unable to dig it out easily (some hours looking for it, really), I decided to post here.

Can anyone explain me where it is? I remember you can use it through the dmenu!

**Comment by narukeh** [comment]
🤷...search peertube or odysee...🤷

**Comment by BuddhiLW** [comment]
It's not that I'm unable to watch his videos. It's that is no specific video he devoted to talk about the subject. So, practically, I would have to watch hours on end of material to find a 20 seconds clip.

I'm just seeing if someone can tell me the specific video/time it is; or tell me the command in dmenu.

**Comment by LukeSmithxyz** [comment]
https://videos.lukesmith.xyz/videos/watch/eea230ba-3a88-41d5-9dfe-09781088288c
https://github.com/lukesmithxyz/st

**Comment by BuddhiLW** [comment]
Thank you, Luke!
