### ISSUE TITLE
Using deprecated `lowdown` flags

### ISSUE THREAD

**Issue by narukeh** [LukeSmithxyz/voidrice#936]
Since Version 0.8.2, 2021-02-19, lowdown has removed option `-d -D -e -E`
(so `compiler` doesn't work on `.md` if one has only lowdown installed)
see https://kristaps.bsd.lv/lowdown/archive.html

----

https://github.com/LukeSmithxyz/voidrice/blob/f05cb5e1bb2315e89baaa70b40ee82c72019d8ec/.local/bin/compiler#L40
for `-d nointerm` they now use `--parse-no-intraemph`
for `-e super` i dint find an option to enable super; only to disable it `--parse-no-super` **as i understood it**
i wasn't sure, otherwise i would have patched it along in the #935 PR

**Comment by elianpersonal** [comment]
Maybe lowdown now parses superscripts by default, that could explain why there is no option to enable it but there is a option to disable it.
