### ISSUE TITLE
`~/.profile` line 9 incompatible with VNC

### ISSUE THREAD

**Issue by lukerb52** [LukeSmithxyz/voidrice#938]
The line `export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"` gives this error when you try to run a VNC server with your LARBS user

`/home/user/.profile: line 9: $PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}: bad substitution`

I ran shellcheck on `~/.profile` (after temporarily changing `#!/bin/zsh` to `#!/bin/sh` so that shellcheck would run) and it gave me no error relating to that line.

**Comment by narukeh** [comment]
@lukerb52  btw it gives the same error mesage, `bad substitution`, when you use `bash` , `dash`, or busybox's `ash` as login shell. But only while having a symlink (or a copy) of `~/.config/shell/profile` in `~/.profile`.
So to solve your problem, just remove ~/.profile (or edit the conflicting line), or use zsh as login shell.

----

### to replicate:
have `~/.profile`
then just:
`su $USER -l -s /bin/bash`
`su $USER -l -s /bin/dash`
`su $USER -l -s /bin/ash`

**Comment by LukeSmithxyz** [comment]
I mean really I should just remove the `~/.profile` link because it's really just for zsh.

**Comment by narukeh** [comment]
@LukeSmithxyz  `~/.profile` is just for bash, dash, ash.

And if you:
```
cd ~/.config/zsh
ln -sf ../shell/profile ./.zprofile
sudo su -c 'echo ZDOTDIR=\"\$\{XDG_CONFIG_HOME:-\$HOME/.config\}/zsh\" > /etc/zsh/zshenv'
rm ~/.zprofile
```
you **dont** even need `~/.zprofile`.
read https://wiki.archlinux.org/index.php/XDG_Base_Directory#Hardcoded , zsh row.

i have been using it like this since many installs, never had a problem.

**Comment by LukeSmithxyz** [comment]
This repo obviously doesn't set system settings.

**Comment by narukeh** [comment]
@LukeSmithxyz well yes, obviously. It was meant just to inform you. To remove the ~/.zprofile from voidrice repo, it would take merging one PR in voidrice repo (the symlinking),  and one PR in larbs repo (the /etc/zsh/zshenv).
