### ISSUE TITLE
Wallpaper and color scheme lag when starting i3

### ISSUE THREAD

**Issue by SaltyClaridge** [LukeSmithxyz/voidrice#94]
When booting into i3, I noticed the wallpaper and color scheme takes a couple seconds to pop up. I suspected it had something to do with how the i3 config was telling wal to reset the wallpaper and regenerate the color scheme every time i3 started. 

Based on what I read on the pywal wiki, using the -R tag enables it to reuse the last active color scheme instead of resetting and regenerating every time. 

Just in my few reboots, it seems to be loading i3 smoother.

**Comment by LukeSmithxyz** [comment]
Yeah, you know what, that's a good idea. There used to be a reason I had to have it refresh each time, but I suppose I might as well add it now.

**Comment by ExploXd** [comment]
i'm literally dumb sorry.

**Comment by LukeSmithxyz** [comment]
Okay, this has now been added.

**Comment by LukeSmithxyz** [comment]
I just realized that this change will not set the colorscheme on first start, which can be avoided, but it also does not set the color scheme properly for the i3 status bar. I've reverted the change for now and will try to work on a fix.
