### ISSUE TITLE
Open application outside terminal

### ISSUE THREAD

**Issue by ElModdy** [LukeSmithxyz/voidrice#946]
Hi, is there a way to open a gui application without replacing the terminal window where I launch the application?
I've tried `nohup okular "$1" >/dev/null 2>&1 &` but doesn't work.
I really appraciate any kind of help

**Comment by narukeh** [comment]
This works:
```bash
setsid -f zathura "$1" >/dev/null 2>&1
```
(Dont forget to close the issue)

**Comment by kronikpillow** [comment]
edit your dwm config file and give the program you want to run the noswallow option
