### ISSUE TITLE
How does the lf file managers extract work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [LukeSmithxyz/voidrice#948]
Hi Luke,
I noticed that u had this 
```
cmd extract ${{
	clear; tput cup $(($(tput lines)/3)); tput bold
	set -f
	printf "%s\n\t" "$fx"
	printf "extract?[y/N]"
	read ans
	[ $ans = "y" ] && ext $fx
}}
```

I just get  when trying to use it for extracting zip or tar files.

`running shell: exit status 127`

**Comment by kronikpillow** [comment]
it uses the ext script from .local/bin/ext ... but for some reason it's not working with lf ... not entirely sure why this script is needed in the first place when LARBS ships with atool, which is basically a archive extractor and very good at extracting the majority of files, when luke used vifm it was bound to use atool

**Comment by thepenguinthatwants** [comment]
I actually tried to bind atool with lf but failed. But there were quite amount of examples of just scripting with bash to get extract function so I stick with those.
