### ISSUE TITLE
Support spaces in paths @ bin/shortcuts?

### ISSUE THREAD

**Issue by kiprasmel** [LukeSmithxyz/voidrice#950]
Hey there, could we support having paths with spaces in the bin/shortcuts generator? It's obviously best to avoid spaces in the first place, but there are directories/files whose path I cannot control yet still want to bookmark.

**Comment by narukeh** [comment]
yeah, that would require work though 😅
sooo, do what i do 😁:
let __all__ your "unrename-able stuff" in a directory, e.g. called "archive", (u wont do work here), __than__ you make symbolic links of those files/dirs/both whereever however you want (goal: no_space_dir).
maybe i made it sound more complicated than it actually is, trust me its really easy.
