### ISSUE TITLE
Changing colors with wal broke Brave notifications (issue 333 in LARBS repo)

### ISSUE THREAD

**Issue by wlw-codes** [LukeSmithxyz/voidrice#952]
Original quote from [issue 333 in LARBS](https://github.com/LukeSmithxyz/LARBS/issues/333)
> Not exactly sure what caused this but I believe it to be the fault of wal. Notifications from Brave now display as large ugly banners up top, covering dmenu. This is both for BAT ads or for notifications such as IPFS going online. Where can these notification prompts be edited? Are they part of dmenu, brave, or something else?
\
Also unrelated, but where do you change the keybindings? Will changes in inputrc overwrite the ones that come already configured?
\
Thanks.

In my own experience with this issue, it breaks *all* notifications, not just those originating from Brave. I have since reset the theme but the notification issue persists. I also disabled `pywal` in the `setbg` script as I like the defaults.

**Comment by krisdoodle45** [comment]
It's now fixed, but for people who have this issue you will need to manually fix it. You need to copy ~/.config/zathura/zathurarc and ~/.config/dunst/dunstrc from this repository to your own system at the same spot. After that it should be fixed.
