### ISSUE TITLE
sb-battery won't work with i3blocks unless a newline printed at the end

### ISSUE THREAD

**Issue by hansejo** [LukeSmithxyz/voidrice#958]
Hi Luke, just thought I would let you know, the sb-battery script won't work in i3blocks because a newline is not at the end of the printf command. All other scripts in this directory have a newline at the end. Adding `printf "\n"` on line 36 fixes the issue.

**Comment by narukeh** [comment]
yeah, its been like that for months...
i have a feeling luke doesnt wanna update/merge PR frequently, so it would be smart to assemble alot of tiny stuff (like this) in one PR, idk. fix:
```bash
printf "%s%s%d%%\n" "$status" "$warn" "$capacity"; unset warn
```

**Comment by narukeh** [comment]
i made a PR, #971  , if its merged, should be fixed.
dont forget to close this issue, then.

**Comment by hansejo** [comment]
@narukeh Closing issues can be automated. Edit the OP of your PR with:

`closes #958`

**Comment by narukeh** [comment]
@hansejo thanks! that's pretty useful.

**Comment by narukeh** [comment]
@hansejo  hehe, the issue is fixed, but dot from my PR, sooooo.....
