### ISSUE TITLE
Is the license GPL-3.0-only or GPL-3.0-or-later?

### ISSUE THREAD

**Issue by smlavine** [LukeSmithxyz/voidrice#959]
As I'm sure you're aware, people licensing their software under the
terms of the GNU General Public License can choose to license it solely
under the terms of version 3 of the license, **OR** either version 3 of
the license, or any later version.

Which is it for this repository?

**Comment by HXAPEWiZZ** [comment]
https://github.com/LukeSmithxyz/voidrice/blob/master/LICENSE here, stop taking amphetamine and get some patience by meditating or something, or just websearch how to find the loicence of a project on github. also there exists gpl, lgpl and agpl. gpl has no version newer than 3.0 officially, so what you're even asking about is just retarded in multiple ways.

**Comment by smlavine** [comment]
> https://github.com/LukeSmithxyz/voidrice/blob/master/LICENSE here, stop taking amphetamine and get some patience by meditating or something, or just websearch how to find the loicence of a project on github. also there exists gpl, lgpl and agpl. gpl has no version newer than 3.0 officially, so what you're even asking about is just retarded in multiple ways.

Okay.

First, I know that the license to this repository. It is right there on the side of the web view, next to the scales. Thank you for the link to that, as well.

Secondly, I am aware of the various GNU licenses -- GPL, Lesser GPL, Affero GPL. This repository is using version 3 of the GNU General Public License, as shown by the LICENSE file.

To get to the actual point of what I asked: yes, "GPL version X only" or "GPL version X or later" is an actual issue. For example, The Linux project notably uses GPL version 2 only. Read that LICENSE you just linked and you'll see it for yourself:

>   14. Revised Versions of this License.
> 
>   The Free Software Foundation may publish revised and/or new versions of
> the GNU General Public License from time to time.  Such new versions will
> be similar in spirit to the present version, but may differ in detail to
> address new problems or concerns.
> 
>   Each version is given a distinguishing version number.  If the
> Program specifies that a certain numbered version of the GNU General
> Public License "or any later version" applies to it, you have the
> option of following the terms and conditions either of that numbered
> version or of any later version published by the Free Software
> Foundation.  If the Program does not specify a version number of the
> GNU General Public License, you may choose any version ever published
> by the Free Software Foundation.
> ...
>
>  How to Apply These Terms to Your New Programs
>
>  ...
>
>  ...attach the following notices to the program.
>
>  ...
>
>    <one line to give the program's name and a brief idea of what it does.>
>    Copyright (C) <year>  <name of author>
>
>    This program is free software: you can redistribute it and/or modify
>    it under the terms of the GNU General Public License as published by
>    the Free Software Foundation, either version 3 of the License, or
>    (at your option) any later version.
>
>    This program is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU General Public License for more details.
>
>    You should have received a copy of the GNU General Public License
>    along with this program.  If not, see <http://www.gnu.org/licenses/>.

I don't care which it is, I'd just like to *know* which it is. One (somewhat tedious) way to solve this would be to add that header to script and config files, or add a SPDX identifier of either 'GPL-3.0-only' or 'GPL-3.0-or-later'. Another would be to just state which it is in the README. Another way, and the easiest probably, would just be a line from Luke in this issue clarifying it.

**Comment by narukeh** [comment]
😂😂😂
🤦
😂😂😂
