### ISSUE TITLE
TerminalEmulator

### ISSUE THREAD

**Issue by pondakun** [LukeSmithxyz/voidrice#962]
The problem is when i am in thunar and try to open a terminal in this window  game me an error  could not find failback terminalEmulator application. how can i fix that? 

btw i'm newbie
![pic-selected-210619-1748-56](https://user-images.githubusercontent.com/53324347/122645970-ba07ca80-d125-11eb-8ea8-a6ac62cb63ee.png)

**Comment by wintersand-gh** [comment]
Edit > Configure custom actions > Select the "Open Terminal Here" and click the gear icon. Don't worry if it doesn't recognize the emulator unless it stops working.

**Comment by pondakun** [comment]
> Edit > Configure custom actions > Select the "Open Terminal Here" and click the gear icon. Don't worry if it doesn't recognize the emulator unless it stops working.

when i do what you say there is this commant /usr/bin/exo-open %f i don't thing this is right

**Comment by wintersand-gh** [comment]
Yup, you have to change it. That's for xfce (hence exo-open), so you'll have to change that to your emulator of choice

**Comment by pondakun** [comment]
like st?

**Comment by pondakun** [comment]
> Yup, you have to change it. That's for xfce (hence exo-open), so you'll have to change that to your emulator of choice

Sorry if i bother you but can you tell me the command or when can i find it? Tnx
