### ISSUE TITLE
tremc fuction not working 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/voidrice#965]
tremc-git or tremc is installed on my system and when toggle with cobination mod+f6 is not working . 
it display that I sould install it ....

**Comment by kronikpillow** [comment]
same issue here, when i try to run tremc in terminal i get
`Cannot connect to localhost:9091: [Errno 111] Connection refused
`

**Comment by kronikpillow** [comment]
solution: edit to ~/.local/bin/torwap and change the first line where it's looking for tremc-git and change it to just tremc, problem solved...

when tremc-git compiles the executable is named tremc, so ifinstalled is looking for a non-existing executable as its looking for tremc-git

**Comment by grantusaus** [comment]
> solution: edit to ~/.local/bin/torwap and change the first line where it's looking for tremc-git and change it to just tremc, problem solved...
> 
> when tremc-git compiles the executable is named tremc, so ifinstalled is looking for a non-existing executable as its looking for tremc-git

Yes. I had to do this as well. Changing tremc-git to tremc in the torwrap script works.

**Comment by krisdoodle45** [comment]
Same here, changing it makes it work

**Comment by krisdoodle45** [comment]
#973 fixes it
