### ISSUE TITLE
Transparency only applies to st?

### ISSUE THREAD

**Issue by victornor** [LukeSmithxyz/voidrice#967]
Hey,
I'm wondering why transparency is only applied to the st terminal.
Even when running compton, i am unable to get transparency on other windows.
I have not encountered this before, so maybe it's something related to dwm or arch?

Thanks

**Comment by wintersand-gh** [comment]
Transparency only applies to st because of the fact that the `alpha` patch allows for transparency for *st*, not other applications. If you want transparency for inactive windows look into the picom configuration file, that's where you can set it.

**Comment by void00r** [comment]
larbs uses xcompmgr by default for transparancy. 
Install picom and in its config file (~/.config/picom/picom.conf)
add rules for the windows you want transparency. 
like this:
opacity-rule = [
	"82:class_g  = 'dwm'",
	"95:class_g = 'Thunar'",
	"87:class_g =  'TelegramDesktop'",
	"81:class_g =  'Zathura'",
	"81:class_g =  'surf'",
];

Also in  ~/.xprofile or ~/.config/x11/xprofile 
comment xcompmgr line and add
picom &	
line. 

All the best
