### ISSUE TITLE
cannot reboot by  sysactions 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/voidrice#968]
I don't know ... I am using at the time artix with openrc 

my sudoers i uncomment the 
` %wheel ALL=(ALL) NOPASSWD: ALL`

and i comment the other lines and i cannot reboot .. is there something i am missing 

https://www.youtube.com/watch?v=Ykv-vk5ojIY

Luke thanks for your awesome software

**Comment by wintersand-gh** [comment]
Can you reboot by doing the command `sudo -A openrc-shutdown -r`?

**Comment by jemadux** [comment]
> Can you reboot by doing the command `sudo -A openrc-shutdown -r`?

not it will not work .. it wil work with the 
`sudo -A openrc-shutdown -r now `
