### ISSUE TITLE
gimp on tag 9 ?

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/voidrice#969]
sometimes when i launch the gimp it display on tag 9 ... 

what should i do to run specific applications tags that I want ?

**Comment by jakubreron** [comment]
You need to change relevant lines in [DWM](https://github.com/LukeSmithxyz/dwm) `config.h` file and recompile it
Here are the rules: 
![image](https://user-images.githubusercontent.com/25802053/124353480-0a435a00-dc07-11eb-9964-ab18e64f2423.png)

**Comment by jemadux** [comment]
thank you ..
