### ISSUE TITLE
helping with custom script  dmenu 

### ISSUE THREAD

**Issue by jemadux** [LukeSmithxyz/voidrice#970]
sometimes I want read some mangas ( jappanese comic)  

yes I have downloaded in my drive . 

i am trying to like  that for instance in directory of One Piece 

```
# !/bin/sh
cd ~/Pictures/OP
chosen=$( ls ~/Pictures/OP  | dmenu -i -l 30  )
open=$(cd $chosen | sxiv * )

[ -z "$chosen" ] && exit


if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' opened." &
if

```

works kinda but the the chapter name is with the "Ch  100: name of chapter " and always sxiv the 
first chapter , can u please tell how to fix it ?

**Comment by narukeh** [comment]
first thing i see:
everything inside single quotes is treated literally, so:
```bash
notify-send ""${chosen}" opened."
```
secondly, you are reading manga as single .jpg/.png??? whats wrong with you 😛😛
zip the chapter folder, with a `.cbz` extension, then open it with zathura. no need for sxiv.
```bash
zip -r Chapter_001.cbz ./Chapter_001/
zathura Chapter_001.cbz
```
and you will read the archive as if it were a pdf. `.cbz` is a holly format!
**You obviously need the `zathura-cb` package, so have it installed!!!**

btw: **This is not a voidrice issue, so it will/should be removed**

**Comment by jemadux** [comment]
@narukeh thank you my friend ... i will do it like that
