### ISSUE TITLE
Wallpaper change script

### ISSUE THREAD

**Issue by hepan-git** [LukeSmithxyz/voidrice#98]
I put `wal -c -i ~/Pictures/Wallpapers/` (that being the directory of my wallpapers) in wallchange.sh and made a cronjob using `crontab -e` that says `*/15 * * * * /home/damien/.scripts/wallchange.sh`. I made the file executable and when I run it on its own it works and does everything I expect it to do, change the wallpaper and the colours. However, when the cronjob runs it only changes the colours and not the wallpaper.
Any ideas?

I don't know if this is a problem with larbs, but since it is using software from larbs I thought that it could be.

**Comment by LukeSmithxyz** [comment]
This isn't a question relevant to this repository. Your problem is that you don't tell what display cron should use for the command though. Look up this up and that will be the solution.
