### ISSUE TITLE
(Suggestion) Add ifuse support to dmenumount

### ISSUE THREAD

**Issue by cronidea** [LukeSmithxyz/voidrice#980]
ifuse allows for the mounting of iPhones and other iDevices under Linux. Since dmenumount already has android support, I feel that having a normie-friendly easy way to mount Apple devices would be great for those starting out and unfamiliar with the command line.

**Comment by FabianPaci** [comment]
I think that would just be bloat, its defiantly a good idea for new users but not many people use apple devices with Linux let alone mounting them. maybe it could be optional in LARBS or something.

**Comment by cronidea** [comment]
Hmm, okay. Thanks for the feedback, I guess I could try and implement it but again as you said, how many people use apple devices with Linux? I mean is it really worth our time to develop something people won't use? That kinda goes against the whole non-bloat ideology of this repository.
