### ISSUE TITLE
lf bulkrename: vidir not found

### ISSUE THREAD

**Issue by c-torre** [LukeSmithxyz/voidrice#981]
Using the `B` shortcut for `bulkrename` inside `lf` errors: "running shell: exit status 127". The output is:  "errors--: line 2: vidir: command not found".

I checked the following for `vidir`:

- `~/.local/src`: not found
- LARBS/progs.csv: not found
- Arch repos: https://archlinux.org/packages/community/x86_64/moreutils/
- AUR: https://aur.archlinux.org/packages/vidir/

I can solve this for myself, but what should be the solution for voidrice and/or LARBS? Or perhaps it should work and I'm missing something?

**Comment by krisdoodle45** [comment]
This issue can now be closed, it is fixed in [](https://github.com/LukeSmithxyz/LARBS/commit/881a6acf402a95e3f53300929e36737f4010ebd9).
