### ISSUE TITLE
Compiler in nvim

### ISSUE THREAD

**Issue by santilococo** [LukeSmithxyz/voidrice#984]
Hi, what do I need to install in order to run the compiler that is used in nvim?

```
" Compile document, be it groff/LaTeX/markdown/etc.
	map <leader>c :w! \| !compiler "<c-r>%"<CR>
```

**Comment by narukeh** [comment]
read the script `/.local/bin/compiler`
based on what you want to compile, you need that installed.
e.g. if you want to compile c source, you have to have `make` installed. open the `config.h` (of the project), then run the compiler script on it.
if you're asking how to run it, just press `,` and `c`
