### ISSUE TITLE
Consider using bat instead of highlight

### ISSUE THREAD

**Issue by DanKGooGLy** [LukeSmithxyz/voidrice#985]
[bat](https://github.com/sharkdp/bat) is a modern `cat` clone/replacement that I personally find very useful. The possible advantages are:
- Much faster than highlight - Written in rust (although you may dislike rust).
- Support for more filetypes - It supports 100+ languages (which may seem bloated).
- Git integration - Can show modifications done to files through git.
- File concatenation - Works exactly like `cat` even in non-interactive sessions when you want it to.
- Automatic paging - Pipes into `less` if the output is larger than the screen.

You can even alias `cat` to `bat -pp` so it functions the same.

All this may seem bloated, but I personally find it much nicer than `highlight`.

**Comment by narukeh** [comment]
Bloated or not, it doesnt matter, __if its faster than highlight__. Right?
Are you sure its faster, though?

**Comment by DanKGooGLy** [comment]
> Bloated or not, it doesnt matter, **if its faster than highlight**. Right?
> Are you sure its faster, though?

Weirdly enough, it turns out it isn't. I'm not sure how I'm supposed to properly benchmark this but this is what `hyperfine` gave me. GNU Time gave me similar results.
![image](https://user-images.githubusercontent.com/34890978/130155917-c59ab42c-a603-49d7-87ad-c2dd21e8059e.png)

**Comment by narukeh** [comment]
😎😄
```
alias hat="highlight --out-format=ansi"
```
