### ISSUE TITLE
Unmount menu (Mod+F10) doesn't work

### ISSUE THREAD

**Issue by gabriel-doriath-dohler** [LukeSmithxyz/voidrice#99]
Mod+F9 works but not Mod+F10. No idea why...
Can always use: # umount /path/to/directory

**Comment by LukeSmithxyz** [comment]
What is the mountpoint of the drive in question? `dmenuumount` does not look to unmount essential partitions like `/` and `/home`, etc. to prevent dangerous unmountings.

**Comment by gabriel-doriath-dohler** [comment]
the drive is mounted to ~/usb

**Comment by LukeSmithxyz** [comment]
The unmount script has now been changed and will detect drives mounted inside the `/home` directory, although not `/home` itself.
