### ISSUE TITLE
white-spaces break texclear

### ISSUE THREAD

**Issue by GanddoffChan** [LukeSmithxyz/voidrice#992]
voidrice/.local/bin/texclear

Issue: texclear does not work for file names with white-spaces in them.

Example:
**works** for `lmao.tex`
**does not work** for `l\ m\ a\ o.tex`

**Comment by narukeh** [comment]
quick fix, RENAME your file!
or just leave all your files (if for whatever reason you cant rename them) in a archive folder, and symlink everything in that  archive folder, to somewhere else where to a name without spaces.
dont use spaces in unix.

**Comment by LukeSmithxyz** [comment]
PRs are welcome, but I'm not going to bother to change this myself, although it shouldn't be too difficult.

(The real solution is that you shouldn't be using files with whitespaces on a Unix operating system.)
