### ISSUE TITLE
What is the standard way of installing/symlinking `.local/*` dir

### ISSUE THREAD

**Issue by molleweide** [LukeSmithxyz/voidrice#997]
Hi there,

May I ask how people following issues on this repo install the `.local/*` folders?
Do you symlink the whole `.local` folder or do you link each dir individually?

I am asking because this has had me confused for a while. For example, many programs output log files
under eg. `.local/shared/PROGRAM/somelogfile` and so then everything will be added to this repo/fork
if I symlink the whole `.local/shared` dir right? 

I am not an expert at unix/linux and so it seems very nice and simple to symlink the whole
`.local` dir but that doesn't seem to be the right way to go about it, no? But on the other hand
from how I understand it I can symlink the whole `.config` dir since I pretty much want each programs
configs to end up or added to my fork. I am also reading up on XDG base directory to see how everything
is suppose to be structured but this is still confusing to me.

I would appreciate if anyone has time over to explain to me what is the right way to handle this problem?
Hopefully I have explained my confusion well but please tell me to clarify if not.

// molleweide

**Comment by kronikpillow** [comment]
I have no clue why in the world would you ever symlink .config or .local

**Comment by molleweide** [comment]
Allright, thanks for replying. Well, I was thinking that wouldn't I want all configs to be collected into
my dotfiles, but since you relpied the way you did I am thinking that this is probably not something that I want.
